// questions/t10.jsx, Theme 10: COPD
// Source: ISocMedEd Theme 10 MCQ Bank. Image-dependent items omitted. Answers authored.

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t10_a1", "t10", "Anatomy",
    "Which structural change is characteristic of emphysema?",
    ["Thickened alveolar walls with fibrosis", "Destruction of alveolar walls with enlarged airspaces", "Excess goblet cells in the alveoli", "Cartilage rings in the bronchioles", "Increased number of alveoli"], 1,
    "Emphysema destroys alveolar walls, merging airspaces into larger, less efficient units with reduced surface area and elastic recoil.",
    "Emphysema = alveolar wall destruction, enlarged airspaces."),
  Q("t10_a2", "t10", "Anatomy",
    "Chronic bronchitis is characterised histologically by:",
    ["Loss of all goblet cells", "Hypertrophy of mucous glands and goblet cell hyperplasia", "Squamous metaplasia of the alveoli", "Thinning of the bronchial wall", "Increased ciliary function"], 1,
    "Chronic bronchitis shows mucous gland hypertrophy and goblet cell hyperplasia, increasing mucus and the Reid index.",
    "Chronic bronchitis: mucous gland hypertrophy + goblet hyperplasia."),
  Q("t10_a3", "t10", "Anatomy",
    "Which muscles are recruited as accessory muscles of expiration in COPD?",
    ["Diaphragm and external intercostals", "Abdominal muscles and internal intercostals", "Scalenes", "Sternocleidomastoid", "Pectoralis minor"], 1,
    "Forced expiration in COPD recruits the abdominal muscles and internal intercostals to push air out of hyperinflated lungs.",
    "Forced expiration: abdominals + internal intercostals."),
  Q("t10_a4", "t10", "Anatomy",
    "A 'barrel chest' in COPD results from:",
    ["Pleural effusion", "Chronic air trapping and lung hyperinflation", "Rib fractures", "Pectus excavatum", "Diaphragm paralysis"], 1,
    "Chronic air trapping hyperinflates the lungs, increasing the antero-posterior chest diameter, the barrel chest.",
    "Barrel chest = chronic hyperinflation/air trapping."),
  Q("t10_a5", "t10", "Anatomy",
    "Which epithelial change (metaplasia) commonly occurs in the airways of chronic smokers?",
    ["Columnar to pseudostratified", "Ciliated columnar to stratified squamous", "Squamous to columnar", "Cuboidal to squamous", "No change occurs"], 1,
    "Smoking drives squamous metaplasia, ciliated columnar epithelium is replaced by stratified squamous, impairing mucociliary clearance.",
    "Smoking → squamous metaplasia of airway epithelium."),

  // ── Physiology & Pathophysiology ──
  Q("t10_p1", "t10", "Physiology & Biochem",
    "Which spirometry result confirms an obstructive picture in COPD?",
    ["FEV1/FVC > 0.7", "FEV1/FVC < 0.7 that is not fully reversible", "Normal FEV1/FVC", "Increased FEV1", "Restrictive pattern"], 1,
    "COPD shows a post-bronchodilator FEV1/FVC below 0.7 with limited reversibility, distinguishing it from asthma.",
    "COPD: FEV1/FVC < 0.7, not fully reversible."),
  Q("t10_p2", "t10", "Physiology & Biochem",
    "Why do some COPD patients become CO2 retainers ('blue bloaters')?",
    ["They hyperventilate constantly", "Chronic hypercapnia blunts the central CO2 drive, relying on hypoxic drive", "They have too few red cells", "Their airways are fully reversible", "They produce excess surfactant"], 1,
    "In chronic CO2 retention the central chemoreceptor response is blunted, so respiration becomes more reliant on the hypoxic drive, relevant when giving oxygen.",
    "Chronic CO2 retainers depend more on hypoxic drive."),
  Q("t10_p3", "t10", "Physiology & Biochem",
    "Why is controlled (not high-flow) oxygen used in some COPD patients?",
    ["High oxygen has no effect", "Excess oxygen can worsen CO2 retention and cause respiratory acidosis", "Oxygen is toxic to all tissues", "It prevents infection", "It increases hypoxic drive"], 1,
    "In CO2 retainers, uncontrolled high-flow oxygen can reduce respiratory drive and worsen hypercapnia/acidosis (target SpO2 88–92%).",
    "Controlled O2 in COPD avoids worsening CO2 retention (aim 88–92%)."),
  Q("t10_p4", "t10", "Physiology & Biochem",
    "What causes the loss of elastic recoil in emphysema?",
    ["Increased surfactant", "Destruction of elastin in alveolar walls (e.g. by proteases)", "Excess collagen deposition", "Bronchial muscle hypertrophy", "Goblet cell loss"], 1,
    "Protease–antiprotease imbalance (worsened by smoking) destroys alveolar elastin, reducing recoil and causing air trapping.",
    "Emphysema: protease destruction of elastin → lost recoil."),
  Q("t10_p5", "t10", "Physiology & Biochem",
    "Alpha-1 antitrypsin deficiency predisposes to early emphysema because:",
    ["It increases mucus production", "Without antitrypsin, neutrophil elastase destroys alveolar tissue unchecked", "It causes bronchospasm", "It thickens the basement membrane", "It blocks surfactant"], 1,
    "Alpha-1 antitrypsin normally inhibits neutrophil elastase; its deficiency lets elastase destroy alveolar walls, causing early (often basal) emphysema.",
    "No alpha-1 antitrypsin → unopposed elastase → early emphysema."),
  Q("t10_p6", "t10", "Physiology & Biochem",
    "Cor pulmonale in COPD refers to:",
    ["Left heart failure from hypertension", "Right heart failure secondary to chronic lung disease", "A heart attack", "Valve stenosis", "Pericarditis"], 1,
    "Chronic hypoxia causes pulmonary vasoconstriction and pulmonary hypertension, leading to right ventricular strain and failure, cor pulmonale.",
    "Cor pulmonale = right heart failure from lung disease."),
  Q("t10_p7", "t10", "Physiology & Biochem",
    "Which mechanism explains hypoxic pulmonary vasoconstriction?",
    ["Low alveolar O2 dilates pulmonary vessels", "Low alveolar O2 constricts local pulmonary vessels to divert blood to better-ventilated areas", "High O2 constricts vessels", "It only occurs in systemic arteries", "It improves all gas exchange"], 1,
    "Pulmonary vessels constrict in response to low alveolar oxygen, diverting blood to better-ventilated alveoli; when widespread (COPD) it raises pulmonary pressure.",
    "Hypoxia constricts pulmonary vessels (matches perfusion to ventilation)."),
  Q("t10_p8", "t10", "Physiology & Biochem",
    "Why do 'pink puffers' maintain near-normal blood gases?",
    ["They have no lung damage", "They increase ventilation to compensate, keeping O2/CO2 near normal but becoming breathless", "They retain large amounts of CO2", "They have polycythaemia", "They never desaturate"], 1,
    "Emphysema-predominant 'pink puffers' hyperventilate to maintain gases near normal, at the cost of marked breathlessness.",
    "Pink puffers hyperventilate to keep gases near-normal."),

  // ── Clinical & Pharmacology ──
  Q("t10_c1", "t10", "Clinical & Pharmacology",
    "Which inhaler class is typically first-line maintenance in COPD (unlike in asthma)?",
    ["Inhaled corticosteroid monotherapy", "Long-acting bronchodilators (LABA and/or LAMA)", "Oral steroids daily", "Leukotriene antagonists", "Antibiotics daily"], 1,
    "COPD maintenance is built on long-acting bronchodilators (LABA and/or LAMA); inhaled steroids are added in specific cases, not used alone.",
    "COPD maintenance: long-acting bronchodilators (LABA/LAMA)."),
  Q("t10_c2", "t10", "Clinical & Pharmacology",
    "A LAMA (e.g. tiotropium) produces bronchodilation by:",
    ["Stimulating beta-2 receptors", "Blocking muscarinic (M3) receptors to reduce bronchoconstriction", "Blocking histamine", "Increasing mucus", "Inhibiting leukotrienes"], 1,
    "Long-acting muscarinic antagonists block M3 receptors on airway smooth muscle, preventing cholinergic bronchoconstriction.",
    "LAMAs block M3 muscarinic receptors → bronchodilation."),
  Q("t10_c3", "t10", "Clinical & Pharmacology",
    "What is the single most effective intervention to slow COPD progression?",
    ["Antibiotics", "Smoking cessation", "Daily oral steroids", "Bronchodilators alone", "Annual spirometry"], 1,
    "Smoking cessation is the only intervention shown to slow the decline in lung function in COPD.",
    "Smoking cessation slows COPD progression most."),
  Q("t10_c4", "t10", "Clinical & Pharmacology",
    "Which is a recognised long-term treatment that improves survival in chronic hypoxaemic COPD?",
    ["Long-term oral steroids", "Long-term oxygen therapy (≥15 hours/day)", "Daily antibiotics", "Regular nebulised saline", "Caffeine"], 1,
    "Long-term oxygen therapy for at least 15 hours/day improves survival in chronically hypoxaemic COPD patients.",
    "LTOT (≥15 h/day) improves survival in hypoxaemic COPD."),
  Q("t10_c5", "t10", "Clinical & Pharmacology",
    "Which organism is a common cause of infective COPD exacerbations?",
    ["Mycobacterium tuberculosis", "Haemophilus influenzae", "Pneumocystis jirovecii", "Clostridium difficile", "Helicobacter pylori"], 1,
    "Haemophilus influenzae (with Strep pneumoniae and Moraxella catarrhalis) is a common cause of infective COPD exacerbations.",
    "H. influenzae is a classic COPD exacerbation pathogen."),

  // ── Ethics & EBM ──
  Q("t10_e1", "t10", "Ethics & EBM",
    "A long-term smoker with COPD continues to smoke. The doctor should:",
    ["Refuse to treat the patient", "Continue to offer evidence-based support and respect the patient's autonomy", "Withhold inhalers until they quit", "Discharge them from clinic", "Report them to authorities"], 1,
    "Care should remain non-judgemental: keep offering cessation support and treatment while respecting the patient's autonomy.",
    "Keep supporting and treating; respect autonomy."),
  Q("t10_e2", "t10", "Ethics & EBM",
    "A study reports that smoking cessation reduces COPD mortality with a relative risk reduction of 30%. This describes:",
    ["The absolute number of deaths prevented", "The proportional reduction in risk in the treated group versus control", "The number needed to harm", "The incidence of COPD", "The prevalence of smoking"], 1,
    "Relative risk reduction is the proportional fall in risk in the intervention group compared with the control group.",
    "RRR = proportional risk reduction vs control."),

  // ── Behavioural & Social Sciences ──
  Q("t10_b1", "t10", "BSS",
    "A patient with COPD wants to stop smoking and asks for help. Using the Transtheoretical model, which stage are they in?",
    ["Precontemplation", "Contemplation", "Preparation/Action", "Relapse", "Termination"], 2,
    "Actively seeking help to quit indicates the preparation/action stage of behaviour change.",
    "Ready and seeking help = preparation/action."),
  Q("t10_b2", "t10", "BSS",
    "Which is an example of a social determinant that worsens COPD outcomes?",
    ["Genetic predisposition only", "Living in an area of high air pollution and deprivation", "Normal ageing", "Having a GP", "Receiving vaccinations"], 1,
    "Air pollution and socioeconomic deprivation are social determinants associated with worse COPD outcomes.",
    "Pollution + deprivation worsen COPD outcomes."),
  Q("t10_b3", "t10", "BSS",
    "Pulmonary rehabilitation improves COPD outcomes mainly by:",
    ["Curing the lung damage", "Improving exercise capacity, confidence and quality of life", "Replacing all medication", "Reversing emphysema", "Eliminating breathlessness entirely"], 1,
    "Pulmonary rehabilitation (exercise + education) improves exercise tolerance, confidence and quality of life, though it cannot reverse the structural damage.",
    "Pulmonary rehab improves function and quality of life."),
);
