// questions/t11.jsx, Theme 11: Heart valve dysfunction
// Source: ISocMedEd Theme 11 Heart Valve Dysfunction 2025. Image items omitted. Answers authored.

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t11_a1", "t11", "Anatomy",
    "Which heart valve lies between the left atrium and left ventricle?",
    ["Tricuspid valve", "Pulmonary valve", "Mitral (bicuspid) valve", "Aortic valve", "Eustachian valve"], 2,
    "The mitral (bicuspid) valve separates the left atrium and left ventricle. The tricuspid valve is the right-sided atrioventricular valve.",
    "Mitral valve = left atrium → left ventricle."),
  Q("t11_a2", "t11", "Anatomy",
    "Where is the aortic valve best auscultated?",
    ["5th intercostal space, mid-clavicular line", "2nd intercostal space, right sternal edge", "2nd intercostal space, left sternal edge", "Lower left sternal edge", "Apex"], 1,
    "The aortic area is the 2nd intercostal space at the right sternal edge.",
    "Aortic valve auscultated at 2nd ICS, right sternal edge."),
  Q("t11_a3", "t11", "Anatomy",
    "Which structures prevent the atrioventricular valves from prolapsing into the atria during systole?",
    ["Trabeculae carneae", "Chordae tendineae and papillary muscles", "Moderator band", "Pectinate muscles", "Coronary sinus"], 1,
    "Chordae tendineae, anchored by papillary muscles, hold the AV valve leaflets and prevent prolapse during ventricular contraction.",
    "Chordae tendineae + papillary muscles stop AV-valve prolapse."),
  Q("t11_a4", "t11", "Anatomy",
    "The mitral area (apex) is normally located at the:",
    ["2nd intercostal space, right sternal edge", "5th intercostal space, mid-clavicular line", "Xiphisternum", "2nd left intercostal space", "4th right intercostal space"], 1,
    "The apex beat and mitral area lie at the 5th intercostal space in the mid-clavicular line.",
    "Mitral area/apex: 5th ICS, mid-clavicular line."),
  Q("t11_a5", "t11", "Anatomy",
    "Which valves are the semilunar valves?",
    ["Mitral and tricuspid", "Aortic and pulmonary", "Aortic and mitral", "Pulmonary and tricuspid", "Mitral and pulmonary"], 1,
    "The aortic and pulmonary valves are the semilunar valves, lying between the ventricles and their great arteries.",
    "Semilunar valves: aortic + pulmonary."),
  Q("t11_a6", "t11", "Anatomy",
    "Radiation of an aortic stenosis murmur is classically heard:",
    ["To the axilla", "To the carotids", "To the back", "To the epigastrium", "No radiation"], 1,
    "The ejection-systolic murmur of aortic stenosis classically radiates to the carotids. Mitral regurgitation radiates to the axilla.",
    "Aortic stenosis murmur radiates to the carotids."),

  // ── Physiology & Pathophysiology ──
  Q("t11_p1", "t11", "Physiology & Biochem",
    "Which murmur is characteristic of aortic stenosis?",
    ["Early diastolic murmur", "Ejection systolic murmur", "Pansystolic murmur", "Mid-diastolic rumble", "Continuous machinery murmur"], 1,
    "Aortic stenosis produces an ejection systolic murmur (crescendo-decrescendo) loudest in the aortic area, radiating to the carotids.",
    "Aortic stenosis = ejection systolic murmur."),
  Q("t11_p2", "t11", "Physiology & Biochem",
    "Mitral regurgitation typically produces which murmur?",
    ["Ejection systolic", "Pansystolic murmur radiating to the axilla", "Early diastolic", "Mid-diastolic", "No murmur"], 1,
    "Mitral regurgitation gives a pansystolic (holosystolic) murmur at the apex radiating to the axilla.",
    "Mitral regurgitation = pansystolic murmur → axilla."),
  Q("t11_p3", "t11", "Physiology & Biochem",
    "In aortic stenosis, the left ventricle compensates by:",
    ["Dilating (eccentric hypertrophy)", "Concentric hypertrophy to overcome the pressure load", "Becoming thinner", "Reducing its muscle mass", "No change"], 1,
    "The pressure overload of aortic stenosis drives concentric left ventricular hypertrophy (thickened wall, preserved cavity size).",
    "Aortic stenosis → concentric LV hypertrophy (pressure overload)."),
  Q("t11_p4", "t11", "Physiology & Biochem",
    "Which valve lesion causes a volume overload leading to eccentric (dilated) hypertrophy?",
    ["Aortic stenosis", "Mitral/aortic regurgitation", "Pulmonary stenosis", "Tricuspid stenosis", "None"], 1,
    "Regurgitant lesions create a volume overload, producing eccentric hypertrophy with chamber dilation.",
    "Regurgitation → volume overload → eccentric (dilated) hypertrophy."),
  Q("t11_p5", "t11", "Physiology & Biochem",
    "The classic triad of symptoms in severe aortic stenosis is:",
    ["Fever, cough, weight loss", "Angina, syncope and breathlessness (heart failure)", "Palpitations, fever, rash", "Haemoptysis, oedema, jaundice", "Headache, nausea, vomiting"], 1,
    "Severe aortic stenosis classically presents with the triad of exertional angina, syncope and heart failure/breathlessness (SAD: Syncope, Angina, Dyspnoea).",
    "Aortic stenosis triad: angina, syncope, dyspnoea."),
  Q("t11_p6", "t11", "Physiology & Biochem",
    "A 'slow-rising' pulse is most associated with:",
    ["Aortic regurgitation", "Aortic stenosis", "Mitral stenosis", "Mitral regurgitation", "Tricuspid regurgitation"], 1,
    "Aortic stenosis produces a slow-rising, low-volume pulse (pulsus parvus et tardus); aortic regurgitation gives a collapsing pulse.",
    "Aortic stenosis: slow-rising pulse; aortic regurgitation: collapsing pulse."),
  Q("t11_p7", "t11", "Physiology & Biochem",
    "Rheumatic fever is a classic cause of which valve lesion?",
    ["Mitral stenosis", "Aortic dilatation", "Pulmonary stenosis", "Tricuspid atresia", "Atrial septal defect"], 0,
    "Rheumatic heart disease most characteristically causes mitral stenosis, with thickened, fused valve leaflets.",
    "Rheumatic fever → mitral stenosis."),
  Q("t11_p8", "t11", "Physiology & Biochem",
    "Which heart sound corresponds to closure of the aortic and pulmonary (semilunar) valves?",
    ["First heart sound (S1)", "Second heart sound (S2)", "Third heart sound (S3)", "Fourth heart sound (S4)", "Opening snap"], 1,
    "S2 is produced by closure of the aortic and pulmonary valves; S1 is closure of the mitral and tricuspid valves.",
    "S2 = aortic + pulmonary valve closure."),

  // ── Clinical & Pharmacology ──
  Q("t11_c1", "t11", "Clinical & Pharmacology",
    "What is the definitive treatment for symptomatic severe aortic stenosis?",
    ["Beta-blockers", "Aortic valve replacement (surgical or TAVI)", "Diuretics alone", "Lifestyle change only", "Aspirin"], 1,
    "Symptomatic severe aortic stenosis is treated definitively by aortic valve replacement, surgical or transcatheter (TAVI).",
    "Symptomatic severe AS → valve replacement (surgery or TAVI)."),
  Q("t11_c2", "t11", "Clinical & Pharmacology",
    "Patients with mechanical heart valves require long-term:",
    ["Aspirin only", "Warfarin (anticoagulation)", "No medication", "Antibiotics daily", "Beta-blockers only"], 1,
    "Mechanical valves are thrombogenic and require lifelong anticoagulation with warfarin (DOACs are not licensed for mechanical valves).",
    "Mechanical valves need lifelong warfarin."),
  Q("t11_c3", "t11", "Clinical & Pharmacology",
    "Which investigation is first-line to assess valve structure and function?",
    ["Chest X-ray", "Echocardiography", "ECG", "Coronary angiography", "Full blood count"], 1,
    "Echocardiography is the first-line, non-invasive investigation for assessing valve anatomy, severity and ventricular function.",
    "Echocardiography is first-line for valve assessment."),
  Q("t11_c4", "t11", "Clinical & Pharmacology",
    "Infective endocarditis prophylaxis or prompt treatment is especially important in valve disease because vegetations can:",
    ["Improve valve function", "Embolise and destroy the valve", "Lower blood pressure safely", "Prevent arrhythmias", "Strengthen the chordae"], 1,
    "Endocarditis vegetations can embolise and progressively destroy the valve, causing regurgitation and systemic emboli.",
    "Endocarditis vegetations embolise and wreck the valve."),

  // ── Behavioural & Social Sciences ──
  Q("t11_b1", "t11", "BSS",
    "An elderly patient with severe aortic stenosis declines surgery after understanding the risks and benefits. The team should:",
    ["Override the decision in their best interest", "Respect their autonomous, informed decision", "Refuse further care", "Tell the family to persuade them", "Proceed once sedated"], 1,
    "A competent, informed patient's decision to decline surgery must be respected, even if the team disagrees.",
    "Respect a competent patient's informed refusal."),
  Q("t11_b2", "t11", "BSS",
    "Which factor may reduce an older patient's access to timely valve surgery?",
    ["Living near a hospital", "Frailty, comorbidity and health inequalities", "Good social support", "Early diagnosis", "Regular follow-up"], 1,
    "Frailty, comorbidity and broader health inequalities can delay or limit access to valve surgery in older patients.",
    "Frailty and inequality limit access to valve surgery."),
);
