// questions/t12.jsx, Theme 12: Ischaemic heart disease
// Source: ISocMedEd Theme 12 MCQ Bank 2025/26. Image-dependent items omitted. Answers authored.

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t12_a1", "t12", "Anatomy",
    "The inferior wall of the left ventricle is most commonly supplied by which artery?",
    ["Left anterior descending", "Right coronary artery", "Left circumflex", "Left main stem", "Diagonal branch"], 1,
    "In a right-dominant circulation (most people) the right coronary artery supplies the inferior wall via the posterior descending artery.",
    "Inferior wall → RCA (right-dominant circulation)."),
  Q("t12_a2", "t12", "Anatomy",
    "ST elevation in leads V1–V4 indicates infarction of which territory, supplied by which artery?",
    ["Inferior; RCA", "Anteroseptal; LAD", "Lateral; circumflex", "Posterior; RCA", "Apical; diagonal"], 1,
    "V1–V4 view the anteroseptal wall, supplied by the left anterior descending artery.",
    "V1–V4 = anteroseptal (LAD)."),
  Q("t12_a3", "t12", "Anatomy",
    "The left coronary artery divides into which two main branches?",
    ["RCA and PDA", "LAD and circumflex", "Marginal and PDA", "Diagonal and septal only", "Circumflex and RCA"], 1,
    "The left main coronary artery divides into the left anterior descending and the left circumflex arteries.",
    "Left main → LAD + circumflex."),
  Q("t12_a4", "t12", "Anatomy",
    "Which leads represent the lateral wall of the left ventricle?",
    ["II, III, aVF", "V1–V2", "I, aVL, V5–V6", "V3–V4", "aVR only"], 2,
    "The lateral leads are I, aVL, V5 and V6, supplied by the left circumflex (and diagonal) arteries.",
    "Lateral leads: I, aVL, V5–V6."),
  Q("t12_a5", "t12", "Anatomy",
    "The coronary arteries fill mainly during which phase of the cardiac cycle?",
    ["Systole", "Diastole", "Isovolumetric contraction", "Atrial systole only", "They fill equally throughout"], 1,
    "Coronary perfusion occurs mainly in diastole, when the myocardium relaxes; tachycardia (short diastole) can therefore worsen ischaemia.",
    "Coronaries fill in diastole."),

  // ── Physiology & Pathophysiology ──
  Q("t12_p1", "t12", "Physiology & Biochem",
    "What is the underlying pathological process in most ischaemic heart disease?",
    ["Vasospasm only", "Atherosclerosis of the coronary arteries", "Valve calcification", "Pericardial inflammation", "Conduction block"], 1,
    "Atherosclerosis, lipid-rich plaque in the coronary arteries, is the basis of most ischaemic heart disease.",
    "IHD is usually due to coronary atherosclerosis."),
  Q("t12_p2", "t12", "Physiology & Biochem",
    "Stable angina pain is typically:",
    ["Constant and unrelated to activity", "Brought on by exertion and relieved by rest or GTN", "Worse lying flat", "Sharp and pleuritic", "Relieved by exercise"], 1,
    "Stable angina is exertional chest pain from a fixed demand–supply mismatch, relieved within minutes by rest or GTN.",
    "Stable angina: exertional, relieved by rest/GTN."),
  Q("t12_p3", "t12", "Physiology & Biochem",
    "Which best distinguishes unstable angina from a NSTEMI?",
    ["ST elevation present in NSTEMI", "Troponin is raised in NSTEMI but not in unstable angina", "Unstable angina always shows Q waves", "They are identical", "NSTEMI has no symptoms"], 1,
    "Both are acute coronary syndromes without ST elevation; a NSTEMI causes myocardial necrosis with raised troponin, whereas unstable angina does not.",
    "NSTEMI raises troponin; unstable angina does not."),
  Q("t12_p4", "t12", "Physiology & Biochem",
    "Which biomarker is most specific for myocardial infarction?",
    ["Myoglobin", "Cardiac troponin (I or T)", "Creatine kinase (total)", "AST", "LDH"], 1,
    "Cardiac troponin I/T is the most sensitive and specific biomarker of myocardial injury, rising within a few hours of infarction.",
    "Cardiac troponin = most specific MI marker."),
  Q("t12_p5", "t12", "Physiology & Biochem",
    "Which type of necrosis occurs in the myocardium after infarction?",
    ["Liquefactive", "Coagulative necrosis", "Caseous", "Fat necrosis", "Fibrinoid"], 1,
    "Myocardial infarction causes coagulative necrosis, with preserved tissue outlines for several days.",
    "MI → coagulative necrosis."),
  Q("t12_p6", "t12", "Physiology & Biochem",
    "A patient with inferior STEMI develops bradycardia and hypotension. This is often due to:",
    ["LAD occlusion", "RCA involvement affecting the SA/AV node and vagal tone", "Aortic dissection", "Pulmonary embolism", "Pericarditis"], 1,
    "The RCA usually supplies the SA and AV nodes, so inferior (RCA) infarcts often cause bradyarrhythmias and increased vagal tone.",
    "Inferior STEMI (RCA) can cause bradycardia (nodal supply)."),
  Q("t12_p7", "t12", "Physiology & Biochem",
    "Why can a rapid heart rate worsen myocardial ischaemia?",
    ["It increases diastolic filling time", "It shortens diastole, reducing coronary perfusion while increasing oxygen demand", "It lowers blood pressure only", "It dilates coronaries", "It has no effect"], 1,
    "Tachycardia both raises myocardial oxygen demand and shortens diastole (when coronaries fill), worsening the supply–demand mismatch.",
    "Tachycardia ↑demand and ↓coronary filling time."),
  Q("t12_p8", "t12", "Physiology & Biochem",
    "Which complication may occur days after a large MI due to wall weakening?",
    ["Valve stenosis", "Myocardial (free wall or septal) rupture", "Atrial myxoma", "Pericardial cyst", "Coronary aneurysm"], 1,
    "Several days post-MI, necrotic myocardium is weakest and may rupture (free wall, septum or papillary muscle), often catastrophically.",
    "Myocardial rupture risk peaks a few days post-MI."),

  // ── Clinical & Pharmacology ──
  Q("t12_c1", "t12", "Clinical & Pharmacology",
    "What is the immediate definitive treatment for a STEMI presenting within the PCI window?",
    ["Thrombolysis only", "Primary percutaneous coronary intervention (PCI)", "Beta-blocker alone", "Warfarin", "Watchful waiting"], 1,
    "Primary PCI to reopen the occluded artery is the definitive reperfusion treatment for STEMI when available in time.",
    "STEMI → primary PCI (reperfusion)."),
  Q("t12_c2", "t12", "Clinical & Pharmacology",
    "Which drug combination is part of immediate management of an acute coronary syndrome?",
    ["Aspirin + a second antiplatelet (e.g. ticagrelor)", "Two antibiotics", "Two diuretics", "Insulin + steroid", "Vitamin K + iron"], 0,
    "Dual antiplatelet therapy, aspirin plus a P2Y12 inhibitor (e.g. ticagrelor or clopidogrel), is given early in ACS.",
    "ACS: dual antiplatelets (aspirin + P2Y12 inhibitor)."),
  Q("t12_c3", "t12", "Clinical & Pharmacology",
    "How does glyceryl trinitrate (GTN) relieve angina?",
    ["Increases heart rate", "Venodilation reduces preload and dilates coronaries, lowering oxygen demand", "Blocks platelets", "Raises blood pressure", "Thins the blood"], 1,
    "GTN releases nitric oxide, causing venodilation (reduced preload) and coronary dilation, lowering myocardial oxygen demand.",
    "GTN: venodilation → ↓preload → ↓oxygen demand."),
  Q("t12_c4", "t12", "Clinical & Pharmacology",
    "Which class of drug is given long-term post-MI to reduce mortality by lowering heart rate and myocardial demand?",
    ["Calcium gluconate", "Beta-blockers", "Antihistamines", "Proton pump inhibitors", "Laxatives"], 1,
    "Beta-blockers reduce heart rate and contractility, lowering myocardial oxygen demand and improving survival after MI.",
    "Beta-blockers improve post-MI survival."),
  Q("t12_c5", "t12", "Clinical & Pharmacology",
    "Which lipid-lowering drug class is standard secondary prevention after MI?",
    ["Fibrates", "High-intensity statins", "Bile-acid resins only", "Niacin", "No lipid treatment"], 1,
    "High-intensity statins (e.g. atorvastatin 80 mg) are standard secondary prevention, stabilising plaque and lowering LDL.",
    "Statins are standard secondary prevention post-MI."),
  Q("t12_c6", "t12", "Clinical & Pharmacology",
    "The mnemonic for initial medical management of ACS (besides PCI) is often 'MONA' plus antiplatelets. What does it stand for?",
    ["Morphine, Oxygen (if hypoxic), Nitrates, Aspirin", "Metformin, Oxygen, Naloxone, Adrenaline", "Morphine, Omeprazole, Nitrates, Atropine", "Magnesium, Oxygen, Nitrates, Adenosine", "Morphine, Oxygen, Naproxen, Amiodarone"], 0,
    "MONA = Morphine, Oxygen (only if hypoxic), Nitrates and Aspirin, adjuncts alongside reperfusion and a second antiplatelet.",
    "MONA: Morphine, Oxygen (if needed), Nitrates, Aspirin."),

  // ── Ethics & EBM ──
  Q("t12_e1", "t12", "Ethics & EBM",
    "A trial shows a new antiplatelet reduces MI deaths from 10% to 8%. What is the absolute risk reduction?",
    ["20%", "2%", "8%", "10%", "80%"], 1,
    "Absolute risk reduction = 10% − 8% = 2% (the NNT would be 1/0.02 = 50).",
    "ARR = control − treatment risk = 2%."),
  Q("t12_e2", "t12", "Ethics & EBM",
    "An unconscious patient with a STEMI needs emergency PCI but cannot consent. The team should:",
    ["Wait for the patient to wake up", "Act in the patient's best interests under emergency doctrine", "Refuse treatment", "Only treat if family sign forms", "Discharge the patient"], 1,
    "In an emergency where the patient lacks capacity, clinicians act in the patient's best interests without delay.",
    "Emergency + no capacity → act in best interests."),

  // ── Behavioural & Social Sciences ──
  Q("t12_b1", "t12", "BSS",
    "Which lifestyle factor is the single most important modifiable risk factor for ischaemic heart disease?",
    ["Caffeine intake", "Smoking", "Reading", "Sleeping 8 hours", "Drinking water"], 1,
    "Smoking is the most important modifiable risk factor for IHD; cessation substantially lowers risk.",
    "Smoking is the key modifiable IHD risk factor."),
  Q("t12_b2", "t12", "BSS",
    "Cardiac rehabilitation after an MI primarily aims to:",
    ["Cure the coronary disease", "Improve recovery, reduce risk factors and support psychological wellbeing", "Replace all medication", "Avoid all exercise", "Increase hospital stays"], 1,
    "Cardiac rehabilitation combines supervised exercise, risk-factor modification and psychological support to improve recovery and reduce recurrence.",
    "Cardiac rehab: exercise + risk reduction + psychological support."),
);
