// questions/t13.jsx, Theme 13: Hypertension
// Source: ISocMedEd Theme 13 MCQ Bank 2026. Image-dependent items (anatomy diagram
// questions 3 & 4) omitted. Answers & explanations authored to accompany the bank.

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t13_a1", "t13", "Anatomy",
    "Which of the following correctly describes the jugular notch?",
    ["A palpable dip in the manubrium between the clavicles at the level of T2",
     "A palpable dip in the manubrium between the clavicles at the level of the 2nd rib",
     "A transverse ridge at the junction of the manubrium and body of the sternum at the level of T4/T5",
     "A transverse ridge at the junction of the manubrium and body of the sternum at the level of T2",
     "A midline bony prominence at the inferior end of the sternal body at the level of T9"], 0,
    "The jugular (suprasternal) notch is the palpable dip in the superior border of the manubrium, between the medial ends of the clavicles, lying at about the level of T2. The transverse ridge at the manubriosternal junction (option C) is the sternal angle at T4/T5, and the prominence at the inferior sternum (option E) is the xiphoid process.",
    "Jugular notch = dip in the manubrium between the clavicles (~T2)."),
  Q("t13_a2", "t13", "Anatomy",
    "The 2nd rib articulates with the sternum at which palpable landmark?",
    ["Jugular notch", "Xiphoid process", "Sternal angle", "Sternoclavicular joint", "Body of sternum (midpoint)"], 2,
    "The 2nd costal cartilage articulates at the sternal angle (angle of Louis), the ridge at the manubriosternal junction. This makes it the key surface landmark for counting ribs.",
    "Sternal angle = articulation of the 2nd rib (rib-counting landmark)."),
  Q("t13_a5", "t13", "Anatomy",
    "Which of the following defines the superior border of the heart?",
    ["3rd right costal cartilage → 6th right costal cartilage",
     "6th right costal cartilage → 5th intercostal space, midclavicular line",
     "2nd left costal cartilage → 5th intercostal space, midclavicular line",
     "5th intercostal space, midclavicular line → 6th right costal cartilage",
     "2nd left costal cartilage → 3rd right costal cartilage"], 4,
    "The superior border of the heart is the line joining the 2nd left costal cartilage to the 3rd right costal cartilage. The right border runs 3rd→6th right costal cartilage, the inferior border 6th right costal cartilage→cardiac apex, and the left border 2nd left costal cartilage→apex.",
    "Superior border: 2nd left costal cartilage → 3rd right costal cartilage."),
  Q("t13_a6", "t13", "Anatomy",
    "Which of the following defines the left border of the heart?",
    ["3rd right costal cartilage → 6th right costal cartilage",
     "6th right costal cartilage → 5th intercostal space, midclavicular line",
     "2nd left costal cartilage → 5th intercostal space, midclavicular line",
     "2nd left costal cartilage → 3rd right costal cartilage",
     "5th intercostal space → 2nd right costal cartilage"], 2,
    "The left border, formed mainly by the left ventricle, runs from the 2nd left costal cartilage down to the apex at the 5th intercostal space in the midclavicular line.",
    "Left border: 2nd left costal cartilage → apex (5th ICS, MCL)."),
  Q("t13_a7", "t13", "Anatomy",
    "The apex of the heart is usually located at which of the following thoracic landmarks?",
    ["2nd intercostal space, right sternal edge",
     "5th intercostal space, midclavicular line",
     "4th intercostal space, left sternal edge",
     "Just below the clavicle",
     "6th intercostal space, midaxillary line"], 1,
    "The cardiac apex (formed by the left ventricle) lies in the 5th intercostal space in the left midclavicular line, where the apex beat is normally palpated.",
    "Cardiac apex = 5th intercostal space, midclavicular line."),
  Q("t13_a8", "t13", "Anatomy",
    "The apex of the lung can be found at which of the following levels?",
    ["Just above the first rib",
     "Level of the sternal notch",
     "Approximately 2–3 cm above the medial third of the clavicle",
     "At the level of the 2nd intercostal space",
     "Midway between the clavicle and the manubrium"], 2,
    "The lung apex extends into the root of the neck, projecting about 2–3 cm above the medial third of the clavicle, which is why it is vulnerable in supraclavicular procedures.",
    "Lung apex sits ~2–3 cm above the medial third of the clavicle."),

  // ── Physiology & Pathophysiology ──
  Q("t13_p9", "t13", "Physiology & Biochem",
    "Which vessel type is best characterised by a prominent internal elastic lamina and a tunica media dominated by smooth muscle rather than elastic lamellae?",
    ["Elastic (conducting) artery", "Muscular (distributing) artery", "Capillary", "Venule", "Lymphatic capillary"], 1,
    "Muscular (distributing) arteries have a thick, smooth-muscle-rich tunica media bounded by a prominent internal elastic lamina, allowing them to regulate flow to organs. Elastic arteries instead have media dominated by concentric elastic lamellae.",
    "Muscular artery: smooth-muscle media + prominent internal elastic lamina."),
  Q("t13_p10", "t13", "Physiology & Biochem",
    "Which statement best explains why deep veins in the lower limb can return blood to the heart despite low venous pressure?",
    ["Venous tunica media is thicker than arterial tunica media, generating higher resting pressure",
     "One-way valves plus skeletal muscle contraction (the calf muscle pump) propel blood proximally and prevent reflux",
     "High capillary hydrostatic pressure directly forces venous return",
     "Pulmonary venous pressure is transmitted to the systemic venous system",
     "Venous return is independent of pressure gradients because venous blood is actively transported"], 1,
    "Low-pressure venous return from the legs relies on the calf muscle pump: contraction squeezes the deep veins while one-way valves ensure blood moves only towards the heart and cannot reflux.",
    "Venous return from legs = calf muscle pump + one-way valves."),
  Q("t13_p11", "t13", "Physiology & Biochem",
    "A student states: \u201cMean arterial pressure (MAP) is proportional to cardiac output (CO) \u00d7 total peripheral resistance (TPR).\u201d Which change would increase MAP primarily by increasing TPR?",
    ["Increased heart rate with unchanged arteriolar tone",
     "Increased stroke volume due to increased venous return",
     "Arteriolar vasoconstriction in multiple vascular beds",
     "Reduced blood viscosity due to anaemia",
     "Reduced sympathetic outflow to resistance vessels"], 2,
    "TPR is set mainly by arteriolar tone. Widespread arteriolar vasoconstriction raises resistance and therefore MAP. Increased heart rate or stroke volume would raise MAP through cardiac output, not TPR.",
    "Arteriolar vasoconstriction raises MAP via TPR."),
  Q("t13_p12", "t13", "Physiology & Biochem",
    "Which sequence correctly describes blood flow through the pulmonary circulation?",
    ["Left ventricle → aorta → pulmonary arteries → pulmonary veins → left atrium",
     "Right ventricle → pulmonary arteries → pulmonary capillaries → pulmonary veins → left atrium",
     "Right atrium → aorta → systemic capillaries → vena cava → right ventricle",
     "Left atrium → pulmonary arteries → pulmonary capillaries → pulmonary veins → right ventricle",
     "Right ventricle → aorta → bronchial arteries → pulmonary veins → left atrium"], 1,
    "Deoxygenated blood leaves the right ventricle via the pulmonary arteries to the pulmonary capillaries (gas exchange), then returns oxygenated through the pulmonary veins to the left atrium.",
    "RV → pulmonary arteries → capillaries → pulmonary veins → LA."),
  Q("t13_p13", "t13", "Physiology & Biochem",
    "A patient develops ankle swelling after prolonged standing. Which mechanism most directly explains how oedema can be limited under normal physiology?",
    ["Decreased capillary hydrostatic pressure prevents filtration",
     "Increased plasma oncotic pressure pulls fluid into the interstitium",
     "Lymphatic flow can increase markedly to remove excess interstitial fluid when filtration rises",
     "Venous valves prevent any increase in capillary filtration",
     "Red blood cell osmotic pressure prevents fluid movement across capillaries"], 2,
    "When capillary filtration rises (e.g. raised hydrostatic pressure on standing), lymphatic flow can increase substantially to drain the extra interstitial fluid, an important safeguard against oedema.",
    "Increased lymphatic drainage limits oedema when filtration rises."),
  Q("t13_p14", "t13", "Physiology & Biochem",
    "Which statement best describes aldosterone\u2019s place in the renin-angiotensin-aldosterone system (RAAS)?",
    ["Aldosterone directly converts angiotensinogen to angiotensin I",
     "Angiotensin II stimulates aldosterone secretion from the adrenal zona glomerulosa",
     "Aldosterone is secreted primarily by the posterior pituitary",
     "Aldosterone decreases renal sodium reabsorption in the collecting duct",
     "Aldosterone secretion is regulated only by atrial natriuretic peptide (ANP)"], 1,
    "Angiotensin II stimulates the adrenal zona glomerulosa to release aldosterone, which then increases sodium (and water) reabsorption in the collecting duct, raising blood volume and pressure.",
    "Angiotensin II → aldosterone from the zona glomerulosa."),
  Q("t13_p15", "t13", "Physiology & Biochem",
    "A patient has increased circulating atrial natriuretic peptide (ANP). Which physiological effect is most consistent with ANP activity?",
    ["Increased renin release and increased aldosterone",
     "Increased sympathetic outflow and vasoconstriction",
     "Natriuresis/diuresis with suppression of RAAS activity",
     "Increased arginine vasopressin (AVP) action via aquaporin-2 insertion",
     "Increased vascular smooth muscle proliferation and fibrosis"], 2,
    "ANP, released by atrial stretch (volume overload), promotes sodium and water excretion (natriuresis/diuresis) and suppresses the RAAS, lowering blood volume and pressure.",
    "ANP → natriuresis/diuresis and RAAS suppression."),
  Q("t13_p16", "t13", "Physiology & Biochem",
    "Chronic overactivity of angiotensin II signalling can contribute to hypertension beyond acute vasoconstriction by which mechanism?",
    ["Reduction of vascular wall thickness and increased compliance",
     "Vascular wall remodelling with inflammation and increased stiffness",
     "Selective dilation of resistance arterioles with reduced TPR",
     "Increased endothelial nitric oxide production as the dominant long-term effect",
     "Direct inhibition of aldosterone production in the adrenal cortex"], 1,
    "Beyond its acute vasoconstrictor action, chronic angiotensin II drives vascular remodelling, inflammation and fibrosis, stiffening vessel walls and sustaining a raised blood pressure.",
    "Chronic angiotensin II → vascular remodelling, inflammation, stiffness."),
  Q("t13_p17", "t13", "Physiology & Biochem",
    "Which pattern best distinguishes primary (essential) hypertension from secondary hypertension?",
    ["Primary hypertension is always due to a single, identifiable endocrine tumour",
     "Secondary hypertension has no identifiable cause and is diagnosed by exclusion",
     "Primary hypertension reflects multifactorial dysregulation of BP control systems, whereas secondary hypertension is driven by a specific underlying condition",
     "Primary hypertension occurs only in pregnancy-capable individuals",
     "Secondary hypertension is defined only by higher systolic thresholds than primary hypertension"], 2,
    "Primary (essential) hypertension, about 90–95% of cases, arises from multifactorial dysregulation of blood-pressure control with no single cause. Secondary hypertension is driven by an identifiable underlying condition (e.g. renal or endocrine disease).",
    "Primary HTN = multifactorial; secondary HTN = a specific underlying cause."),
  Q("t13_p18", "t13", "Physiology & Biochem",
    "Which statement best reflects the typical overall effect of regular aerobic training on resting blood pressure across different baseline blood pressure categories?",
    ["Aerobic training has no meaningful effect on resting blood pressure at the population level",
     "Aerobic training lowers resting blood pressure on average, with larger reductions generally seen in people with hypertension than in those with normal blood pressure",
     "Aerobic training increases resting systolic blood pressure because it increases stroke volume",
     "Blood pressure reduction only occurs with very high intensity exercise; moderate intensity has no effect",
     "Aerobic training lowers diastolic blood pressure only, not systolic blood pressure"], 1,
    "Regular aerobic exercise lowers resting blood pressure on average, and the reduction is generally greater in people who are hypertensive than in those who are normotensive, which is why it is recommended as a core lifestyle measure.",
    "Aerobic training lowers resting BP, most in hypertensives."),

  // ── Pharmacology ──
  Q("t13_c1", "t13", "Clinical & Pharmacology",
    "In UK NICE stepwise treatment for uncomplicated hypertension, which drug class is commonly used as first-line (Step 1) in people aged under 55 years (who are not pregnant)?",
    ["Thiazide-like diuretic", "ACE inhibitor", "Loop diuretic", "Alpha blocker", "Direct renin inhibitor"], 1,
    "NICE recommends an ACE inhibitor (or ARB) as Step 1 for people under 55 (and not of Black African/Caribbean origin), reflecting their typically higher-renin hypertension. People ≥55 or of Black African/Caribbean origin start on a calcium channel blocker.",
    "NICE Step 1 (<55, not pregnant): ACE inhibitor (or ARB)."),
  Q("t13_c2", "t13", "Clinical & Pharmacology",
    "Which statement best describes how ACE inhibitors lower blood pressure?",
    ["They block L-type calcium channels in vascular smooth muscle causing vasodilation",
     "They block conversion of angiotensin I to angiotensin II, lowering arteriolar resistance and reducing aldosterone effects over time",
     "They directly block mineralocorticoid receptors in the collecting duct",
     "They directly increase renin release to raise blood pressure",
     "They inhibit the Na-Cl cotransporter in the thick ascending limb of the loop of Henle"], 1,
    "ACE inhibitors block angiotensin-converting enzyme, reducing angiotensin II formation. This lowers arteriolar resistance and, over time, reduces aldosterone-driven sodium and water retention.",
    "ACE inhibitors block angiotensin I → II conversion."),
  Q("t13_c3", "t13", "Clinical & Pharmacology",
    "Which drug class most directly lowers blood pressure by blocking calcium entry into vascular smooth muscle and causing arteriolar vasodilation?",
    ["Calcium channel blocker", "ACE inhibitor", "Angiotensin receptor blocker", "Beta-blocker", "Thiazide diuretic"], 0,
    "Calcium channel blockers (e.g. amlodipine) block L-type calcium channels in vascular smooth muscle, reducing contraction and causing arteriolar vasodilation that lowers peripheral resistance.",
    "CCBs block Ca²⁺ entry → arteriolar vasodilation."),
  Q("t13_c4", "t13", "Clinical & Pharmacology",
    "A patient remains hypertensive on optimal doses of an ACE inhibitor (or ARB), a calcium channel blocker and a thiazide-like diuretic (NICE Step 3). Which add-on is a typical next option in resistant hypertension when potassium is ≤4.5 mmol/L?",
    ["Spironolactone", "Amlodipine", "Hydrochlorothiazide alone as monotherapy", "ACE inhibitor plus ARB combination", "Sublingual nitroglycerin"], 0,
    "For resistant hypertension at Step 4, NICE suggests low-dose spironolactone if blood potassium is ≤4.5 mmol/L; if potassium is higher, an alpha- or beta-blocker is preferred instead.",
    "Step 4 resistant HTN, K⁺ ≤4.5: add spironolactone."),

  // ── Behavioural and Social Sciences ──
  Q("t13_b1", "t13", "BSS",
    "A patient with type 2 diabetes struggles to adhere to lifestyle advice despite understanding the risks. Which behavioural model best explains the importance of perceived susceptibility and severity in motivating behaviour change?",
    ["The Health Belief Model", "The Transtheoretical Model", "Social Cognitive Theory", "The Theory of Planned Behaviour", "Classical Conditioning"], 0,
    "The Health Belief Model proposes that behaviour change depends on perceived susceptibility and perceived severity of a condition, weighed against the perceived benefits and barriers of acting.",
    "Perceived susceptibility + severity → Health Belief Model."),
  Q("t13_b2", "t13", "BSS",
    "A patient attempting weight loss moves from \u201cI know I should eat healthier\u201d to actively planning meals and reducing portion sizes. Which stage of change does this represent in the Transtheoretical Model?",
    ["Precontemplation", "Contemplation", "Preparation", "Action", "Maintenance"], 2,
    "Beginning to make concrete plans and small initial changes, like planning meals and cutting portions, characterises the preparation stage, the step between contemplation and full action.",
    "Planning + small initial changes = Preparation stage."),
  Q("t13_b3", "t13", "BSS",
    "A clinician encourages a patient to increase physical activity by setting achievable goals and improving confidence in their ability to exercise regularly. Which concept from Social Cognitive Theory is being applied?",
    ["Self-efficacy", "Reinforcement", "Observational learning", "Outcome expectations", "Reciprocal determinism"], 0,
    "Self-efficacy is a person's belief in their own ability to perform a behaviour. Setting achievable goals to build confidence is a classic strategy for strengthening it.",
    "Building confidence to act = self-efficacy."),
  Q("t13_b4", "t13", "BSS",
    "Which of the following is a well-established wider societal benefit of increased physical activity levels?",
    ["Increased healthcare costs due to more injuries",
     "Reduced workforce productivity",
     "Lower incidence of chronic diseases such as cardiovascular disease and type 2 diabetes",
     "Increased reliance on pharmacological treatments",
     "Reduced mental well-being at a population level"], 2,
    "At a population level, greater physical activity lowers the incidence of chronic diseases such as cardiovascular disease and type 2 diabetes, reducing the wider burden on healthcare and society.",
    "Population physical activity → lower chronic disease burden."),
  Q("t13_b5", "t13", "BSS",
    "A smoker says, \u201cI know smoking is bad and I\u2019ve been thinking about quitting, but I haven\u2019t made any plans yet.\u201d Which stage of change does this represent in the Transtheoretical Model?",
    ["Precontemplation", "Contemplation", "Preparation", "Action", "Maintenance"], 1,
    "Being aware of the problem and thinking about change, but not yet committed to a plan or timeframe, defines the contemplation stage.",
    "Aware + considering change, no plan yet = Contemplation."),
  Q("t13_b6", "t13", "BSS",
    "Which of the following best defines adherence in a healthcare context?",
    ["The extent to which a patient follows medical advice exactly as instructed by the clinician",
     "The degree to which a patient\u2019s behaviour aligns with agreed recommendations from a healthcare professional",
     "A patient\u2019s willingness to accept a diagnosis and its implications",
     "The ability of a patient to consistently attend follow-up appointments",
     "A patient\u2019s understanding of their condition and treatment plan"], 1,
    "Adherence is defined as the degree to which a patient's behaviour aligns with recommendations that were mutually agreed with the healthcare professional, emphasising a collaborative relationship, unlike the more paternalistic notion of 'compliance' (option A).",
    "Adherence = behaviour matching mutually agreed recommendations."),
);
