// questions/t14.jsx, Theme 14: Haematology
// Source: ISocMedEd Theme 14 Haematology MCQ Answers 2026 (official key). Image item omitted.

window.QUESTIONS.push(
  // ── Anatomy & Histology ──
  Q("t14_a1", "t14", "Anatomy",
    "Where does erythropoiesis primarily occur in adults?",
    ["Liver", "Spleen", "Red bone marrow", "Lymph nodes", "Thymus"], 2,
    "In adults, erythropoiesis occurs mainly in the red bone marrow of the flat bones.",
    "Adult erythropoiesis: red bone marrow."),
  Q("t14_a2", "t14", "Anatomy",
    "What is the average lifespan of a red blood cell?",
    ["30 days", "60 days", "90 days", "120 days", "180 days"], 3,
    "Red blood cells circulate for about 120 days before being removed (mainly by the spleen).",
    "RBC lifespan ≈ 120 days."),
  Q("t14_a3", "t14", "Anatomy",
    "Which white blood cell is most abundant in circulation?",
    ["Lymphocyte", "Monocyte", "Neutrophil", "Eosinophil", "Basophil"], 2,
    "Neutrophils make up about 60–70% of circulating leukocytes.",
    "Neutrophils are the most abundant white cell (60–70%)."),
  Q("t14_a4", "t14", "Anatomy",
    "Which leukocyte is primarily involved in allergic reactions?",
    ["Neutrophil", "Monocyte", "Eosinophil", "Basophil", "Lymphocyte"], 3,
    "Both eosinophils and basophils participate in allergic reactions; basophils (like mast cells) release histamine. (The bank accepts eosinophil or basophil here.)",
    "Basophils and eosinophils mediate allergy."),
  Q("t14_a5", "t14", "Anatomy",
    "Which leukocyte has a multilobed nucleus?",
    ["Monocyte", "Lymphocyte", "Neutrophil", "Basophil", "Eosinophil"], 2,
    "Neutrophils have a characteristic segmented (multilobed) nucleus.",
    "Neutrophils have a segmented, multilobed nucleus."),
  Q("t14_a6", "t14", "Anatomy",
    "Which cell type differentiates into macrophages in tissues?",
    ["Neutrophils", "Monocytes", "Lymphocytes", "Eosinophils", "Basophils"], 1,
    "Monocytes migrate from blood into tissues and differentiate into macrophages.",
    "Monocytes become tissue macrophages."),
  Q("t14_a7", "t14", "Anatomy",
    "Which organ is responsible for producing erythropoietin?",
    ["Liver", "Spleen", "Kidney", "Bone marrow", "Pancreas"], 2,
    "The kidneys release erythropoietin in response to low oxygen levels.",
    "The kidney makes erythropoietin (in response to hypoxia)."),
  Q("t14_a8", "t14", "Anatomy",
    "Which leukocyte is most significantly elevated in parasitic infections?",
    ["Basophil", "Eosinophil", "Neutrophil", "Lymphocyte", "Monocyte"], 1,
    "Eosinophils are significantly elevated in parasitic infections, especially against helminths (worms).",
    "Eosinophils rise in parasitic (helminth) infection."),

  // ── Physiology ──
  Q("t14_p10", "t14", "Physiology & Biochem",
    "Which of the following correctly describes haematopoietic stem cells (HSCs)?",
    ["Can only differentiate but not self-renew", "Only produce erythrocytes", "Capable of self-renewal and differentiation", "Found only in the liver", "Produce only leukocytes"], 2,
    "HSCs are pluripotent cells capable of both self-renewal and differentiation into all blood cell types.",
    "HSCs self-renew and differentiate into all blood lineages."),
  Q("t14_p11", "t14", "Physiology & Biochem",
    "During foetal development, what is the primary site of haematopoiesis between 2–7 months of gestation?",
    ["Yolk sac", "Bone marrow", "Liver and spleen", "Thymus", "Kidney"], 2,
    "Foetal haematopoiesis is chronological: yolk sac (0–2 months), liver and spleen (2–7 months), then bone marrow (>6 months).",
    "Foetal haematopoiesis 2–7 months: liver and spleen."),
  Q("t14_p12", "t14", "Physiology & Biochem",
    "A patient with severe hypoxia shows increased red blood cell production. Which hormone is responsible?",
    ["Thrombopoietin", "GM-CSF", "Erythropoietin", "IL-5", "M-CSF"], 2,
    "Erythropoietin is released in response to hypoxia and stimulates erythropoiesis in the bone marrow.",
    "Erythropoietin drives RBC production in hypoxia."),
  Q("t14_p13", "t14", "Physiology & Biochem",
    "Which stage of erythropoiesis still contains ribosomal RNA and circulates briefly in peripheral blood?",
    ["Proerythroblast", "Normoblast", "Reticulocyte", "Erythroblast", "Mature erythrocyte"], 2,
    "Reticulocytes contain residual RNA and circulate for 1–2 days before maturing into erythrocytes.",
    "Reticulocytes have residual RNA and circulate 1–2 days."),
  Q("t14_p14", "t14", "Physiology & Biochem",
    "Which factor decreases haemoglobin's affinity for oxygen?",
    ["Decreased temperature", "Increased pH", "Increased 2,3-DPG", "Foetal haemoglobin", "Low carbon dioxide"], 2,
    "Increased 2,3-DPG reduces haemoglobin's affinity for oxygen, shifting the dissociation curve to the right and promoting oxygen unloading.",
    "↑2,3-DPG shifts the O2 curve right (unloads oxygen)."),
  Q("t14_p15", "t14", "Physiology & Biochem",
    "A patient receives a red blood cell transfusion. What is the expected increase in haemoglobin after one unit?",
    ["1 g/L", "5 g/L", "10 g/L", "20 g/L", "50 g/L"], 2,
    "One unit of red blood cells typically raises haemoglobin by approximately 10 g/L.",
    "One unit of RBCs ≈ +10 g/L haemoglobin."),
  Q("t14_p16", "t14", "Physiology & Biochem",
    "A patient presents with fatigue and a mean corpuscular volume (MCV) of 110 fL. What type of anaemia is this?",
    ["Microcytic", "Normocytic", "Macrocytic", "Haemolytic", "Iron deficiency"], 2,
    "An MCV > 100 fL indicates macrocytic anaemia, commonly due to B12 or folate deficiency.",
    "MCV > 100 fL = macrocytic anaemia (B12/folate)."),
  Q("t14_p17", "t14", "Physiology & Biochem",
    "Which finding is typical in haemolytic anaemia?",
    ["Low reticulocyte count", "Low bilirubin", "High haptoglobin", "Raised LDH", "Reduced RBC turnover"], 3,
    "Haemolytic anaemia destroys RBCs faster than they can be replaced, causing raised LDH, bilirubin and reticulocytes with reduced haptoglobin.",
    "Haemolysis: ↑LDH, ↑bilirubin, ↑reticulocytes, ↓haptoglobin."),
  Q("t14_p18", "t14", "Physiology & Biochem",
    "A patient with recurrent parasitic infections has low levels of which cell?",
    ["Neutrophils", "Basophils", "Eosinophils", "Monocytes", "Lymphocytes"], 2,
    "Eosinophils defend against parasitic infections, so low levels increase susceptibility to parasites.",
    "Low eosinophils → more susceptible to parasites."),
  Q("t14_p19", "t14", "Physiology & Biochem",
    "A newborn develops haemolytic disease due to Rh incompatibility. What is the mechanism?",
    ["Foetal RBCs attack maternal cells", "Maternal antibodies destroy foetal RBCs", "Platelet destruction", "Complement deficiency", "Iron overload"], 1,
    "Maternal anti-Rh antibodies cross the placenta and destroy foetal red blood cells, causing haemolysis.",
    "Rh disease: maternal anti-Rh antibodies destroy foetal RBCs."),
  Q("t14_p20", "t14", "Physiology & Biochem",
    "A patient presents with bone pain, hypercalcaemia, anaemia and renal impairment. What is the diagnosis?",
    ["Leukaemia", "Lymphoma", "Multiple myeloma", "Thalassaemia", "Iron deficiency anaemia"], 2,
    "This is the CRAB picture (hyperCalcaemia, Renal impairment, Anaemia, Bone pain), characteristic of multiple myeloma.",
    "CRAB (Calcium, Renal, Anaemia, Bone) = multiple myeloma."),
  Q("t14_p21", "t14", "Physiology & Biochem",
    "Which antibody is present in a person with blood type A?",
    ["Anti-A and Anti-B antibodies", "Anti-A antibody only", "Anti-B antibody only", "No antibodies present", "Anti-Rh antibodies"], 2,
    "Blood group A has A antigens on its red cells and produces anti-B antibodies against foreign B antigens.",
    "Group A → anti-B antibodies."),
  Q("t14_p22", "t14", "Physiology & Biochem",
    "A patient with chronic myeloid leukaemia (raised granulocytes, Philadelphia chromosome) should receive which first-line treatment?",
    ["CHOP chemotherapy", "Radiotherapy", "Tyrosine kinase inhibitors", "Immediate bone marrow transplant", "Steroids only"], 2,
    "CML is caused by the BCR-ABL fusion and is treated first-line with tyrosine kinase inhibitors such as imatinib.",
    "CML first-line: tyrosine kinase inhibitor (imatinib)."),
  Q("t14_p23", "t14", "Physiology & Biochem",
    "A patient undergoing chemotherapy develops pancytopenia. What is the best definition of pancytopenia?",
    ["Increased RBC, WBC and platelets", "Reduced RBC only", "Reduced WBC only", "Reduced RBC, WBC and platelets", "Increased WBC only"], 3,
    "Pancytopenia is a reduction in all three blood cell lines due to bone marrow suppression.",
    "Pancytopenia = low RBC + WBC + platelets."),
  Q("t14_p24", "t14", "Physiology & Biochem",
    "A patient with sickle cell disease presents with severe chest pain and hypoxia. What is the most likely mechanism?",
    ["Iron deposition in lungs", "Vaso-occlusion due to Hb polymerisation", "Autoimmune platelet destruction", "Reduced erythropoietin release", "Folate deficiency"], 1,
    "Deoxygenated HbS polymerises, causing red cells to sickle and occlude vessels, producing painful vaso-occlusive crises.",
    "Sickle crisis: HbS polymerises → sickling → vaso-occlusion."),

  // ── Ethics & Law ──
  Q("t14_e1", "t14", "Ethics & EBM",
    "A 62-year-old with acute GI bleeding is alert and fully oriented but refuses a blood transfusion on personal grounds, despite being told refusal may be fatal. What is the most appropriate next step?",
    ["Proceed with transfusion as it is life-saving", "Respect the patient's decision and document the refusal", "Ask the family to override the decision", "Give the transfusion covertly to prevent death", "Delay treatment until legal advice is obtained"], 1,
    "A competent adult has the right to refuse treatment even if refusal may result in death. Their autonomy must be respected and the decision documented after proper discussion.",
    "A competent adult may refuse even life-saving treatment."),
  Q("t14_e2", "t14", "Ethics & EBM",
    "A 30-year-old Jehovah's Witness with severe postpartum haemorrhage (Hb 4.8 g/dL) refuses whole blood but says she may accept certain blood products. What is the most appropriate next step?",
    ["Refuse all treatment and respect a blanket refusal", "Immediately give whole blood transfusion", "Explore acceptable alternatives such as blood fractions or cell salvage", "Seek a court order before discussing options", "Ask the family to decide on her behalf"], 2,
    "Many Jehovah's Witnesses accept blood derivatives (e.g. albumin, clotting factors) or autologous techniques such as cell salvage. An individualised discussion of acceptable treatments is essential.",
    "Explore acceptable alternatives (fractions, cell salvage)."),
  Q("t14_e3", "t14", "Ethics & EBM",
    "A 14-year-old needs an urgent transfusion after trauma. The parents refuse on religious grounds, the child lacks capacity, and the situation is immediately life-threatening. What is the most appropriate management?",
    ["Respect parental refusal and provide no transfusion", "Wait for court approval before treating", "Proceed with transfusion in the child's best interests", "Discharge the patient against medical advice", "Ask extended family to make the decision"], 2,
    "In a life-threatening emergency, treatment immediately necessary to save life can be given in the child's best interests, even against parental wishes, without delay for legal proceedings (GMC guidance).",
    "Emergency, child lacks capacity → treat in best interests."),
);
