// questions/t15.jsx, Theme 15: DVT & PE (Venous thromboembolism)
// Source: ISocMedEd Theme 15 MCQ Bank 2025. Image-dependent items omitted. Answers authored.

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t15_a1", "t15", "Anatomy",
    "Deep vein thromboses most commonly originate in the deep veins of which region?",
    ["Upper arm", "Calf (deep veins of the leg)", "Neck", "Abdomen", "Hand"], 1,
    "Most DVTs begin in the deep calf veins; proximal extension into the popliteal/femoral veins raises the risk of pulmonary embolism.",
    "DVTs usually start in the deep calf veins."),
  Q("t15_a2", "t15", "Anatomy",
    "Which is a deep vein of the lower limb?",
    ["Great saphenous vein", "Small saphenous vein", "Femoral vein", "Dorsal venous arch", "Perforator vein"], 2,
    "The femoral vein is a deep vein. The great and small saphenous veins are superficial veins.",
    "Femoral vein = deep; saphenous veins = superficial."),
  Q("t15_a3", "t15", "Anatomy",
    "Pulmonary emboli lodge in the pulmonary arteries, which carry blood from the:",
    ["Left ventricle to the body", "Right ventricle to the lungs", "Lungs to the left atrium", "Right atrium to the right ventricle", "Aorta to the lungs"], 1,
    "The pulmonary arteries carry deoxygenated blood from the right ventricle to the lungs; an embolus here obstructs pulmonary perfusion.",
    "Pulmonary arteries: right ventricle → lungs."),
  Q("t15_a4", "t15", "Anatomy",
    "Venous return from the legs is aided by valves and which 'pump'?",
    ["Cardiac suction only", "The skeletal muscle (calf) pump", "Gravity", "Arterial pressure alone", "The respiratory pump only"], 1,
    "The calf muscle pump compresses the deep veins during walking; combined with one-way valves it drives venous return. Immobility removes this, promoting stasis.",
    "Calf muscle pump + valves drive venous return."),

  // ── Physiology & Pathophysiology ──
  Q("t15_p1", "t15", "Physiology & Biochem",
    "Virchow's triad describes the three contributors to thrombosis. Which is NOT part of it?",
    ["Venous stasis", "Endothelial injury", "Hypercoagulability", "Arterial vasodilation"], 3,
    "Virchow's triad is stasis, endothelial injury and hypercoagulability. Arterial vasodilation is not part of it.",
    "Virchow's triad: stasis, endothelial injury, hypercoagulability."),
  Q("t15_p2", "t15", "Physiology & Biochem",
    "Which is a classic clinical feature of a DVT?",
    ["Bilateral symmetrical swelling", "Unilateral calf swelling, warmth and tenderness", "Cold pale foot", "Chest pain only", "Generalised rash"], 1,
    "A DVT typically causes a unilateral, warm, swollen, tender calf; bilateral swelling suggests another cause.",
    "DVT: unilateral warm, swollen, tender calf."),
  Q("t15_p3", "t15", "Physiology & Biochem",
    "Which symptoms suggest a pulmonary embolism?",
    ["Gradual weight gain", "Sudden pleuritic chest pain, breathlessness and tachycardia", "Bradycardia and constipation", "Painless jaundice", "Isolated headache"], 1,
    "A PE classically presents with sudden pleuritic chest pain, dyspnoea, tachycardia and sometimes haemoptysis.",
    "PE: sudden pleuritic chest pain + dyspnoea + tachycardia."),
  Q("t15_p4", "t15", "Physiology & Biochem",
    "How does a large pulmonary embolism cause haemodynamic compromise?",
    ["By dilating the pulmonary arteries", "By obstructing pulmonary flow and acutely straining the right ventricle", "By lowering heart rate", "By increasing left atrial filling", "By causing anaemia"], 1,
    "A large PE obstructs pulmonary blood flow, raising pulmonary artery pressure and acutely straining/dilating the right ventricle, which can cause obstructive shock.",
    "Large PE → acute right-heart strain (obstructive shock)."),
  Q("t15_p5", "t15", "Physiology & Biochem",
    "A high D-dimer in suspected VTE indicates:",
    ["Definite pulmonary embolism", "Evidence of fibrin breakdown, sensitive but not specific", "Normal clotting", "Low clot burden always", "A specific diagnosis of DVT"], 1,
    "D-dimer is a fibrin degradation product: sensitive but non-specific. A normal D-dimer helps exclude VTE in low-risk patients; a raised one needs imaging.",
    "D-dimer is sensitive, not specific, good for ruling out."),
  Q("t15_p6", "t15", "Physiology & Biochem",
    "Which classic ECG pattern is sometimes (but rarely) seen in PE?",
    ["Delta wave", "S1Q3T3 pattern", "Saw-tooth baseline", "Tall tented T waves", "Short PR"], 1,
    "The S1Q3T3 pattern (deep S in I, Q wave and inverted T in III) reflects acute right-heart strain, though sinus tachycardia is the commonest ECG finding in PE.",
    "S1Q3T3 = right-heart strain in PE (sinus tachy is commonest)."),
  Q("t15_p7", "t15", "Physiology & Biochem",
    "Which inherited thrombophilia is the most common?",
    ["Antithrombin deficiency", "Factor V Leiden", "Protein C deficiency", "Protein S deficiency", "Prothrombin gene mutation"], 1,
    "Factor V Leiden, causing resistance to activated protein C, is the most common inherited thrombophilia.",
    "Factor V Leiden = commonest inherited thrombophilia."),
  Q("t15_p8", "t15", "Physiology & Biochem",
    "Which imaging is first-line to confirm a pulmonary embolism?",
    ["Chest X-ray", "CT pulmonary angiogram (CTPA)", "Abdominal ultrasound", "Echocardiogram only", "Plain abdominal film"], 1,
    "CT pulmonary angiography is the first-line confirmatory imaging for PE (a V/Q scan is an alternative, e.g. in renal impairment or pregnancy).",
    "CTPA is first-line to confirm PE."),

  // ── Clinical & Pharmacology ──
  Q("t15_c1", "t15", "Clinical & Pharmacology",
    "What is the usual first-line anticoagulant for most confirmed VTE?",
    ["Intravenous heparin lifelong", "A direct oral anticoagulant (DOAC) such as apixaban or rivaroxaban", "Aspirin", "Warfarin only", "No treatment"], 1,
    "DOACs (e.g. apixaban, rivaroxaban) are first-line for most VTE, being effective without routine monitoring.",
    "Most VTE: first-line DOAC (apixaban/rivaroxaban)."),
  Q("t15_c2", "t15", "Clinical & Pharmacology",
    "How does warfarin exert its anticoagulant effect?",
    ["Direct thrombin inhibition", "Inhibiting vitamin K epoxide reductase, reducing factors II, VII, IX, X", "Activating plasmin", "Blocking platelets", "Increasing antithrombin"], 1,
    "Warfarin inhibits vitamin K epoxide reductase, reducing synthesis of the vitamin-K-dependent clotting factors II, VII, IX and X.",
    "Warfarin blocks vitamin-K-dependent factors II, VII, IX, X."),
  Q("t15_c3", "t15", "Clinical & Pharmacology",
    "A patient on a massive (haemodynamically unstable) PE with shock may require:",
    ["Oral aspirin only", "Thrombolysis (e.g. alteplase)", "Discharge home", "Iron tablets", "Reassurance only"], 1,
    "A massive PE causing haemodynamic instability is an indication for thrombolysis to rapidly dissolve the clot.",
    "Massive PE with shock → thrombolysis."),
  Q("t15_c4", "t15", "Clinical & Pharmacology",
    "Which is the reversal agent for warfarin in major bleeding?",
    ["Protamine sulfate", "Vitamin K and prothrombin complex concentrate", "Idarucizumab", "Tranexamic acid only", "Fresh frozen plasma alone"], 1,
    "Major warfarin-related bleeding is reversed with intravenous vitamin K plus prothrombin complex concentrate. (Protamine reverses heparin; idarucizumab reverses dabigatran.)",
    "Warfarin reversal: vitamin K + PCC."),
  Q("t15_c5", "t15", "Clinical & Pharmacology",
    "Which is a key VTE prophylaxis measure for immobile hospital inpatients?",
    ["Bed rest with no intervention", "Low-molecular-weight heparin and/or mechanical prophylaxis (TEDs/intermittent compression)", "High-dose aspirin for all", "Routine thrombolysis", "Avoiding all mobilisation"], 1,
    "Hospital VTE prophylaxis combines pharmacological (LMWH) and/or mechanical methods (anti-embolism stockings, intermittent pneumatic compression) plus early mobilisation.",
    "VTE prophylaxis: LMWH and/or mechanical measures."),

  // ── Behavioural & Social Sciences ──
  Q("t15_b1", "t15", "BSS",
    "Which is a common provoking risk factor for VTE that students should recognise?",
    ["Daily walking", "Recent surgery, immobility or long-haul travel", "High fluid intake", "Young age", "Low BMI"], 1,
    "Recent surgery, prolonged immobility and long-haul travel are common provoking factors for VTE (along with pregnancy, malignancy and the contraceptive pill).",
    "VTE risk: surgery, immobility, long-haul travel."),
  Q("t15_b2", "t15", "BSS",
    "Why is patient education important when starting long-term anticoagulation?",
    ["It is not important", "To improve adherence and awareness of bleeding risks and interactions", "To increase clinic visits", "To replace the medication", "To avoid all activity"], 1,
    "Education improves adherence and helps patients recognise bleeding risks, drug/food interactions and when to seek help.",
    "Anticoagulation education improves adherence and safety."),
);
