// questions/t16.jsx, Theme 16: Shock
// Source: ISocMedEd Theme 16 Shock MCQs. Image-dependent items omitted. Answers authored.

window.QUESTIONS.push(
  // ── Physiology & Pathophysiology ──
  Q("t16_p1", "t16", "Physiology & Biochem",
    "What is the fundamental definition of shock?",
    ["Low blood pressure only", "Inadequate tissue perfusion leading to cellular hypoxia", "A psychological fright response", "High cardiac output", "Fever with infection"], 1,
    "Shock is a state of inadequate tissue perfusion and oxygen delivery, causing cellular hypoxia and dysfunction, regardless of the blood pressure.",
    "Shock = inadequate tissue perfusion → cellular hypoxia."),
  Q("t16_p2", "t16", "Physiology & Biochem",
    "Which type of shock results from severe blood or fluid loss?",
    ["Cardiogenic", "Hypovolaemic", "Distributive", "Obstructive", "Neurogenic"], 1,
    "Hypovolaemic shock results from a loss of circulating volume (e.g. haemorrhage or severe dehydration), reducing preload and cardiac output.",
    "Hypovolaemic shock = volume loss (haemorrhage/dehydration)."),
  Q("t16_p3", "t16", "Physiology & Biochem",
    "Septic and anaphylactic shock are both subtypes of which category?",
    ["Cardiogenic", "Obstructive", "Distributive shock", "Hypovolaemic", "Compensated"], 2,
    "Septic, anaphylactic and neurogenic shock are distributive: widespread vasodilation drops systemic vascular resistance and maldistributes blood flow.",
    "Septic + anaphylactic = distributive shock (vasodilation)."),
  Q("t16_p4", "t16", "Physiology & Biochem",
    "Cardiogenic shock is caused by:",
    ["Massive vasodilation", "Pump failure, the heart cannot maintain adequate output (e.g. after a large MI)", "Loss of blood volume", "A blocked pulmonary artery", "An allergic reaction"], 1,
    "Cardiogenic shock is due to failure of the heart as a pump, most commonly after a large myocardial infarction.",
    "Cardiogenic shock = pump failure (often post-MI)."),
  Q("t16_p5", "t16", "Physiology & Biochem",
    "Which is an example of obstructive shock?",
    ["Haemorrhage", "Massive pulmonary embolism or cardiac tamponade", "Anaphylaxis", "Spinal cord injury", "Sepsis"], 1,
    "Obstructive shock results from a physical obstruction to circulation, e.g. massive PE, cardiac tamponade or tension pneumothorax.",
    "Obstructive shock: PE, tamponade, tension pneumothorax."),
  Q("t16_p6", "t16", "Physiology & Biochem",
    "In early (compensated) hypovolaemic shock, which compensatory response occurs?",
    ["Bradycardia and vasodilation", "Tachycardia and peripheral vasoconstriction", "Reduced heart rate only", "Warm flushed skin", "Increased urine output"], 1,
    "Baroreceptor-driven sympathetic activation causes tachycardia and vasoconstriction (cool, pale skin) to maintain blood pressure in compensated shock.",
    "Compensated shock: tachycardia + vasoconstriction."),
  Q("t16_p7", "t16", "Physiology & Biochem",
    "Why is the skin typically warm in early septic (distributive) shock, unlike hypovolaemic shock?",
    ["Because of fever alone", "Widespread vasodilation increases peripheral blood flow", "Because of vasoconstriction", "Reduced cardiac output", "Increased clotting"], 1,
    "Distributive (septic) shock causes peripheral vasodilation, giving warm, flushed skin ('warm shock'), in contrast to the cold, clammy skin of hypovolaemic shock.",
    "Septic shock: vasodilation → warm skin ('warm shock')."),
  Q("t16_p8", "t16", "Physiology & Biochem",
    "Which blood marker rises in shock due to anaerobic metabolism and indicates poor perfusion?",
    ["Sodium", "Lactate", "Albumin", "Calcium", "Bicarbonate (rises)"], 1,
    "Inadequate oxygen delivery forces anaerobic metabolism, raising lactate. A high/rising lactate marks hypoperfusion and guides resuscitation.",
    "Raised lactate signals hypoperfusion (anaerobic metabolism)."),
  Q("t16_p9", "t16", "Physiology & Biochem",
    "Neurogenic shock following spinal cord injury characteristically causes:",
    ["Tachycardia and hypertension", "Hypotension with bradycardia due to loss of sympathetic tone", "Warm shock with tachycardia", "No change in vital signs", "Pure volume loss"], 1,
    "Neurogenic shock results from loss of sympathetic tone, causing vasodilation with hypotension AND bradycardia (unopposed vagal tone), unlike other shocks where tachycardia occurs.",
    "Neurogenic shock: hypotension + bradycardia (lost sympathetic tone)."),
  Q("t16_p10", "t16", "Physiology & Biochem",
    "If untreated, decompensated shock leads to:",
    ["Spontaneous recovery", "Multi-organ failure and death", "Mild fatigue only", "A rise in blood pressure", "Improved perfusion"], 1,
    "When compensation fails, sustained hypoperfusion causes progressive cellular injury, multi-organ failure and death.",
    "Decompensated shock → multi-organ failure and death."),

  // ── Clinical & Pharmacology ──
  Q("t16_c1", "t16", "Clinical & Pharmacology",
    "What is the first-line treatment for most hypovolaemic and septic shock?",
    ["Immediate vasopressors", "Intravenous fluid resuscitation", "Oral rehydration only", "Beta-blockers", "Diuretics"], 1,
    "Initial management of hypovolaemic and septic shock is prompt IV fluid resuscitation to restore circulating volume; vasopressors are added if fluids are insufficient.",
    "Hypovolaemic/septic shock: IV fluids first."),
  Q("t16_c2", "t16", "Clinical & Pharmacology",
    "What is the first-line drug for anaphylactic shock?",
    ["IV hydrocortisone", "Intramuscular adrenaline (1:1000, 500 micrograms)", "Oral antihistamine", "IV fluids only", "Salbutamol nebuliser"], 1,
    "Intramuscular adrenaline 500 micrograms (0.5 mL of 1:1000) into the anterolateral thigh is the immediate life-saving treatment for anaphylaxis.",
    "Anaphylaxis: IM adrenaline 500 mcg (1:1000) first."),
  Q("t16_c3", "t16", "Clinical & Pharmacology",
    "Which vasopressor is first-line in septic shock when fluids alone fail to maintain blood pressure?",
    ["Adrenaline", "Noradrenaline", "Dobutamine", "Atropine", "Dopamine"], 1,
    "Noradrenaline is the first-line vasopressor in septic shock, raising systemic vascular resistance and mean arterial pressure.",
    "Septic shock vasopressor of choice: noradrenaline."),
  Q("t16_c4", "t16", "Clinical & Pharmacology",
    "The 'Sepsis Six' bundle includes giving oxygen, IV fluids and antibiotics, and taking which three measurements/samples?",
    ["Blood cultures, lactate and urine output", "ECG, CT and X-ray", "Weight, height and BMI", "Glucose, calcium and sodium only", "Temperature only"], 0,
    "The Sepsis Six: give oxygen, IV antibiotics and IV fluids; take blood cultures, measure lactate and monitor urine output.",
    "Sepsis Six 'take': cultures, lactate, urine output."),
  Q("t16_c5", "t16", "Clinical & Pharmacology",
    "In cardiogenic shock, which drug may be used to improve cardiac contractility?",
    ["A pure vasoconstrictor only", "An inotrope such as dobutamine", "A diuretic alone", "An antihistamine", "A beta-blocker"], 1,
    "Inotropes such as dobutamine increase myocardial contractility and cardiac output in cardiogenic shock (definitive treatment targets the underlying cause).",
    "Cardiogenic shock: inotrope (e.g. dobutamine) to boost output."),
  Q("t16_c6", "t16", "Clinical & Pharmacology",
    "Definitive treatment of obstructive shock from cardiac tamponade is:",
    ["IV fluids alone", "Pericardiocentesis (drainage of the pericardial fluid)", "Adrenaline", "Antibiotics", "Reassurance"], 1,
    "Cardiac tamponade is relieved by pericardiocentesis to drain the fluid compressing the heart; fluids are only a temporising measure.",
    "Tamponade → pericardiocentesis."),

  // ── Ethics & EBM ──
  Q("t16_e1", "t16", "Ethics & EBM",
    "A patient in septic shock lacks capacity and needs urgent treatment. There is no advance directive or next of kin available. The team should:",
    ["Wait until capacity returns", "Treat in the patient's best interests without delay", "Withhold all treatment", "Seek a court order first", "Discharge the patient"], 1,
    "When a patient lacks capacity in an emergency and no valid advance decision or representative is available, clinicians must act in the patient's best interests without delay.",
    "No capacity + emergency → treat in best interests."),
  Q("t16_e2", "t16", "Ethics & EBM",
    "An early-warning score (e.g. NEWS2) is used in shock primarily to:",
    ["Diagnose the exact cause", "Identify and track deteriorating patients to prompt timely escalation", "Replace clinical judgement", "Calculate drug doses", "Determine discharge"], 1,
    "NEWS2 aggregates vital signs to flag deteriorating patients early and trigger appropriate escalation of care.",
    "NEWS2 flags deterioration to prompt escalation."),
);
