// questions/t1b.jsx, Theme 1b: Fertilisation, pregnancy & parturition
// Source: ISocMedEd Theme 1b MCQ Bank 2025. Image-dependent items omitted.
// Answers & explanations authored to accompany the bank (no official key supplied).

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t1b_a1", "t1b", "Anatomy",
    "The pelvic inlet is bounded posteriorly by which structure?",
    ["Ischial spine", "Sacral promontory", "Pubic crest", "Iliac crest", "Ischial tuberosity"], 1,
    "The pelvic inlet (brim) is bounded posteriorly by the sacral promontory, anteriorly by the pubic symphysis, and laterally by the iliopectineal (arcuate) lines.",
    "The sacral promontory marks the posterior edge of the pelvic inlet."),
  Q("t1b_a5", "t1b", "Anatomy",
    "Which bones fuse to form the os coxa (hip bone)?",
    ["Ilium, sacrum, coccyx", "Pubis, ischium, coccyx", "Ilium, ischium, pubis", "Ilium, sacrum, pubis", "Ischium, sacrum, coccyx"], 2,
    "Each hip bone (os coxa) is formed by fusion of the ilium, ischium and pubis, which meet at the acetabulum.",
    "Os coxa = ilium + ischium + pubis."),
  Q("t1b_a6", "t1b", "Anatomy",
    "The true pelvis is located:",
    ["Above the pelvic inlet", "Below the pelvic inlet", "Between the iliac crests", "Anterior to the sacral promontory", "Superior to the pelvic brim"], 1,
    "The true (lesser) pelvis lies below the pelvic inlet/brim and contains the pelvic organs; the false (greater) pelvis lies above it.",
    "True pelvis = below the pelvic brim."),
  Q("t1b_a7", "t1b", "Anatomy",
    "In the sagittal view of the female pelvis, which structure lies most anteriorly?",
    ["Rectum", "Vagina", "Uterus", "Bladder", "Ovary"], 3,
    "From anterior to posterior the pelvic organs run: bladder → uterus/vagina → rectum. The bladder is the most anterior.",
    "Order front-to-back: bladder, uterus/vagina, rectum."),
  Q("t1b_a8", "t1b", "Anatomy",
    "The uterine artery is a branch of which artery?",
    ["Common iliac", "External iliac", "Internal iliac", "Ovarian", "Superior vesical"], 2,
    "The uterine artery arises from the anterior division of the internal iliac artery and famously crosses over the ureter ('water under the bridge').",
    "Uterine artery → internal iliac; it crosses over the ureter."),
  Q("t1b_a9", "t1b", "Anatomy",
    "Which ligament helps maintain the anteverted, anteflexed position of the uterus?",
    ["Suspensory ligament of the ovary", "Round ligament", "Broad ligament", "Ovarian ligament", "Uterosacral ligament"], 1,
    "The round ligament runs from the uterine horn to the labia majora and helps hold the uterus in its normal anteverted, anteflexed position.",
    "The round ligament maintains uterine anteversion/anteflexion."),
  Q("t1b_a10", "t1b", "Anatomy",
    "The part of the uterus above the openings of the uterine tubes is called the:",
    ["Cervix", "Fundus", "Isthmus", "Body", "Canal"], 1,
    "The fundus is the rounded uterine region superior to the entry points of the uterine (fallopian) tubes.",
    "Fundus = the dome of the uterus above the tubal openings."),
  Q("t1b_a11", "t1b", "Anatomy",
    "The lining epithelium of the uterine tube is best described as:",
    ["Simple squamous", "Simple cuboidal", "Ciliated simple columnar", "Stratified squamous", "Transitional"], 2,
    "The uterine tube is lined by ciliated simple columnar epithelium; the cilia help waft the oocyte towards the uterus.",
    "Uterine tube: ciliated simple columnar epithelium."),
  Q("t1b_a12", "t1b", "Anatomy",
    "During the secretory phase of the uterine cycle the:",
    ["Uterine glands increase in size and coil", "Endometrium of the fundus remains unchanged", "Straight arteries extend into the functionalis layer", "Superficial part of the spiral arteries degenerate", "Cervix receives an increased blood supply"], 0,
    "Under progesterone in the secretory phase, the endometrial glands enlarge, coil and secrete glycogen-rich fluid to prepare for implantation.",
    "Secretory phase (progesterone): glands coil and secrete."),
  Q("t1b_a13", "t1b", "Anatomy",
    "The vagina is lined by which type of epithelium?",
    ["Simple columnar", "Stratified squamous non-keratinised", "Stratified squamous keratinised", "Transitional", "Simple cuboidal"], 1,
    "The vagina is lined by stratified squamous non-keratinised epithelium, suited to friction while remaining moist.",
    "Vagina: stratified squamous non-keratinised epithelium."),

  // ── Embryology, Physiology & Biochemistry ──
  Q("t1b_p14", "t1b", "Physiology & Biochem",
    "Failure of the cranial neuropore to close by day 25 results in which condition?",
    ["Spina bifida", "Anencephaly", "Encephalocele", "Hydrocephalus", "Arnold-Chiari malformation"], 1,
    "Failure of the cranial (anterior) neuropore to close causes anencephaly. Failure of the caudal neuropore instead causes spina bifida.",
    "Cranial neuropore failure → anencephaly; caudal → spina bifida."),
  Q("t1b_p15", "t1b", "Physiology & Biochem",
    "Which process directly follows gastrulation in early embryonic development?",
    ["Implantation", "Somitogenesis", "Neurulation", "Cardiogenesis", "Limb-bud formation"], 2,
    "Gastrulation forms the three germ layers; neurulation (formation of the neural tube from ectoderm) follows directly afterwards.",
    "Gastrulation → neurulation."),
  Q("t1b_p16", "t1b", "Physiology & Biochem",
    "What is the most common implantation site for an ectopic pregnancy?",
    ["Cervix", "Ovary", "Ampulla", "Isthmus", "Peritoneal cavity"], 2,
    "Around 70% of ectopic pregnancies implant in the ampulla of the uterine tube, the widest part where fertilisation usually occurs.",
    "Most ectopics implant in the ampulla of the fallopian tube."),
  Q("t1b_p17", "t1b", "Physiology & Biochem",
    "Which statement best describes how oestrogen is synthesised in the developing follicle?",
    ["LH acts on granulosa cells to convert cholesterol to progesterone", "FSH acts on theca cells to convert androgens to oestrogen", "LH stimulates theca cells to produce androgens that granulosa cells aromatise under FSH influence", "Progesterone from granulosa cells is aromatised by theca cells", "FSH directly converts cholesterol to oestradiol"], 2,
    "In the two-cell, two-gonadotrophin model, LH drives theca cells to make androgens, which diffuse to granulosa cells where FSH-induced aromatase converts them to oestrogen.",
    "Two-cell model: LH→theca androgens; FSH→granulosa aromatase→oestrogen."),
  Q("t1b_p18", "t1b", "Physiology & Biochem",
    "Which hormone maintains early pregnancy by sustaining corpus luteum progesterone secretion?",
    ["Oestrogen", "hCG", "Oxytocin", "Prostaglandin", "Prolactin"], 1,
    "hCG from the syncytiotrophoblast maintains the corpus luteum so it keeps secreting progesterone until the placenta takes over.",
    "hCG sustains the corpus luteum in early pregnancy."),
  Q("t1b_p19", "t1b", "Physiology & Biochem",
    "Which change best explains the functional closure of the foramen ovale after birth?",
    ["Increased right atrial pressure and decreased left atrial pressure", "Decreased pulmonary blood flow and hypoxia", "Decreased right atrial pressure and increased left atrial pressure", "Increased prostaglandin E₂ levels", "Decreased systemic vascular resistance"], 2,
    "After birth, lung expansion increases pulmonary blood flow and left atrial pressure while right atrial pressure falls, pushing the septum primum against secundum to close the foramen ovale.",
    "↑LA pressure + ↓RA pressure closes the foramen ovale at birth."),
  Q("t1b_p20", "t1b", "Physiology & Biochem",
    "What change occurs immediately after the first breath?",
    ["Increase in pulmonary vascular resistance", "Decrease in systemic vascular resistance", "Increase in pulmonary blood flow due to vasodilation", "Collapse of alveoli due to lack of surfactant", "Increase in right-to-left shunt"], 2,
    "The first breath expands the alveoli and oxygenates the pulmonary vessels, causing pulmonary vasodilation, falling pulmonary vascular resistance and a large rise in pulmonary blood flow.",
    "First breath → pulmonary vasodilation → ↑ pulmonary blood flow."),
  Q("t1b_p21", "t1b", "Physiology & Biochem",
    "What is the immediate molecular consequence of oestrogen binding to its intracellular receptor?",
    ["Activation of adenylate cyclase leading to cAMP generation", "Receptor dimerisation and binding to oestrogen response elements (EREs)", "Activation of phospholipase C leading to IP₃ and DAG release", "Phosphorylation of protein kinase A", "Binding to a G-protein-coupled receptor"], 1,
    "As a steroid, oestrogen binds an intracellular receptor that then dimerises and binds oestrogen response elements in DNA to regulate transcription.",
    "Oestrogen receptor dimerises and binds EREs to alter transcription."),
  Q("t1b_p22", "t1b", "Physiology & Biochem",
    "Where are the receptors that mediate the primary actions of steroid hormones typically located?",
    ["Plasma membrane linked to G proteins", "Bound to ribosomal RNA", "Free in the cytoplasm or nucleus, acting as transcription factors", "Mitochondrial inner membrane", "Rough endoplasmic reticulum"], 2,
    "Steroid hormones are lipophilic and cross the membrane to bind intracellular (cytoplasmic or nuclear) receptors that act as transcription factors.",
    "Steroid receptors are intracellular transcription factors."),
  Q("t1b_p23", "t1b", "Physiology & Biochem",
    "At what stage does the primitive heart first begin to beat in the developing embryo?",
    ["Day 10", "Day 18", "Day 22", "Day 30", "Week 5"], 2,
    "The primitive heart tube begins to beat at around day 22 of development, making the cardiovascular system the first to function.",
    "The embryonic heart starts beating around day 22."),
  Q("t1b_p24", "t1b", "Physiology & Biochem",
    "How are the fingers and toes separated during embryonic development?",
    ["Splitting of cartilaginous tissue", "Apoptosis between developing digital rays", "Neural crest migration into digits", "Mesodermal proliferation", "Loss of ectodermal ridge"], 1,
    "Programmed cell death (apoptosis) of the interdigital webbing between the digital rays separates the fingers and toes. Failure causes syndactyly.",
    "Apoptosis of interdigital webbing separates the digits."),
  Q("t1b_p25", "t1b", "Physiology & Biochem",
    "What is the main role of the notochord during early development?",
    ["It becomes the spinal cord", "It signals to overlying ectoderm to form the neural plate", "It becomes the nucleus pulposus of vertebral discs", "It gives rise to the heart", "It supports yolk sac formation"], 1,
    "The notochord's key developmental role is inducing the overlying ectoderm to form the neural plate (neural induction). It later persists only as the nucleus pulposus.",
    "Notochord induces the neural plate; its remnant is the nucleus pulposus."),
  Q("t1b_p26", "t1b", "Physiology & Biochem",
    "Which hormone is primarily responsible for maintaining the secretory activity of the endometrial glands after ovulation?",
    ["FSH", "LH", "Oestrogen", "Progesterone", "Inhibin A"], 3,
    "Progesterone from the corpus luteum maintains the secretory, glandular endometrium that supports a potential implantation.",
    "Progesterone maintains the secretory endometrium after ovulation."),
  Q("t1b_p27", "t1b", "Physiology & Biochem",
    "Which best describes the primary mechanism by which the combined oral contraceptive pill prevents pregnancy?",
    ["Thickening of cervical mucus to prevent sperm penetration", "Inhibition of implantation by endometrial thinning", "Suppression of FSH and LH release to inhibit ovulation", "Acceleration of ciliary movement in the fallopian tubes", "Inhibition of spermatogenesis"], 2,
    "The combined pill's main action is negative feedback on the hypothalamic–pituitary axis, suppressing FSH and LH and thereby preventing ovulation.",
    "COCP works mainly by suppressing FSH/LH to block ovulation."),
  Q("t1b_p28", "t1b", "Physiology & Biochem",
    "Which statement about the progestogen-only pill (POP) is true?",
    ["It consistently suppresses ovulation in all users", "It is contraindicated during breastfeeding", "It causes regular withdrawal bleeding cycles", "It thickens cervical mucus, preventing sperm entry", "It contains both oestrogen and progesterone"], 3,
    "The traditional POP works chiefly by thickening cervical mucus to block sperm; it is safe in breastfeeding and does not reliably suppress ovulation.",
    "POP's main action is thickening cervical mucus."),
  Q("t1b_p32", "t1b", "Physiology & Biochem",
    "Which hormone inhibits both FSH and LH secretion and is secreted by granulosa cells during the menstrual cycle?",
    ["Oestrogen", "Progesterone", "Inhibin", "hCG", "Testosterone"], 2,
    "Inhibin, produced by granulosa cells, selectively suppresses FSH (and contributes to LH feedback), helping regulate follicle development.",
    "Inhibin (granulosa cells) suppresses FSH."),
  Q("t1b_p33", "t1b", "Physiology & Biochem",
    "Why do some women develop gestational diabetes?",
    ["Decreased hCG", "Placental hPL induces insulin resistance", "Reduced progesterone", "Low cortisol", "Increased insulin secretion"], 1,
    "Human placental lactogen (hPL) and other placental hormones induce maternal insulin resistance; when the pancreas cannot compensate, gestational diabetes results.",
    "Placental hPL drives insulin resistance in pregnancy."),
  Q("t1b_p34", "t1b", "Physiology & Biochem",
    "Which sequence best describes the positive feedback mechanism that strengthens uterine contractions during labour?",
    ["Stretch of the cervix activates hypothalamic neurons, increasing oxytocin release and enhancing uterine contractions", "Uterine contractions stimulate the pituitary to secrete progesterone, reducing further contractions", "Cervical distension inhibits oxytocin secretion to limit myometrial excitability", "Fetal head pressure suppresses prostaglandin synthesis and decreases contractility", "Placental CRH release increases progesterone dominance to maintain quiescence"], 0,
    "Cervical stretch triggers hypothalamic oxytocin release, which strengthens contractions, pushing the fetus further onto the cervix, the classic Ferguson reflex positive-feedback loop.",
    "Ferguson reflex: cervical stretch → oxytocin → stronger contractions."),
  Q("t1b_p35", "t1b", "Physiology & Biochem",
    "Which statement best explains the physiological role of surfactant?",
    ["Surfactant increases surface tension in the alveoli, helping the lungs recoil after crying", "Surfactant maintains pulmonary vascular resistance by thickening the alveolar film", "Surfactant reduces alveolar surface tension, allowing the first breath to expand the lungs and preventing alveolar collapse on expiration", "Surfactant stimulates closure of the ductus arteriosus by increasing prostaglandin synthesis", "Surfactant is secreted by type I pneumocytes and removes fetal lung fluid"], 2,
    "Surfactant, made by type II pneumocytes, lowers alveolar surface tension so the lungs can expand with the first breath and the alveoli do not collapse on expiration.",
    "Surfactant lowers surface tension and prevents alveolar collapse."),
  Q("t1b_p36", "t1b", "Physiology & Biochem",
    "Which side-effect is most common with progesterone-only contraception?",
    ["Headache and hypertension", "Irregular or unscheduled vaginal bleeding", "Heavy periods", "Hyperpigmentation", "Fluid retention and weight gain"], 1,
    "Irregular or unscheduled bleeding is the most common reason women stop the progestogen-only pill.",
    "POP's commonest side-effect is irregular bleeding."),
  Q("t1b_p37", "t1b", "Physiology & Biochem",
    "Which statement best describes how the source of reproductive hormones changes as the placenta develops?",
    ["The corpus luteum maintains progesterone secretion until delivery", "hCG from the syncytiotrophoblast maintains the corpus luteum early on, but by weeks 8–12 the placenta becomes the main source of oestrogen and progesterone", "The maternal anterior pituitary continues to secrete large amounts of LH to sustain the endometrium", "Fetal adrenal glands produce hCG after week 10 to maintain progesterone levels", "Placental oestrogen falls progressively to allow progesterone dominance before term"], 1,
    "Early on, hCG sustains the corpus luteum; by around weeks 8–12 the placenta takes over as the dominant source of oestrogen and progesterone (the luteo-placental shift).",
    "Luteo-placental shift: placenta takes over hormone production by ~weeks 8–12."),
  Q("t1b_p38", "t1b", "Physiology & Biochem",
    "Following placental delivery, what does continued oxytocin release do?",
    ["Suppresses lactation by reducing prolactin secretion", "Contracts the uterus to prevent postpartum haemorrhage", "Causes uterine relaxation to aid placental expulsion", "Stimulates prostaglandin breakdown to stabilise tone", "Increases progesterone secretion to maintain endometrium"], 1,
    "After delivery, oxytocin keeps the uterus contracted, clamping the spiral arteries to reduce postpartum haemorrhage, the basis for giving oxytocics in the third stage.",
    "Post-delivery oxytocin contracts the uterus to limit haemorrhage."),
  Q("t1b_p39", "t1b", "Physiology & Biochem",
    "Which of the following structures mainly develops from neural crest cells?",
    ["Skeletal muscle of the limbs", "Endothelium of blood vessels", "Melanocytes in the skin", "Hepatocytes in the liver", "Smooth muscle of the gut"], 2,
    "Neural crest cells are migratory and give rise to melanocytes, peripheral neurons, Schwann cells, adrenal medulla and parts of the facial skeleton.",
    "Neural crest → melanocytes, peripheral nerves, adrenal medulla."),

  // ── Ethics & EBM ──
  Q("t1b_e4", "t1b", "Ethics & EBM",
    "Evidence-Based Medicine (EBM) is best defined as:",
    ["Applying research findings without considering patient preference", "Using clinical judgement alone to make decisions", "Integrating clinical expertise, the best available evidence, and patient values", "Relying solely on randomised controlled trials for treatment choices", "Prioritising cost-effectiveness over patient-centred care"], 2,
    "EBM integrates the best available research evidence with clinical expertise and the patient's own values and preferences.",
    "EBM = evidence + clinical expertise + patient values."),

  // ── Behavioural & Social Sciences ──
  Q("t1b_b1", "t1b", "BSS",
    "Which of the following best describes instrumental social support?",
    ["Providing emotional reassurance and empathy", "Sharing similar experiences to foster belonging", "Offering tangible help such as childcare or transport", "Giving advice and information about health decisions", "Expressing appreciation and validation"], 2,
    "Instrumental support is practical, tangible help, for example childcare, transport or money, as opposed to emotional or informational support.",
    "Instrumental support = practical, tangible help."),
  Q("t1b_b2", "t1b", "BSS",
    "How can cultural values most directly influence a woman's experience of pregnancy and childbirth?",
    ["By determining the level of hospital funding", "By affecting preferences for pain relief, family involvement, and place of birth", "By altering the physiological stages of labour", "By increasing the risk of obstetric complications", "By reducing access to antenatal screening"], 1,
    "Culture shapes preferences and expectations, around pain relief, who is present, and place of birth, rather than the underlying physiology of labour.",
    "Culture shapes birth preferences, not labour physiology."),
  Q("t1b_b3", "t1b", "BSS",
    "Which statement correctly describes how maternity care is structured in the UK?",
    ["All women are cared for exclusively by obstetricians", "Care is consultant-led throughout pregnancy for all women", "Midwife-led care is provided for low-risk pregnancies, with escalation to obstetric-led care if complications arise", "Antenatal and postnatal care are provided only in hospital settings", "The GP manages labour and delivery for most patients"], 2,
    "UK maternity care is midwife-led for low-risk pregnancies, with escalation to obstetric (consultant)-led care if risks or complications develop.",
    "Low-risk = midwife-led; escalate to obstetric-led if complications."),
  Q("t1b_b5", "t1b", "BSS",
    "Which best illustrates the psychological impact of pregnancy-related sickness?",
    ["Risk of dehydration due to hyperemesis", "Reduced ability to attend work leading to financial strain", "Worry that something is going wrong with the pregnancy", "Feeling 'pregnant' and reassured", "Impact of anti-emetics on the foetus"], 2,
    "A psychological impact relates to thoughts and emotions, here, anxiety that something may be wrong, rather than physical (dehydration) or social (work/finance) effects.",
    "Psychological impact = the worry/anxiety itself."),
  Q("t1b_b6", "t1b", "BSS",
    "Which of the following is a social advantage of becoming pregnant at age 30 rather than younger?",
    ["Reduced fertility leading to fewer pregnancies", "Increased risk of gestational hypertension", "Greater financial stability and social support", "Increased anxiety about genetic abnormalities", "Lower level of physical fitness"], 2,
    "Older (but not advanced) maternal age often brings greater financial stability and established social support, a social advantage, distinct from the biological risks of age.",
    "A social advantage of later pregnancy: more financial/social stability."),
);
