// questions/t2.jsx, Theme 2: Chromosomal abnormalities
// Source: ISocMedEd Theme 2 MCQ Bank + official Answers 2025. Image items omitted.

window.QUESTIONS.push(
  // ── Anatomy (perineum & pelvic floor) ──
  Q("t2_a4", "t2", "Anatomy",
    "The pudendal nerve gives off three branches. Which three are correct?",
    ["Obturator nerve, inferior rectal and perineal", "Perineal nerve, nerve to levator ani, inferior rectal", "Inferior rectal, dorsal nerve of the clitoris, perineal nerve", "Dorsal nerve of the clitoris, inferior rectal and femoral", "Inferior rectal, perineal and sacral"], 2,
    "The pudendal nerve divides into the inferior rectal nerve, the perineal nerve, and the dorsal nerve of the clitoris/penis.",
    "Pudendal branches: inferior rectal, perineal, dorsal nerve of clitoris/penis."),
  Q("t2_a5", "t2", "Anatomy",
    "Which nerve is the main innervator of the perineum and where does it arise?",
    ["Obturator nerve – L2-4", "Femoral nerve – L2-4", "Pudendal nerve – S2-4", "Pudendal nerve – S4-5", "Pudendal nerve – S3-5"], 2,
    "The pudendal nerve, the main nerve of the perineum, arises from the ventral rami of S2–S4. The obturator and femoral nerves supply the lower limb.",
    "Pudendal nerve = S2–S4 ('S2,3,4 keep the perineum off the floor')."),
  Q("t2_a6", "t2", "Anatomy",
    "Which muscle contributes to the pelvic floor but is not part of the levator ani muscle?",
    ["Iliococcygeus", "Piriformis", "Pubococcygeus", "Puborectalis", "Coccygeus"], 1,
    "Levator ani comprises only puborectalis, pubococcygeus and iliococcygeus. Piriformis contributes to the postero-lateral pelvic wall, not levator ani.",
    "Levator ani = puborectalis + pubococcygeus + iliococcygeus."),
  Q("t2_a7", "t2", "Anatomy",
    "What is the main arterial supply of the perineum?",
    ["Abdominal aorta", "Internal pudendal artery", "Internal iliac artery", "External iliac artery", "Ovarian artery"], 1,
    "The internal pudendal artery, a branch of the anterior division of the internal iliac artery, is the main supply of the perineum.",
    "Perineum is supplied by the internal pudendal artery."),
  Q("t2_a8", "t2", "Anatomy",
    "What is the origin of iliococcygeus?",
    ["Superior anterior iliac spine", "Anococcygeal body", "Iliac crest", "Ischial spine", "Posterior inferior iliac spine"], 3,
    "Iliococcygeus arises from the ischial spine and the tendinous arch of the levator ani, inserting into the anococcygeal body and coccyx.",
    "Iliococcygeus originates from the ischial spine / tendinous arch."),
  Q("t2_a9", "t2", "Anatomy",
    "What is the insertion of piriformis?",
    ["Head of the femur", "Lesser trochanter of the femur", "Tendinous arch", "Greater trochanter of the femur", "Intertrochanteric crest of the femur"], 3,
    "Piriformis runs from the anterior sacrum to insert on the greater trochanter of the femur, acting as a lateral rotator of the hip.",
    "Piriformis inserts on the greater trochanter of the femur."),
  Q("t2_a10", "t2", "Anatomy",
    "What forms the lateral and posterolateral boundaries of the perineum?",
    ["Lateral: sacrotuberous ligament, Posterolateral: ischial tuberosity", "Lateral: ischial tuberosity, Posterolateral: ischiopubic rami", "Lateral: ischiopubic rami, Posterolateral: coccyx", "Lateral: ischiopubic rami, Posterolateral: sacrospinous ligament", "Lateral: ischial tuberosity, Posterolateral: sacrotuberous ligament"], 4,
    "The diamond-shaped perineum has the ischial tuberosities laterally and the sacrotuberous ligaments posterolaterally (with the pubic symphysis anteriorly and coccyx posteriorly).",
    "Perineum: ischial tuberosities lateral, sacrotuberous ligaments posterolateral."),
  Q("t2_a11", "t2", "Anatomy",
    "Which is NOT present in the superficial perineal pouch?",
    ["External urethral sphincter", "Ischiocavernosus", "Bulbospongiosus", "Superficial transverse perineal muscle", "Perineal body"], 0,
    "The external urethral sphincter (and deep transverse perineal muscle) lie in the deep perineal pouch; ischiocavernosus, bulbospongiosus, superficial transverse perineal muscle and the perineal body are superficial.",
    "External urethral sphincter is in the deep pouch, not the superficial one."),
  Q("t2_a12", "t2", "Anatomy",
    "A line between which bony landmarks divides the perineum into urogenital and anal triangles?",
    ["Ischial spines", "Ischial tuberosities", "Posterior inferior iliac spines", "Lesser sciatic notches", "Anterior inferior iliac spines"], 1,
    "An imaginary line between the two ischial tuberosities divides the perineum into the anterior urogenital triangle and the posterior anal triangle.",
    "The interischial-tuberosity line splits the perineum into UG and anal triangles."),

  // ── Physiology & Biochemistry ──
  Q("t2_p1", "t2", "Physiology & Biochem",
    "Normally, up to how many weeks will abortion be allowed if certain criteria are met?",
    ["22 weeks", "23 weeks", "24 weeks", "25 weeks", "26 weeks"], 2,
    "Abortion is generally permitted up to 24 weeks' gestation if specific criteria are met; beyond this it is allowed only for severe fetal abnormality or serious risk to the mother.",
    "The standard upper limit is 24 weeks."),
  Q("t2_p2", "t2", "Physiology & Biochem",
    "Which of the following contains only acrocentric chromosomes?",
    ["12, 13, 14, 21, 22", "14, 15, 16, 20, 21", "12, 13, 14, 20, 21", "13, 14, 15, 21, 22", "None of the above"], 3,
    "The human acrocentric chromosomes, centromere near one end, are 13, 14, 15, 21 and 22. These can take part in Robertsonian translocations.",
    "Acrocentric chromosomes: 13, 14, 15, 21, 22."),
  Q("t2_p3", "t2", "Physiology & Biochem",
    "What are the four things a quadruple (quad) test measures?",
    ["fβhCG, inhibin A, unconjugated oestriol, AFP", "fβhCG, inhibin A, FSH, AFP", "fβhCG, FSH, unconjugated oestriol, hPL", "fβhCG, inhibin A, conjugated oestriol, AFP", "fβhCG, inhibin A, oestrogen, hPL"], 0,
    "The second-trimester quad test measures AFP, unconjugated oestriol (uE3), free β-hCG and inhibin A to screen for Down and Edwards syndromes.",
    "Quad test: AFP, uE3, fβhCG, inhibin A."),
  Q("t2_p4", "t2", "Physiology & Biochem",
    "Duplication of one chromosome arm with loss of the other, so the chromosome has two identical arms, is called…?",
    ["Deletion", "Inversion", "Duplication", "Isochromosome", "Translocation"], 3,
    "An isochromosome forms when the chromosome divides across the centromere incorrectly, producing two identical arms (and loss of the other), giving unbalanced genetic material.",
    "Isochromosome = two identical arms (one arm duplicated, the other lost)."),
  Q("t2_p5", "t2", "Physiology & Biochem",
    "Having an extra copy of chromosome 18 (trisomy 18) is referred to as which syndrome?",
    ["Turner syndrome", "Edwards syndrome", "Klinefelter syndrome", "18 syndrome", "Evans syndrome"], 1,
    "Trisomy 18 is Edwards syndrome, associated with heart defects, clenched fists, a small head and a high infant mortality.",
    "Trisomy 18 = Edwards; trisomy 13 = Patau; trisomy 21 = Down."),
  Q("t2_p6", "t2", "Physiology & Biochem",
    "From which week can an amniocentesis procedure be performed?",
    ["11", "12", "13", "14", "15"], 4,
    "Amniocentesis is usually performed from 15 weeks, when there is enough amniotic fluid for safe sampling.",
    "Amniocentesis: from ~15 weeks."),
  Q("t2_p7", "t2", "Physiology & Biochem",
    "In which stage of mitosis does the nuclear membrane begin to disintegrate?",
    ["Prophase", "Prometaphase", "Metaphase", "Anaphase", "Telophase"], 1,
    "The nuclear membrane breaks down in prometaphase, allowing spindle microtubules to attach to kinetochores before chromosomes align in metaphase.",
    "Nuclear envelope breaks down in prometaphase."),
  Q("t2_p8", "t2", "Physiology & Biochem",
    "What is a paracentric inversion?",
    ["Inversion of a segment on an acrocentric chromosome", "Inversion of a segment that is part of the long arm only", "Inversion of a segment that includes the centromere", "Inversion of a segment that does not include the centromere"], 3,
    "A paracentric inversion is an inverted chromosome segment that does NOT include the centromere (pericentric inversions do include it).",
    "Paracentric = excludes the centromere; pericentric = includes it."),
  Q("t2_p9", "t2", "Physiology & Biochem",
    "Which checkpoint ensures that DNA has been correctly duplicated before mitosis begins?",
    ["G1 checkpoint", "G2 checkpoint", "M checkpoint", "S checkpoint", "Cytokinetic checkpoint"], 1,
    "The G2 checkpoint verifies that S-phase DNA replication completed correctly before the cell enters mitosis.",
    "G2 checkpoint: checks DNA replication is complete before mitosis."),
  Q("t2_p10", "t2", "Physiology & Biochem",
    "Which of the following is NOT a structural chromosomal abnormality?",
    ["Deletion", "Inversion", "Duplication", "Polyploidy", "Translocation"], 3,
    "Polyploidy is a change in the number of whole chromosome sets (a numerical abnormality). Deletions, inversions, duplications and translocations alter chromosome structure.",
    "Polyploidy is numerical, not structural."),
  Q("t2_p11", "t2", "Physiology & Biochem",
    "What is the only monosomy compatible with life?",
    ["Down syndrome", "Edwards syndrome", "Turner syndrome", "Klinefelter syndrome", "Patau syndrome"], 2,
    "Turner syndrome (45,X) is the only viable monosomy, causing short stature and ovarian failure; all other complete monosomies are lethal.",
    "Turner syndrome (45,X) is the only survivable monosomy."),
  Q("t2_p12", "t2", "Physiology & Biochem",
    "The only way to produce an XYY karyotype (Jacob's syndrome) is through:",
    ["Non-disjunction in meiosis I", "Non-disjunction in meiosis II", "Robertsonian translocation", "Anaphase lag", "Gene deletion"], 1,
    "An extra Y can only come from the sister chromatids failing to separate in meiosis II of spermatogenesis, producing a YY sperm.",
    "47,XYY arises from non-disjunction in meiosis II (paternal)."),
  Q("t2_p13", "t2", "Physiology & Biochem",
    "A translocation between chromosomes 13 and 17 involving equal DNA exchange would be classified as:",
    ["Robertsonian translocation", "Non-disjunction", "Isochromosome", "Reciprocal translocation", "Insertion"], 3,
    "Equal exchange between two non-homologous chromosomes is a reciprocal translocation. Robertsonian translocations occur only between acrocentric chromosomes (13,14,15,21,22).",
    "Equal swap between non-homologous chromosomes = reciprocal translocation."),
  Q("t2_p14", "t2", "Physiology & Biochem",
    "Which point mutation creates a premature stop codon?",
    ["Silent mutation", "Missense mutation", "Nonsense mutation", "Frameshift mutation", "Insertion mutation"], 2,
    "A nonsense mutation changes an amino-acid codon into a stop codon (e.g. UAU→UAA), truncating the protein.",
    "Nonsense mutation → premature stop codon → truncated protein."),
  Q("t2_p15", "t2", "Physiology & Biochem",
    "What is the timing of the anomaly scan during pregnancy?",
    ["10–12 weeks", "13–14 weeks", "18–21 weeks", "22–24 weeks", "After 25 weeks"], 2,
    "The mid-trimester anomaly scan is performed at 18–21 weeks to detect structural abnormalities such as cardiac and neural tube defects.",
    "Anomaly scan: 18–21 weeks."),

  // ── Ethics, Law & EBM ──
  Q("t2_ebm1", "t2", "Ethics & EBM",
    "Which of the following correctly defines screening?",
    ["Diagnosis of disease in symptomatic patients", "Identifying apparently healthy individuals at increased risk of disease", "Confirming a clinical diagnosis", "Genetic testing of confirmed cases", "Prenatal diagnostic imaging"], 1,
    "Screening identifies apparently healthy people at increased risk so further testing can be offered. It is a risk-assessment tool, not a diagnostic test.",
    "Screening = risk assessment of healthy people, not diagnosis."),
  Q("t2_ebm2", "t2", "Ethics & EBM",
    "Which formula correctly defines the sensitivity of a screening test?",
    ["TN / (TN + FP)", "TP / (TP + FN)", "TP / (TP + FP)", "TN / (TN + FN)", "FN / (TP + TN)"], 1,
    "Sensitivity = TP / (TP + FN): the proportion of people with the disease correctly identified as positive.",
    "Sensitivity = TP / (TP + FN)."),
  Q("t2_ebm3", "t2", "Ethics & EBM",
    "The positive predictive value (PPV) of a screening test refers to:",
    ["Proportion of healthy people testing negative", "Probability that a person with a positive test actually has the disease", "Ability to detect mild cases", "Chance that a person with a negative test is healthy", "Sensitivity of a test"], 1,
    "PPV is the probability that someone who tests positive truly has the disease; it depends on sensitivity, specificity and disease prevalence.",
    "PPV = chance a positive test is a true positive."),
  Q("t2_ebm4", "t2", "Ethics & EBM",
    "Which drugs are used for medical (non-surgical) abortion?",
    ["Methotrexate and misonidazole", "Mifepristone and misoprostol", "Oxytocin and ergometrine", "Misoprostol and prostaglandin E1", "Clomiphene and mifepristone"], 1,
    "Medical abortion uses mifepristone (an antiprogestogen) followed by misoprostol (a prostaglandin analogue that induces contractions).",
    "Medical abortion = mifepristone then misoprostol."),
  Q("t2_eth1", "t2", "Ethics & EBM",
    "Until which week of pregnancy is abortion legal in the UK (apart from Northern Ireland), excluding extreme circumstances?",
    ["22nd week", "24th week", "28th week", "20th week", "12th week"], 1,
    "Abortion is legal in England, Scotland and Wales up to 24 weeks (later only if the mother's life is at risk or severe fetal abnormality). In Northern Ireland the limit is 12 weeks.",
    "UK (excl. NI): legal to 24 weeks."),
  Q("t2_eth2", "t2", "Ethics & EBM",
    "A 14-year-old who is pregnant requests a termination and refuses to involve her parents. A doctor can proceed with the termination:",
    ["Based on the patient's best interests", "Because there is a foetal abnormality", "If the patient is legally competent to consent", "Only if a guardian/parent can consent on the patient's behalf"], 2,
    "A 14-year-old can consent to treatment, including termination, if she is Gillick competent (understands, retains and can weigh the decision). Parental consent is not then required.",
    "A Gillick-competent minor can consent without parental involvement."),
  Q("t2_eth3", "t2", "Ethics & EBM",
    "A doctor withholds a harmful medication despite the patient's insistence on continuing it. This is an example of which ethical principle?",
    ["Non-maleficence", "Beneficence", "Autonomy", "Justice"], 0,
    "Acting to prevent harm, here by withholding a harmful drug, is non-maleficence ('first, do no harm').",
    "Preventing harm = non-maleficence."),

  // ── Behavioural & Social Sciences ──
  Q("t2_b1", "t2", "BSS",
    "Which statement is correct regarding the social model of disability?",
    ["People with disabilities should choose activities that suit their level to stay comfortable", "The model refers mainly to physical disabilities", "Disabilities are primarily determined by genetic factors", "People are disabled because society fails to accommodate their differences"], 3,
    "The social model holds that disability arises from societal barriers (e.g. stairs without a ramp) rather than from the impairment itself.",
    "Social model: society's barriers disable, not the impairment."),
  Q("t2_b2", "t2", "BSS",
    "How does a pregnancy with a fetus affected by Down syndrome differ physiologically from a normal pregnancy?",
    ["The pregnancy is physiologically more demanding on the mother", "The pregnancy involves significant hormonal differences", "There is no physiological difference in the pregnancy itself", "The mother will have gestational diabetes by default"], 2,
    "The chromosomal condition affects the fetus, not maternal pregnancy physiology, which usually progresses as in any other pregnancy.",
    "Down syndrome affects the fetus, not the mother's pregnancy physiology."),
  Q("t2_b3", "t2", "BSS",
    "Which of the following is NOT a typical feature of care in high-risk pregnancies?",
    ["Continuous fetal monitoring during labour", "Multidisciplinary team involvement", "Standard appointment frequency", "Potential planned birth (e.g. induction or C-section)"], 2,
    "Standard appointment frequency applies to low-risk pregnancies; high-risk pregnancies have more frequent monitoring and MDT input.",
    "High-risk care = more frequent, not standard, appointments."),
  Q("t2_b4", "t2", "BSS",
    "How can cultural assumptions about disability influence decisions about antenatal screening?",
    ["They have no impact on decision-making", "They can shape whether families view screening as preparation, prevention, or unnecessary", "They only influence healthcare professionals, not families", "They determine the accuracy of screening results"], 1,
    "Cultural beliefs shape how families frame screening, as preparation, prevention, or as unnecessary on moral/spiritual grounds.",
    "Culture frames how families view the purpose of screening."),
  Q("t2_b5", "t2", "BSS",
    "Which of the following is an intrinsic influence on decisions about antenatal screening?",
    ["Health system resources", "Religious or moral beliefs", "National policy", "Availability of laboratory tests"], 1,
    "Intrinsic influences come from a person's own values; religious or moral beliefs directly shape screening decisions. The others are extrinsic.",
    "Intrinsic influence = personal values/beliefs."),
  Q("t2_b6", "t2", "BSS",
    "Which factor most directly affects how individuals perceive risk in antenatal screening?",
    ["Statistical probability alone", "Emotional response, personal experience, and cultural framing of uncertainty", "Government policy", "Technical accuracy of the test"], 1,
    "Risk perception is subjective: emotion, personal experience and cultural framing often outweigh the raw statistics.",
    "Risk perception is driven by emotion and context, not just numbers."),
);
