// questions/t3.jsx, Theme 3: Cystic Fibrosis
// Source: ISocMedEd Theme 3 MCQ Bank 2025. Image-dependent items omitted.
// Answers & explanations authored (no official key supplied).

window.QUESTIONS.push(
  // ── Anatomy & Histology ──
  Q("t3_a1", "t3", "Anatomy",
    "Which of the following is true about the clavicle?",
    ["The inferior surface is smoother than the superior surface", "It articulates medially with the acromion of the scapula", "The inferior surface is rougher due to attachments of muscles and ligaments", "The acromial end is medial and bulbous; the sternal end is lateral and flat", "The subclavian groove is on the superior surface"], 2,
    "The inferior surface of the clavicle is rough because of ligament and muscle attachments (e.g. the conoid tubercle, costoclavicular ligament). Medially it articulates with the sternum, not the acromion.",
    "The clavicle's inferior surface is rough (ligament/muscle attachments)."),
  Q("t3_a4", "t3", "Anatomy",
    "What type of joint is the acromioclavicular joint?",
    ["Synovial plane joint", "Synovial ball-and-socket joint", "Synovial hinge joint", "Synovial condyloid joint", "Synovial saddle joint"], 0,
    "The acromioclavicular joint is a synovial plane (gliding) joint between the acromion and the lateral clavicle.",
    "The AC joint is a synovial plane (gliding) joint."),
  Q("t3_a7", "t3", "Anatomy",
    "Which movements are enabled at the radiocarpal (wrist) joint?",
    ["Circumduction, flexion, extension, abduction, adduction, rotation", "Circumduction, flexion, extension, abduction, adduction (no rotation)", "Only flexion and extension", "Only rotational movements", "Only circumduction"], 1,
    "The wrist is a condyloid (ellipsoid) joint allowing flexion/extension, abduction/adduction and circumduction, but not true rotation, which occurs at the radioulnar joints.",
    "The wrist (condyloid joint) does everything except rotation."),
  Q("t3_a9", "t3", "Anatomy",
    "Which of the following is true about the gastrointestinal system?",
    ["There are 3 pairs of major salivary glands: parotid, submandibular and sublingual", "The exocrine function of the pancreas is hormone secretion for glucose regulation", "The gallbladder produces bile, secreted straight into the duodenum", "Saliva contains proteases that break down protein into amino acids", "The small intestine produces hydrochloric acid to aid digestion"], 0,
    "There are three pairs of major salivary glands, parotid, submandibular and sublingual. Bile is produced by the liver (the gallbladder stores it), hormone secretion is the endocrine pancreas, and HCl is produced by the stomach.",
    "Three paired salivary glands: parotid, submandibular, sublingual."),
  Q("t3_a10", "t3", "Anatomy",
    "Which of the following is true about the lungs?",
    ["The left lung has three lobes separated by horizontal and oblique fissures", "The right lung has two lobes separated by a single oblique fissure", "The right lung has three lobes (superior, middle, inferior) separated by horizontal and oblique fissures", "The left lung has a horizontal fissure dividing superior and inferior lobes", "The left lung is larger and heavier than the right due to the heart"], 2,
    "The right lung has three lobes (superior, middle, inferior) divided by horizontal and oblique fissures. The left has two lobes and is smaller because of the cardiac notch.",
    "Right lung = 3 lobes; left lung = 2 lobes (cardiac notch)."),
  Q("t3_h11", "t3", "Anatomy",
    "Which best describes the epithelium lining the trachea?",
    ["Simple cuboidal non-ciliated epithelium", "Stratified squamous keratinised epithelium", "Pseudostratified ciliated columnar epithelium with goblet cells", "Simple columnar ciliated epithelium", "Simple squamous epithelium"], 2,
    "The trachea is lined by pseudostratified ciliated columnar epithelium with goblet cells (respiratory epithelium), which traps and clears debris via the mucociliary escalator.",
    "Respiratory epithelium = pseudostratified ciliated columnar with goblet cells."),
  Q("t3_h12", "t3", "Anatomy",
    "Which structural feature is lost as the airways transition from bronchi to bronchioles?",
    ["Smooth muscle", "Cilia", "Goblet cells", "Cartilage", "Elastic fibres"], 3,
    "Cartilage is lost at the level of the bronchioles; their patency instead depends on surrounding elastic tissue and smooth muscle tone.",
    "Bronchioles have no cartilage."),
  Q("t3_h13", "t3", "Anatomy",
    "What is the main function of ciliated epithelial cells in the conducting zone?",
    ["Gas exchange", "Secretion of surfactant", "Propelling mucus towards the pharynx", "Oxygen absorption", "Phagocytosis of debris"], 2,
    "Cilia beat to move the mucus layer (with trapped debris) up towards the pharynx, the mucociliary escalator. This clearance fails in CF.",
    "Cilia drive the mucociliary escalator towards the pharynx."),

  // ── Physiology, Pathophysiology & Biochemistry ──
  Q("t3_p14", "t3", "Physiology & Biochem",
    "A newborn presents with abdominal distension and failure to pass meconium. Which process best explains this in cystic fibrosis?",
    ["Midgut volvulus due to malrotation", "Pyloric hypertrophy causing gastric outlet obstruction", "Hirschsprung aganglionosis", "Intestinal atresia due to vascular insult", "Meconium ileus due to dehydrated intestinal contents"], 4,
    "In CF, thick dehydrated intestinal secretions cause meconium ileus, obstruction of the bowel by inspissated meconium, often the earliest presentation.",
    "Meconium ileus is a classic neonatal presentation of CF."),
  Q("t3_p15", "t3", "Physiology & Biochem",
    "Which chronic structural lung change is most characteristic of CF?",
    ["Emphysematous bullae", "Organizing pneumonia with Masson bodies", "Interstitial fibrosis with honeycombing", "Alveolar proteinosis", "Bronchiectasis from repeated infection and inflammation"], 4,
    "Recurrent infection and inflammation in CF cause bronchiectasis, permanent abnormal dilation of the bronchi with impaired clearance.",
    "CF lungs develop bronchiectasis from repeated infection."),
  Q("t3_p16", "t3", "Physiology & Biochem",
    "A school-age child with CF has a chronic productive cough. Which organism most strongly associates with chronic colonisation and biofilm formation?",
    ["Moraxella catarrhalis", "Streptococcus pneumoniae", "Mycoplasma pneumoniae", "Haemophilus influenzae", "Pseudomonas aeruginosa"], 4,
    "Pseudomonas aeruginosa forms biofilms and chronically colonises CF airways, associated with faster decline in lung function.",
    "Pseudomonas aeruginosa = chronic biofilm coloniser in CF."),
  Q("t3_p17", "t3", "Physiology & Biochem",
    "Which statement best distinguishes colonisation from infection in CF lungs?",
    ["Infection occurs only with primary pathogens", "Colonisation occurs only in upper airways", "Colonisation = microbial presence without tissue injury", "Infection always causes fever", "Colonisation implies viral presence"], 2,
    "Colonisation is the presence of microbes without tissue damage or an inflammatory response; infection involves tissue injury and host response.",
    "Colonisation = microbes present without tissue injury."),
  Q("t3_p18", "t3", "Physiology & Biochem",
    "Which early respiratory pathogen commonly colonises children with CF before Pseudomonas?",
    ["Stenotrophomonas maltophilia", "Acinetobacter baumannii", "Burkholderia cepacia", "Staphylococcus aureus", "Escherichia coli"], 3,
    "Staphylococcus aureus (and H. influenzae) typically colonise CF airways in early childhood, before Pseudomonas predominates later.",
    "S. aureus colonises CF lungs early, before Pseudomonas."),
  Q("t3_p19", "t3", "Physiology & Biochem",
    "A CF patient develops steatorrhoea and fat-soluble vitamin deficiency. The underlying lesion is:",
    ["Gastric acid deficiency", "Pancreatic duct obstruction with exocrine insufficiency", "Hepatic cholestasis", "Ileal bile-salt loss", "Coeliac enteropathy"], 1,
    "Thick secretions block the pancreatic ducts, causing exocrine pancreatic insufficiency: lipase fails to reach the gut, producing steatorrhoea and malabsorption of fat-soluble vitamins (A, D, E, K).",
    "CF → pancreatic duct obstruction → fat malabsorption (A,D,E,K)."),
  Q("t3_p20", "t3", "Physiology & Biochem",
    "CFTR in airway epithelia functions as:",
    ["An ATP-gated chloride channel allowing down-gradient flow", "A sodium leak channel", "A passive pore not using ATP", "An ATP-driven pump moving Cl⁻ against its gradient", "A voltage-gated potassium channel"], 0,
    "CFTR is an ATP-gated chloride channel: ATP binding/hydrolysis gates the pore, but Cl⁻ then moves passively down its electrochemical gradient (it is not a pump).",
    "CFTR is an ATP-gated Cl⁻ channel (gated, not a pump)."),
  Q("t3_p21", "t3", "Physiology & Biochem",
    "Loss of CFTR-mediated Cl⁻ secretion immediately causes:",
    ["Increased HCO₃⁻ secretion → alkaline mucus", "Decreased Na⁺ absorption → hydrated surface", "Increased ENaC-mediated Na⁺ absorption → dehydrated mucus", "Increased K⁺ secretion → thin mucus", "Decreased ENaC activity → watery mucus"], 2,
    "Loss of CFTR also disinhibits ENaC, so Na⁺ (and water) is absorbed from the airway surface, dehydrating the mucus.",
    "No CFTR → ↑ENaC Na⁺ absorption → dehydrated, thick mucus."),
  Q("t3_p22", "t3", "Physiology & Biochem",
    "The F508del mutation primarily results in:",
    ["Normal trafficking but reduced ATP affinity", "Hyperactive surface channels", "Misfolded CFTR degraded before reaching the membrane", "A premature stop codon in exon 11", "Altered ion selectivity only"], 2,
    "F508del (a Class II defect) causes CFTR to misfold and be degraded by the proteasome before it can traffic to the cell membrane.",
    "F508del → misfolded CFTR degraded before reaching the membrane."),
  Q("t3_p23", "t3", "Physiology & Biochem",
    "Mucociliary failure in CF is mainly due to:",
    ["Overproduction of watery mucus", "Ciliary structural defects", "Goblet-cell metaplasia alone", "Dehydrated, viscous mucus that cilia cannot propel", "Epithelial apoptosis"], 3,
    "In CF the cilia are structurally normal but cannot move the abnormally thick, dehydrated mucus, so clearance fails. (Structural ciliary defects instead define primary ciliary dyskinesia.)",
    "CF: normal cilia, but mucus too thick to clear."),
  Q("t3_p24", "t3", "Physiology & Biochem",
    "In sweat glands, normal CFTR action is to:",
    ["Activate aquaporins to secrete water", "Secrete Cl⁻ into sweat → low sweat chloride", "Block ENaC → reduce Na⁺ in sweat", "Reabsorb Cl⁻ from sweat → loss causes salty sweat", "Reabsorb urea from sweat"], 3,
    "In sweat ducts, CFTR normally reabsorbs Cl⁻ (with Na⁺ following). When it fails, salt stays in the sweat, the basis of the diagnostic sweat test (high sweat chloride).",
    "CF → can't reabsorb Cl⁻ in sweat ducts → salty sweat (sweat test)."),
  Q("t3_p25", "t3", "Physiology & Biochem",
    "The CF pulmonary cascade is best summarised by:",
    ["CFTR loss → ↑ Cl⁻ secretion → thin mucus", "CFTR loss → normal ions → infection only with fever", "CFTR loss → ↓ ENaC → hydrated mucus", "CFTR loss → ↓ Cl⁻ secretion → ↑ Na⁺ uptake → ↓ water → thick mucus → infection/inflammation", "CFTR loss → ↑ Cl⁻ → airway dehydration prevented"], 3,
    "Loss of CFTR reduces Cl⁻ secretion and increases Na⁺ (and water) absorption, dehydrating the mucus; the thick mucus impairs clearance, leading to chronic infection and inflammation.",
    "CF cascade: ↓Cl⁻ secretion + ↑Na⁺ uptake → thick mucus → infection."),
  Q("t3_p26", "t3", "Physiology & Biochem",
    "CFTR belongs to which family, and how does ATP act?",
    ["GPCR; ATP makes cAMP", "ABC transporter; ATP controls channel-opening probability", "SLC transporter; ATP pumps ions uphill", "Ionotropic receptor; ATP forms the pore", "Voltage-gated channel; ATP is irrelevant"], 1,
    "CFTR is a member of the ATP-binding cassette (ABC) transporter family, but uniquely acts as a channel: ATP binding to its nucleotide-binding domains controls the probability of the channel opening.",
    "CFTR = ABC transporter; ATP gates channel opening."),
  Q("t3_p27", "t3", "Physiology & Biochem",
    "The appropriate modulator for a Class II trafficking defect (F508del) is:",
    ["A channel blocker", "A gene silencer", "A corrector ± potentiator (e.g. lumacaftor/tezacaftor/elexacaftor)", "An aquaporin agonist", "A potentiator alone (ivacaftor)"], 2,
    "Class II (trafficking) defects need a corrector to help CFTR fold and reach the membrane, usually combined with a potentiator to improve channel function, e.g. elexacaftor/tezacaftor/ivacaftor.",
    "F508del (Class II) → corrector ± potentiator."),
  Q("t3_p28", "t3", "Physiology & Biochem",
    "Which marker is used in newborn CF screening, and why is it elevated?",
    ["α-1 antitrypsin – hepatic synthesis defect", "Amylase – salivary leakage", "Lipase – gastric absorption problem", "Immunoreactive trypsinogen (IRT) – pancreatic duct blockage causes leakage", "C-reactive protein – systemic inflammation"], 3,
    "Newborn screening measures immunoreactive trypsinogen (IRT), which rises because blocked pancreatic ducts cause trypsinogen to leak back into the blood.",
    "Newborn CF screen = raised IRT (pancreatic duct blockage)."),
  Q("t3_p29", "t3", "Physiology & Biochem",
    "Which best describes the primary function of the skin in innate immunity?",
    ["Secretes antibodies that neutralise pathogens", "Provides a physical and chemical barrier preventing microbial entry", "Produces cytokines that attract neutrophils", "Phagocytoses invading bacteria directly", "Acts as an antigen-presenting surface"], 1,
    "The skin is a first-line innate barrier, a physical layer plus chemical defences (low pH, antimicrobial peptides) that keep microbes out.",
    "Skin = physical + chemical innate barrier."),
  Q("t3_p30", "t3", "Physiology & Biochem",
    "Where would you expect mucous membranes to play a major role in preventing infection?",
    ["Skeletal muscles", "Peritoneal cavity", "Respiratory, digestive and genitourinary tracts", "Bone marrow", "Lymph nodes"], 2,
    "Mucous membranes line the respiratory, digestive and genitourinary tracts, providing innate barrier defence at these exposed surfaces.",
    "Mucosae guard the respiratory, GI and GU tracts."),
  Q("t3_p31", "t3", "Physiology & Biochem",
    "A CF patient has chronic airway inflammation partly due to continuous IL-8 release by epithelial cells. What is the main immune consequence?",
    ["Recruitment of neutrophils to the airways", "Activation of the complement pathway", "Increased antibody production by plasma cells", "Stimulation of macrophage antigen presentation", "Activation of eosinophils against parasites"], 0,
    "IL-8 is a potent neutrophil chemokine; its sustained release recruits neutrophils, whose enzymes drive much of the chronic airway damage in CF.",
    "IL-8 recruits neutrophils, central to CF airway damage."),

  // ── Ethics, Law & EBM ──
  Q("t3_eth1", "t3", "Ethics & EBM",
    "A CF patient enrolled in a drug trial has side effects but wishes to continue. Which ethical principle supports respecting this choice?",
    ["Beneficence", "Justice", "Confidentiality", "Autonomy", "Non-maleficence"], 3,
    "Respecting a competent patient's own decision about their treatment is autonomy.",
    "Respecting the patient's choice = autonomy."),
  Q("t3_eth2", "t3", "Ethics & EBM",
    "In the UK, termination for serious fetal abnormality (e.g. CF) is legally permitted under which condition?",
    ["Only if both parents consent", "Only if the fetus is under 10 weeks' gestation", "Only if approved by a judge", "If two doctors agree there is a significant risk of serious handicap", "Only in private clinics"], 3,
    "Ground E of the Abortion Act permits termination at any gestation if two doctors agree there is a substantial risk of serious fetal handicap.",
    "Serious fetal abnormality: two doctors agree → no upper time limit."),
  Q("t3_ebm1", "t3", "Ethics & EBM",
    "Two CF carriers plan a pregnancy. What is the recurrence risk?",
    ["10% affected", "50% affected", "25% affected, 50% carriers, 25% unaffected", "0% in daughters only", "100% carriers, no disease"], 2,
    "CF is autosomal recessive: two carriers have a 1-in-4 chance of an affected child, 1-in-2 carriers and 1-in-4 unaffected each pregnancy.",
    "Two carriers (autosomal recessive): 25% affected, 50% carriers, 25% clear."),
  Q("t3_ebm2", "t3", "Ethics & EBM",
    "What is the best study design to prove the efficacy of a new CFTR modulator?",
    ["Case series", "Cross-sectional study", "Randomised controlled trial", "Case-control study", "Retrospective audit"], 2,
    "A randomised controlled trial is the gold standard for establishing the efficacy of a treatment, minimising bias and confounding.",
    "RCT = gold standard for proving treatment efficacy."),
  Q("t3_ebm3", "t3", "Ethics & EBM",
    "Which approach reflects correct antibiotic stewardship in CF?",
    ["Broad-spectrum therapy indefinitely", "Culture-guided, narrowest effective regimen, adequate duration", "Avoid cultures before therapy", "Use a single agent for all infections", "Stop antibiotics as soon as symptoms improve"], 1,
    "Good stewardship means using culture results to choose the narrowest effective antibiotic for an adequate course, limiting resistance.",
    "Stewardship: culture-guided, narrow-spectrum, adequate duration."),

  // ── Behavioural & Social Sciences ──
  Q("t3_b1", "t3", "BSS",
    "Non-adherence often rises in adolescence with emerging abstract reasoning and independence. Which Piaget stage is this?",
    ["Concrete operational", "Formal operational", "Sensorimotor", "Transitional sensorimotor", "Pre-operational"], 1,
    "The formal operational stage (from ~11 years) brings abstract and hypothetical reasoning, coinciding with the drive for independence that can reduce adherence.",
    "Abstract reasoning in adolescence = Piaget's formal operational stage."),
  Q("t3_b2", "t3", "BSS",
    "Which member of the multidisciplinary team manages a cystic fibrosis patient's nutrition?",
    ["Physiotherapist", "Pharmacist", "CF nurse specialist", "Dietitian", "Respiratory physician"], 3,
    "The dietitian leads nutritional management in CF, which is vital given the high energy needs and malabsorption.",
    "The dietitian leads CF nutritional care."),
  Q("t3_b3", "t3", "BSS",
    "An infant repeatedly drops a toy to see if the parent will pick it up, showing the toy still exists when out of sight. This best represents:",
    ["Egocentrism", "Conservation", "Hypothetical reasoning", "Abstract thinking", "Object permanence"], 4,
    "Understanding that objects continue to exist when unseen is object permanence, which develops in the sensorimotor stage.",
    "Knowing an unseen object still exists = object permanence."),
  Q("t3_b4", "t3", "BSS",
    "Children with CF often require a higher caloric intake than healthy peers. The main reason is:",
    ["To increase muscle mass", "Reduced appetite", "Increased metabolic demand and malabsorption", "Lower resting energy expenditure", "Reduced physical activity"], 2,
    "CF raises energy needs through increased metabolic demand (chronic infection, breathing effort) and malabsorption from pancreatic insufficiency.",
    "CF: higher calories needed due to ↑demand + malabsorption."),
);
