// questions/t4.jsx, Theme 4: Postnatal growth & puberty
// Source: ISocMedEd Theme 4 MCQ Bank 2025. Image-dependent items omitted.
// Answers & explanations authored (no official key supplied).

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t4_a5", "t4", "Anatomy",
    "What is the route taken by sperm through the male reproductive system?",
    ["Seminiferous tubule → rete testis → straight tubules → efferent ductule → epididymis → ejaculatory duct → ductus deferens → urethra", "Seminiferous tubule → straight tubules → rete testis → efferent ductule → epididymis → ductus deferens → ejaculatory duct → urethra", "Seminiferous tubule → straight tubules → rete testis → afferent ductule → epididymis → ductus deferens → ejaculatory duct → urethra", "Seminiferous tubule → straight tubules → epididymis → efferent ductule → ductus deferens → ejaculatory duct → urethra", "Seminiferous tubule → rete testis → efferent ductule → ductus deferens → ejaculatory duct → epididymis → urethra"], 1,
    "Sperm pass: seminiferous tubules → straight tubules → rete testis → efferent ductules → epididymis → ductus (vas) deferens → ejaculatory duct → urethra.",
    "SEVEN UP route: Seminiferous, Epididymis, Vas, Ejaculatory duct, (Nothing), Urethra, Penis."),
  Q("t4_a6", "t4", "Anatomy",
    "Which structure produces sperm?",
    ["Epididymis", "Seminiferous tubules", "Vas deferens", "Urethra", "Prostate gland"], 1,
    "Spermatogenesis occurs in the seminiferous tubules, supported by Sertoli cells.",
    "Sperm are produced in the seminiferous tubules."),
  Q("t4_a7", "t4", "Anatomy",
    "The epididymis is mainly responsible for:",
    ["Testosterone production", "Lubrication", "Sperm maturation and storage", "Semen alkalinisation", "Sperm production"], 2,
    "Sperm gain motility and are stored as they pass through the epididymis; they are produced in the seminiferous tubules.",
    "Epididymis = sperm maturation and storage."),
  Q("t4_a8", "t4", "Anatomy",
    "Where is the prostate gland located?",
    ["In the scrotum", "Behind the bladder", "Below the bladder, surrounding the urethra", "Within the testis", "In front of the seminal vesicles"], 2,
    "The prostate sits inferior to the bladder and surrounds the prostatic urethra, which is why enlargement causes urinary obstruction.",
    "Prostate sits below the bladder, encircling the urethra."),
  Q("t4_a9", "t4", "Anatomy",
    "What is the innervation of the epididymis?",
    ["Testicular plexus", "Pudendal nerve", "Hypogastric plexus", "Sympathetic vagus", "Femoral nerve"], 0,
    "The epididymis is innervated by autonomic fibres of the testicular plexus, which travels with the testicular vessels.",
    "Epididymis: testicular (autonomic) plexus."),
  Q("t4_a10", "t4", "Anatomy",
    "What is the function of the cremaster muscle?",
    ["Maintains scrotal skin tone", "Contracts in response to decreased temperature", "Contracts during sexual arousal", "Transports sperm", "Controls movement of the bladder"], 1,
    "The cremaster elevates the testis (e.g. in cold) to help thermoregulate the testes for spermatogenesis; it also mediates the cremasteric reflex.",
    "Cremaster raises the testis in the cold (thermoregulation)."),
  Q("t4_a11", "t4", "Anatomy",
    "Which of the following is NOT a structure of the male urethra?",
    ["Intramural (pre-prostatic) part", "Prostatic urethra", "Intermediate (membranous) part", "Ejaculatory duct", "Spongy urethra"], 3,
    "The male urethra has four parts: intramural, prostatic, membranous and spongy. The ejaculatory duct opens into the prostatic urethra but is not part of it.",
    "Urethra parts: intramural, prostatic, membranous, spongy."),

  // ── Physiology, Pathology & Biochemistry ──
  Q("t4_p1", "t4", "Physiology & Biochem",
    "Which hormone directly acts on Sertoli cells to produce inhibin and facilitate spermatogenesis?",
    ["Luteinising hormone (LH)", "Follicle-stimulating hormone (FSH)", "Testosterone", "GnRH", "Progesterone"], 1,
    "FSH acts on Sertoli cells to support spermatogenesis and stimulate inhibin secretion (which feeds back to suppress FSH). LH acts on Leydig cells to make testosterone.",
    "FSH → Sertoli cells (spermatogenesis + inhibin); LH → Leydig (testosterone)."),
  Q("t4_p2", "t4", "Physiology & Biochem",
    "Why is a single random blood sample unreliable for measuring growth hormone (GH)?",
    ["It is only secreted during REM sleep", "It has a very short half-life of 2 minutes", "It is secreted in a pulsatile manner, predominantly at night", "It is bound completely to albumin in the blood", "It is converted immediately to IGF-1 upon secretion"], 2,
    "GH is released in pulses (mainly at night), so a random level may catch a trough or peak. IGF-1, which is stable, is measured instead to assess GH status.",
    "GH is pulsatile, measure IGF-1 for a stable readout."),
  Q("t4_p3", "t4", "Physiology & Biochem",
    "During bone growth, in which zone of the epiphyseal plate do chondrocytes actively divide to form columns?",
    ["Zone of reserve cartilage", "Zone of proliferation", "Zone of hypertrophy", "Zone of calcification", "Zone of resorption"], 1,
    "In the zone of proliferation, chondrocytes divide and stack into columns, driving lengthwise growth before they hypertrophy and calcify.",
    "Chondrocytes divide in the proliferative zone of the growth plate."),
  Q("t4_p4", "t4", "Physiology & Biochem",
    "A 15-year-old boy's father is 180 cm and mother is 167 cm. Using the mid-parental height calculation, what is his predicted adult height?",
    ["173.5 cm", "178.5 cm", "180.0 cm", "182.5 cm", "186.5 cm"], 2,
    "For a boy: (father + mother + 13) / 2 = (180 + 167 + 13)/2 = 180 cm.",
    "Boy's MPH = (father + mother + 13) / 2."),
  Q("t4_p5", "t4", "Physiology & Biochem",
    "Which hormonal event is primarily responsible for closing the epiphyseal plates, ending longitudinal growth?",
    ["Peak secretion of IGF-1", "The action of oestrogen on the growth plate", "The rise in serum testosterone", "The decrease in TSH", "The plateau of GH levels"], 1,
    "Oestrogen (including that aromatised from testosterone in boys) drives epiphyseal plate fusion, ending linear growth.",
    "Oestrogen fuses the growth plates, in both sexes."),
  Q("t4_p6", "t4", "Physiology & Biochem",
    "A 14-year-old boy has short stature, delayed puberty and delayed bone age; his father was a 'late bloomer'. What is the most likely diagnosis?",
    ["Growth hormone deficiency", "Laron syndrome", "Constitutional delay of growth and puberty (CDGP)", "Familial short stature", "Hypothyroidism"], 2,
    "Delayed bone age with a family history of late puberty points to constitutional delay of growth and puberty, a normal variant where growth eventually catches up.",
    "Delayed bone age + 'late bloomer' parent = CDGP."),
  Q("t4_p7", "t4", "Physiology & Biochem",
    "Which physical change is specifically attributed to dihydrotestosterone (DHT), and which testicular cell converts testosterone to DHT under FSH stimulation?",
    ["Voice deepening; Leydig cells", "Muscle and bone growth; Sertoli cells", "Male-pattern hair loss; Sertoli cells", "Sebum production; Leydig cells", "Libido; Sertoli cells"], 2,
    "DHT (the more potent androgen) drives male-pattern hair loss, prostate growth and external genitalia. FSH acts on Sertoli cells, which carry out the conversion of testosterone in the testis.",
    "DHT → male-pattern balding/prostate; FSH acts on Sertoli cells."),
  Q("t4_p8", "t4", "Physiology & Biochem",
    "Where in the male reproductive tract do sperm acquire motility?",
    ["Rete testis", "Efferent ductules", "Epididymis", "Seminal vesicles", "Prostate gland"], 2,
    "Sperm leave the testis immotile and acquire functional motility as they mature through the epididymis.",
    "Sperm gain motility in the epididymis."),
  Q("t4_p9", "t4", "Physiology & Biochem",
    "What is the first clinical sign of puberty in boys?",
    ["Pubic hair growth", "Penile lengthening", "Voice breaking", "Testicular volume enlargement to 4 mL", "Growth spurt"], 3,
    "The earliest sign of puberty in boys is testicular enlargement to ≥4 mL (assessed with an orchidometer).",
    "First sign of male puberty: testicular volume ≥4 mL."),
  Q("t4_p10", "t4", "Physiology & Biochem",
    "Which structure secretes the majority of the ejaculate volume (≈46–80%), rich in fructose and prostaglandins?",
    ["Epididymis", "Prostate gland", "Bulbo-urethral gland", "Seminal vesicle", "Seminiferous tubules"], 3,
    "The seminal vesicles contribute most of the semen volume, fructose-rich fluid (energy for sperm) containing prostaglandins.",
    "Seminal vesicles: most of the ejaculate, fructose + prostaglandins."),
  Q("t4_bc1", "t4", "Physiology & Biochem",
    "Which best describes the initial cellular event following testosterone entry into a target cell?",
    ["Activation of membrane-bound receptor tyrosine kinases", "Binding to an intracellular receptor and translocation to the nucleus", "Stimulation of adenylyl cyclase and cAMP production", "Opening of ligand-gated ion channels", "Activation of the JAK-STAT pathway"], 1,
    "Testosterone is a steroid: it crosses the membrane and binds an intracellular androgen receptor, and the complex moves to the nucleus to regulate transcription.",
    "Testosterone binds an intracellular receptor → acts on transcription."),
  Q("t4_bc2", "t4", "Physiology & Biochem",
    "Which characteristic distinguishes steroid hormones from peptide hormones?",
    ["Steroid hormones require second-messenger systems", "Steroid hormones have a faster onset (seconds to minutes)", "Steroid hormones are lipophilic and cross cell membranes directly", "Steroid hormones bind cell-surface receptors", "Steroid hormones are stored in secretory vesicles"], 2,
    "Steroids are lipophilic and diffuse through the membrane to intracellular receptors; peptide hormones are water-soluble and act via surface receptors and second messengers.",
    "Steroids are lipophilic → intracellular receptors; peptides → surface receptors."),
  Q("t4_bc3", "t4", "Physiology & Biochem",
    "What is the primary hypothalamic signal that initiates testosterone release in males?",
    ["Growth hormone-releasing hormone (GHRH)", "Corticotropin-releasing hormone (CRH)", "Thyrotropin-releasing hormone (TRH)", "Gonadotropin-releasing hormone (GnRH)", "Dopamine"], 3,
    "GnRH from the hypothalamus drives pituitary LH/FSH release; LH then stimulates Leydig cells to make testosterone.",
    "GnRH → LH/FSH → testosterone."),
  Q("t4_bc4", "t4", "Physiology & Biochem",
    "Which hormone directly stimulates Sertoli cells to support spermatogenesis during puberty?",
    ["Testosterone", "Luteinising hormone (LH)", "Follicle-stimulating hormone (FSH)", "Inhibin B", "Activin"], 2,
    "FSH acts directly on Sertoli cells to support the developing sperm.",
    "FSH stimulates Sertoli cells."),
  Q("t4_bc5", "t4", "Physiology & Biochem",
    "A 16-year-old male has an aromatase deficiency. Which aspect of his development is most likely affected?",
    ["Initial testicular descent", "Development of male external genitalia", "Epiphyseal plate closure", "Spermatogonia differentiation", "Wolffian duct development"], 2,
    "Aromatase converts androgens to oestrogen, and oestrogen is required for epiphyseal plate closure; its deficiency causes continued growth and tall stature.",
    "No aromatase → no oestrogen → growth plates don't fuse."),
  Q("t4_bc6", "t4", "Physiology & Biochem",
    "After testosterone binds its intracellular receptor, what is the next step in the signalling cascade?",
    ["Phosphorylation of cytoplasmic proteins", "Formation of a hormone-receptor complex that acts as a transcription factor", "Activation of protein kinase A", "Increase in intracellular calcium", "Activation of phospholipase C"], 1,
    "The hormone-receptor complex acts as a transcription factor, binding hormone-response elements to alter gene expression.",
    "Steroid-receptor complex = a transcription factor."),
  Q("t4_bc7", "t4", "Physiology & Biochem",
    "Growth hormone promotes linear growth primarily through which mediator?",
    ["Direct action on chondrocytes", "Insulin-like growth factor 1 (IGF-1) from the liver", "Thyroid hormone potentiation", "Increased cortisol secretion", "Direct stimulation of osteoblasts"], 1,
    "Most of GH's growth-promoting effect is mediated by IGF-1, produced mainly by the liver in response to GH.",
    "GH works largely via liver-derived IGF-1."),
  Q("t4_bc8", "t4", "Physiology & Biochem",
    "Which phase of linear growth is primarily dependent on growth hormone and sex steroids?",
    ["Fetal phase", "Infantile phase (0–2 years)", "Childhood phase (2 years to puberty)", "Pubertal phase", "All phases equally"], 3,
    "The pubertal growth phase depends on the combined action of GH and rising sex steroids (the infantile phase is nutrition-dependent; childhood is GH/thyroid-dependent).",
    "Pubertal growth = GH + sex steroids."),
  Q("t4_bc9", "t4", "Physiology & Biochem",
    "A child with untreated congenital hypothyroidism would most likely exhibit which growth pattern?",
    ["Normal growth velocity with delayed bone age", "Severely impaired growth with delayed bone age", "Accelerated growth with advanced bone age", "Normal growth with advanced bone age", "Growth acceleration then premature fusion"], 1,
    "Thyroid hormone is essential for growth and skeletal maturation, so untreated hypothyroidism severely impairs growth and markedly delays bone age.",
    "Untreated hypothyroidism: poor growth + delayed bone age."),
  Q("t4_bc10", "t4", "Physiology & Biochem",
    "Testosterone acts on which testicular cells to maintain spermatogenesis after puberty?",
    ["Leydig cells only", "Sertoli cells only", "Spermatogonia directly", "Spermatids directly", "Peritubular myoid cells only"], 1,
    "Testosterone (made by Leydig cells) acts on Sertoli cells, which in turn support and maintain spermatogenesis.",
    "Testosterone supports spermatogenesis via Sertoli cells."),
  Q("t4_bc11", "t4", "Physiology & Biochem",
    "Which zone of the growth plate is primarily responsible for longitudinal bone growth?",
    ["Resting zone", "Proliferative zone", "Hypertrophic zone", "Zone of provisional calcification", "Primary ossification centre"], 1,
    "The proliferative zone, where chondrocytes divide and stack, drives longitudinal growth.",
    "Longitudinal growth comes from the proliferative zone."),
  Q("t4_bc12", "t4", "Physiology & Biochem",
    "What pattern of GnRH secretion is necessary for normal pubertal development?",
    ["Continuous high-level secretion", "Pulsatile secretion with increasing amplitude and frequency", "A single daily surge", "Random sporadic release", "Constant low-level secretion"], 1,
    "Puberty requires pulsatile GnRH of rising amplitude and frequency; continuous GnRH actually suppresses the axis (the basis of GnRH-agonist therapy).",
    "Pulsatile GnRH drives puberty; continuous GnRH suppresses it."),

  // ── Ethics, Law & EBM ──
  Q("t4_e2", "t4", "Ethics & EBM",
    "A 15-year-old with constitutional delay wants to start testosterone; the parents prefer to wait and the doctor feels treatment is reasonable but not urgent. Which approach fits the shared decision-making continuum?",
    ["Doctor decides based on clinical expertise (paternalistic)", "Doctor presents the option and parents decide (informed choice)", "Collaborative discussion exploring the values and preferences of patient, parents and the evidence", "Patient decides alone as they are Gillick competent", "Defer the decision until the patient turns 16"], 2,
    "Shared decision-making is a collaborative process that brings together the clinical evidence with the values and preferences of patient and family.",
    "Shared decision-making = collaborative, values + evidence."),
  Q("t4_e3", "t4", "Ethics & EBM",
    "A 15-year-old requests puberty blockers without parental knowledge. When assessing Gillick competence, which factor is LEAST relevant?",
    ["The young person's ability to understand the information", "The young person's ability to retain the information", "Whether the parents agree with the decision", "The young person's ability to weigh the information", "The young person's ability to communicate their decision"], 2,
    "Gillick competence depends on the young person's own capacity to understand, retain, weigh and communicate, not on whether the parents agree.",
    "Gillick competence is about the minor's capacity, not parental agreement."),
  Q("t4_e_mph", "t4", "Ethics & EBM",
    "A 10-year-old boy's father is 180 cm and mother is 165 cm. Using the mid-parental height formula, what is his predicted adult height?",
    ["162.5 cm", "172.5 cm", "175 cm", "180 cm", "185 cm"], 3,
    "For a boy: (father + mother + 13)/2 = (180 + 165 + 13)/2 = 179 cm ≈ 180 cm.",
    "Boy's MPH = (father + mother + 13)/2 ≈ 179 cm."),
  Q("t4_e4", "t4", "Ethics & EBM",
    "Which is a key benefit of shared decision-making when choosing treatments for short stature?",
    ["Reduces the need for clinical follow-up", "Guarantees the child reaches the 50th centile", "Aligns treatment choices with patient/family values", "Avoids the need to discuss treatment risks", "Automatically reduces treatment costs"], 2,
    "Shared decision-making ensures the chosen treatment fits the patient's and family's values and priorities.",
    "Shared decision-making aligns care with patient/family values."),

  // ── Behavioural & Social Sciences ──
  Q("t4_b1", "t4", "BSS",
    "A 14-year-old boy with short stature refuses GH treatment, saying he's 'fine being short', but his diary reveals he is being bullied. Which component of the biopsychosocial model is most relevant to understanding his decision?",
    ["Biological factors only (GH deficiency)", "Psychological factors (coping/denial)", "Social factors (peer relationships and bullying)", "The integrated interaction of psychological and social factors", "Medical non-compliance"], 3,
    "His decision reflects the interaction of psychological (denial/coping) and social (bullying) factors, the essence of the biopsychosocial model.",
    "Biopsychosocial: psychological and social factors interact."),
  Q("t4_b2", "t4", "BSS",
    "Which type of support involves offering praise, encouragement and confidence to someone?",
    ["Instrumental support", "Companionship support", "Esteem support", "Structural support", "Peer support"], 2,
    "Esteem (emotional/appraisal) support builds a person's confidence and self-worth through praise and encouragement.",
    "Esteem support = praise and encouragement."),
  Q("t4_b3", "t4", "BSS",
    "What does structural support refer to?",
    ["Practical help like lending money", "Encouraging someone to believe in their abilities", "Providing advice or guidance", "The size and stability of a person's social network (family, friends, community)", "Helping to build a neighbour's house"], 3,
    "Structural support describes the size and stability of a person's social network, distinct from the functional types (emotional, instrumental, informational).",
    "Structural support = the make-up of one's social network."),
);
