// questions/t5.jsx, Theme 5: HIV & Immunity
// Source: ISocMedEd Theme 5 MCQ Bank 2025. Image-dependent items omitted.
// Answers & explanations authored (no official key supplied).

window.QUESTIONS.push(
  // ── Anatomy & Histology ──
  Q("t5_a2", "t5", "Anatomy",
    "Which of the following muscles assists in wrist flexion?",
    ["Flexor pollicis longus", "Brachioradialis", "Palmaris longus", "Flexor digitorum superficialis", "Pronator quadratus"], 2,
    "Palmaris longus is a weak wrist flexor (and tensor of the palmar aponeurosis). Flexor pollicis longus flexes the thumb and pronator quadratus pronates.",
    "Palmaris longus assists wrist flexion."),
  Q("t5_a4", "t5", "Anatomy",
    "Which of the following are the deep muscles of the posterior compartment of the forearm?",
    ["Brachioradialis, extensor carpi radialis longus/brevis, extensor digitorum", "Pronator teres, flexor carpi radialis, palmaris longus, flexor carpi ulnaris", "Flexor digitorum profundus, flexor pollicis longus, pronator quadratus", "Biceps brachii, coracobrachialis, brachialis", "Supinator, abductor pollicis longus, extensor pollicis longus/brevis, extensor indicis"], 4,
    "The deep posterior compartment contains supinator, abductor pollicis longus, extensor pollicis longus and brevis, and extensor indicis. Flexor digitorum profundus etc. are the deep anterior compartment.",
    "Deep posterior forearm: supinator, APL, EPL/EPB, extensor indicis."),
  Q("t5_a5", "t5", "Anatomy",
    "Which muscle is involved in wrist abduction (radial deviation)?",
    ["Pronator teres", "Flexor carpi radialis", "Brachioradialis", "Extensor digitorum", "Lumbricals"], 1,
    "Flexor carpi radialis (with the extensor carpi radialis muscles and abductor pollicis longus) abducts/radially deviates the wrist.",
    "Flexor carpi radialis radially deviates (abducts) the wrist."),
  Q("t5_a7", "t5", "Anatomy",
    "What is the function of the thymus?",
    ["An organ where red blood cells are produced and stored", "An organ where antibodies are synthesised and released", "An organ where B lymphocytes mature and differentiate", "An organ where T lymphocytes mature and differentiate", "An organ responsible for filtering toxins from the blood"], 3,
    "The thymus is where T lymphocytes mature and undergo positive/negative selection. B cells mature in the bone marrow.",
    "T cells mature in the Thymus; B cells in the Bone marrow."),
  Q("t5_a8", "t5", "Anatomy",
    "Which of the following is true about the right lymphatic duct?",
    ["It drains the entire lower half of the body", "It merges with other vessels to form the cisterna chyli", "It ascends through the thorax to enter the left venous angle", "It drains the entire upper half of the body", "It enters and drains into the right venous angle"], 4,
    "The right lymphatic duct drains the right upper quadrant (right head/neck, arm and thorax) into the right venous angle. The thoracic duct drains the rest of the body.",
    "Right lymphatic duct → right venous angle (drains the right upper quadrant)."),
  Q("t5_a12", "t5", "Anatomy",
    "Which nerve supplies the muscles of the posterior compartment of the forearm?",
    ["Ulnar nerve", "Radial nerve", "Musculocutaneous nerve", "Median nerve", "Axillary nerve"], 1,
    "The radial nerve (via its deep/posterior interosseous branch) supplies the extensor muscles of the posterior forearm compartment.",
    "Radial nerve supplies the posterior (extensor) forearm."),
  Q("t5_h13", "t5", "Anatomy",
    "What type of cells line the epididymis?",
    ["Stratified columnar epithelium with long stereocilia", "Pseudostratified columnar epithelium with long stereocilia", "Pseudostratified squamous epithelium", "Pseudostratified columnar epithelium (no stereocilia)", "Simple squamous epithelium with long stereocilia"], 1,
    "The epididymis is lined by pseudostratified columnar epithelium with long stereocilia, which absorb fluid and aid sperm maturation.",
    "Epididymis: pseudostratified columnar with stereocilia."),
  Q("t5_h14", "t5", "Anatomy",
    "Which zone of the prostate gland surrounds the ejaculatory ducts?",
    ["Transition zone", "Central zone", "Peripheral zone", "Posterior zone", "Fibromuscular stroma"], 1,
    "The central zone surrounds the ejaculatory ducts. The peripheral zone is where most prostate cancers arise; the transition zone enlarges in BPH.",
    "Central zone surrounds the ejaculatory ducts."),

  // ── Physiology, Pathophysiology & Biochemistry ──
  Q("t5_p16", "t5", "Physiology & Biochem",
    "Which mediator is contained in basophil granules?",
    ["IFN-γ", "Histamine", "IL-8", "Lactoferrin", "IL-12"], 1,
    "Basophils (and mast cells) store histamine, released in allergic and inflammatory responses.",
    "Basophil granules contain histamine."),
  Q("t5_p17", "t5", "Physiology & Biochem",
    "Which of the following is a feature of innate immunity?",
    ["Specific to a pathogen", "Has immunological memory", "Immediate response", "Amplifies with repeated exposure", "Mediated exclusively by antibodies"], 2,
    "Innate immunity is immediate and non-specific, without memory. Specificity, memory and amplification are features of the adaptive response.",
    "Innate immunity: immediate, non-specific, no memory."),
  Q("t5_p18", "t5", "Physiology & Biochem",
    "Which antibody is required to most effectively activate the classical complement pathway?",
    ["IgA", "IgE", "IgG", "IgD", "IgM"], 4,
    "IgM, with its pentameric structure, is the most efficient activator of the classical complement pathway (IgG can also activate it).",
    "IgM is the strongest classical-pathway complement activator."),
  Q("t5_p19", "t5", "Physiology & Biochem",
    "How does the membrane attack complex (MAC) kill bacteria?",
    ["Inducing apoptosis", "Enhancing phagocytosis", "Punching holes in the membrane", "Neutralising toxins", "Triggering cytokine release"], 2,
    "The MAC (C5b–C9) forms pores in the microbial membrane, causing osmotic lysis.",
    "MAC lyses cells by punching membrane pores."),
  Q("t5_p20", "t5", "Physiology & Biochem",
    "Which statement about opsonisation is correct?",
    ["It aids phagocytosis by coating pathogens with IgG or C3b", "It directly kills pathogens by forming pores", "It prevents neutrophils from binding pathogens", "It is mediated exclusively by IgE", "It only occurs after MAC formation"], 0,
    "Opsonisation coats pathogens with opsonins (IgG, C3b) that phagocyte receptors recognise, greatly enhancing phagocytosis.",
    "Opsonins (IgG, C3b) tag pathogens for phagocytosis."),
  Q("t5_p21", "t5", "Physiology & Biochem",
    "Which granulocyte is most abundant in blood?",
    ["Mast cell", "Monocyte", "Eosinophil", "Neutrophil", "Basophil"], 3,
    "Neutrophils are the most abundant circulating white cell and the first responders to bacterial infection.",
    "Neutrophils are the most abundant granulocyte."),
  Q("t5_p22", "t5", "Physiology & Biochem",
    "What are eosinophils primarily involved in?",
    ["Viral infections", "Type I hypersensitivity and multicellular parasites", "Phagocytosis of bacteria", "Antibody production", "Recognition of cells lacking MHC I"], 1,
    "Eosinophils combat multicellular parasites (helminths) and contribute to type I hypersensitivity/allergic responses.",
    "Eosinophils: parasites and allergy."),
  Q("t5_p23", "t5", "Physiology & Biochem",
    "Which chemokine is most important for neutrophil recruitment to a site of injury?",
    ["IL-1", "IL-6", "IL-8", "TNF-α", "IFN-γ"], 2,
    "IL-8 (CXCL8) is the key chemokine that recruits and activates neutrophils.",
    "IL-8 recruits neutrophils."),
  Q("t5_p24", "t5", "Physiology & Biochem",
    "Fever during infection is primarily triggered by:",
    ["Histamine", "IL-1β and TNF-α", "Platelet-activating factor", "Leukotrienes", "Interferons"], 1,
    "The endogenous pyrogens IL-1β and TNF-α act on the hypothalamus (via prostaglandin E2) to raise the temperature set point.",
    "Endogenous pyrogens: IL-1β and TNF-α."),
  Q("t5_p25", "t5", "Physiology & Biochem",
    "Which of the following is NOT typically found in pus?",
    ["Live neutrophils", "Dead microbes", "Dead macrophages", "Red blood cells", "Dead local tissue cells"], 3,
    "Pus consists of neutrophils (live and dead), dead microbes and dead tissue cells; red blood cells are not a typical component.",
    "Pus is mainly neutrophils + dead microbes/tissue, not RBCs."),
  Q("t5_p26", "t5", "Physiology & Biochem",
    "Which protein is the major structural protein of the HIV viral capsid?",
    ["p24", "p64", "p10", "gp120", "gp41"], 0,
    "p24 forms the HIV capsid and is used as an early diagnostic marker. gp120/gp41 are envelope glycoproteins used for entry.",
    "p24 = HIV capsid protein (early marker)."),
  Q("t5_p27", "t5", "Physiology & Biochem",
    "What is a potential consequence of removal of the thymus several months before birth?",
    ["No cell-mediated immunity", "Rejection of organs during transplant", "Decreased blood circulation", "Increased effectiveness of adaptive immunity", "Progressive death of B cells throughout life"], 0,
    "Without a thymus, T cells cannot mature, so cell-mediated immunity fails (as in DiGeorge syndrome).",
    "No thymus → no T-cell maturation → no cell-mediated immunity."),
  Q("t5_p28", "t5", "Physiology & Biochem",
    "Which of these is NOT part of the lifecycle of a retrovirus?",
    ["Integration", "Reverse translation", "Binding", "Budding", "Release and maturation"], 1,
    "Retroviruses use reverse transcription (RNA→DNA), not 'reverse translation' (which does not exist).",
    "Retroviruses do reverse transcription, not 'reverse translation'."),
  Q("t5_p29", "t5", "Physiology & Biochem",
    "What immediately precedes widespread dissemination of HIV?",
    ["Constriction of blood vessels", "Extreme sweating", "Fever", "Fusion of dendritic cells and CD4 lymphocytes", "Entry of virus-infected cells into the bloodstream"], 3,
    "Dendritic cells capture HIV at mucosal surfaces and carry it to lymphoid tissue, where they interact with CD4 T cells, seeding the infection before systemic dissemination.",
    "Dendritic cell–CD4 interaction in lymphoid tissue precedes spread."),
  Q("t5_p30", "t5", "Physiology & Biochem",
    "Which of these is NOT secreted by T helper cells?",
    ["IL-1", "IL-2", "IL-3", "Granulocyte-monocyte colony-stimulating factor", "Interferon gamma"], 0,
    "IL-1 is produced mainly by macrophages. T helper cells secrete IL-2, IL-3, GM-CSF and IFN-γ.",
    "IL-1 is a macrophage cytokine, not a Th-cell one."),
  Q("t5_p31", "t5", "Physiology & Biochem",
    "Which of the following statements is FALSE?",
    ["IgE is involved in hypersensitivity reactions", "IgG can cross the placenta", "IgM is the most abundant antibody in a primary immune response", "IgD is the major antibody in breast milk", "IgE is important in parasitic infections"], 3,
    "IgA, not IgD, is the major antibody in breast milk and mucosal secretions. The other statements are true.",
    "Secretory IgA (not IgD) dominates breast milk."),
  Q("t5_p32", "t5", "Physiology & Biochem",
    "The typical IgG antibody has:",
    ["Two heavy and two light polypeptide chains", "A constant portion that binds the antigen", "Ten binding sites", "No binding ability", "A pentamer structure"], 0,
    "IgG is a monomer of two heavy and two light chains, with two antigen-binding sites in its variable regions. IgM is the pentamer.",
    "IgG = 2 heavy + 2 light chains, 2 binding sites."),
  Q("t5_p33", "t5", "Physiology & Biochem",
    "What do cell–cell adhesion molecules do in antigen presentation?",
    ["Bind the T cell to the pathogen to release cytotoxic substances", "Bind a T cell to an MHC complex", "Bind an antigen-presenting cell to a T cell", "Bind a B cell to its antibodies", "Bind an antigen to an antigen-presenting cell"], 2,
    "Adhesion molecules stabilise the contact between an antigen-presenting cell and a T cell, supporting the immunological synapse.",
    "Adhesion molecules hold the APC and T cell together."),
  Q("t5_p34", "t5", "Physiology & Biochem",
    "What is the name of the protein released by cytotoxic T cells that punches holes in target cells?",
    ["p17 matrix protein", "Perforins", "Conester", "p53", "ZP3"], 1,
    "Cytotoxic T cells release perforin, which forms pores in the target cell membrane, allowing granzymes to enter and trigger apoptosis.",
    "Perforin punches pores; granzymes then induce apoptosis."),

  // ── Clinical & Pharmacology ──
  Q("t5_c1", "t5", "Clinical & Pharmacology",
    "What is the benefit of including the p24 protein as a biomarker in HIV diagnostic testing?",
    ["Helps determine viral load during antiretroviral therapy", "Confirms HIV drug-resistant mutations", "Closes the 'window period' before antibodies have formed", "Detects long-term immunity after HIV vaccination", "Identifies HIV-2 specifically"], 2,
    "p24 antigen appears before antibodies, so combined antigen/antibody tests detect infection earlier, shortening the window period.",
    "p24 antigen shortens the HIV window period."),
  Q("t5_c2", "t5", "Clinical & Pharmacology",
    "Which is the most common serious opportunistic infection in advanced HIV?",
    ["Toxoplasma gondii encephalitis", "Cytomegalovirus retinitis", "Pneumocystis jirovecii pneumonia", "Mycobacterium avium complex infection", "Cryptococcal meningitis"], 2,
    "Pneumocystis jirovecii pneumonia (PCP/PJP) is the classic AIDS-defining opportunistic infection, typically when CD4 falls below 200.",
    "PCP is the classic AIDS-defining infection (CD4 < 200)."),
  Q("t5_c3", "t5", "Clinical & Pharmacology",
    "A viral load of under 50 copies/mL means:",
    ["The virus is spreading rapidly", "The virus is undetectable and therefore untransmissible", "The virus will soon exit the body", "The virus is not HIV", "The virus is undetectable but can still be transmitted"], 1,
    "An undetectable viral load (<50 copies/mL) on treatment means HIV cannot be sexually transmitted, 'Undetectable = Untransmissible' (U=U).",
    "Undetectable = Untransmissible (U=U)."),
  Q("t5_c4", "t5", "Clinical & Pharmacology",
    "Which best describes the principle of immunohistochemistry?",
    ["Staining tissue based on DNA content using dyes", "Using antibodies to detect specific proteins in tissue sections", "Visualising live cells using electron microscopy", "Measuring RNA levels in tissue homogenates", "Counting cells in a tissue section"], 1,
    "Immunohistochemistry uses labelled antibodies to localise specific proteins (antigens) within tissue sections.",
    "IHC = antibodies detecting specific proteins in tissue."),
  Q("t5_c5", "t5", "Clinical & Pharmacology",
    "A CD4 cell count of 200–349 cells/mm³ indicates:",
    ["Mild immunodeficiency", "Moderate immunodeficiency", "Severe immunodeficiency", "Normal immunity"], 1,
    "CD4 200–349 is moderate immunodeficiency; below 200 is severe (AIDS-defining threshold).",
    "CD4 200–349 = moderate; <200 = severe (AIDS)."),
  Q("t5_ph1", "t5", "Clinical & Pharmacology",
    "Abacavir is:",
    ["An NRTI that mimics a nucleoside; once incorporated into the viral DNA chain it terminates the chain", "An NNRTI that mimics a nucleoside and terminates the DNA chain", "An NNRTI that binds reverse transcriptase causing a conformational change", "An NRTI that binds reverse transcriptase causing a conformational change", "None of the above"], 0,
    "Abacavir is a nucleoside reverse transcriptase inhibitor (NRTI): it mimics a nucleoside and, once incorporated, terminates the growing viral DNA chain.",
    "Abacavir = NRTI (chain terminator)."),
  Q("t5_ph2", "t5", "Clinical & Pharmacology",
    "Darunavir is:",
    ["An NNRTI", "An NRTI", "A protease inhibitor", "An antibiotic", "An INSTI"], 2,
    "Darunavir is a protease inhibitor, blocking cleavage of viral polyproteins needed for maturation.",
    "Darunavir = protease inhibitor."),
  Q("t5_ph3", "t5", "Clinical & Pharmacology",
    "An antiretroviral (ART) regimen is usually:",
    ["A single drug, because multiple drugs cause adverse effects", "A single drug, because multiple drugs raise the CD4 count too high", "A combination that usually incorporates two different NRTIs as a backbone", "A combination that must incorporate at least one INSTI", "Chosen based on the doctor's preference"], 2,
    "Standard ART combines a backbone of two NRTIs with a third agent (an INSTI, NNRTI or PI) to suppress the virus and limit resistance.",
    "ART = 2-NRTI backbone + a third agent."),
  Q("t5_ph4", "t5", "Clinical & Pharmacology",
    "An example of a beta-lactam antibiotic is:",
    ["Vancomycin, used for MRSA", "Gentamicin, which targets ribosomes", "Azithromycin", "Penicillin, which inhibits peptidoglycan cross-linking", "Levofloxacin, which inhibits nucleic acid synthesis"], 3,
    "Penicillins are beta-lactams that inhibit peptidoglycan cross-linking in the bacterial cell wall.",
    "Penicillin = beta-lactam (blocks cell-wall cross-linking)."),

  // ── Ethics & Law ──
  Q("t5_e1", "t5", "Ethics & EBM",
    "A patient with newly diagnosed HIV who understands the implications refuses to share the information with their GP. According to GMC guidance, what is the appropriate next step?",
    ["Don't disclose to the GP under any circumstances", "Inform the GP because HIV is communicable", "Explain why sharing with the GP matters and try to seek consent again", "Tell colleagues at the hospital for advice", "Disclose to Public Health England as HIV requires mandatory reporting"], 2,
    "Respect the competent patient's confidentiality, but explain the benefits of sharing with the GP and seek consent again. HIV is not subject to mandatory named reporting.",
    "Respect confidentiality; explain benefits and re-seek consent."),
  Q("t5_e2", "t5", "Ethics & EBM",
    "In which situation can confidentiality be legally breached without consent?",
    ["When the patient lacks capacity and disclosure is in their best interests", "When the patient refuses to follow medical advice", "When the patient's family asks for their information", "When another healthcare worker asks for the files"], 0,
    "Disclosure without consent can be justified when a patient lacks capacity and sharing is in their best interests (also for serious public-safety risks or by law).",
    "Breach allowed if patient lacks capacity and it's in their best interests."),

  // ── Behavioural & Social Sciences ──
  Q("t5_b2", "t5", "BSS",
    "A smoker says 'I know smoking is bad, but I am not ready to quit yet.' Which stage of the Transtheoretical model is this?",
    ["Precontemplation", "Contemplation", "Preparation", "Action", "Maintenance"], 1,
    "Awareness of the problem while not yet committed to change is the contemplation stage. Precontemplation is no awareness/intention.",
    "Aware but not ready = contemplation."),
  Q("t5_b3", "t5", "BSS",
    "Which stage involves a person actively changing their behaviour (Transtheoretical model)?",
    ["Precontemplation", "Contemplation", "Preparation", "Action", "Maintenance"], 3,
    "The action stage is where the person is actively modifying their behaviour; maintenance is sustaining that change.",
    "Active change = action stage."),
  Q("t5_b4", "t5", "BSS",
    "According to the COM-B model, which is NOT one of the core components required for a behaviour?",
    ["Capability", "Opportunity", "Motivation", "Intention", "Behaviour"], 3,
    "COM-B comprises Capability, Opportunity and Motivation, which interact to produce Behaviour. Intention is not a COM-B component.",
    "COM-B = Capability, Opportunity, Motivation → Behaviour."),
  Q("t5_b5", "t5", "BSS",
    "Which factor directly predicts behaviour according to the Theory of Planned Behaviour?",
    ["Attitudes", "Intentions", "Subjective norms", "Perceived behavioural control", "Past behaviour"], 1,
    "In the Theory of Planned Behaviour, intention is the direct predictor of behaviour; attitudes, subjective norms and perceived control shape intention.",
    "Intention is the direct predictor of behaviour (TPB)."),
);
