// questions/t6.jsx, Theme 6: Cancer
// Source: ISocMedEd Theme 6 MCQ Bank 2025. Image-dependent items omitted.
// Q16 & Q23 use the bank's own stated answers; others authored.

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t6_a4", "t6", "Anatomy",
    "A 46-year-old has breast cancer in the superomedial quadrant with a malignant node alongside the internal thoracic artery. Which lymphatic pathway best explains this spread?",
    ["Subareolar plexus → pectoral nodes → central nodes → apical nodes → subclavian trunk", "Subareolar plexus → parasternal nodes → bronchomediastinal trunk → venous angle", "Subareolar plexus → interpectoral nodes → supraclavicular nodes → thoracic duct", "Subareolar plexus → humeral nodes → apical nodes → right lymphatic duct", "Subareolar plexus → inferior phrenic nodes → cisterna chyli → thoracic duct"], 1,
    "The medial breast drains to the parasternal (internal thoracic) nodes that run with the internal thoracic artery, then via the bronchomediastinal trunk to the venous angle.",
    "Medial breast → parasternal (internal thoracic) nodes."),
  Q("t6_a5", "t6", "Anatomy",
    "A lesion of the musculocutaneous nerve will MOST impair which combination of functions?",
    ["Forearm pronation and wrist flexion", "Shoulder abduction and elbow flexion", "Shoulder flexion and elbow extension", "Elbow flexion and forearm supination", "Shoulder abduction and wrist extension"], 3,
    "The musculocutaneous nerve supplies biceps brachii, brachialis and coracobrachialis, so its lesion weakens elbow flexion and forearm supination.",
    "Musculocutaneous nerve = elbow flexion + supination (biceps)."),
  Q("t6_a6", "t6", "Anatomy",
    "The axillary artery begins at the lateral border of the first rib and ends at the inferior border of which muscle?",
    ["Subscapularis", "Latissimus dorsi", "Serratus anterior", "Teres major", "Pectoralis major"], 3,
    "The axillary artery becomes the brachial artery at the inferior border of teres major.",
    "Axillary → brachial artery at the inferior border of teres major."),
  Q("t6_a7", "t6", "Anatomy",
    "A surgeon separates breast tissue from the underlying pectoral fascia. Which anatomical space are they dissecting?",
    ["Quadrangular space", "Rectomammary space", "Retromammary space", "Thoracic fascia", "Axillary sheath"], 2,
    "The retromammary space is the loose areolar plane between the breast and the pectoral fascia, allowing the breast to move over the muscle.",
    "Retromammary space lies between breast and pectoral fascia."),
  Q("t6_a8", "t6", "Anatomy",
    "A patient cannot initiate abduction of the arm (0–15°) but abduction from 15–90° remains possible. Which nerve is most likely damaged?",
    ["Axillary nerve", "Subscapular nerve", "Suprascapular nerve", "Long thoracic nerve", "Thoracodorsal nerve"], 2,
    "Supraspinatus initiates the first ~15° of abduction and is supplied by the suprascapular nerve; deltoid (axillary nerve) continues abduction thereafter.",
    "First 15° of abduction = supraspinatus (suprascapular nerve)."),
  Q("t6_a9", "t6", "Anatomy",
    "A knife injury damages the medial head of triceps brachii. Which feature helps identify this head?",
    ["Origin superior to the radial groove", "Origin from the coracoid process", "Origin inferior to the radial groove", "Origin from the infraglenoid tubercle", "Insertion on the radial tuberosity"], 2,
    "The medial head of triceps arises from the humerus inferior to the radial (spiral) groove; the lateral head arises superior to it, and the long head from the infraglenoid tubercle.",
    "Medial head of triceps originates below the radial groove."),
  Q("t6_a10", "t6", "Anatomy",
    "Which structures form the medial wall of the axilla?",
    ["Intertubercular sulcus + subscapularis", "Ribs + intercostal muscles + serratus anterior", "Pectoralis major + pectoralis minor", "Latissimus dorsi + teres major + subscapularis", "Skin + axillary fascia"], 1,
    "The medial wall of the axilla is formed by the upper ribs with their intercostal muscles, covered by serratus anterior.",
    "Medial axillary wall: ribs + intercostals + serratus anterior."),
  Q("t6_a11", "t6", "Anatomy",
    "All rotator cuff muscles insert onto the greater tubercle except one. Which is the exception and where does it insert?",
    ["Supraspinatus + lesser tubercle", "Infraspinatus + bicipital groove", "Teres major + crest of lesser tubercle", "Subscapularis + lesser tubercle", "Teres minor + superior to radial groove"], 3,
    "Subscapularis is the only rotator cuff muscle to insert on the lesser tubercle (the other three, supraspinatus, infraspinatus, teres minor, insert on the greater tubercle).",
    "Subscapularis inserts on the lesser tubercle (rest → greater tubercle)."),
  Q("t6_a12", "t6", "Anatomy",
    "Which option correctly distinguishes teres major from teres minor?",
    ["Teres major laterally rotates the arm", "Teres major is innervated by the axillary nerve", "Teres major inserts on the medial lip of the intertubercular groove", "Teres minor inserts on the lesser tubercle", "Teres minor adducts the arm"], 2,
    "Teres major inserts on the medial lip of the intertubercular (bicipital) groove and medially rotates/adducts the arm. Teres minor is a rotator cuff muscle (greater tubercle, lateral rotation, axillary nerve).",
    "Teres major → medial lip of bicipital groove (medial rotator)."),

  // ── Physiology ──
  Q("t6_p13", "t6", "Physiology & Biochem",
    "Which cyclin/CDK complex is active in early G1, driving the cell through G1 towards S phase?",
    ["Cyclin A/CDK2", "Cyclin D/CDK4", "Cyclin A/CDK1", "Cyclin B/CDK1", "Cyclin E/CDK2"], 1,
    "Cyclin D/CDK4 (and CDK6) is active in early G1 and phosphorylates Rb to advance the cycle; Cyclin E/CDK2 then drives the G1/S transition.",
    "Cyclin D/CDK4 acts in early G1 (phosphorylates Rb)."),
  Q("t6_p14", "t6", "Physiology & Biochem",
    "In the intrinsic pathway of apoptosis, which protein leaks from the mitochondrial intermembrane space into the cytoplasm?",
    ["Caspases", "Paracaspases", "BAX", "Cytochrome C", "DISC"], 3,
    "Mitochondrial outer-membrane permeabilisation releases cytochrome c, which forms the apoptosome and activates caspase-9.",
    "Intrinsic apoptosis: cytochrome c → apoptosome → caspase-9."),
  Q("t6_p15", "t6", "Physiology & Biochem",
    "Phosphorylation of histone H1 by cyclin B results in:",
    ["Spindle formation", "Nuclear envelope formation", "Nuclear envelope breakdown", "DNA replication", "Chromosome condensation"], 4,
    "Cyclin B/CDK1 phosphorylates histone H1, driving chromosome condensation as the cell enters mitosis.",
    "Cyclin B/CDK1 → histone H1 phosphorylation → chromosome condensation."),
  Q("t6_p16", "t6", "Physiology & Biochem",
    "To differentiate familial from sporadic cancers, familial cancers can result in:",
    ["Late onset", "A single tumour usually", "Multiple tumours of the same type", "Only one copy of the tumour cell's TSG inactivated", "Only oncogenic cancers"], 2,
    "Familial cancers (a germline mutation already present in every cell) tend to present earlier and with multiple tumours of the same type, unlike the usually single sporadic tumour.",
    "Familial cancers: earlier onset, often multiple same-type tumours."),
  Q("t6_p17", "t6", "Physiology & Biochem",
    "Which of these is NOT a way of activating proto-oncogenes into oncogenes?",
    ["Point mutations", "Gene amplification", "Chromosomal translocation", "Loss-of-function mutation", "Viral stimulation"], 3,
    "Oncogene activation is a gain of function (point mutation, amplification, translocation, viral insertion). Loss-of-function mutations instead inactivate tumour suppressor genes.",
    "Oncogenes activate by gain of function, not loss of function."),
  Q("t6_p18", "t6", "Physiology & Biochem",
    "Which tumour suppressor gene promotes apoptosis and DNA repair?",
    ["P53", "BRCA1", "APC", "HER2", "Rb"], 0,
    "p53, the 'guardian of the genome', halts the cycle for repair or triggers apoptosis if DNA damage is irreparable.",
    "p53 = guardian of the genome (repair or apoptosis)."),
  Q("t6_p19", "t6", "Physiology & Biochem",
    "Which is a reversible early stage where there is growth of tissue by proliferation of abnormal cells?",
    ["Neoplasia", "Anaplasia", "Dysplasia", "Metaplasia", "Hypertrophy"], 2,
    "Dysplasia is disordered but potentially reversible growth of abnormal cells; if unchecked it can progress to carcinoma in situ and invasive cancer.",
    "Dysplasia = abnormal, still-reversible growth."),
  Q("t6_p20", "t6", "Physiology & Biochem",
    "According to TNM staging, T3 N2 M1 means:",
    ["Tumour <2 cm, 9 nodes involved, no metastasis", "Tumour >5 cm, 3 nodes involved, no metastasis", "Tumour 2–5 cm, 6 nodes involved, no metastasis", "Tumour >5 cm, 6 nodes involved, metastasis present", "Tumour >10 cm, 9 nodes involved, metastasis present"], 3,
    "T3 indicates a larger tumour (>5 cm in breast staging), N2 regional node involvement, and M1 the presence of distant metastasis.",
    "M1 always means distant metastasis is present."),
  Q("t6_p21", "t6", "Physiology & Biochem",
    "The mechanism of action of tamoxifen is:",
    ["Aromatase inhibition decreasing oestrogen synthesis", "Selective oestrogen receptor antagonism (in breast tissue)", "Direct inhibition of HER2 signalling", "Induction of apoptosis through p53", "Inhibition of oestrogen receptor transcription in the hypothalamus"], 1,
    "Tamoxifen is a selective oestrogen receptor modulator (SERM) that antagonises the oestrogen receptor in breast tissue, used in ER-positive breast cancer.",
    "Tamoxifen = SERM, antagonist at the breast oestrogen receptor."),
  Q("t6_p22", "t6", "Physiology & Biochem",
    "Which of these is NOT a risk factor for breast cancer?",
    ["Female gender", "Genetics (e.g. BRCA)", "Older age", "Later menarche", "Long-term smoking"], 3,
    "Early menarche (longer oestrogen exposure) increases risk, so later menarche is protective, not a risk factor.",
    "Early menarche raises risk; later menarche is protective."),
  Q("t6_p23", "t6", "Physiology & Biochem",
    "In mammography, calcifications are most commonly associated with:",
    ["Dense breast tissue", "Early-stage cancer", "Hormonal imbalance", "HER2-positive breast cancer", "Fibroadenoma"], 1,
    "Microcalcifications mark areas where cells are turning over faster than normal and are an important early radiological sign of cancer.",
    "Mammographic microcalcifications can be an early sign of cancer."),
  Q("t6_p24", "t6", "Physiology & Biochem",
    "Which is the most common type of breast cancer, starting in the ducts and invading surrounding tissue?",
    ["Ductal carcinoma in situ", "Invasive ductal carcinoma", "Invasive lobular carcinoma", "Inflammatory breast cancer", "Triple-negative breast cancer"], 1,
    "Invasive ductal carcinoma (no special type) is the most common breast cancer; it begins in the ducts and invades the surrounding stroma. DCIS is non-invasive.",
    "Invasive ductal carcinoma is the commonest breast cancer."),
  Q("t6_p25", "t6", "Physiology & Biochem",
    "Which medication is often used in breast cancer in post-menopausal women?",
    ["Tamoxifen", "Herceptin", "Letrozole", "Clomiphene citrate", "Finasteride"], 2,
    "Letrozole is an aromatase inhibitor used in post-menopausal women, where peripheral aromatisation is the main oestrogen source. Tamoxifen is generally preferred pre-menopause.",
    "Aromatase inhibitors (letrozole) suit post-menopausal breast cancer."),

  // ── Ethics & Law ──
  Q("t6_e1", "t6", "Ethics & EBM",
    "Which best describes shared decision-making (SDM) in the context of informed consent?",
    ["The doctor decides the best treatment and informs the patient afterward", "The patient makes all decisions independently, without clinician input", "A collaborative process where clinician expertise and patient preferences guide the decision", "A legal form signed before a procedure", "Providing information only when the patient asks"], 2,
    "Shared decision-making brings together the clinician's expertise and the patient's values and preferences to reach a decision together.",
    "SDM = clinician expertise + patient preferences, together."),
  Q("t6_e2", "t6", "Ethics & EBM",
    "Which factor does NOT affect a patient's capacity to give informed consent?",
    ["Age", "Language barrier", "Intellectual disability", "External pressure", "Level of sedation"], 0,
    "Capacity is decision-specific and assumed in adults; age alone does not remove it. Language, intellectual disability, coercion and sedation can all impair understanding or voluntariness.",
    "Capacity is decision-specific, not determined by age alone."),
  Q("t6_e3", "t6", "Ethics & EBM",
    "What is the primary ethical justification for obtaining informed consent?",
    ["To protect doctors from legal action", "To satisfy hospital policies", "To uphold patient autonomy by enabling voluntary, informed choices", "To ensure all patients receive the same treatment", "To improve healthcare efficiency"], 2,
    "Informed consent exists chiefly to respect patient autonomy, the right to make a voluntary, informed choice about one's own care.",
    "Informed consent upholds patient autonomy."),

  // ── Behavioural & Social Sciences ──
  Q("t6_b1", "t6", "BSS",
    "A patient refuses chemotherapy because hair loss will 'make people see me as a cancer patient'. Which concept explains this?",
    ["Illness behaviour", "Threats to illness identity / social stigma", "Internal locus of control", "High self-efficacy", "Cue to action"], 1,
    "The fear of a visible 'cancer patient' label reflects concerns about illness identity and social stigma influencing the treatment decision.",
    "Visible-illness concerns = illness identity / stigma."),
  Q("t6_b2", "t6", "BSS",
    "A woman attends screening because her sister was diagnosed with breast cancer, making her feel 'at high risk'. Which Health Belief Model construct applies?",
    ["Cues to action", "Perceived susceptibility", "Perceived benefits", "Emotional coping", "Self-efficacy"], 1,
    "Feeling personally at risk because of a family diagnosis is perceived susceptibility, the belief about one's own likelihood of developing the condition.",
    "Believing you're personally at risk = perceived susceptibility."),
  Q("t6_b3", "t6", "BSS",
    "A woman with breast cancer lives alone with no one to accompany her, so she keeps missing chemotherapy. Which COM-B domain is the major influence?",
    ["Psychological capability", "Physical capability", "Social opportunity", "Reflective motivation", "Automatic motivation"], 2,
    "Lacking the social support and circumstances needed to attend is a deficit in social opportunity within the COM-B model.",
    "No social support to attend = social opportunity (COM-B)."),
);
