// questions/t7.jsx, Theme 7: Ageing, frailty & polypharmacy
// Source: ISocMedEd Theme 7 MCQ Bank 2025. Image-dependent items omitted.
// Answers & explanations authored (no official key supplied).

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t7_a4", "t7", "Anatomy",
    "Which nerve roots give rise to the axillary nerve?",
    ["C5–C7", "C8–T1", "C5–T1", "C6–T1", "C5–C6"], 4,
    "The axillary nerve arises from the posterior cord with root values C5–C6.",
    "Axillary nerve: C5–C6 (posterior cord)."),
  Q("t7_a5", "t7", "Anatomy",
    "Which nerve innervates the posterior compartment of the forearm?",
    ["Median nerve", "Ulnar nerve", "Musculocutaneous nerve", "Axillary nerve", "Radial nerve"], 4,
    "The radial nerve supplies the posterior (extensor) compartment of the forearm.",
    "Radial nerve = posterior forearm extensors."),
  Q("t7_a6", "t7", "Anatomy",
    "Which spinal curvatures are considered primary curvatures?",
    ["Cervical + thoracic", "Thoracic + sacral", "Lumbar + sacral", "Cervical + lumbar", "Thoracic + lumbar"], 1,
    "The thoracic and sacral curvatures are primary (present from fetal life, concave anteriorly). The cervical and lumbar curvatures are secondary, developing with head control and walking.",
    "Primary curvatures: thoracic + sacral; secondary: cervical + lumbar."),
  Q("t7_a7", "t7", "Anatomy",
    "The latissimus dorsi receives motor innervation from which nerve, and from which cord does it originate?",
    ["Thoracodorsal nerve, posterior cord", "Thoracodorsal nerve, medial cord", "Upper subscapular nerve, posterior cord", "Upper subscapular nerve, medial cord", "Lateral pectoral nerve, lateral cord"], 0,
    "Latissimus dorsi is supplied by the thoracodorsal nerve, a branch of the posterior cord of the brachial plexus.",
    "Latissimus dorsi: thoracodorsal nerve (posterior cord)."),
  Q("t7_a8", "t7", "Anatomy",
    "At which anatomical landmark does the brachial artery bifurcate and thus terminate?",
    ["Anatomical snuffbox", "Lateral border of the first rib", "Axilla", "Carpal tunnel", "Cubital fossa"], 4,
    "The brachial artery divides into the radial and ulnar arteries in the cubital fossa.",
    "Brachial artery splits into radial and ulnar arteries in the cubital fossa."),
  Q("t7_a9", "t7", "Anatomy",
    "Excessive kyphosis refers to the exaggeration of which curvature?",
    ["Thoracic", "Lateral", "Cervical", "Lumbar", "Sacrococcygeal"], 0,
    "Kyphosis is an exaggerated thoracic curvature (a forward-rounded upper back), common with osteoporotic vertebral changes in ageing.",
    "Kyphosis = exaggerated thoracic curvature."),
  Q("t7_a10", "t7", "Anatomy",
    "Which nerve arises directly from the lateral cord of the brachial plexus?",
    ["Median nerve", "Ulnar nerve", "Musculocutaneous nerve", "Axillary nerve", "Radial nerve"], 2,
    "The musculocutaneous nerve is the terminal branch of the lateral cord. (The median nerve has contributions from both lateral and medial cords.)",
    "Musculocutaneous nerve comes off the lateral cord."),
  Q("t7_a11", "t7", "Anatomy",
    "The deep palmar arch is primarily supplied by which artery?",
    ["Radial artery", "Ulnar artery", "Subclavian artery", "Brachial artery", "Axillary artery"], 0,
    "The deep palmar arch is mainly the continuation of the radial artery; the superficial palmar arch is mainly from the ulnar artery.",
    "Deep arch = radial artery; superficial arch = ulnar artery."),
  Q("t7_a12", "t7", "Anatomy",
    "A patient has numbness and tingling on the palmar surface of the lateral three-and-a-half digits. This is due to compression of which nerve?",
    ["Median nerve", "Ulnar nerve", "Musculocutaneous nerve", "Axillary nerve", "Radial nerve"], 0,
    "The median nerve supplies the palmar lateral three-and-a-half digits; compression at the wrist (carpal tunnel syndrome) causes this pattern.",
    "Lateral 3½ digits (palmar) = median nerve (carpal tunnel)."),

  // ── Physiology, Pathophysiology & Biochemistry ──
  Q("t7_p13", "t7", "Physiology & Biochem",
    "Perpendicular blood supply to the osteon is provided by:",
    ["Volkmann's canals", "Haversian canals", "Canaliculi", "Circumferential canals", "Lamellae"], 0,
    "Volkmann's (perforating) canals run perpendicular to the long axis of the bone, connecting the longitudinal Haversian canals and carrying vessels between them.",
    "Volkmann's canals run perpendicular; Haversian canals run longitudinally."),
  Q("t7_p14", "t7", "Physiology & Biochem",
    "The composition of the bone matrix is:",
    ["Calcium chloride, sodium hydroxide and collagen fibres", "Collagen and elastic fibres", "Crystals of hydroxyapatite and collagen fibres", "Crystals of hydroxyapatite and elastic fibres", "Calcium phosphate, calcium hydroxide and elastic fibres"], 2,
    "Bone matrix is hydroxyapatite (a calcium-phosphate mineral) deposited on a framework of type I collagen fibres, giving hardness plus tensile strength.",
    "Bone = hydroxyapatite + collagen fibres."),
  Q("t7_p15", "t7", "Physiology & Biochem",
    "Osteocytes are formed when:",
    ["Osteoprogenitor cells differentiate into osteocytes", "Granulocyte progenitor cells differentiate into osteocytes", "Monocyte progenitor cells differentiate into osteocytes", "Osteoblasts become trapped in their own secretions and become osteocytes", "Collagen molecules react with osteoclasts"], 3,
    "As osteoblasts lay down matrix, some become surrounded by it and mature into osteocytes residing in lacunae.",
    "Osteoblasts trapped in matrix mature into osteocytes."),
  Q("t7_p16", "t7", "Physiology & Biochem",
    "Which cytokines are produced by osteoblasts during bone remodelling?",
    ["IGF-1 and TGF-β", "TNF-α and TGF-β", "IL-6 and IGF-1", "IL-6 and TNF-α", "IL-1β and IL-6"], 0,
    "Osteoblasts secrete growth factors including IGF-1 and TGF-β, which are stored in the matrix and help couple resorption to new bone formation.",
    "Osteoblasts release IGF-1 and TGF-β into the matrix."),
  Q("t7_p17", "t7", "Physiology & Biochem",
    "The three tendons forming the boundaries of the anatomical snuffbox are:",
    ["Flexor pollicis longus, extensor pollicis brevis, flexor digitorum profundus", "Flexor carpi radialis, flexor digitorum superficialis, abductor pollicis longus", "Abductor pollicis longus, extensor pollicis brevis, extensor pollicis longus", "Extensor indicis, abductor pollicis longus, extensor carpi radialis longus", "Abductor pollicis longus, extensor digitorum, extensor pollicis longus"], 2,
    "The snuffbox is bounded by abductor pollicis longus and extensor pollicis brevis (anteriorly) and extensor pollicis longus (posteriorly). The scaphoid lies in its floor.",
    "Snuffbox borders: APL, EPB and EPL."),
  Q("t7_p18", "t7", "Physiology & Biochem",
    "The primary curvatures of the vertebral column are:",
    ["Cervical and thoracic", "Thoracic and lumbar", "Lumbar and sacral", "Thoracic and sacral", "Cervical and lumbar"], 3,
    "The thoracic and sacral curvatures are primary (present at birth); cervical and lumbar curvatures are secondary.",
    "Primary curvatures: thoracic + sacral."),
  Q("t7_p19", "t7", "Physiology & Biochem",
    "What does a decline in oestrogen after menopause lead to?",
    ["Increased osteoblastic activity → greater resorption than formation", "Increased osteoclastic activity → greater resorption than formation", "Increased osteoblastic activity → greater formation than resorption", "Decreased osteoclastic activity → greater resorption than formation", "Increased osteoclastic activity → greater formation than resorption"], 1,
    "Oestrogen normally restrains osteoclasts; its loss after menopause increases osteoclastic activity, so resorption outpaces formation and bone density falls (osteoporosis).",
    "Menopausal oestrogen loss → ↑osteoclasts → net bone loss."),
  Q("t7_p20", "t7", "Physiology & Biochem",
    "Which correctly describes the difference between osteoblasts and osteoclasts?",
    ["Osteoblasts from MSCs, osteoclasts from HSCs; osteoblasts smaller and uninucleated, osteoclasts larger and uninucleated", "Osteoblasts from MSCs, osteoclasts from HSCs; osteoblasts smaller and uninucleated, osteoclasts larger and multinucleated", "Osteoblasts from HSCs, osteoclasts from MSCs; osteoblasts smaller and uninucleated, osteoclasts larger and multinucleated", "Osteoblasts from HSCs, osteoclasts from MSCs; osteoblasts larger and uninucleated, osteoclasts smaller and multinucleated", "Osteoblasts from HSCs, osteoclasts from MSCs; osteoblasts smaller and multinucleated, osteoclasts larger and multinucleated"], 1,
    "Osteoblasts derive from mesenchymal stem cells and are small, uninucleate bone-formers; osteoclasts derive from haematopoietic (monocyte) lineage and are large, multinucleate bone-resorbers.",
    "Osteoblasts: MSC, uninucleate. Osteoclasts: HSC, multinucleate."),
  Q("t7_p21", "t7", "Physiology & Biochem",
    "Which bone marker is used to assess osteoclastic (resorption) activity?",
    ["Bone-specific alkaline phosphatase (BALP)", "Osteocalcin", "PINP", "NTX (N-terminal telopeptide)"], 3,
    "NTX is a collagen breakdown product and marks bone resorption (osteoclast activity). BALP, osteocalcin and PINP are formation (osteoblast) markers.",
    "NTX = resorption marker; BALP/osteocalcin/PINP = formation markers."),
  Q("t7_p22", "t7", "Physiology & Biochem",
    "Which protein transports calcium into the intestinal epithelial cell cytoplasm?",
    ["Calcitriol", "Cholecalciferol", "Calbindin", "Calcifediol", "CBP"], 2,
    "Calbindin is the vitamin-D-dependent intracellular protein that shuttles absorbed calcium across the enterocyte cytoplasm.",
    "Calbindin carries calcium through the enterocyte (vitamin D-dependent)."),

  // ── Pharmacology & Clinical Medicine ──
  Q("t7_ph1", "t7", "Clinical & Pharmacology",
    "The primary principle behind prescribing HRT in menopausal women is:",
    ["To increase progesterone levels only", "To prevent all age-related cardiovascular disease", "To replace declining oestrogen and relieve menopausal symptoms", "To restore fertility", "To reduce growth hormone deficiency"], 2,
    "HRT replaces declining oestrogen (with a progestogen if the uterus is present) to relieve menopausal symptoms such as flushes and urogenital atrophy.",
    "HRT replaces oestrogen to relieve menopausal symptoms."),
  Q("t7_ph2", "t7", "Clinical & Pharmacology",
    "Which is a recognised risk associated with combined HRT?",
    ["Reduced risk of venous thromboembolism", "Reduced breast cancer risk", "Increased risk of breast cancer with long-term use", "Increased risk of ovarian cysts only", "No known risks"], 2,
    "Long-term combined (oestrogen + progestogen) HRT increases the risk of breast cancer and venous thromboembolism.",
    "Long-term combined HRT raises breast cancer (and VTE) risk."),
  Q("t7_ph3", "t7", "Clinical & Pharmacology",
    "Which is a relative contraindication to systemic corticosteroid use?",
    ["Hypertension", "Uncontrolled diabetes", "Osteoarthritis", "Iron-deficiency anaemia", "Gallstones"], 1,
    "Corticosteroids raise blood glucose, so uncontrolled diabetes is a relative contraindication (they also worsen hypertension and osteoporosis, used with caution).",
    "Steroids raise glucose, caution in uncontrolled diabetes."),
  Q("t7_ph4", "t7", "Clinical & Pharmacology",
    "Which pharmacokinetic change is expected with normal ageing?",
    ["Increased hepatic metabolism", "Increased renal clearance", "Increased total body water", "Decreased renal excretion", "Increased plasma albumin"], 3,
    "Renal function declines with age, decreasing the excretion of renally-cleared drugs and predisposing to accumulation and toxicity.",
    "Ageing reduces renal excretion, renally-cleared drugs accumulate."),
  Q("t7_ph5", "t7", "Clinical & Pharmacology",
    "Why are older adults more prone to adverse drug reactions in polypharmacy?",
    ["They metabolise all drugs faster", "Their diseases eliminate all drugs more efficiently", "They store fewer drugs in tissues", "Age-related organ decline alters drug metabolism and clearance", "They avoid high-risk drugs"], 3,
    "Declining hepatic and renal function (plus altered body composition and more interactions) changes drug handling, increasing ADR risk with multiple medicines.",
    "Organ decline + many drugs → higher ADR risk in older adults."),
  Q("t7_c6", "t7", "Clinical & Pharmacology",
    "Which statement best defines infection control in a clinical environment?",
    ["The complete sterilisation of all hospital surfaces", "Practices designed to reduce transmission of infectious agents", "Routine antibiotic use in all admitted patients", "Wearing gloves at all times", "Treating all patients as though they are infectious"], 1,
    "Infection control comprises the practices (hand hygiene, PPE, isolation, asepsis) that reduce transmission of infectious agents.",
    "Infection control = practices that cut transmission."),
  Q("t7_c7", "t7", "Clinical & Pharmacology",
    "Which antibiotic is effective against MRSA infections?",
    ["Penicillin", "Amoxicillin", "Flucloxacillin", "Vancomycin", "Erythromycin"], 3,
    "MRSA is resistant to beta-lactams (including flucloxacillin); vancomycin (a glycopeptide) is a first-line agent against it.",
    "Vancomycin treats MRSA (beta-lactams don't)."),
  Q("t7_c8", "t7", "Clinical & Pharmacology",
    "Which is important for early sepsis management?",
    ["Waiting to give fluids until blood pressure falls critically", "Obtaining blood cultures and identifying the source of infection", "Administering prolonged corticosteroid therapy", "Avoiding oxygen therapy", "Withholding antibiotics until imaging is complete"], 1,
    "The Sepsis Six includes taking blood cultures (and identifying the source) before/with early antibiotics, fluids and oxygen, do not delay treatment.",
    "Early sepsis: cultures + source ID, then prompt antibiotics/fluids."),

  // ── Behavioural & Social Sciences ──
  Q("t7_b1", "t7", "BSS",
    "According to the biopsychosocial model, which factor is 'social' in achieving successful ageing?",
    ["Maintaining a balanced diet", "Opportunities to participate in community groups or activities", "Adequate sleep", "Positive self-perception", "Regular health screening"], 1,
    "Social participation, community groups and activities, is the social dimension; diet/sleep are biological and self-perception is psychological.",
    "Social dimension = community participation."),
  Q("t7_b2", "t7", "BSS",
    "Which scenario best reflects successful ageing according to the biopsychosocial model?",
    ["A 60-year-old with no chronic illness but socially isolated", "A 72-year-old with arthritis who maintains social activities and positive coping", "An older adult who avoids exercise to prevent injury", "A 54-year-old who relies on medication for wellbeing", "A 63-year-old who refuses help due to stigma"], 1,
    "Successful ageing integrates biological, psychological and social wellbeing, managing illness while staying socially active and coping positively, rather than merely the absence of disease.",
    "Successful ageing = coping well and staying engaged despite illness."),
  Q("t7_b3", "t7", "BSS",
    "Which best reflects the psychological aspect of successful ageing in the biopsychosocial model?",
    ["Maintaining stable blood pressure", "Having good social support networks", "Adapting positively to life transitions such as retirement", "Access to healthcare services", "Engaging in regular physical activity"], 2,
    "Positive psychological adaptation to change, such as adjusting to retirement, is the psychological component of successful ageing.",
    "Psychological dimension = positive adaptation to life changes."),
);
