// questions/t8.jsx, Theme 8: Pneumothorax
// Source: ISocMedEd Theme 8 MCQ Bank. Image-dependent items omitted. Answers authored.

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t8_a4", "t8", "Anatomy",
    "A tension pneumothorax requires urgent thoracostomy. At which level is this usually performed?",
    ["7th/8th intercostal space, mid-clavicular line", "2nd/3rd intercostal space, mid-clavicular line", "4th/5th intercostal space, mid-axillary line", "4th/5th intercostal space, mid-clavicular line", "2nd/3rd intercostal space, mid-axillary line"], 2,
    "Current guidance places finger/chest-drain thoracostomy in the 'safe triangle' at the 4th/5th intercostal space in the mid-axillary line.",
    "Chest drain: 4th/5th ICS, mid-axillary line (safe triangle)."),
  Q("t8_a5", "t8", "Anatomy",
    "Which rib(s) contain grooves for the subclavian artery and vein?",
    ["Rib XII", "Rib XI and Rib XII", "Rib I", "Rib I and Rib II", "Rib II"], 2,
    "Rib I bears the grooves for the subclavian vein (anterior) and subclavian artery (posterior), separated by the scalene tubercle.",
    "Rib I carries the subclavian artery and vein grooves."),
  Q("t8_a6", "t8", "Anatomy",
    "Which of the following correctly lists the atypical ribs?",
    ["Rib II and XI", "Rib I, II, XI and XII", "Rib I, II, X, XI and XII", "Rib I and II", "Rib XI and XII"], 2,
    "The atypical ribs are I, II, X, XI and XII; the typical ribs are 3–9.",
    "Atypical ribs: 1, 2, 10, 11, 12."),
  Q("t8_a7", "t8", "Anatomy",
    "Which type of joint is formed when rib I articulates with the sternum?",
    ["Synovial hinge", "Fibrocartilaginous (synchondrosis)", "Synovial plane", "Synovial pivot", "Symphysis"], 1,
    "The first sternocostal joint is a synchondrosis (primary cartilaginous joint); the 2nd–7th are synovial plane joints.",
    "1st sternocostal joint = synchondrosis (cartilaginous)."),
  Q("t8_a8", "t8", "Anatomy",
    "Where is an inhaled foreign body most likely to be found?",
    ["Right main bronchus", "Left main bronchus", "Trachea", "Carina", "Oesophagus"], 0,
    "The right main bronchus is wider, shorter and more vertical, so inhaled objects preferentially enter it.",
    "Inhaled objects lodge in the right main bronchus."),
  Q("t8_a9", "t8", "Anatomy",
    "Which of the following structures does NOT pass through the diaphragm?",
    ["Hemiazygos vein", "Inferior vena cava", "Oesophagus", "Aorta", "Sympathetic trunk"], 4,
    "The sympathetic trunk passes posteriorly, deep to the medial arcuate ligament, rather than through a diaphragmatic opening.",
    "The sympathetic trunk passes behind (not through) the diaphragm."),
  Q("t8_a10", "t8", "Anatomy",
    "Bronchopulmonary segments are supplied by:",
    ["Tertiary (segmental) bronchi", "Bronchioles", "Secondary bronchi", "Intrapulmonary bronchi"], 0,
    "Each bronchopulmonary segment is supplied by a tertiary (segmental) bronchus and a segmental branch of the pulmonary artery.",
    "Bronchopulmonary segment = one tertiary (segmental) bronchus."),
  Q("t8_a11", "t8", "Anatomy",
    "Which of the following does NOT pierce the diaphragm?",
    ["Subclavian artery", "Inferior vena cava", "Aorta", "Oesophagus"], 0,
    "The subclavian artery is in the root of the neck/thorax and does not pierce the diaphragm; the IVC (T8), oesophagus (T10) and aorta (T12) do.",
    "Subclavian artery does not pierce the diaphragm."),
  Q("t8_a12", "t8", "Anatomy",
    "Which nerve provides motor innervation to the diaphragm?",
    ["Phrenic nerve", "Accessory nerve", "Vagus nerve", "Oculomotor nerve", "Long thoracic nerve"], 0,
    "The phrenic nerve (C3–C5) provides all motor supply to the diaphragm. 'C3, 4, 5 keep the diaphragm alive.'",
    "Phrenic nerve (C3–C5) drives the diaphragm."),
  Q("t8_a13", "t8", "Anatomy",
    "Which of the following is considered a true rib?",
    ["Rib XII", "Rib XI", "Rib X", "Rib VII", "Rib VIII"], 3,
    "True (vertebrosternal) ribs are 1–7, attaching directly to the sternum by their own costal cartilage.",
    "True ribs = 1–7."),

  // ── Physiology ──
  Q("t8_p1", "t8", "Physiology & Biochem",
    "Which of the following describes the transpulmonary pressure?",
    ["Difference between intra-alveolar and intrapleural pressures", "Difference between atmospheric and intra-alveolar pressures", "Difference between atmospheric and intrapleural pressures"], 0,
    "Transpulmonary pressure is the difference between intra-alveolar and intrapleural pressures, the distending pressure that keeps the lung inflated.",
    "Transpulmonary pressure = alveolar − intrapleural."),
  Q("t8_p2", "t8", "Physiology & Biochem",
    "Which is a muscle involved in forced inspiration?",
    ["Serratus anterior", "Diaphragm", "External oblique", "Rectus abdominis", "Transversus abdominis"], 0,
    "Forced inspiration recruits accessory muscles such as serratus anterior, sternocleidomastoid and scalenes (the diaphragm drives quiet inspiration).",
    "Serratus anterior is an accessory muscle of forced inspiration."),
  Q("t8_p3", "t8", "Physiology & Biochem",
    "Which pressure is negative relative to atmospheric pressure, and why?",
    ["Intra-alveolar; inward pull > outward pull", "Intra-alveolar; outward pull > inward pull", "Intrapleural; the opposing recoil of lung (inward) and chest wall (outward) creates suction", "Intrapleural; inward pull > outward pull"], 2,
    "Intrapleural pressure is sub-atmospheric because the lung's inward elastic recoil and the chest wall's outward recoil pull the pleural layers apart, creating a slight vacuum.",
    "Intrapleural pressure is negative (opposing lung/chest-wall recoil)."),
  Q("t8_p4", "t8", "Physiology & Biochem",
    "Which correctly describes the sequence of events in passive expiration?",
    ["Diaphragm and external intercostals relax → ribs move down and in → thoracic volume decreases → intra-alveolar pressure increases → air flows out", "Diaphragm and external intercostals relax → ribs move down and in → thoracic volume decreases → intra-alveolar pressure decreases → air flows in", "Diaphragm and external intercostals contract → ribs move up and out → volume increases → pressure increases → air flows in", "Diaphragm and external intercostals contract → ribs move up and out → volume increases → pressure decreases → air flows in", "Diaphragm and internal intercostals relax, abdominals contract → ribs move down and in → volume decreases → pressure increases → air flows out"], 0,
    "Passive expiration: inspiratory muscles relax, the thorax recoils and shrinks, raising intra-alveolar pressure so air flows out.",
    "Passive expiration = recoil → smaller thorax → ↑pressure → air out."),
  Q("t8_p5", "t8", "Physiology & Biochem",
    "Hassan cannot elevate his first two ribs during forced inspiration. Which muscle is most likely affected?",
    ["Sternocleidomastoid", "Serratus anterior", "Scalene muscles", "Latissimus dorsi", "Pectoralis major"], 2,
    "The scalene muscles elevate the first two ribs during forced inspiration.",
    "Scalenes elevate ribs 1 and 2 in forced inspiration."),
  Q("t8_p6", "t8", "Physiology & Biochem",
    "Where are breath sounds MOST likely to diminish with an open pneumothorax?",
    ["Over the affected side", "On both sides", "Over the unaffected side", "On neither side"], 0,
    "Air in the pleural space stops the lung transmitting sound, so breath sounds diminish over the affected side.",
    "Pneumothorax: reduced breath sounds over the affected side."),
  Q("t8_p7", "t8", "Physiology & Biochem",
    "Basal cells sit in the bronchi. What is their primary function?",
    ["Produce leukocytes", "Secrete lung surfactant", "Site of gaseous exchange", "Secrete mucus", "Replace damaged epithelial cells"], 4,
    "Basal cells are the stem cells of the respiratory epithelium, regenerating damaged ciliated and goblet cells.",
    "Basal cells are airway epithelial stem cells."),
  Q("t8_p8", "t8", "Physiology & Biochem",
    "What is the function of type I alveolar cells, and which epithelium lines them?",
    ["Replace damaged cells; simple columnar", "Produce surfactant; simple columnar", "Produce surfactant; simple squamous", "Site of gaseous exchange; simple squamous", "Site of gaseous exchange; pseudostratified columnar"], 3,
    "Type I pneumocytes are flat simple squamous cells forming the thin gas-exchange surface; type II cells make surfactant.",
    "Type I pneumocytes: simple squamous, gas exchange."),
  Q("t8_p9", "t8", "Physiology & Biochem",
    "A patient has increased pleural pressure in the right lung. Which pathology, and where does the trachea deviate?",
    ["Spontaneous pneumothorax; trachea deviates left", "Tension pneumothorax; trachea deviates right", "Tension pneumothorax; trachea does not deviate", "Spontaneous pneumothorax; trachea deviates right", "Tension pneumothorax; trachea deviates left"], 4,
    "A tension pneumothorax raises pleural pressure and pushes the mediastinum (and trachea) AWAY from the affected side, here, to the left.",
    "Tension pneumothorax deviates the trachea away from the affected side."),
  Q("t8_p10", "t8", "Physiology & Biochem",
    "Which is the maximum volume that can be inspired and then expired?",
    ["Inspiratory reserve volume", "Residual volume", "Vital capacity", "Total lung capacity", "Expiratory reserve volume"], 2,
    "Vital capacity is the maximum volume exhaled after a maximal inspiration (IRV + TV + ERV).",
    "Vital capacity = max inspired then expired (IRV+TV+ERV)."),
  Q("t8_p11", "t8", "Physiology & Biochem",
    "To relieve asthmatic bronchoconstriction, which receptor is targeted and is it stimulated or inhibited?",
    ["Alpha-2 receptor; inhibition", "Beta-2 receptor; stimulation", "Beta-1 receptor; inhibition", "Beta-2 receptor; inhibition", "Beta-1 receptor; stimulation"], 1,
    "Beta-2 agonists (e.g. salbutamol) stimulate airway beta-2 receptors to relax bronchial smooth muscle and dilate the airways.",
    "Beta-2 stimulation dilates airways (salbutamol)."),
  Q("t8_p12", "t8", "Physiology & Biochem",
    "You note decreased breath sounds and hyperresonance on percussion. Which condition do you immediately suspect?",
    ["Haemothorax", "Tension pneumothorax", "Simple pneumothorax", "Open pneumothorax", "Chylothorax"], 1,
    "Decreased breath sounds with hyperresonance indicates air in the pleural space under pressure, a tension pneumothorax (a haemothorax would be dull).",
    "Hyperresonance + reduced breath sounds → (tension) pneumothorax."),
  Q("t8_p13", "t8", "Physiology & Biochem",
    "The trachea, bronchi and terminal bronchioles are examples of:",
    ["Anatomical dead space", "Alveolar dead space", "Physiological dead space", "Respiratory portions"], 0,
    "These conducting airways carry air but do not exchange gas, forming the anatomical dead space.",
    "Conducting airways = anatomical dead space."),
  Q("t8_p14", "t8", "Physiology & Biochem",
    "Which of the following CANNOT be measured by spirometry?",
    ["Residual volume", "Vital capacity", "Expiratory reserve volume", "Inspiratory reserve volume", "Tidal volume"], 0,
    "Residual volume cannot be exhaled, so spirometry cannot measure it (it needs body plethysmography or gas dilution).",
    "Spirometry can't measure residual volume."),
  Q("t8_p15", "t8", "Physiology & Biochem",
    "An increased Functional Residual Capacity (FRC) is likely to manifest as:",
    ["Hyperinflated chest", "Shallow breathing", "Hypoxia / cyanosis", "High respiratory rate"], 0,
    "A raised FRC means more air is trapped at rest, producing a hyperinflated (barrel) chest, as in COPD.",
    "↑FRC → hyperinflated chest."),
  Q("t8_p16", "t8", "Physiology & Biochem",
    "Functional Residual Capacity (FRC) equals:",
    ["ERV + RV", "TV + IRV + ERV + RV", "TV + IRV + ERV", "FVC − TV", "IC + ERV"], 0,
    "FRC = expiratory reserve volume + residual volume, the air remaining in the lungs after a normal expiration.",
    "FRC = ERV + RV."),

  // ── Behavioural & Social Sciences (stress) ──
  Q("t8_b1", "t8", "BSS",
    "Which of the following is NOT a physical component of stress?",
    ["Release of cortisol and adrenaline", "Increased sympathetic nervous system activity", "Increased central nervous system activity", "Emotional arousal", "Triggering of fight-or-flight"], 3,
    "Emotional arousal is a psychological component; the others are physical/physiological responses.",
    "Emotional arousal is psychological, not physical."),
  Q("t8_b2", "t8", "BSS",
    "In Selye's General Adaptation Syndrome, which is a feature of the alarm stage?",
    ["Depression", "Fatigue", "Increased heart rate", "Pupillary constriction", "Mental exhaustion"], 2,
    "The alarm stage is the acute fight-or-flight response, tachycardia, pupil dilation and catecholamine release.",
    "Alarm stage = acute fight-or-flight (↑heart rate)."),
  Q("t8_b3", "t8", "BSS",
    "Which is a distinct feature of the resistance stage of GAS?",
    ["Increase in adrenaline release", "Burnout", "Change in appetite", "Weakened immune system", "Mental exhaustion"], 2,
    "In the resistance stage the body adapts to sustained stress (e.g. appetite changes); burnout, immune weakening and exhaustion belong to the exhaustion stage.",
    "Resistance stage = sustained adaptation (e.g. appetite change)."),
  Q("t8_b4", "t8", "BSS",
    "Which statement describes a secondary appraisal of a stressor?",
    ["'These injuries will finish my career'", "'What recovery plan will I need to work through this?'", "'I don't deserve this'", "'Is this bad?'", "'Will this affect my future?'"], 1,
    "Secondary appraisal evaluates one's coping resources and options ('what can I do about it?'), whereas primary appraisal judges the threat itself.",
    "Secondary appraisal = assessing how to cope."),
  Q("t8_b5", "t8", "BSS",
    "Which of the following is NOT a recognised physical reaction to stress?",
    ["Stress reactivity", "Stress recovery", "Allostatic load", "Stress resistance", "Stress load"], 4,
    "'Stress load' is not a standard term; reactivity, recovery, resistance and allostatic load are recognised physical stress concepts.",
    "'Stress load' is not a recognised concept."),
);
