// questions/t9.jsx, Theme 9: Asthma
// Source: ISocMedEd Theme 9 MCQ Bank 2025. Image-dependent items omitted. Answers authored.

window.QUESTIONS.push(
  // ── Anatomy ──
  Q("t9_a1", "t9", "Anatomy",
    "What are the nasal conchae and what is their function?",
    ["Nasal hairs for filtration and protection", "Nasal hairs for sensory feedback", "Bony shelves in the nasal cavity that warm and humidify air", "Bony shelves that give structural support to the nose", "A term for both the hairs and bony shelves that filter air"], 2,
    "The conchae (turbinates) are bony shelves that increase surface area to warm, humidify and filter inspired air.",
    "Conchae = bony shelves that warm and humidify air."),
  Q("t9_a2", "t9", "Anatomy",
    "A patient with a cold reports 'pain under my eyes that gets worse when I bend forward'. Which sinus is likely affected?",
    ["Frontal", "Ethmoid", "Maxillary", "Temporal", "Sphenoid"], 2,
    "Pain in the cheeks/under the eyes that worsens on bending forward is typical of maxillary sinusitis.",
    "Cheek pain worse on bending = maxillary sinus."),
  Q("t9_a3", "t9", "Anatomy",
    "Which of these bones does NOT directly articulate with any other bone?",
    ["Inferior nasal concha", "Ethmoid bone", "Tongue", "Hyoid bone", "Cricoid cartilage"], 3,
    "The hyoid bone is suspended by muscles and ligaments and articulates with no other bone.",
    "The hyoid articulates with no other bone."),
  Q("t9_a4", "t9", "Anatomy",
    "Which correctly identifies a difference between the right and left main bronchi?",
    ["The left bronchus is shorter", "The right bronchus is narrower", "The right bronchus is more horizontal", "The left bronchus is shorter and narrower", "The right bronchus is wider and more vertical"], 4,
    "The right main bronchus is wider, shorter and more vertical than the left, hence aspiration tends to the right.",
    "Right main bronchus: wider, shorter, more vertical."),
  Q("t9_a6", "t9", "Anatomy",
    "Which impression/landmark CANNOT be found on the medial surface of the left lung?",
    ["Aortic arch", "Descending abdominal aorta", "Cardiac impression", "Diaphragmatic surface", "Hilum"], 1,
    "The abdominal aorta lies below the diaphragm and leaves no impression on the lung.",
    "The abdominal aorta makes no lung impression."),
  Q("t9_a7", "t9", "Anatomy",
    "A right penetrating stab wound between ribs 5 and 6 (anteriorly) most likely damages which lobe?",
    ["Right middle lobe", "Left lower lobe", "Left upper lobe", "Right upper lobe", "Right lower lobe"], 0,
    "Anteriorly at the 5th–6th rib level on the right, the right middle lobe is most superficial and likely injured.",
    "Anterior right 5th/6th rib → right middle lobe."),
  Q("t9_a8", "t9", "Anatomy",
    "At what level does the trachea bifurcate?",
    ["Between T3 and T4", "T3", "T4", "Between T4 and T5", "T5"], 3,
    "The trachea bifurcates at the carina, at the level of the sternal angle (between T4 and T5).",
    "Tracheal bifurcation: sternal angle (T4/T5)."),
  Q("t9_a9", "t9", "Anatomy",
    "What happens to the cartilage rings as you descend the respiratory tract?",
    ["They become complete rings forming a sheet of cartilage", "They vanish after the trachea", "They become irregular plates before vanishing at the bronchioles", "They become regular plates before vanishing at the bronchioles", "They stay as C-shaped rings until the respiratory zone"], 2,
    "Tracheal C-shaped rings give way to irregular cartilage plates in the bronchi, which disappear at the bronchioles.",
    "Cartilage becomes plates, then disappears at the bronchioles."),
  Q("t9_a10", "t9", "Anatomy",
    "Which type of epithelium lines most of the conducting portion of the respiratory tract?",
    ["Simple squamous", "Stratified squamous", "Pseudostratified ciliated columnar with goblet cells", "Simple cuboidal", "Transitional"], 2,
    "The conducting airways are lined by pseudostratified ciliated columnar epithelium with goblet cells (respiratory epithelium).",
    "Conducting airways: pseudostratified ciliated columnar with goblet cells."),

  // ── Physiology & Pathophysiology ──
  Q("t9_p1", "t9", "Physiology & Biochem",
    "Which immunoglobulin mediates the type I hypersensitivity reaction underlying allergic asthma?",
    ["IgG", "IgA", "IgE", "IgM", "IgD"], 2,
    "Allergic asthma is a type I (IgE-mediated) hypersensitivity: allergen cross-links IgE on mast cells, triggering degranulation.",
    "Allergic asthma = IgE-mediated type I hypersensitivity."),
  Q("t9_p2", "t9", "Physiology & Biochem",
    "Which cell releases histamine during the early phase of an asthma attack?",
    ["Neutrophil", "Mast cell", "Macrophage", "Plasma cell", "Goblet cell"], 1,
    "Mast cells degranulate when allergen cross-links their surface IgE, releasing histamine and leukotrienes that cause bronchoconstriction.",
    "Mast cells release histamine in the early asthma response."),
  Q("t9_p3", "t9", "Physiology & Biochem",
    "Which spirometry pattern is characteristic of asthma?",
    ["FEV1/FVC ratio increased", "FEV1/FVC ratio reduced (obstructive), reversible with bronchodilator", "FEV1 and FVC both reduced with normal ratio (restrictive)", "Normal spirometry that cannot change", "Increased residual volume only"], 1,
    "Asthma is obstructive: a reduced FEV1/FVC ratio that improves significantly after a bronchodilator (reversibility).",
    "Asthma: obstructive (low FEV1/FVC) and reversible."),
  Q("t9_p4", "t9", "Physiology & Biochem",
    "What is the main effect of leukotrienes in asthma?",
    ["Bronchodilation", "Bronchoconstriction and increased mucus", "Reduced vascular permeability", "Decreased eosinophil recruitment", "Inhibition of inflammation"], 1,
    "Leukotrienes are potent bronchoconstrictors that also increase mucus secretion and vascular permeability; leukotriene-receptor antagonists (montelukast) block them.",
    "Leukotrienes constrict airways and boost mucus."),
  Q("t9_p5", "t9", "Physiology & Biochem",
    "During an acute asthma attack, what happens to airway resistance and the work of breathing?",
    ["Both decrease", "Resistance increases, work of breathing increases", "Resistance decreases, work of breathing increases", "Resistance increases, work of breathing decreases", "Both remain unchanged"], 1,
    "Bronchoconstriction narrows the airways, raising resistance and dramatically increasing the work of breathing.",
    "Asthma attack: ↑airway resistance → ↑work of breathing."),
  Q("t9_p6", "t9", "Physiology & Biochem",
    "Which best explains why expiration is more difficult than inspiration in asthma?",
    ["Airways widen on expiration", "Airways are passively narrowed on expiration, trapping air", "The diaphragm cannot relax", "Surfactant is destroyed", "The pleural space fills with air"], 1,
    "On expiration the airways narrow passively; in asthma the already-constricted airways collapse further, trapping air and causing the prolonged wheezy expiration.",
    "Asthma traps air because narrowed airways collapse on expiration."),
  Q("t9_p7", "t9", "Physiology & Biochem",
    "Chronic airway remodelling in asthma includes:",
    ["Thinning of the basement membrane", "Smooth muscle hypertrophy and goblet cell hyperplasia", "Loss of all mucous glands", "Alveolar wall destruction", "Replacement by squamous epithelium only"], 1,
    "Chronic asthma causes airway remodelling: smooth muscle hypertrophy/hyperplasia, goblet cell hyperplasia and basement membrane thickening.",
    "Asthma remodelling: muscle hypertrophy + goblet cell hyperplasia."),
  Q("t9_p8", "t9", "Physiology & Biochem",
    "Which arterial blood gas picture suggests life-threatening asthma?",
    ["Low CO2 (respiratory alkalosis)", "Normal or rising CO2 despite distress", "High O2", "Metabolic alkalosis", "Low bicarbonate only"], 1,
    "Early asthma causes hyperventilation and low CO2; a normalising or rising CO2 in a tiring patient signals life-threatening asthma and impending failure.",
    "A normal/rising CO2 in acute asthma is a red flag."),
  Q("t9_p9", "t9", "Physiology & Biochem",
    "Which cell type is most characteristically increased in the airways in eosinophilic asthma?",
    ["Neutrophils", "Eosinophils", "Basophils", "Plasma cells", "Red blood cells"], 1,
    "Eosinophilic asthma is characterised by airway eosinophilia, driven by Th2 cytokines (IL-5); it tends to respond well to inhaled corticosteroids.",
    "Eosinophilic asthma = airway eosinophilia (IL-5/Th2)."),
  Q("t9_p10", "t9", "Physiology & Biochem",
    "What is the action of inhaled corticosteroids in asthma?",
    ["Immediate bronchodilation", "Reduce airway inflammation over time (preventer)", "Block beta-2 receptors", "Increase mucus production", "Stimulate mast cell degranulation"], 1,
    "Inhaled corticosteroids are preventers: they reduce airway inflammation over time rather than providing immediate relief.",
    "Inhaled steroids = anti-inflammatory preventers (not relievers)."),

  // ── Ethics & EBM ──
  Q("t9_e1", "t9", "Ethics & EBM",
    "A clinical trial compares a new asthma inhaler with the current standard. To minimise bias, patients are randomly assigned and neither patient nor assessor knows the allocation. This design is:",
    ["Open-label cohort study", "Double-blind randomised controlled trial", "Case-control study", "Cross-sectional survey", "Case series"], 1,
    "Random allocation with both participants and assessors blinded is a double-blind RCT, the most robust design for comparing treatments.",
    "Random + double-blinding = double-blind RCT."),
  Q("t9_e2", "t9", "Ethics & EBM",
    "A 15-year-old with asthma wants to manage her own inhalers and asks the doctor not to tell her parents the details. She fully understands her condition and treatment. The doctor should:",
    ["Refuse, as she is under 16", "Respect her wishes if she is assessed as Gillick competent", "Always inform the parents regardless", "Stop her treatment until she is 16", "Refer to a court"], 1,
    "If she is Gillick competent (understands, retains and can weigh the information), her confidentiality and decision should be respected.",
    "A Gillick-competent minor's confidentiality is respected."),
  Q("t9_e3", "t9", "Ethics & EBM",
    "In an asthma study, the number needed to treat (NNT) is 10. This means:",
    ["10% of patients are harmed", "10 patients must be treated for 1 to benefit", "Treatment works in 10 seconds", "The drug is 10 times better", "1 in 10 patients have side effects"], 1,
    "The NNT is the number of patients who must receive the treatment for one additional good outcome, here, 10.",
    "NNT 10 = treat 10 for 1 to benefit."),

  // ── Behavioural & Social Sciences ──
  Q("t9_b1", "t9", "BSS",
    "A teenager skips his preventer inhaler because he 'feels fine' and doesn't want friends to see him use it. Which factors are influencing his adherence?",
    ["Only biological factors", "Beliefs about necessity and social stigma (psychosocial factors)", "Only the drug's pharmacokinetics", "The cost of the inhaler alone", "Genetic factors"], 1,
    "His non-adherence reflects health beliefs (not feeling ill = not needing treatment) and social stigma, psychosocial factors.",
    "Non-adherence here is driven by illness beliefs and stigma."),
  Q("t9_b2", "t9", "BSS",
    "Which approach is most likely to improve a patient's adherence to asthma medication?",
    ["Telling them off for non-adherence", "Shared decision-making and personalised action plans", "Giving as little information as possible", "Removing them from the clinic", "Only prescribing relievers"], 1,
    "Collaborative, personalised approaches (shared decision-making, written asthma action plans) improve adherence and outcomes.",
    "Shared decision-making + action plans improve adherence."),
  Q("t9_b3", "t9", "BSS",
    "Which is an example of a structural (environmental) trigger that can worsen childhood asthma?",
    ["Genetic predisposition", "Damp, mouldy housing", "The child's blood type", "Normal exercise", "Vaccination"], 1,
    "Damp, mouldy or poor-quality housing is a social/environmental determinant that can worsen childhood asthma.",
    "Poor housing (damp/mould) is an environmental asthma trigger."),
);
