// questions/y2t15.jsx, Year 2 Theme 15: Liver (legacy bank, ISOCMEDED).
// Diagram questions (Anatomy 1–3) and the multi-answer posterior-wall question (Anatomy 5) are omitted.
window.QUESTIONS.push(
  Q("y2t15_a4", "y2t15", "Anatomy",
    "The convergence between which two veins forms the hepatic portal vein?",
    ["Inferior mesenteric vein and left renal vein", "Inferior mesenteric vein and right colic vein", "Superior mesenteric vein and splenic vein", "Superior mesenteric vein and left gastric vein", "Superior rectal vein and left gastro-omental vein"], 2,
    "The superior mesenteric vein and splenic vein join together to form the hepatic portal vein."),
  Q("y2t15_a6", "y2t15", "Anatomy",
    "The lesser omentum attaches the liver to the stomach and duodenum. Which two ligaments form this structure?",
    ["The hepatoduodenal and hepatogastric ligaments", "The right and left triangular ligaments", "The falciform and coronary ligaments", "The coronary and triangular ligaments", "The phrenic and cystic ligaments"], 0,
    "The lesser omentum consists of the hepatoduodenal ligament (to the duodenum) and the hepatogastric ligament (to the stomach). These two peritoneal folds connect the liver to the upper gastrointestinal tract."),
  Q("y2t15_a7", "y2t15", "Anatomy",
    "Which vessel provides the dominant blood supply (75%) to the liver parenchyma?",
    ["Hepatic artery proper", "Coeliac trunk", "Superior mesenteric artery", "Hepatic portal vein", "Inferior vena cava"], 3,
    "The hepatic portal vein supplies 75% of hepatic blood flow, carrying nutrient-rich blood from the gut. The hepatic artery provides the remaining 25% oxygenated blood."),
  Q("y2t15_a8", "y2t15", "Anatomy",
    "In which abdominal region is the liver predominantly located?",
    ["Left hypochondrium", "Right hypochondrium", "Right lumbar and hypogastric", "Left iliac and suprapubic", "Epigastric and left lumbar"], 1,
    "The liver primarily occupies the right hypochondrium and extends into the epigastric region. Its bulk lies under the right ribcage."),
  Q("y2t15_a9", "y2t15", "Anatomy",
    "Which surface of the liver is described as being smooth, convex, and in contact with the diaphragm?",
    ["The visceral surface", "The posterior surface", "The diaphragmatic surface", "The inferior surface", "The medial surface"], 2,
    "The diaphragmatic surface faces upward and forward, moulding to the concave undersurface of the diaphragm, which gives it its smooth, convex shape."),
  Q("y2t15_a10", "y2t15", "Anatomy",
    "Which anatomical space is described as a potential space located between the visceral surface of the liver and the right kidney?",
    ["Morison's pouch", "The subhepatic space", "The subphrenic space", "The lesser sac", "The bare area"], 0,
    "Morison's pouch (hepatorenal recess) is the potential space between the liver and right kidney. It is the deepest part of the peritoneal cavity when supine."),
  Q("y2t15_a11", "y2t15", "Anatomy",
    "Which of the following organs is NOT in contact with the visceral surface of the liver?",
    ["The right kidney", "The gallbladder", "The first part of the duodenum", "The stomach", "The spleen"], 4,
    "The visceral surface contacts the right kidney, gallbladder, duodenum, stomach, and other structures, but not the spleen, which lies on the left side of the abdomen."),
  Q("y2t15_p1", "y2t15", "Clinical & Pharmacology",
    "Jane, a 65 year old female, presents with confusion and a flapping tremor. The doctor suspects she may have hepatic encephalopathy due to these symptoms and her past medical history of a diseased liver. Which of the following biochemical molecules or compounds will be markedly elevated in hepatic encephalopathy?",
    ["Albumin", "NH3", "CH4", "Alpha-fetoprotein", "Thrombopoietin", "Erythropoietin"], 1,
    "Ammonia (NH3) is markedly elevated in hepatic encephalopathy. Liver disease leads to an inability to detoxify ammonia to urea, so ammonia builds up in the blood and crosses the blood-brain barrier, leading to neurotoxicity, confusion and reduced consciousness."),
  Q("y2t15_p2", "y2t15", "Clinical & Pharmacology",
    "A 55 year old patient is diagnosed with liver cirrhosis following an assessment from the consultant. Which of the following scoring criteria will be used to assess his prognosis?",
    ["CHADSVASc Score", "Wells' Criteria", "Child-Pugh Score", "CURB-65 Score", "Glasgow Coma Scale", "Rockall Score"], 2,
    "The Child-Pugh Score is used to assess the severity of liver disease and its prognosis. It assesses 5 parameters: bilirubin, albumin, INR, ascites and hepatic encephalopathy."),
  Q("y2t15_p3", "y2t15", "Clinical & Pharmacology",
    "Name the condition characterised by excess copper deposition in the body?",
    ["Haemochromatosis", "Wilson's Disease", "Gilbert's syndrome", "Crigler-Najjar syndrome", "Primary biliary sclerosis"], 1,
    "Wilson's Disease is characterised by excess copper deposition in the body, due to a mutation in the ATP7B gene. It is an autosomal recessive condition and copper deposition in the liver may lead to chronic hepatitis."),
  Q("y2t15_p4", "y2t15", "Clinical & Pharmacology",
    "Which of the following viral hepatitis conditions has a contrastingly high mortality rate in pregnant women?",
    ["Hep A", "Hep B", "Hep C", "Hep D", "Hep E"], 4,
    "Hepatitis E is characterised by a high mortality rate (15-25%) for pregnant women and potential foetal complications. It can lead to fulminant hepatic failure. It is spread via the faecal-oral route, with water contamination being a common cause, and is prevalent in Asia and Africa."),
  Q("y2t15_p5", "y2t15", "Clinical & Pharmacology",
    "A patient undergoes serological testing for Hepatitis B. Which of the following blood test results would suggest he has been vaccinated but not affected yet?",
    ["HbsAg = +ve, HbeAg = +ve, HbcAb IgM = +ve, HbsAb = -ve", "HbsAg = -ve, HbeAg = -ve, HbcAb IgG = +ve, HbsAb = +ve", "HbsAg = -ve, HbeAg = -ve, HbcAb IgG = -ve, HbsAb = +ve", "HbsAg = +ve, HbeAg = +ve, HbcAb IgG = +ve, HbsAb = -ve"], 2,
    "In vaccination: HbsAg (surface antigen) is negative (no active infection), HbcAb (core antibody) IgG is negative (no past infection), HBeAg is negative, and only HBsAb (surface antibody) is positive due to immunity from the vaccination. A past infection would show positive HbcAb IgG alongside positive HbsAb."),
  Q("y2t15_p6", "y2t15", "Clinical & Pharmacology",
    "The liver plays a central role in drug metabolism. Which of the following increases CYP450 activity to increase the metabolic rate?",
    ["Ketoconazole", "Carbamazepine", "Cimetidine", "Grapefruit juice", "Erythromycin"], 1,
    "Carbamazepine, an antiepileptic drug, acts as an enzyme inducer, increasing CYP450 activity and the metabolic rate of drugs in the liver. Inhibitory drugs include cimetidine, ketoconazole, fluconazole, clarithromycin, erythromycin and grapefruit juice (inhibits CYP3A4)."),
  Q("y2t15_p7", "y2t15", "Physiology & Biochem",
    "Which cell type in the liver is responsible for phagocytosing bacteria and debris from portal blood?",
    ["Hepatocytes", "Kupffer cells", "Stellate cells", "Cholangiocytes", "Endothelial cells"], 1,
    "Kupffer cells are resident macrophages of the liver and part of the innate immune system."),
  Q("y2t15_p8", "y2t15", "Physiology & Biochem",
    "What are hepatic stellate cells primarily responsible for?",
    ["Producing bile", "Detoxifying drugs", "Storing vitamin A and producing collagen in fibrosis", "Phagocytosing pathogens", "Synthesising clotting factors"], 2,
    "Stellate cells are in a quiescent state; when activated during injury, they become proliferative, migratory, fibrogenic and contractile. In this form stellate cells produce collagen → liver fibrosis → cirrhosis."),
  Q("y2t15_p9", "y2t15", "Clinical & Pharmacology",
    "A liver biopsy from a patient with chronic alcohol misuse shows eosinophilic cytoplasmic inclusions composed of damaged cytokeratin intermediate filaments within hepatocytes. What are these structures called?",
    ["Councilman bodies", "Lewy bodies", "Russell bodies", "Negri bodies", "Mallory–Denk bodies"], 4,
    "When cells are damaged (like in alcoholic liver disease), cytokeratin filaments can become clumped and misfolded, forming Mallory bodies. These abnormal aggregates are a sign of cell stress and injury, classically seen in alcoholic liver disease."),
  Q("y2t15_p10", "y2t15", "Clinical & Pharmacology",
    "A 55-year-old man with chronic liver disease develops ascites and leg edema. Which lab reflects synthetic dysfunction?",
    ["High ALT", "Low albumin", "High GGT", "High bilirubin", "High ALP"], 1,
    "Low albumin reflects reduced protein synthesis, a marker of chronic liver disease. Albumin is the major plasma protein responsible for maintaining plasma oncotic pressure; low levels cause oedema and ascites."),
  Q("y2t15_p11", "y2t15", "Clinical & Pharmacology",
    "A patient with cholestasis is most likely to show which pattern on blood tests?",
    ["↑ Platelets", "↑ ALT & AST only", "↑ ALP & GGT predominantly", "↑ Bilirubin only", "↓ Albumin only"], 2,
    "ALP and GGT are cholestatic enzymes; elevations indicate bile flow obstruction. You might also get some derangement in ALT and AST but the main thing in a cholestatic picture is ALP and GGT."),
  Q("y2t15_p12", "y2t15", "Clinical & Pharmacology",
    "A 52-year-old man with a long history of heavy alcohol use presents with fatigue and mild jaundice. Blood tests show: AST 220 U/L, ALT 90 U/L, GGT 150 U/L, ALP 110 U/L. Which of the following is most characteristic of alcoholic liver disease in this patient?",
    ["AST > ALT, ratio >2", "ALP > ALT, ratio irrelevant", "AST < ALT, ratio <1", "ALT > AST, ratio <1", "AST ≈ ALT, ratio ~1"], 0,
    "In alcoholic liver disease, AST is usually higher than ALT, typically AST:ALT >2:1. ALT rarely rises above 300 U/L. AST:ALT ratio >2 = alcoholic liver disease; AST:ALT ratio <1 = viral hepatitis or NAFLD (use history to deduce)."),
  Q("y2t15_p13", "y2t15", "Clinical & Pharmacology",
    "A 50-year-old man with cirrhosis presents with confusion and asterixis. His labs show increased serum ammonia. Which of the following best explains the pathophysiology of the symptoms experienced by this patient?",
    ["Increased urea cycle activity in hepatocytes", "Increased intestinal absorption of bilirubin", "Decreased hepatic gluconeogenesis", "Decreased conversion of ammonia to urea", "Decreased production of clotting factors"], 3,
    "The liver normally detoxifies ammonia via the urea cycle (NH₃ → urea → excretion by kidneys). In cirrhosis, hepatocytes are damaged so the urea cycle is impaired, causing ammonia to accumulate and cross the BBB, causing hepatic encephalopathy."),
  Q("y2t15_p14", "y2t15", "Physiology & Biochem",
    "Which enzyme catalyzes the rate-limiting step of glycolysis?",
    ["Hexokinase", "Phosphofructokinase-1 (PFK-1)", "Pyruvate kinase", "Glucose-6-phosphatase", "Lactate dehydrogenase"], 1,
    "PFK-1 catalyzes fructose-6-phosphate → fructose-1,6-bisphosphate, the rate-limiting step in glycolysis. PFK-1 is allosterically regulated by ATP (inhibitor) and AMP (activator), allowing the cell to adjust energy production based on demand."),
  Q("y2t15_p15", "y2t15", "Clinical & Pharmacology",
    "Which virus is the most common cause of chronic viral hepatitis worldwide?",
    ["Hepatitis A virus", "Hepatitis B virus", "Hepatitis C virus", "Hepatitis D virus", "Hepatitis E virus"], 1,
    "Hepatitis B virus (HBV) is the most common cause of chronic viral hepatitis globally, affecting hundreds of millions of people. Chronic infection increases the risk of cirrhosis and hepatocellular carcinoma."),
  Q("y2t15_p16", "y2t15", "Clinical & Pharmacology",
    "Which feature of hepatitis B virus allows it to persist chronically in hepatocytes?",
    ["RNA genome replication in the cytoplasm", "Integration of viral DNA into the host genome", "Replication exclusively in mitochondria", "Lack of immune recognition", "Production of only non-structural proteins"], 1,
    "HBV DNA can integrate into the host hepatocyte genome, contributing to chronic infection and increasing the risk of hepatocellular carcinoma."),
  Q("y2t15_p17", "y2t15", "Clinical & Pharmacology",
    "Which biochemical marker indicates active replication of hepatitis B virus?",
    ["HBsAg", "Anti-HBs", "Anti-HBc IgG", "HBeAg", "Anti-HBe"], 3,
    "HBeAg (hepatitis B e antigen) indicates active viral replication and high infectivity. Its presence correlates with higher viral loads and increased transmission risk."),
  Q("y2t15_p18", "y2t15", "Clinical & Pharmacology",
    "Which laboratory finding is most characteristic of acute viral hepatitis?",
    ["Mild elevation of alkaline phosphatase only", "Markedly elevated ALT and AST", "Reduced bilirubin levels", "Low albumin with normal transaminases", "Elevated creatinine"], 1,
    "Acute viral hepatitis typically causes markedly elevated aminotransferases (ALT and AST) due to hepatocyte injury and leakage of intracellular enzymes."),
  Q("y2t15_p19", "y2t15", "Clinical & Pharmacology",
    "Which immune mechanism is primarily responsible for hepatocyte damage in viral hepatitis?",
    ["Direct viral cytotoxicity", "Complement activation alone", "Cytotoxic T lymphocyte–mediated killing", "Neutrophil phagocytosis", "Antibody-mediated apoptosis"], 2,
    "Hepatocyte injury in viral hepatitis is largely due to CD8+ cytotoxic T lymphocytes targeting infected hepatocytes rather than direct viral destruction."),
  Q("y2t15_p20", "y2t15", "Physiology & Biochem",
    "Which metabolic pathway represents Phase I drug metabolism in the liver?",
    ["Glucuronidation", "Sulfation", "Oxidation by cytochrome P450 enzymes", "Acetylation", "Conjugation with glutathione"], 2,
    "Phase I reactions involve oxidation, reduction, or hydrolysis, primarily mediated by cytochrome P450 enzymes, which introduce functional groups to drugs."),
  Q("y2t15_p21", "y2t15", "Physiology & Biochem",
    "Which process represents a Phase II reaction in hepatic drug metabolism?",
    ["Oxidation", "Hydrolysis", "Reduction", "Glucuronidation", "Dealkylation"], 3,
    "Phase II reactions conjugate drugs with molecules such as glucuronic acid, sulfate, or glutathione, increasing water solubility and facilitating excretion."),
  Q("y2t15_p22", "y2t15", "Clinical & Pharmacology",
    "Which mechanism best explains paracetamol-induced liver injury?",
    ["Inhibition of bile secretion", "Formation of a toxic metabolite (NAPQI) that depletes glutathione", "Direct viral cytotoxicity", "Autoimmune destruction of hepatocytes", "Increased hepatic blood flow"], 1,
    "Paracetamol is metabolised by cytochrome P450 to NAPQI, a toxic metabolite normally detoxified by glutathione. Overdose depletes glutathione, allowing NAPQI to damage hepatocytes."),
);
