// questions/y2t10.jsx, Year 2 Theme 10: Oesophagus (legacy bank, ISOCMEDED).
// Answers & explanations from the official ISocMedEd answer PDF.
// Diagram-dependent questions (Anatomy 1–3, Histology 1) are omitted.
window.QUESTIONS.push(
  Q("y2t10_a4", "y2t10", "Anatomy",
    "The external oblique covers which of the following ribs?",
    ["Ribs VII to XI", "Ribs V to XII", "Ribs VI to XII", "Ribs IX to XII", "Ribs VIII to XII"], 1,
    "The external oblique originates from the external surfaces of the lower eight ribs (ribs 5-12)."),
  Q("y2t10_a5", "y2t10", "Anatomy",
    "The anterior rami of which thoracic spinal nerves innervates the abdominal wall muscles?",
    ["T6-T12", "T1-T12", "T7-T12", "T11-T12", "T10-T12"], 2,
    "T7-T12 represent the lower six thoracic spinal nerves which innervate the abdominal wall muscles such as external oblique, internal oblique, transversus abdominis and rectus abdominis."),
  Q("y2t10_a6", "y2t10", "Anatomy",
    "Which of the following spinal nerves provides sensation at the umbilicus region?",
    ["T7-T9", "T7-T12", "T10", "T11-L1", "L1"], 2,
    "T10 provides sensation at the umbilicus region (belly button). Whilst T7-T9 provide sensation from the xiphoid process to just superior to the umbilicus. T11-T12 provide sensation from inferior to the umbilicus to the pubic region. L1 does for the inguinal region (groin)."),
  Q("y2t10_a7", "y2t10", "Anatomy",
    "The superficial epigastric and circumflex iliac arteries are branches of which artery?",
    ["Femoral artery", "External iliac artery", "Internal iliac artery", "Internal thoracic artery", "Musculophrenic artery"], 0,
    "The femoral artery provides branches such as the superficial epigastric and circumflex iliac arteries. These two arteries provide arterial supply to the inferior part of the abdominal wall."),
  Q("y2t10_h2", "y2t10", "Anatomy",
    "Which feature is the most distinguishable of the appendix?",
    ["Peyer's patches", "Brunner's glands", "Lymphoid tissue", "Crypts of Lieberkühn", "Taeniae coli"], 2,
    "The appendix is most distinguishable by the presence of prominent lymphoid tissue. Brunner's glands feature in the duodenum; Peyer's patches feature in the ileum; Crypts of Lieberkühn feature in both intestines; Taeniae coli features in the colon."),
  Q("y2t10_h3", "y2t10", "Anatomy",
    "Name the 4 layers of the GI tract from innermost to outermost.",
    ["Muscularis Externa, Mucosa, Serosa, Submucosa", "Mucosa, Submucosa, Muscularis Externa and Serosa", "Serosa, Muscularis Externa, Submucosa and Mucosa", "Mucosa, Muscularis Externa, Submucosa and Serosa", "Muscularis Externa, Mucosa, Submucosa, Serosa"], 1,
    "From innermost to outermost it follows: Mucosa, Submucosa, Muscularis Externa and Serosa."),
  Q("y2t10_h4", "y2t10", "Anatomy",
    "From the duodenum descending to the ileum, which of the following is correct?",
    ["Length of villi decreases, goblet cells increase, plicae circularis less prominent", "Length of villi decreases, goblet cells decrease, plicae circularis less prominent", "Length of villi decreases, goblet cells decrease, plicae circularis more prominent", "Length of villi increases, goblet cells increase, plicae circularis more prominent", "Length of villi increases, goblet cells increase, plicae circularis less prominent"], 0,
    "From the duodenum descending to the ileum: length of villi decreases, goblet cells increase since more mucus is required due to dryness, and plicae circularis becomes less prominent."),
  Q("y2t10_p1", "y2t10", "Physiology & Biochem",
    "Which of the following components of the brain controls swallowing?",
    ["Midbrain", "Pons", "Medulla oblongata", "Temporal lobe", "Occipital lobe"], 2,
    "The medulla oblongata is the swallowing centre, it coordinates the involuntary sequence of swallowing. The lower pons is also involved, but not primarily to the extent of the medulla."),
  Q("y2t10_p2", "y2t10", "Physiology & Biochem",
    "Ahmed, a 68 year old male, is diagnosed with achalasia. This condition describes the loss of inhibitory neurones at which location?",
    ["Basal ganglia", "Myenteric plexus", "Interstitial cells of Cajal", "Submucosal plexus", "Vagus nerve"], 1,
    "The myenteric (Auerbach) plexus' loss of inhibitory neurones leads to a failure of the lower oesophageal sphincter to release. This is known as achalasia."),
  Q("y2t10_p3", "y2t10", "Physiology & Biochem",
    "For an individual with suspected achalasia, which investigation will you prioritise carrying out first?",
    ["Oesophageal manometry", "MRI scan", "CT scan", "Barium swallow test", "Upper GI endoscopy"], 4,
    "Upper GI endoscopy is the first investigation to be carried out. This involves inserting a camera down the oesophagus to assess for obstructions and carcinomas, important to rule out malignancy first. Although oesophageal manometry is the gold standard diagnostic tool for achalasia, it would follow after the endoscopy. The barium swallow can be a tertiary investigation, supporting the achalasia diagnosis by displaying a 'bird beak' picture."),
  Q("y2t10_p4", "y2t10", "Physiology & Biochem",
    "Peristalsis is initiated by which types of cells?",
    ["Myenteric plexus neurones", "Submucosal plexus neurones", "Interstitial cells of Cajal", "Basal ganglia neurones", "Vagus nerve"], 2,
    "Interstitial cells of Cajal function as pacemakers of the GI system. They generate the electrical activity which leads to peristalsis."),
  Q("y2t10_p5", "y2t10", "Physiology & Biochem",
    "Barrett's oesophagus describes which of the following histological findings?",
    ["The transition of epithelium from simple squamous to simple columnar", "The transition of epithelium from simple columnar to simple squamous", "The transition of epithelium from simple cuboidal to simple squamous", "The transition of epithelium from simple columnar to stratified squamous", "The transition of epithelium from stratified squamous to simple columnar"], 4,
    "Barrett's oesophagus occurs when chronic acid reflux from the stomach to the oesophagus results in its epithelium gradually changing from stratified squamous to simple columnar."),
  Q("y2t10_p6", "y2t10", "Physiology & Biochem",
    "Damage to parietal cells can lead to deficiency in which vitamin?",
    ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D", "Vitamin E", "Vitamin K"], 1,
    "Parietal cells secrete intrinsic factor which is essential for vitamin B12 absorption. Therefore damage to parietal cells will result in vitamin B12 deficiency."),
  Q("y2t10_p7", "y2t10", "Physiology & Biochem",
    "Sammy, a 35 year old patient, is diagnosed with gastro-oesophageal reflux disease. Which of the following symptoms is she least likely to have?",
    ["Heartburn", "Acid regurgitation", "Vomiting", "Dyspepsia", "Epigastric pain"], 2,
    "Vomiting is not a feature of GORD. Acid regurgitation may occur, however vomiting is associated with other pathologies. Heartburn, dyspepsia and epigastric pain are all common symptoms alongside acid regurgitation."),
  Q("y2t10_p8", "y2t10", "Physiology & Biochem",
    "Which cells secrete somatostatin?",
    ["G cells", "D cells", "Chief cells", "Parietal cells", "S cells"], 1,
    "Somatostatin is released by D cells. It is an inhibitory hormone which inhibits the release of gastrin alongside secretin. Secretin is released by S cells."),
  Q("y2t10_p9", "y2t10", "Physiology & Biochem",
    "Which 2 hormones inhibit the release of gastrin?",
    ["Gastrin inhibitory peptide and secretin", "Somatostatin and secretin", "Pepsin and gastrin inhibitory peptide", "Somatostatin and gastrin inhibitory peptide", "Histamine and gastrin inhibitory peptide"], 1,
    "Somatostatin and secretin are both inhibitory hormones which inhibit the release of gastrin when the pH becomes acidic. Gastrin inhibitory peptide does not directly inhibit gastrin release, but it works to inhibit the release of gastric acid from parietal cells."),
  Q("y2t10_p10", "y2t10", "Physiology & Biochem",
    "A patient presents with a reduced ability to digest fats in their GI system. Which of the following hormones is most likely to be deficient?",
    ["Ghrelin", "CCK", "Secretin", "Gastrin", "Histamine"], 1,
    "Cholecystokinin (CCK) is secreted by the I cells of the duodenum and jejunum when fats are present and require digestion. It stimulates the gallbladder to contract, enabling more bile to enter the duodenum to emulsify fats, stimulates the pancreas to secrete digestive enzymes, and inhibits gastric emptying to enable sufficient time for digestion and absorption."),
  Q("y2t10_ph1", "y2t10", "Clinical & Pharmacology",
    "Proton Pump Inhibitors (PPIs) reduce gastric acid secretion by which mechanism?",
    ["Inhibiting gastrin receptors", "Inhibiting the H+/K+ ATPase pump", "Inhibiting H2 receptors", "Inhibiting the release of somatostatin", "Inhibiting the release of secretin"], 1,
    "PPIs reduce gastric acid secretion by irreversibly inhibiting the H+/K+ ATPase pump. This prevents the transportation of H+ ions into the stomach lumen, thus restricting the binding with Cl- ions to form HCl."),
  Q("y2t10_ph2", "y2t10", "Clinical & Pharmacology",
    "When should PPIs be taken ideally?",
    ["At meal time", "Before meals", "In the morning", "Before you sleep"], 1,
    "PPIs should be taken 30 mins before meals. This will help prevent acid regurgitation and heartburn whilst eating. Taking with meals can delay absorption and prevent the levels reaching maximum concentration."),
  Q("y2t10_ph3", "y2t10", "Clinical & Pharmacology",
    "Which of the following is a histamine-2 receptor antagonist?",
    ["Omeprazole", "Famotidine", "Gaviscon", "Naloxone", "Theophylline"], 1,
    "Famotidine is a histamine-2 receptor antagonist. It reduces gastric acid secretion by competitively inhibiting the H2 receptors directly on parietal cells in the stomach."),
  Q("y2t10_e1", "y2t10", "Ethics & EBM",
    "An 89 year old female with advanced chronic kidney disease is receiving dialysis. She has multiple co-morbidities which have got worse recently. Following discussion, the multidisciplinary team (MDT) at the hospital have decided that dialysis is no longer beneficial and they recommend withdrawal of treatment in her best interests. She consents and agrees to this. Which of the following best describes this decision?",
    ["Active voluntary euthanasia", "Passive voluntary euthanasia", "Passive involuntary euthanasia", "Active involuntary euthanasia", "Assisted suicide"], 1,
    "The situation describes passive voluntary euthanasia. It is passive since death is brought about due to a withdrawal of treatment, it would only be active if one was directly administering treatment to bring death. It is voluntary since the person has consented. Non-voluntary would be where the person is unable to make a decision themselves."),
  Q("y2t10_b1", "y2t10", "BSS",
    "A 24-year-old man has recently been diagnosed with HIV. He feels overwhelmed by the diagnosis and is unsure how to manage his condition. He believes that HIV is untreatable and that there is little he can do to control it. Which of the following theories would help to understand his illness beliefs better?",
    ["Health Belief model", "Self-regulatory model", "COM-B Model", "PRIME theory", "Transtheoretical model"], 1,
    "The components of the Self-Regulatory model in this context: Identity, understanding what HIV means to him; Cause, his beliefs about why he has the condition; Timeline, perception of HIV as a long-term or incurable condition; Consequences, his view of the seriousness and impact of HIV; Control/Curability, his belief that HIV is untreatable and that he has little ability to manage his condition."),
);
