// questions/y2t16.jsx, Year 2 Theme 16: Diabetes (legacy bank, ISOCMEDED).
// Two "select all that apply" questions (P&B 1, 4) are omitted (the quiz is single-answer).
window.QUESTIONS.push(
  Q("y2t16_p2", "y2t16", "Clinical & Pharmacology",
    "Paul, a 45 year old male, arrives at the clinic complaining of excess thirst and urination. In order to diagnose diabetes, the doctor orders several tests. The first test he orders is the HbA1c test. Which of the following results of HbA1c would support the diagnosis of diabetes?",
    ["≥48 mmol/mol", "≥11.1 mmol/mol", "≥11.1 mmol/L", "≥7 mmol/mol", "≥7 mmol/L", "≥48 mmol/L"], 0,
    "The HbA1c measures the average blood glucose levels over the last 2-3 months (dependent on the lifespan of the RBC). A value of 42-47 mmol/mol suggests pre-diabetes whilst a value of 48 mmol/mol or greater suggests diabetes. Bear in mind, the units are mmol/mol rather than mmol/L."),
  Q("y2t16_p3", "y2t16", "Clinical & Pharmacology",
    "The second test ordered is the fasting plasma glucose for Paul. Which of the following results of fasting plasma glucose would support the diagnosis of diabetes?",
    ["≥48 mmol/mol", "≥11.1 mmol/mol", "≥11.1 mmol/L", "≥7 mmol/mol", "≥7 mmol/L", "≥48 mmol/L"], 4,
    "The fasting plasma glucose level measures glucose levels after at least 8 hours of fasting. A value of 7 mmol/L or greater suggests diabetes. For a random plasma glucose, a value of 11.1 mmol/L or greater would suggest diabetes, supported with classic symptoms such as polyuria, polydipsia and/or weight loss."),
  Q("y2t16_p5", "y2t16", "Physiology & Biochem",
    "Insulin deficiency can lead to which of the following electrolyte imbalances in the blood serum?",
    ["Hypercalcaemia", "Hyperphosphatemia", "Hypokalaemia", "Hyperkalaemia", "Hypernatraemia"], 3,
    "Insulin deficiency leads to hyperkalaemia (raised K+) in the blood serum. Insulin normally drives K+ into cells; when deficient, the Na+/K+ pump is no longer able to pump K+ into cells, leaving potassium to accumulate in the blood serum. Insulin deficiency can also lead to hyponatraemia since hyperglycaemia draws water out to be excreted in the urine."),
  Q("y2t16_p6", "y2t16", "Physiology & Biochem",
    "Which of the following is an insulin dependent receptor?",
    ["GLUT 1", "GLUT 2", "GLUT 3", "GLUT 4", "GLUT 5"], 3,
    "Insulin binds to receptors on cells, leading to receptor tyrosine kinase activation. Signalling molecules (IRS, PI3K, AKT) signal the translocation of GLUT4 receptors onto the cell membrane, enabling glucose uptake. GLUT4 is found on adipose tissue, striated muscle, and the heart. GLUT 1 and 2 are insulin insensitive."),
  Q("y2t16_p7", "y2t16", "Physiology & Biochem",
    "What type of receptor does glucagon act on?",
    ["Tyrosine kinase receptor", "G protein coupled receptor", "Ligand gated receptor", "Nuclear receptor", "Cytokine receptor (JAK-STAT receptor)"], 1,
    "Glucagon acts on G protein coupled receptors, stimulating adenylate cyclase, increasing cAMP and protein kinase A. This increases glycogenolysis and gluconeogenesis by inhibiting glucokinase. It also means fewer GLUT-4 channels are opened, so less glucose can enter skeletal muscle and fat."),
  Q("y2t16_p8", "y2t16", "Physiology & Biochem",
    "HbA1c measures glucose control over a period of …?",
    ["3 days", "4 weeks", "3 months", "4 months", "4 years"], 2,
    "HbA1c analyses the amount of haemoglobin that has been glycated; this measures glucose control over a period of 3 months as that is the life cycle of RBCs."),
  Q("y2t16_p9", "y2t16", "Clinical & Pharmacology",
    "Insulin deficiency in type 1 diabetes often leads to which presentation on an ABG?",
    ["Respiratory acidosis", "Respiratory alkalosis", "Metabolic acidosis", "Metabolic alkalosis", "Mixed respiratory and metabolic acidosis"], 2,
    "Diabetic ketoacidosis: the body lacks enough insulin to use glucose for energy, and starts to break down fat instead, forming ketones. The buildup of ketones results in metabolic acidosis, causing a decreased blood pH. This presents with nausea and/or vomiting, abdominal pain, and hyperventilation at later stages."),
  Q("y2t16_p10", "y2t16", "Clinical & Pharmacology",
    "A 68 year old male presents to the GP and complains of a 5-week history of thirst, going to the bathroom more than normal and tiredness. He is obese and has a family history of hypercholesterolemia. The GP is concerned and decides to run some tests to confirm their suspicions. What is the preferred investigation to diagnose the likely condition?",
    ["HbA1c", "Random plasma glucose", "Urinalysis", "Ketones", "C peptide"], 1,
    "Random plasma glucose is often the first line investigation in a case of suspected diabetes. In a symptomatic patient: fasting glucose ≥7.0 mmol/L or random glucose ≥11.1 mmol/L. If asymptomatic, the criteria must be demonstrated on two separate occasions. HbA1c may not accurately reflect a recent rapid rise in serum glucose. C-peptide distinguishes T1DM from T2DM but is not first line."),
  Q("y2t16_p11", "y2t16", "Physiology & Biochem",
    "Which of the following is true?",
    ["GLUT1 and GLUT2 are insulin sensitive", "SGLT2 has a higher affinity to glucose than SGLT1", "The mean age for diagnosis of T1DM is 63", "Antibodies to glomerular basement membrane levels are elevated in autoimmune diabetes", "Glucagon acts to decrease PKA levels"], 1,
    "The Km of glucose in SGLT2 is 5mM compared to 2 in SGLT1, the concentration of glucose that saturates the transporter is higher. GLUT4 is the only insulin sensitive GLUT receptor; T1DM has a peak incidence around 10-14 years; anti-GBM antibodies are elevated in Goodpasture syndrome (anti-GAD, ICA, IAA, IA-2A in T1DM); glucagon increases PKA levels."),
  Q("y2t16_p12", "y2t16", "Physiology & Biochem",
    "Which glucose transporter is located in the early proximal convoluted tubule?",
    ["SGLT2", "SGLT1", "GLUT3", "GLUT5", "GLUT4"], 0,
    "In the early proximal tubule >90% of glucose is absorbed by SGLT2. In the late proximal tubule almost all of the remaining glucose is absorbed by SGLT1. GLUT3 is found in the brain/neurons, GLUT5 is a fructose transporter in the intestine, GLUT4 is in skeletal muscle, heart, and adipose tissue."),
  Q("y2t16_ph1", "y2t16", "Clinical & Pharmacology",
    "A 58 year old patient with diabetes has a BMI of 43.5. He is already on metformin and empagliflozin. Which of the following medications should the doctor consider adding in order to help him lose weight?",
    ["Glipizide", "Semaglutide", "Pioglitazone", "Gliclazide", "Alogliptin"], 1,
    "GLP-1 agonists such as semaglutide help promote weight loss by inhibiting gastric emptying and suppressing appetite."),
  Q("y2t16_ph2", "y2t16", "Clinical & Pharmacology",
    "Which of the following diabetic medications are also commonly used to treat heart failure?",
    ["Gliclazide", "Dapagliflozin", "Liraglutide", "Alogliptin", "Metformin"], 1,
    "SGLT2 inhibitors such as dapagliflozin are commonly used in heart failure (especially with reduced EF). They have been shown to reduce mortality and hospitalisation, and can even be used alone for patients with heart failure, regardless of whether they have diabetes."),
  Q("y2t16_ph3", "y2t16", "Clinical & Pharmacology",
    "A patient is due a HbA1c test to assess a potential diagnosis for diabetes. Which of the following medications may affect the results and lead to a greater glucose reading?",
    ["Amlodipine", "Sodium valproate", "Prednisolone", "Ramipril", "Methotrexate"], 2,
    "Prednisolone is a glucocorticoid drug which increases hepatic glucose production, thus leading to raised glucose levels and affecting the HbA1c results."),
  Q("y2t16_ph4", "y2t16", "Clinical & Pharmacology",
    "Which of the following options comprise the first line treatment for Type 2 diabetes?",
    ["Thiazolidinediones", "SGLT2 inhibitor", "Metformin", "GLP1 agonists", "DPP4 inhibitor"], 2,
    "As per NICE guidance, metformin (with an SGLT2 inhibitor where indicated) is offered as first-line treatment for type 2 diabetes unless contraindicated. Metformin works by decreasing hepatic gluconeogenesis and increasing insulin sensitivity. The rest are added depending on patient preference, comorbidities and CV risk."),
  Q("y2t16_ph5", "y2t16", "Clinical & Pharmacology",
    "What is the main side effect of SGLT2 inhibitors?",
    ["Weight gain", "Urinary tract infections (UTIs)", "Headaches", "Nausea and Vomiting", "Metabolic alkalosis"], 1,
    "SGLT2 inhibitors reduce glucose reabsorption in the kidneys, increasing glucose excretion in urine. This increased urinary glucose promotes genital yeast infections and urinary tract infections (UTIs). They can also cause dehydration, electrolyte imbalances and diabetic ketoacidosis."),
  Q("y2t16_ph6", "y2t16", "Clinical & Pharmacology",
    "GLP-1 receptor agonists are contraindicated or used with caution in patients with:",
    ["Heart failure", "Acute pancreatitis", "Asthma", "Hepatitis B", "Crohns disease"], 1,
    "Although rare, there is a potential risk of acute pancreatitis in patients taking GLP-1 receptor agonists."),
  Q("y2t16_ph7", "y2t16", "Clinical & Pharmacology",
    "Which of the following drugs increases the risks of weight gain?",
    ["Liraglutide", "Semaglutide", "SGLT2 inhibitors", "Metformin", "Sulfonylureas"], 4,
    "Sulfonylureas act on pancreatic beta cells to increase insulin secretion, causing weight gain and hypoglycaemia."),
  Q("y2t16_b1", "y2t16", "BSS",
    "What percentage of adults in the UK are obese?",
    ["38%", "17%", "29%", "72%", "67%"], 2,
    "Around 29% of adults in the UK are obese, a statistic worth knowing for exams."),
  Q("y2t16_b2", "y2t16", "BSS",
    "Obesity is defined as a BMI of over:",
    ["20", "25", "30", "35"], 2,
    "BMI categories: underweight below 18.5; healthy weight 18.5 to 24.9; overweight 25.0 to 29.9; obesity 30.0 or higher."),
);
