// questions/y2t19.jsx, Year 2 Theme 19: Thyroid (legacy bank, ISOCMEDED).
// Diagram questions (Anatomy 1–3) and two multi-answer questions (P&B 7, Pharm 2) are omitted.
window.QUESTIONS.push(
  Q("y2t19_a4", "y2t19", "Anatomy",
    "The thyroid gland is embryologically derived from",
    ["First pharyngeal pouch", "Second pharyngeal arch", "Foramen cecum of the tongue", "Third pharyngeal pouch", "Rathke's pouch"], 2,
    "The foramen caecum of the tongue is the embryological origin of the thyroid. It arises as a 'median outgrowth' from the floor of the pharynx near the base of the tongue."),
  Q("y2t19_a5", "y2t19", "Anatomy",
    "The arterial supply of the thyroid gland is derived from all of the following EXCEPT",
    ["Superior thyroid artery", "Inferior thyroid artery", "Thyroid ima artery", "Internal thoracic artery", "Branches from tracheal arteries"], 3,
    "The main supply of the thyroid is from the superior and inferior thyroid arteries as well as minor branches such as thyroid ima and smaller tracheal branches. The internal thoracic artery does not have any relevant branches which supply the thyroid."),
  Q("y2t19_a6", "y2t19", "Anatomy",
    "The recurrent laryngeal nerve is most at risk during thyroid surgery because it passes:",
    ["Anterior to the common carotid artery", "Through the cricothyroid membrane", "In the tracheoesophageal groove near the posterior thyroid", "Deep to the sternothyroid muscle only", "Lateral to the internal jugular vein"], 2,
    "The recurrent laryngeal nerve runs very close to the thyroid in the tracheoesophageal groove. A lesion to this nerve could result in vocal cord paralysis, notably leading to a hoarse voice and difficulty swallowing."),
  Q("y2t19_a7", "y2t19", "Anatomy",
    "The external laryngeal nerve is at risk during ligation of which vessel?",
    ["Inferior thyroid artery", "Middle thyroid vein", "Superior thyroid artery", "Thyroid ima artery", "Inferior thyroid vein"], 2,
    "The external laryngeal nerve is located close to the superior thyroid artery and vein, hence will likely be at risk during ligation."),
  Q("y2t19_a8", "y2t19", "Anatomy",
    "Enlargement of the thyroid gland is restricted in which direction because of the sternohyoid and sternothyroid muscles?",
    ["Superiorly", "Inferiorly", "Anteriorly", "Posteriorly", "Laterally"], 0,
    "The infrahyoid ('strap') muscles limit upward expansion of the thyroid gland."),
  Q("y2t19_a9", "y2t19", "Anatomy",
    "The inferior thyroid artery most commonly originates from which major vessel?",
    ["Subclavian artery", "Common carotid artery", "External carotid artery", "Internal carotid artery", "Superior thyroid artery"], 0,
    "The subclavian artery gives rise to the thyrocervical trunk which forms a branch called the inferior thyroid artery."),
  Q("y2t19_p1", "y2t19", "Physiology & Biochem",
    "Which of the following symptoms likely resemble a patient with hyperthyroidism compared to hypothyroidism?",
    ["Weight gain", "Cold intolerance", "Anxiety", "Dry skin", "Depression"], 2,
    "Hyperthyroidism is characterised by high levels of thyroid hormones (T4 and T3) which leads to an increased basal metabolic rate (BMR). This results in increased sympathetic activity, leading to symptoms such as sweating, tachycardia, anxiety, heat intolerance, tremor and weight loss."),
  Q("y2t19_p2", "y2t19", "Physiology & Biochem",
    "What is the approximate half-life of T3 and T4?",
    ["T3 = 4 days, T4 = 6-7 days", "T3 = 1 day, T4 = 6-7 days", "T3 = 3 days, T4 = 7-10 days", "T3 = 6-7 days, T4 = 1 day", "T3 = 3 days, T4 = 3 days"], 1,
    "T3 (triiodothyronine) has a significantly short half-life of around 1 day, more active and potent, but cleared rapidly. T4 (thyroxine) is more stable with a half-life of around 7 days."),
  Q("y2t19_p3", "y2t19", "Physiology & Biochem",
    "The sodium-iodide symporter (NIS) involves which of the following?",
    ["1 Na+ ion in, 1 I- ion in", "1 Na+ ion out, 1 I- ion in", "2 Na+ ions in, 1 I- ion in", "2 Na+ ions in, 2 I- ions in", "2 Na+ ions in, 1 I- ion out"], 2,
    "The sodium-iodide symporter (NIS) involves the combined transport of both 2Na+ ions and 1 I- ion in. These go into the thyroid follicular cells."),
  Q("y2t19_p4", "y2t19", "Clinical & Pharmacology",
    "Which of the following is likely to be a secondary cause of hyperthyroidism?",
    ["Thyroiditis", "Pituitary adenoma", "Goitre", "Grave's disease", "Iodine deficiency"], 1,
    "A pituitary adenoma is a secondary cause of hyperthyroidism since it doesn't directly impede on the thyroid, it indirectly stimulates the thyroid by releasing more TSH from the pituitary. The rest directly affect the thyroid (primary); iodine deficiency is a primary cause of hypothyroidism, not hyper."),
  Q("y2t19_p5", "y2t19", "Physiology & Biochem",
    "Aldosterone is secreted from which part of the adrenal cortex?",
    ["Adrenal medulla", "Zona glomerulosa", "Zona reticularis", "Zona fasciculata"], 1,
    "The adrenal cortex is split into 3 zones: zona glomerulosa, mineralocorticoids (e.g. aldosterone); zona fasciculata, glucocorticoids (e.g. cortisol); zona reticularis, androgens. The adrenal medulla is not part of the adrenal cortex."),
  Q("y2t19_p6", "y2t19", "Clinical & Pharmacology",
    "Which of the following conditions is characterised by excess cortisol levels?",
    ["Addison's disease", "Cushing's disease", "Conn's syndrome", "Phaeochromocytoma", "Congenital adrenal hyperplasia"], 1,
    "Cushing's is characterised by excess cortisol levels, leading to central obesity, a moon face and thinning of the skin. It may be caused by long-term use of glucocorticoids, an ACTH producing tumour or a pituitary or adrenal tumour."),
  Q("y2t19_p8", "y2t19", "Physiology & Biochem",
    "The pumping of iodide ions into the follicle cells occurs via which transport?",
    ["Pendrin", "Ca+2/I- co-transporter", "Na+/I- symporter", "Iodide pump", "Thyrotropin co-transporter"], 2,
    "The thyroid follicular cell takes up iodide from the blood using the sodium-iodide symporter (NIS) on the basolateral membrane (2Na+ in, 1 I- in). It uses the sodium gradient created by the Na+/K+ ATPase to co-transport iodide into the cell."),
  Q("y2t19_p9", "y2t19", "Clinical & Pharmacology",
    "A 33-year-old male patient is to commence treatment for hyperthyroidism. As well as biochemical hyperthyroidism, he also has thyroid eye disease. Which of the following treatments is contraindicated in thyroid eye disease?",
    ["Carbimazole", "Propylthiouracil", "Radioactive iodine ablation therapy", "Thyroidectomy", "Propranolol"], 2,
    "Radioactive iodine can worsen thyroid eye disease (Graves' ophthalmopathy) because it may trigger or worsen autoimmune inflammation behind the orbit. Antithyroid drugs or surgery are preferred in significant eye disease."),
  Q("y2t19_p10", "y2t19", "Physiology & Biochem",
    "During thyroid hormone synthesis, which step occurs at the apical membrane of the follicular cell and requires thyroid peroxidase?",
    ["Transport of iodide into the follicular cell via NIS", "Endocytosis of thyroglobulin from colloid", "Peripheral conversion of T4 to T3", "Release of T3 and T4 into circulation", "Coupling of MIT and DIT residues"], 4,
    "Thyroid peroxidase (TPO) acts at the apical membrane/colloid interface. It oxidises iodide and catalyses the coupling reactions: MIT + DIT → T3, and DIT + DIT → T4."),
  Q("y2t19_p11", "y2t19", "Clinical & Pharmacology",
    "Why does Graves' disease commonly produce tachycardia and a widened pulse pressure?",
    ["Thyroid hormones increase sensitivity to catecholamines", "T3 decreases β1 receptor expression in the heart", "Increased ADH secretion causes volume overload", "T4 directly stimulates vagal tone", "Reduced metabolic rate increases cardiac output"], 0,
    "T3 upregulates β-adrenergic receptors, making tissues more sensitive to adrenaline and noradrenaline. This leads to tachycardia, palpitations, systolic hypertension, widened pulse pressure, tremor and anxiety."),
  Q("y2t19_p12", "y2t19", "Clinical & Pharmacology",
    "What does iodine deficiency mainly cause?",
    ["Goitre", "Thyroid cancer", "Solitary thyroid nodules", "Thyroiditis", "All of the above"], 0,
    "Decreased iodide means decreased T3/T4, which causes increased TSH via the feedback loop. Raised TSH causes thyroid enlargement = goitre."),
  Q("y2t19_p13", "y2t19", "Physiology & Biochem",
    "A thyroid follicular cell is unable to transport iodide from the cytoplasm into the colloid. Which membrane protein is most likely defective?",
    ["Na+/K+ ATPase", "Pendrin", "Thyroglobulin", "Thyroid peroxidase", "5'-deiodinase"], 1,
    "Pendrin transports iodide across the apical membrane into the colloid."),
  Q("y2t19_p14", "y2t19", "Clinical & Pharmacology",
    "In Graves' disease, pretibial myxoedema and thyroid eye disease occur primarily because of:",
    ["Direct T3 toxicity to connective tissue", "Deposition of immune complexes in skin and orbit", "TSH deficiency causing fibroblast activation", "Autoimmune stimulation of fibroblasts causing glycosaminoglycan deposition", "Excess calcitonin secretion"], 3,
    "Autoantibodies stimulate orbital and dermal fibroblasts, which produce hydrophilic glycosaminoglycans. Water retention and inflammation cause exophthalmos, periorbital oedema and pretibial myxoedema."),
  Q("y2t19_p15", "y2t19", "Physiology & Biochem",
    "A patient with untreated Graves' disease develops weight loss, tachycardia, heat intolerance, and proximal myopathy. At the cellular level, which mechanism most directly explains the increased basal metabolic rate seen in thyrotoxicosis?",
    ["Increased uncoupling of oxidative phosphorylation due to direct mitochondrial membrane destruction", "Increased transcription of Na+/K+ ATPase and mitochondrial enzymes mediated by nuclear thyroid hormone receptors", "Excess catecholamine production from the adrenal medulla causing sustained lipolysis", "Increased calcitonin secretion leading to accelerated ATP hydrolysis in skeletal muscle", "Direct activation of phospholipase C by circulating T4 at the plasma membrane"], 1,
    "T3 binds to intracellular nuclear receptors and alters gene transcription, increasing production of proteins involved in metabolism such as Na+/K+ ATPase and mitochondrial enzymes. This increases oxygen consumption and ATP turnover throughout the body, leading to heat intolerance, weight loss, and an increased basal metabolic rate."),
  Q("y2t19_ph1", "y2t19", "Clinical & Pharmacology",
    "Which isotope of iodine is used in radioactive therapy for hyperthyroidism?",
    ["I-128", "I-129", "I-130", "I-131", "I-132"], 3,
    "Iodine-131 is used as radioactive therapy for hyperthyroidism. It destroys the overactive thyroid cells by emitting beta and gamma radiation. It may also be used to treat thyroid cancer."),
  Q("y2t19_ph3", "y2t19", "Clinical & Pharmacology",
    "A patient taking Carbimazole develops fever and a sore throat. What is the most important immediate action?",
    ["Continue treatment and review in 1 week", "Start broad-spectrum antibiotics only", "Reduce the dose and repeat thyroid function tests", "Add levothyroxine immediately", "Stop the drug and urgently check a full blood count"], 4,
    "Carbimazole can rarely cause agranulocytosis, a dangerous drop in neutrophils, fever and sore throat warrant stopping the drug and an urgent full blood count."),
  Q("y2t19_ph4", "y2t19", "Clinical & Pharmacology",
    "Which therapeutic from the list of options below is used to treat and manage hyperthyroidism, including Graves' disease, by blocking iodine organification?",
    ["Propylthiouracil", "Azidothymidine", "Cimetidine", "Fluorouracil", "Rimantadine"], 0,
    "Propylthiouracil (PTU) treats hyperthyroidism by inhibiting thyroid peroxidase, which blocks iodine organification and the coupling reactions during T3/T4 synthesis. It also reduces peripheral conversion of T4 → T3."),
);
