// questions/y2t18.jsx, Year 2 Theme 18: Prostate (legacy bank, ISOCMEDED).
// Diagram questions (Anatomy 1–3) and two multi-answer pharmacology questions (Pharm 1, 2) are omitted.
window.QUESTIONS.push(
  Q("y2t18_a4", "y2t18", "Anatomy",
    "Where is the pouch of Douglas located?",
    ["Between the uterus and the rectum", "Between the rectum and the pubis", "Between the bladder and the pubis", "Behind the pubis", "Behind the bladder"], 0,
    "The pouch of Douglas, also known as the rectouterine pouch, is located between the rectum and uterus. It is only found in females; males have the similar rectovesical pouch (between rectum and bladder). Other pouches: uterovesical (between bladder and uterus) and retropubic (behind the pubis)."),
  Q("y2t18_a5", "y2t18", "Anatomy",
    "Which two structures unite to form the ejaculatory duct?",
    ["Spermatic cord and prostatic urethra", "Seminal vesicle and ductus deferens", "Seminal vesicle and spermatic cord", "Prostatic urethra and ductus deferens"], 1,
    "The seminal vesicle and ductus deferens unite to form the ejaculatory duct."),
  Q("y2t18_a6", "y2t18", "Anatomy",
    "Which of these is not a part of the male urethra?",
    ["Prostatic", "Membranous", "Transitional", "Spongy", "Preprostatic"], 2,
    "Preprostatic - Prostatic - Membranous - Spongy are the parts of the male urethra. Transitional is not a part of the urethra, it is a type of epithelium."),
  Q("y2t18_a7", "y2t18", "Anatomy",
    "Which of the following is responsible for detrusor muscle contraction during micturition?",
    ["Sympathetic fibres from T11-L2", "Somatic fibres via pudendal nerve", "Parasympathetic fibres from S2-S4", "Sympathetic fibres from S2-S4", "Hypogastric nerve inhibition"], 2,
    "Detrusor muscle contraction is parasympathetic (S2-S4 via the pelvic nerve) and relaxation is sympathetic."),
  Q("y2t18_a8", "y2t18", "Anatomy",
    "Which statement is correct about the ureteric openings in the bladder?",
    ["Enter obliquely", "Located in the anterior wall", "Positioned superior to the trigone", "Open into the prostatic urethra", "Surrounded by voluntary muscle"], 0,
    "The ureteric openings enter obliquely to prevent reflux. They aren't positioned superiorly to the trigone as they form the superolateral angles of the trigone itself."),
  Q("y2t18_a9", "y2t18", "Anatomy",
    "The ejaculatory ducts open into which part of the urethra?",
    ["Preprostatic", "Prostatic", "Membranous", "Spongy", "Penile"], 1,
    "The ejaculatory ducts open into the prostatic urethra at the seminal colliculus."),
  Q("y2t18_a10", "y2t18", "Anatomy",
    "Which part of the urethra contains the navicular fossa?",
    ["Preprostatic", "Prostatic", "Membranous", "Spongy"], 3,
    "The navicular fossa is a dilated terminal part of the spongy (penile) urethra, located in the glans penis just before the external opening."),
  Q("y2t18_a11", "y2t18", "Anatomy",
    "Which of the following is true about the trigone of the bladder?",
    ["Contains the internal urethral sphincter", "Lined by stratified squamous epithelium", "Located at the dome of the bladder", "It is highly elastic", "It remains smooth during bladder filling"], 4,
    "The trigone is a smooth triangular region on the internal floor of the bladder between the two ureteric openings and the urethral opening. Unlike the rest of the bladder wall, it remains smooth during filling."),
  Q("y2t18_p1", "y2t18", "Clinical & Pharmacology",
    "Which of the following is NOT a feature of nephrotic syndrome?",
    ["Protein in the urine", "Fluid in the legs", "Blood in the urine", "Hypoalbuminemia", "Hyperlipidemia"], 2,
    "Nephrotic syndrome is characterised by excess protein in the urine, fluid in the legs (oedema), hypoalbuminemia and hyperlipidemia. It does not usually lead to blood in the urine (haematuria), that is more commonly found in nephritic syndrome."),
  Q("y2t18_p2", "y2t18", "Clinical & Pharmacology",
    "Which of the following statements is correct?",
    ["Males are more likely to get a urinary tract infection (UTI) because they have a longer urethra than females", "Females are more likely to get a urinary tract infection (UTI) because they have a longer urethra than males", "Males are more likely to get a urinary tract infection (UTI) because they have a shorter urethra than females", "Males are more likely to get a urinary tract infection (UTI) because the urethra has to pass through their prostate", "Females are more likely to get a urinary tract infection (UTI) because they have a shorter urethra than males"], 4,
    "Females are more prone to urinary tract infections (UTI) than men since they have a shorter urethra. This means the bacteria has a shorter distance to travel to reach the bladder and infect it."),
  Q("y2t18_p3", "y2t18", "Clinical & Pharmacology",
    "What is the first-line investigation for a patient with a suspected UTI?",
    ["CT scan of abdomen", "Abdominal X-ray", "Urinalysis (urine dipstick)", "Midstream urine (MSU)", "Ultrasound of bladder"], 2,
    "Urinalysis (urine dipstick) is the first-line investigation. Nitrites suggest bacteria (gram-negative bacteria such as E.coli break down nitrates into these); leukocytes may also be raised. Midstream urine (MSU) may be done afterwards for complicated or recurrent UTIs, it takes 1-3 days for the bacterial culture to grow."),
  Q("y2t18_p4", "y2t18", "Clinical & Pharmacology",
    "Inflammation of the kidney resulting from bacterial infection is known as?",
    ["Nephritic syndrome", "Pyelonephritis", "Nephrotic syndrome", "Cystitis", "Glomerulonephritis", "Acute kidney injury"], 1,
    "Pyelonephritis is an upper urinary tract infection involving inflammation of the kidney, usually caused by bacteria ascending from the bladder via the ureter. It may present with haematuria, fever, and back pain radiating to the groin. A lower UTI can be characterised by cystitis (inflammation of the bladder)."),
  Q("y2t18_p5", "y2t18", "Clinical & Pharmacology",
    "Which of the following is unlikely to lead to an elevated PSA?",
    ["Prostate cancer", "Benign prostatic hyperplasia (BPH)", "Digital rectal examination", "Physical exercise on a bike", "Obesity", "Urinary catheterisation", "Prostatitis"], 4,
    "PSA can be raised by activities which stimulate the prostate such as ejaculation, riding a bike, digital rectal examination and urinary catheterisation, and by conditions such as prostate cancer, BPH, prostatitis and old age. Obesity doesn't affect the prostate."),
  Q("y2t18_p6", "y2t18", "Physiology & Biochem",
    "During the storage phase of micturition, which of the following statements is correct regarding the relaxation of the detrusor muscle?",
    ["Acetylcholine is released from the parasympathetic fibres (S2-S4), binding to the M3-receptors of the bladder.", "Noradrenaline is released from the sympathetic fibres (T10-L2), binding to the β3-adrenoreceptors of the bladder.", "Acetylcholine is released from the sympathetic fibres (T10-L2), binding to the β3-adrenoreceptors of the bladder.", "Noradrenaline is released from the parasympathetic fibres (S2-S4), binding to the α1-receptors of the bladder.", "Acetylcholine is released from the pudendal nerve (S2-S4), binding to the α1-receptors of the bladder."], 1,
    "During storage, noradrenaline is released from the sympathetic fibres (T10-L2) of the hypogastric nerve, binding to β3-adrenoreceptors (detrusor relaxation) and α1-receptors (internal sphincter contraction). During voiding, acetylcholine from parasympathetic fibres (S2-S4) via the pelvic nerve binds to M3 receptors, causing detrusor contraction."),
  Q("y2t18_p7", "y2t18", "Clinical & Pharmacology",
    "A 72-year-old male presents with Lower Urinary Tract Symptoms that suggest BPH. Which of the following features would indicate a more likely diagnosis of prostate cancer?",
    ["Poor urinary stream", "Nocturia", "Increased urinary frequency", "Firm, asymmetrical prostate on digital rectal examination (DRE)", "Mildly elevated PSA"], 3,
    "In BPH, the prostate feels smooth, soft, and symmetrically enlarged, with a maintained central sulcus. In prostate cancer, the prostate feels hard and irregular. Poor urinary stream, nocturia and increased urinary frequency can occur in both, and PSA can be raised in both (the PSA test is not very specific)."),
  Q("y2t18_p8", "y2t18", "Clinical & Pharmacology",
    "A 67-year-old patient presents with 6 months of nocturia, hesitancy and a sensation of being unable to empty his bladder. On examination, his prostate is smooth and symmetrically enlarged, with a maintained central sulcus. Which of the following is his most likely diagnosis?",
    ["Prostate Cancer", "Prostatitis", "Benign Prostatic Hyperplasia", "Bladder Stone", "Bladder Cancer"], 2,
    "BPH is the most likely diagnosis: on DRE the prostate feels smooth and symmetrically enlarged. In prostate cancer it would feel firm and irregular; in prostatitis tender and swollen. BPH commonly presents with incomplete bladder emptying due to urethral compression. Bladder stones classically present with pain and haematuria."),
  Q("y2t18_p9", "y2t18", "Clinical & Pharmacology",
    "Which of the following organisms is most commonly associated with acute bacterial prostatitis in otherwise healthy men?",
    ["Escherichia coli", "Staphylococcus aureus", "Chlamydia trachomatis", "Pseudomonas aeruginosa", "Neisseria gonorrhoeae"], 0,
    "In acute bacterial prostatitis in otherwise healthy men, the most common causative organism is E. coli, a gram-negative bacillus. It ascends the urethra from the gut and infects the prostate."),
  Q("y2t18_p10", "y2t18", "Clinical & Pharmacology",
    "A 70-year-old man is diagnosed with localised prostate cancer. He has a PSA of 11 ng/ml, a Gleason score of 3+4=7 (Grade Group 2), and his tumour is staged as T2b. Using the Cambridge Prognostic Group system, which of the following is the most appropriate risk group?",
    ["CPG 1", "CPG 2", "CPG 3", "CPG 4", "CPG 5"], 2,
    "With a Gleason score of 3+4=7 (grade group 2), PSA between 10 and 20 ng/ml, and clinical stage T2b, this prostate cancer is CPG 3, an intermediate to high risk category, warranting definitive treatment instead of active surveillance."),
  Q("y2t18_p11", "y2t18", "Clinical & Pharmacology",
    "What is the first-line investigation for suspected localised prostate cancer?",
    ["PSA test", "CT scan of abdomen and pelvis", "Bone Scan", "Transrectal ultrasound of the prostate", "Multiparametric MRI"], 4,
    "A multiparametric MRI is the first-line investigation for suspected localised prostate cancer to localise any lesions prior to biopsy. The PSA test is the initial blood test, not imaging. TRUS is sometimes used to guide biopsies."),
  Q("y2t18_ph3", "y2t18", "Clinical & Pharmacology",
    "Which of the following best describes the age-related hormonal changes that are targeted by finasteride in the treatment of benign prostatic hyperplasia?",
    ["Increased aromatase activity converting testosterone to oestrogen", "Increased 5α-reductase activity converting testosterone to dihydrotestosterone despite falling testosterone levels", "Decreased dihydrotestosterone production due to reduced androgen receptor sensitivity", "Increased testosterone production leading to prostate enlargement", "Increased luteinising hormone secretion causing prostate hypertrophy"], 1,
    "After the age of 30, men produce about 1% less testosterone per year, but 5α-reductase activity increases with age, converting testosterone into DHT, so DHT levels can rise despite falling testosterone. Prostate cells respond to increased DHT by living longer and multiplying (the cause of BPH). Finasteride is a 5α-reductase inhibitor which shrinks the prostate."),
  Q("y2t18_ph4", "y2t18", "Clinical & Pharmacology",
    "A 65-year-old male is prescribed medication for his BPH. Which of the following drugs is most likely to have been prescribed if he only notices an improvement in his symptoms after 3-6 months?",
    ["Tamsulosin", "Oxybutynin", "Sildenafil", "Tolterodine", "Finasteride"], 4,
    "Finasteride is a 5α-reductase inhibitor which reduces DHT and gradually shrinks the prostate, so improvement is typically seen after 3-6 months. Tamsulosin works in days to weeks as an α1-antagonist relaxing smooth muscle in the bladder neck, prostate and urethra."),
  Q("y2t18_ph5", "y2t18", "Clinical & Pharmacology",
    "A 71-year-old man presents with worsening lower urinary tract symptoms. He is subsequently diagnosed with BPH and started on a medication that improves his symptoms by relaxing smooth muscle in the prostate and neck of the bladder. Three weeks later, he reports dizziness on standing, which he suspects is due to the new medication. Which of the following was most likely the drug he was prescribed?",
    ["Finasteride", "Tamsulosin", "Ciprofloxacin", "Trimethoprim", "Leuprolide"], 1,
    "Tamsulosin is an α1-antagonist which relaxes smooth muscle in the neck of the bladder, prostate and urethra. Common side effects include orthostatic hypotension and dizziness."),
);
