// questions/y2t12.jsx, Year 2 Theme 12: Stomach (legacy bank, ISOCMEDED).
// Diagram-dependent questions (Anatomy 1–3) and two multi-answer questions (P&P 2, 9) are omitted.
window.QUESTIONS.push(
  Q("y2t12_a4", "y2t12", "Anatomy",
    "Which of the following arteries supply blood to the oesophagus?",
    ["Left inferior phrenic artery", "Right gastric artery", "Left gastric artery", "Splenic artery", "Gastroduodenal artery"], 2,
    "The oesophagus receives arterial supply from the inferior thyroid artery, branches of the aorta, left gastric artery and inferior phrenic arteries."),
  Q("y2t12_a5", "y2t12", "Anatomy",
    "Umee, a 36 year old female, has been diagnosed with an anterior duodenal ulcer following endoscopy. Which of the following anatomical structures may be at risk of erosion?",
    ["Right gastro-omental artery", "Gastroduodenal artery", "Peritoneal cavity", "Posterior superior pancreaticoduodenal artery", "Left gastric artery"], 2,
    "Following an anterior duodenal ulcer, due to its anatomical location, there is a risk of erosion into the peritoneal cavity. This can lead to peritonitis. On the other hand, following a posterior duodenal ulcer the gastroduodenal artery is at risk of erosion."),
  Q("y2t12_a6", "y2t12", "Anatomy",
    "The right gastric artery is a branch from which artery?",
    ["Coeliac trunk", "Hepatic artery proper", "Superior mesenteric artery", "Splenic artery", "Gastroduodenal artery"], 1,
    "The right gastric artery is a branch of the hepatic artery proper."),
  Q("y2t12_p1", "y2t12", "Clinical & Pharmacology",
    "Shani, a 36 year old patient is diagnosed with peptic ulcer disease. Which of the following symptoms is she least likely to have?",
    ["Abdominal pain", "Heartburn", "Dysphagia", "Dyspepsia", "Nausea"], 2,
    "Dysphagia describes the difficulty/inability to swallow. This is not a common symptom in peptic ulcer disease. It is more closely associated with oesophageal pathologies such as achalasia and oesophageal cancer."),
  Q("y2t12_p3", "y2t12", "Clinical & Pharmacology",
    "Which of the following symptoms is NOT indicative of an upper GI bleed?",
    ["Coffee ground vomiting", "Black, tarry stools", "Epigastric pain", "Haemoptysis", "Dyspepsia"], 3,
    "Haemoptysis is the coughing of blood from the respiratory tract, due to respiratory pathology such as pulmonary embolism or lung cancer, not the GI system. Symptoms of an upper GI bleed include haematemesis, melaena (black, tarry stools), dyspepsia, epigastric pain, coffee ground vomiting and signs of iron-deficiency anaemia."),
  Q("y2t12_p4", "y2t12", "Clinical & Pharmacology",
    "For an individual with suspected gastric malignancy, which investigation will you prioritise carrying out first?",
    ["Stool antigen test", "Upper GI endoscopy with biopsy", "Urea breath test", "MRI scan", "Barium swallow test"], 1,
    "Upper GI endoscopy involves inserting a camera down the GI tract to image the lining, with biopsy taken at the same time for histological analysis. This is the only definitive diagnosis for suspected malignancy."),
  Q("y2t12_p5", "y2t12", "Clinical & Pharmacology",
    "Which of the following is a histamine-2 receptor antagonist?",
    ["Omeprazole", "Famotidine", "Gaviscon", "Naloxone", "Theophylline"], 1,
    "Famotidine is a histamine-2 receptor antagonist. It reduces gastric acid secretion by competitively inhibiting the H2 receptors directly on parietal cells in the stomach."),
  Q("y2t12_p6", "y2t12", "Clinical & Pharmacology",
    "Following a stool antigen test conducted at the GP, a 45 year old patient has tested positive for H.pylori. The GP doctor is about to commence her on medications. Her allergies are only penicillin. Which of the following treatment plans would be most effective for managing this patient?",
    ["Famotidine (1x daily), Clarithromycin (1x daily), Amoxicillin (1x daily)", "Clarithromycin (1x daily), Amoxicillin (2x daily), Omeprazole (2x daily)", "Clarithromycin (2x daily), Metronidazole (2x daily), Omeprazole (2x daily)", "Famotidine (2x daily), Clarithromycin (2x daily), Metronidazole (2x daily)", "Clarithromycin (1x daily), Metronidazole (1x daily), Omeprazole (1x daily)"], 2,
    "Following a positive H.pylori test, the patient should be started on 'triple therapy': clarithromycin, amoxicillin and a PPI, all twice daily for 7 days. Since she is allergic to penicillin, amoxicillin is replaced with metronidazole: Clarithromycin (2x daily), Metronidazole (2x daily), Omeprazole (2x daily)."),
  Q("y2t12_p7", "y2t12", "Clinical & Pharmacology",
    "Proton Pump Inhibitors (PPIs) reduce gastric acid secretion by which mechanism?",
    ["Inhibiting gastrin receptors", "Inhibiting the H+/K+ ATPase pump", "Inhibiting H2 receptors", "Inhibiting the release of somatostatin", "Inhibiting the release of secretin"], 1,
    "PPIs irreversibly inhibit the H+/K+ ATPase pump. This prevents the transportation of H+ ions into the stomach lumen, thus restricting the binding with Cl- ions to form HCl."),
  Q("y2t12_p8", "y2t12", "Clinical & Pharmacology",
    "When should PPIs be taken ideally?",
    ["At meal time", "Before meals", "In the morning", "Before you sleep"], 1,
    "PPIs should be taken 30 mins before meals. This will help prevent acid regurgitation and heartburn whilst eating. Taking with meals can delay absorption and prevent the levels reaching maximum concentration."),
  Q("y2t12_p10", "y2t12", "Physiology & Biochem",
    "Goblet cells secrete which of the following mucins?",
    ["MUC2", "MUC6", "MUC19", "MUC3", "MUC5AC"], 0,
    "Goblet cells secrete mucins MUC2 (in the intestines) and MUC5AC (in the respiratory tract). MUC2 is much more common and characteristic of goblet cell secretion."),
  Q("y2t12_p11", "y2t12", "Physiology & Biochem",
    "Brunner's glands of the duodenum secrete which of the following mucins?",
    ["MUC2", "MUC6", "MUC19", "MUC3", "MUC5AC"], 1,
    "MUC6 is secreted by the Brunner's glands of the duodenum."),
  Q("y2t12_p12", "y2t12", "Physiology & Biochem",
    "Which of the following hormones stimulates the pancreas to secrete bicarbonate ions?",
    ["GLP-1", "Somatostatin", "Secretin", "CCK", "Gastrin"], 2,
    "Secretin is secreted from the S cells of the duodenum. It is released when acidity levels rise, hence it stimulates the pancreas to release bicarbonate ions HCO3- to neutralise the acid."),
  Q("y2t12_p13", "y2t12", "Physiology & Biochem",
    "Which of the following hormones stimulates the contraction of the gallbladder?",
    ["GLP-1", "Somatostatin", "Secretin", "CCK", "Gastrin"], 3,
    "Cholecystokinin (CCK) is secreted by the I cells of the duodenum and jejunum when fats are present. It stimulates the gallbladder to contract, enabling more bile to enter the duodenum to emulsify fats. It also stimulates the pancreas to secrete digestive enzymes and inhibits gastric emptying."),
);
