// questions/y2t17.jsx, Year 2 Theme 17: Kidney (legacy bank, ISOCMEDED).
// Diagram questions (Anatomy 1–3) and the multi-answer vasodilator question (P&B 2) are omitted.
window.QUESTIONS.push(
  Q("y2t17_a4", "y2t17", "Anatomy",
    "Which vertebral level does the aorta give rise to the renal arteries?",
    ["T10-T12", "L1-L2", "L2-L4", "L1-L3", "L4-L5"], 1,
    "The renal artery arises from the aorta at the vertebral level of L1-L2 approximately."),
  Q("y2t17_a5", "y2t17", "Anatomy",
    "After travelling through the peritubular capillaries in the kidney, where does the blood travel through next?",
    ["Vasa Recta", "Interlobular Vein", "Glomerulus", "Afferent arteriole", "Efferent arteriole"], 0,
    "Blood flows from the peritubular capillaries into the vasa recta, and then finally the interlobular veins."),
  Q("y2t17_a6", "y2t17", "Anatomy",
    "A patient experiences pain from the flank to the groin due to kidney injury. Which dermatomes have been affected resulting in this pain?",
    ["L1-L4", "T8-T12", "T10-T12", "T10-L1", "T12-L2"], 3,
    "Pain from the kidney is transmitted to sympathetic fibres at the level of T10-L1, which means the dermatomes of T10-L1 are affected. This results in the characteristic flank to groin pain."),
  Q("y2t17_a7", "y2t17", "Anatomy",
    "A patient complains of fatigue, muscle wasting, fragile skin and purple lines across her stomach. Investigations show these symptoms are related to renal function. Which aspect of the renal system has been impacted?",
    ["Medulla", "Cortex", "Urethra", "Glomerulus", "Bowman's capsule"], 1,
    "The (suprarenal) cortex contains cells which secrete glucocorticoids. Having too much glucocorticoid within the body can lead to the symptoms experienced by this patient, which are in line with Cushing's Syndrome."),
  Q("y2t17_a8", "y2t17", "Anatomy",
    "During the course of the ureter, it is narrowed at 3 different sites, one of these sites is the pelvic brim. Name the artery which bifurcates as the ureter crosses the pelvic brim?",
    ["Internal iliac artery", "Abdominal aorta", "Femoral artery", "Common iliac artery", "External iliac artery"], 3,
    "The ureter crosses anterior to the common iliac artery, and is narrowed at around the same point at which the common iliac artery bifurcates into the external and internal iliac arteries."),
  Q("y2t17_a9", "y2t17", "Anatomy",
    "A patient suffering from hypoxia is found to have elevated levels of a hormone that is produced within the renal system, in order to compensate for this hypoxia. Where is this hormone produced?",
    ["Collecting duct", "Renal Pelvis", "Medulla", "Ureter", "Renal Cortex"], 4,
    "The hormone erythropoietin is produced in the cortex, and it helps with red blood cell production. In patients suffering from hypoxia (e.g. at high altitudes) the body compensates by increasing erythropoietin levels, increasing the number of red blood cells."),
  Q("y2t17_h1", "y2t17", "Anatomy",
    "How can Vasa Recta be identified on a histological slide?",
    ["Presence of cuboidal epithelium", "Red blood cells present in the lumen", "Presence of low columnar epithelium", "Presence of a brush border", "Presence of a very large lumen"], 1,
    "Vasa recta are very small blood vessels, therefore they will have red blood cells present within a small, round lumen. They have a simple squamous endothelial lining, resulting in thin-looking walls."),
  Q("y2t17_h2", "y2t17", "Anatomy",
    "What is the name of the layer of cells that contribute to the impermeability of the ureters to water?",
    ["Cuboidal Cells", "Columnar Cells", "Umbrella cells", "Juxtaglomerular cells", "Podocytes"], 2,
    "Umbrella cells are ovoid in shape, and are found in the surface layer of the transitional epithelium of the ureters. They ensure that water does not leave the ureters."),
  Q("y2t17_h3", "y2t17", "Anatomy",
    "Which specific structure within the renal system contains chromaffin cells, and what do these cells do?",
    ["Collecting duct; Secrete catecholamines into the blood", "Cortex; Secrete mineralocorticoids into the blood", "Proximal Convoluted Tubule; Control glucose reabsorption", "Medulla; Secrete catecholamines into the blood", "Ureter; Secrete mineralocorticoids into the blood"], 3,
    "Chromaffin cells are found within the medulla of the suprarenal gland. They secrete catecholamines such as noradrenaline and adrenaline under sympathetic stimulation."),
  Q("y2t17_h4", "y2t17", "Anatomy",
    "What cell structure in the loop of Henle detects NaCl concentration?",
    ["Macula densa", "Podocytes", "Juxtaglomerular", "Intercalated cells", "Principal cells"], 0,
    "Macula densa cells are specialised columnar epithelial cells in the distal convoluted tubule that act as chemoreceptors to monitor salt (NaCl) concentration and adjust blood pressure accordingly."),
  Q("y2t17_h5", "y2t17", "Anatomy",
    "What is a characteristic feature of the PCT (proximal convoluted tubule)?",
    ["Lined by squamous epithelium", "No microvilli", "Large, defined lumen", "Lined by stratified epithelium", "Dense brush border"], 4,
    "The PCT has a dense brush border with many microvilli to increase the surface area and allow for rapid reabsorption of water and ions."),
  Q("y2t17_h6", "y2t17", "Anatomy",
    "What causes a 'fuzzy lumen' microscopic appearance in the PCT?",
    ["Tight junctions", "Intercalated cells", "Cilia", "Microvilli", "Podocytes"], 3,
    "The microvilli creating a dense brush border have actin-filled extensions which project into the lumen of the PCT for absorption enhancement, therefore creating a fuzzy appearance under a microscope."),
  Q("y2t17_p1", "y2t17", "Physiology & Biochem",
    "Daniel, a 35 year old, is climbing K2 mountain. In response to hypoxia at high altitudes, which hormone is secreted by the kidney?",
    ["Parathyroid hormone (PTH)", "Erythropoietin", "Renin", "Calcitriol", "Aldosterone"], 1,
    "In response to hypoxia (low O2 levels), the kidney's peritubular cells secrete erythropoietin (EPO) to stimulate the production of more red blood cells. This will improve oxygen-carrying capacity."),
  Q("y2t17_p3", "y2t17", "Physiology & Biochem",
    "Which ion channel enables passive Na+ influx in the late distal convoluted tubule (DCT) and collecting ducts?",
    ["H/K+ ATPase", "ENaC", "SGLT1", "SGLT2", "NHE3"], 1,
    "In the late DCT and collecting duct, the ENaC (Epithelial Sodium Channel) enables passive Na+ influx. This is regulated by aldosterone which increases ENaC expression and thus increases Na+ reabsorption. NHE3 is the Na+/H+ exchanger in the PCT whilst the SGLT channels are the Na+-glucose cotransporters in the PCT."),
  Q("y2t17_p4", "y2t17", "Clinical & Pharmacology",
    "Chronic kidney disease (CKD) is defined by which criteria?",
    ["eGFR <60 for more than 3 months", "eGFR <90 for more than 3 months", "eGFR <45 for more than 6 months", "eGFR <60 for more than 6 months", "eGFR <45 for more than 3 months"], 0,
    "An eGFR <60 ml/min/1.73m2 for more than 3 months defines CKD. Other factors such as raised creatinine and albumin can also be useful markers. A normal eGFR is greater than 90."),
  Q("y2t17_p5", "y2t17", "Physiology & Biochem",
    "What is released by the macula densa when there is a decrease in arterial pressure?",
    ["Adrenaline", "Serotonin", "Dopamine", "Prostaglandin E2", "Aldosterone"], 3,
    "The macula densa senses a decrease in flow and releases prostaglandin E2 to stimulate renin release. This activates the RAAS system and causes constriction of efferent arterioles to ultimately raise pressure."),
  Q("y2t17_p6", "y2t17", "Physiology & Biochem",
    "What glucose transporter is found on the basolateral membrane of cells?",
    ["ROM-K", "GLUT1", "SGLT-2", "ENaC", "NHE-3"], 1,
    "GLUT-1 is found on the basolateral membrane of the late proximal tubule to transport glucose out of the cell and into the blood."),
  Q("y2t17_p7", "y2t17", "Physiology & Biochem",
    "What is the main trigger of ADH release?",
    ["Decreased plasma osmolality", "Increased plasma osmolality", "High blood pressure", "Cold exposure", "Alcohol consumption"], 1,
    "High plasma osmolality (high salt concentration and low water concentration) is detected by osmoreceptors in the hypothalamus and triggers ADH release from the posterior pituitary. ADH increases water reabsorption and raises blood pressure."),
  Q("y2t17_p8", "y2t17", "Physiology & Biochem",
    "An increase in systemic arterial pressure leads to an initial rise in glomerular filtration rate. What change occurs in the early distal tubule as a direct consequence?",
    ["Increased NaCl concentration", "Decreased hydrostatic pressure", "Reduced urea reabsorption", "Increased water permeability", "Decreased potassium secretion"], 0,
    "More filtrate = faster flow = less NaCl reabsorbed in the PCT, so NaCl concentration in the early distal tubule increases."),
  Q("y2t17_p9", "y2t17", "Physiology & Biochem",
    "As renal arterial pressure increases, what is the response of the afferent and efferent arterioles?",
    ["Afferent constricts, efferent constricts", "Afferent dilates, efferent constricts", "Afferent constricts, efferent unchanged", "Afferent unchanged, efferent constricts", "Afferent dilates, efferent dilates"], 2,
    "The afferent arteriole constricts (increased resistance), helping to stabilise GFR, the myogenic reflex."),
  Q("y2t17_p10", "y2t17", "Physiology & Biochem",
    "A patient develops a urinary tract obstruction that increases hydrostatic pressure in Bowman's capsule. What is the most likely effect on glomerular filtration rate?",
    ["Increases filtration", "No change in filtration", "Increases filtration after efferent constriction", "Decreases filtration", "Increases filtration after sympathetic stimulation"], 3,
    "A urinary tract obstruction backs up urine, raising Bowman's capsule hydrostatic pressure. This opposes glomerular hydrostatic pressure and decreases filtration."),
  Q("y2t17_p11", "y2t17", "Physiology & Biochem",
    "In the loop of Henlé, the ascending and descending limbs differ in that:",
    ["The descending limb is permeable to NaCl and impermeable to water", "The ascending limb allows water reabsorption but not ion transport", "The descending limb is impermeable to both water and solutes", "The ascending limb is impermeable to water but reabsorbs NaCl", "The descending limb facilitates sodium reabsorption via active transport"], 3,
    "The descending limb is permeable to water but not solutes, whilst the ascending limb is impermeable to water but actively reabsorbs NaCl, the basis of the countercurrent multiplier."),
  Q("y2t17_p12", "y2t17", "Physiology & Biochem",
    "Water reabsorption in response to ADH occurs as:",
    ["Water enters through AQP1 and exits through AQP3", "Water enters through AQP3 and exits through AQP4", "Water enters through AQP2 and exits through AQP3 and AQP4", "Water enters through AQP4 and exits through AQP1 and AQP2", "Water enters through AQP2 and exits through AQP1"], 2,
    "ADH stimulates insertion of AQP2 channels into the apical membrane of collecting duct cells, water enters through AQP2 and exits into the blood through basolateral AQP3 and AQP4."),
  Q("y2t17_p13", "y2t17", "Physiology & Biochem",
    "Reabsorption of filtered bicarbonate in the proximal tubule involves:",
    ["Direct apical uptake of HCO₃⁻ via a symporter", "Conversion of HCO₃⁻ to CO₂ and H₂O by CA IV, followed by intracellular regeneration via CA II", "Active transport of bicarbonate through ENaC channels", "Binding of bicarbonate to albumin for facilitated diffusion", "Oxidation of bicarbonate to carbonic acid and passive reabsorption"], 1,
    "Filtered HCO₃⁻ combines with secreted H+ and is converted to CO₂ and H₂O by carbonic anhydrase IV on the brush border. CO₂ diffuses into the cell where carbonic anhydrase II regenerates HCO₃⁻, which is reabsorbed basolaterally."),
  Q("y2t17_ph1", "y2t17", "Clinical & Pharmacology",
    "A patient suffers from hypokalemia due to an excess dose of chlorothiazide. The doctor assesses an effective response to the situation. Which medication would most likely be given in response to this?",
    ["Bumetanide", "Furosemide", "Spironolactone", "Indapamide", "Metolazone"], 2,
    "Spironolactone is a potassium-sparing diuretic, an aldosterone antagonist. It inhibits sodium and water reabsorption whilst preserving potassium. It is commonly given alongside a loop or thiazide diuretic to prevent hypokalemia. The other options are all loop or thiazide diuretics which cause potassium loss and would exacerbate the hypokalemia."),
  Q("y2t17_ph2", "y2t17", "Clinical & Pharmacology",
    "Angiotensin-Converting Enzyme (ACE) inhibitors can cause a dry cough as a side-effect of the medication. What is the primary reason for this?",
    ["Inhibition of the breakdown of prostacyclin", "Inhibition of the breakdown of thromboxane-A2", "Inhibition of the breakdown of bradykinin", "Stimulation of the breakdown of thromboxane-A2", "Stimulation of the breakdown of bradykinin"], 2,
    "ACE inhibitors, such as ramipril, inhibit the breakdown of bradykinin, as well as substance P. This results in elevated levels of these vasodilators and inflammatory mediators, contributing to the cough reflex."),
  Q("y2t17_ph3", "y2t17", "Clinical & Pharmacology",
    "A patient with heart failure is started on a loop diuretic. Which electrolyte abnormality is most commonly associated with long-term use of this medication?",
    ["Hyperkalaemia", "Hypernatraemia", "Hypocalcaemia", "Hypokalaemia", "Hypermagnesaemia"], 3,
    "Loop diuretics inhibit the Na+/K+/2Cl- cotransporter, increasing distal sodium delivery and potassium excretion, hypokalaemia is the classic long-term electrolyte abnormality."),
  Q("y2t17_ph4", "y2t17", "Clinical & Pharmacology",
    "A 68-year-old man with hypertension and proteinuria is started on an ACE inhibitor. What is the primary renal benefit of this medication in the context of proteinuria?",
    ["Increases GFR by dilating the afferent arteriole", "Reduces intraglomerular pressure by dilating the efferent arteriole", "Blocks aldosterone synthesis in the adrenal cortex", "Promotes sodium excretion via ENaC inhibition", "Increases renin secretion from juxtaglomerular cells"], 1,
    "ACE inhibitors reduce angiotensin II, which normally constricts the efferent arteriole. Efferent dilation lowers intraglomerular pressure, reducing protein leak across the glomerulus."),
  Q("y2t17_ph5", "y2t17", "Clinical & Pharmacology",
    "A patient is prescribed a thiazide diuretic for hypertension. At which segment of the nephron does this medication act?",
    ["Thick ascending limb of the loop of Henle", "Proximal convoluted tubule", "Early distal convoluted tubule", "Collecting duct", "Bowman's capsule"], 2,
    "Thiazide diuretics inhibit the Na⁺/Cl⁻ co-transporter in the distal convoluted tubule (DCT). This leads to increased sodium and water excretion, reducing blood volume and lowering blood pressure."),
  Q("y2t17_ph6", "y2t17", "Clinical & Pharmacology",
    "What is the mechanism of action of furosemide?",
    ["Inhibits the Na/Cl- co transporter in DCT", "Aldosterone receptor antagonist in the collecting duct", "Blocks epithelial Na+ channels in the collecting duct", "Inhibits angiotensin-converting enzyme", "Inhibits the Na+/K+/2Cl- co transporter in the thick ascending limb"], 4,
    "Furosemide is a loop diuretic that acts on the ascending limb of the Loop of Henle to inhibit reabsorption of sodium, potassium and chloride ions, therefore reducing fluid overload."),
  Q("y2t17_ph7", "y2t17", "Clinical & Pharmacology",
    "What is a key potential side effect of spironolactone?",
    ["Ototoxicity", "Hypocalcaemia", "Hypokalaemia", "Hyperkalaemia", "Hyperuricaemia"], 3,
    "Spironolactone is an aldosterone antagonist, so it stops the action of aldosterone. This means less potassium is excreted and more potassium builds up in the blood, causing hyperkalaemia."),
  Q("y2t17_ph8", "y2t17", "Clinical & Pharmacology",
    "What class of anti-hypertensive medication would most likely worsen an AKI?",
    ["ACE inhibitors", "Sulfonylureas", "Beta blockers", "Calcium channel blockers", "GLP-1 agonists"], 0,
    "Giving an ACE inhibitor will decrease angiotensin II which causes dilation of the efferent arteriole. This decreases glomerular pressure and subsequently decreases GFR which will worsen an AKI."),
  Q("y2t17_e1", "y2t17", "Ethics & EBM",
    "A 16-year-old patient with end-stage renal disease requires a living donor kidney transplant. Their parent wishes to donate. Which of the following best describes the ethical requirement in this situation?",
    ["The parent's consent alone is sufficient as the legal guardian", "Consent is implied given the familial relationship", "The parent must provide fully informed, voluntary consent independent of any pressure, and their capacity must be assessed", "The transplant can proceed without formal consent if deemed clinically necessary", "Consent from the MDT overrides the need for donor consent"], 2,
    "The parent is required to have capacity and give fully informed consent. This decision should be voluntary, and not from external pressure. An independent assessment may be used to ensure this."),
  Q("y2t17_e2", "y2t17", "Ethics & EBM",
    "Which of the following is required for a kidney transplant?",
    ["Implied consent from the family if the patient is unconscious", "Consent from the transplant surgeon", "Consent is not required if it will be life saving", "Explicitly informed consent from the donor", "Consent from the MDT in charge of care"], 3,
    "UK law requires informed, explicit consent from living donors before transplantation, Human Tissue Act 2004."),
);
