// questions/y2t1.jsx, Year 2 Theme 1: Neuroembryology (legacy bank, ISOCMEDED).
// Diagram-dependent questions from the PDF (Anatomy 1, 2, 3, 5, 7) are omitted.
window.QUESTIONS.push(
  Q("y2t1_a4", "y2t1", "Anatomy",
    "Which of the following bone pairings is correct?",
    ["Palatine bone: Viscerocranium, Paired", "Frontal bone: Viscerocranium, Unpaired", "Nasal bone: Neurocranium, Paired", "Inferior Nasal Conchae: Neurocranium, Paired", "Occipital bone: Neurocranium, Unpaired"], 0,
    "The palatine bones are viscerocranium and paired. The frontal is neurocranium and unpaired, the nasal is viscerocranium and paired, the inferior nasal conchae are viscerocranium and paired, and the occipital is neurocranium and unpaired."),
  Q("y2t1_a6", "y2t1", "Anatomy",
    "Abdul, a 27 year old man, presents to the emergency department after being punched in the jaw during a fight. He reports pain and limited movement when opening his mouth. On examination, there is tenderness anteriorly to the external auditory meatus and deviation of the mandible when opening. Imaging reveals anterior dislocation of the temporomandibular joint (TMJ). Which of the following structures of the skull form the superior articulating surfaces of the TMJ?",
    ["Mandibular fossa and external acoustic meatus of the temporal bone", "Articular tubercle and styloid process of the temporal bone", "Mandibular notch and mandibular fossa of the temporal bone", "Articular tubercle and mastoid process of the temporal bone", "Mandibular fossa and articular tubercle of the temporal bone"], 4,
    "The superior articulating surfaces of the TMJ are the mandibular fossa and the articular tubercle of the temporal bone. The other options are real anatomical landmarks but they do not form the articulating surfaces of the joint."),
  Q("y2t1_a8", "y2t1", "Anatomy",
    "Paul, a 32-year-old man, is brought to the emergency department after a road traffic collision. CT imaging reveals a fracture at the pterion with a small associated epidural haematoma. The consultant explains to the medical students that not only the artery, but also accompanying veins in this region can be injured, which normally pass through the foramen spinosum. Into which venous structure do the middle meningeal veins drain?",
    ["Pterygoid plexus", "Cavernous sinus", "Superior sagittal sinus", "Inferior sagittal sinus", "Confluence of sinuses"], 0,
    "The middle meningeal veins accompany the middle meningeal arteries, exit the skull via the foramen spinosum, and drain into the pterygoid plexus. The cavernous sinus, superior sagittal sinus, and inferior petrosal sinus are other venous channels but they're not the direct drainage site of the veins mentioned in the question stem."),
  Q("y2t1_a9", "y2t1", "Anatomy",
    "A 55-year-old smoker presents with dizziness, vertigo, and diplopia suggestive of posterior circulation ischaemia. CT angiography reveals narrowing of the vertebral arteries. The registrar asks the students: From which artery do the vertebral arteries typically arise?",
    ["Internal carotid artery", "External carotid artery", "Brachiocephalic trunk", "Subclavian artery", "Common carotid artery"], 3,
    "The vertebral arteries are paired branches of the subclavian arteries. They ascend through the transverse foramina of the cervical vertebrae before entering the cranial cavity."),
  Q("y2t1_e1", "y2t1", "Physiology & Biochem",
    "During the embryonic development of the brain, the myelencephalon gives rise to which of the following?",
    ["Pons", "Midbrain", "Medulla oblongata", "Cerebrum", "Thalamus"], 2,
    "The medulla oblongata is derived from the myelencephalon during the embryonic development of the brain."),
  Q("y2t1_e2", "y2t1", "Physiology & Biochem",
    "Which of the following cells are derived from the dorsal pathway after migration from the neural plate?",
    ["Autonomic ganglia", "Melanocytes", "Schwann cells", "Glial cells", "Chromaffin cells"], 1,
    "Melanocytes arise from the dorsal pathway. Whilst the ventral pathway gives rise to autonomic ganglia, schwann cells, glial cells, chromaffin cells and more."),
  Q("y2t1_e3", "y2t1", "Physiology & Biochem",
    "Which of the following medications should be avoided during pregnancy?",
    ["Inositol", "Folic acid", "Sodium valproate", "Heparin", "Acetaminophen"], 2,
    "Sodium valproate is a major teratogen. This means it has a likelihood of causing neural tube defects during pregnancy."),
  Q("y2t1_e4", "y2t1", "Physiology & Biochem",
    "Ginny, a 35 year old female, is expecting a baby. The doctors suggest amniocentesis which involves the insertion of a needle into the amniotic sac to extract fluid. This is to check for a potential neural tube defect. Elevated levels of which substance(s) may indicate an open NTD?",
    ["AST and ALT", "Alpha-fetoprotein (AFP) and acetylcholinesterase (AChE)", "Alkaline phosphatase (ALP)", "Alpha-fetoprotein (AFP)", "LDH"], 1,
    "Alpha-fetoprotein (AFP) and acetylcholinesterase (AChE) together both provide a strong indication of an open NTD. Both are first-line markers, though AFP is less specific since can also be elevated in abdominal wall defects. AChE, however, is the most specific since it originates from foetal neural tissue. A foetal ultrasound should also be carried out in order to confirm the diagnosis."),
  Q("y2t1_e5", "y2t1", "Physiology & Biochem",
    "Fiona, a 37 year old female, has diabetes and is labelled as 'high risk' due to her age and her pre-existing diabetes. What is the recommended daily intake of folic acid for her?",
    ["400μg", "5mg", "100μg", "1mg", "10mg"], 1,
    "5mg/day is the recommended intake for Fiona since she has diabetes hence is labelled as high risk. This dosage is significantly higher than the general recommendation of 400μg/day normally. Folic acid prevents neural tube defects."),
  Q("y2t1_e6", "y2t1", "Physiology & Biochem",
    "Which of the following neuroimaging techniques enables us to assess the metabolic activity of the brain?",
    ["CT scan", "MRI scan", "PET scan", "X-ray", "EEG"], 2,
    "Positron Emission Tomography (PET) scans use radioactive tracers such as FDG-glucose to measure the brain's metabolic activity. This gives us different colours of varying intensity to help identify tumours and infections."),
  Q("y2t1_e7", "y2t1", "Physiology & Biochem",
    "Samuel, a 39 year old patient, arrives into the emergency department with a stroke. Which neuroimaging technique is most suitable to use here?",
    ["CT scan", "MRI scan", "PET scan", "X-ray", "EEG"], 0,
    "Computerised Tomography (CT) scans are typically used in emergencies since they are widely available and fast. MRI scans cannot be used since they will take longer and this stroke is an emergency. X-rays are poor at visualising soft tissues, such as in the brain, hence they are not used here."),
  Q("y2t1_e8", "y2t1", "Physiology & Biochem",
    "A newborn presents with a protruding sac on the lower back. Neurological examination reveals paralysis of the lower limbs and incontinence. Which of the following best describes this condition?",
    ["Spina bifida occulta", "Spina bifida aperta (myelomeningocele)", "Encephalocele", "Chiari I malformation", "Syringomyelia"], 1,
    "Spina bifida aperta has two forms: meningocele (meninges and CSF protrude, often minimal deficit) and myelomeningocele (meninges and spinal cord protrude, causing major deficits such as paralysis and incontinence). This case is most consistent with myelomeningocele. Spina bifida occulta usually has no sac and is often asymptomatic."),
  Q("y2t1_e9", "y2t1", "Physiology & Biochem",
    "During embryonic development, the anterior neuropore fails to close at day 25. This results in:",
    ["Spina bifida", "Encephalocele", "Down's Syndrome", "Craniorachischisis", "Anencephaly"], 4,
    "Failure of anterior neuropore closure results in anencephaly which is the absence of large portions of the brain and skull, which is incompatible with life. Posterior neuropore closure failure causes spina bifida."),
  Q("y2t1_e10", "y2t1", "Physiology & Biochem",
    "A pregnant woman undergoes ultrasound at 20 weeks. Her unborn son, Aubrey Graham, is noted to have flattening of the frontal bones and \"lemon sign\" is seen. This finding is most strongly associated with:",
    ["Open spina bifida", "Spina bifida occulta", "Encephalocele", "Craniorachischisis", "Holoprosencephaly"], 0,
    "The lemon sign describes inward scalloping of the frontal bones on ultrasound, strongly associated with open spina bifida and Chiari II malformations. It is not seen in occulta or encephaloceles."),
  Q("y2t1_e11", "y2t1", "Physiology & Biochem",
    "Hydrocephalus is found in nearly 50% of spina bifida cases. Which of the following mechanisms explains this association?",
    ["Failure of anterior neuropore closure", "Excess folic acid intake", "Cerebellar tonsils obstructing CSF flow (Chiari II malformation)", "Inositol deficiency", "Impaired neuronal migration"], 2,
    "In Chiari II malformation, the cerebellar tonsils herniate through the foramen magnum, blocking CSF flow and leading to hydrocephalus. Other listed options do not explain the high incidence of hydrocephalus."),
  Q("y2t1_e12", "y2t1", "Physiology & Biochem",
    "Which of the following tests is considered the gold standard for diagnosing neural tube defects?",
    ["Amniocentesis", "Maternal serum alpha-fetoprotein (MSAFP) test", "Early ultrasound at 11–14 weeks", "Ultrasound at 18–22 weeks", "Blood karyotyping"], 3,
    "Although maternal serum AFP can suggest NTDs, the definitive gold standard is mid-trimester ultrasound (18–22 weeks). It allows direct detection of cranial and spinal abnormalities, including lemon and banana signs."),
  Q("y2t1_e13", "y2t1", "Physiology & Biochem",
    "A soon-to-be mother is attending a GP appointment and is being advised by her doctor. A deficiency of which nutrient is most strongly linked to neural tube defects, requiring supplementation from 3 months before pregnancy until 3 months after conception?",
    ["Vitamin D", "Folate", "Vitamin A", "Iron", "Inositol"], 1,
    "Folate is essential for DNA synthesis and methylation during neurulation. Periconceptional folate supplementation significantly lowers the risk of NTDs and is the recommended preventive measure. Inositol has been implicated in NTD development but is not an established or universally recommended preventive therapy."),
  Q("y2t1_e14", "y2t1", "Physiology & Biochem",
    "A 3-day-old infant with spina bifida develops rapidly enlarging head circumference. Ophthalmic examination reveals downward-deviated eyes with the upper sclera visible (\"sun-setting eyes\"). This phenomenon occurs because?",
    ["Compression of the abducens nerve reduces lateral gaze", "Weight of the lens pulls the eyes downward under increased intracranial pressure", "Raised pressure compresses the oculomotor nerve, impairing upward gaze", "Impaired neuronal migration prevents supranuclear gaze control", "CSF leaks into the orbit, displacing the eyes inferiorly"], 2,
    "Sun-setting sign results from raised intracranial pressure compressing the oculomotor nerve, limiting upward gaze. It is a classic sign of hydrocephalus."),
  Q("y2t1_e15", "y2t1", "Physiology & Biochem",
    "A 32-year-old pregnant woman is referred for genetic counselling after her foetus is diagnosed with a neural tube defect. Which of the following is NOT a recognised cause of NTDs according to embryological mechanisms?",
    ["Genetic defect of medial hinge points", "Genetic defect of dorsal lateral hinge points", "Excess maternal folic acid supplementation", "Failure of posterior neuropore closure", "Reduced folate availability during neural proliferation"], 2,
    "Causes include failure of neuropore closure, hinge point defects, and folate deficiency. Excess folic acid is not a cause, if anything, folate supplementation is protective."),
  Q("y2t1_e16", "y2t1", "Physiology & Biochem",
    "A woman delivers a baby with spina bifida aperta. Despite successful closure of the spinal defect postnatally, the infant develops progressive hydrocephalus. The most likely explanation is:",
    ["Normal CSF drainage pathways failed to open after closure", "Excess production of CSF in the choroid plexus", "Reduced neuronal proliferation in the germinal matrix", "Secondary obstruction by periventricular heterotopias", "Low folate status at the time of surgery"], 0,
    "Even after surgical repair, hydrocephalus can progress because the CSF pathways (obstructed by Chiari II malformation) remain impaired. This is the most likely mechanism. Other options (e.g. choroid plexus overproduction, folate status) are not primary causes."),
);
