// questions/y2t14.jsx, Year 2 Theme 14: Colon (legacy bank, ISOCMEDED).
// Histology-image questions (A&H 4, 6) and the multi-answer hemicolectomy question (P&P 3) are omitted.
window.QUESTIONS.push(
  Q("y2t14_a1", "y2t14", "Anatomy",
    "Regarding the differences between the jejunum and ileum, which of the following statements is incorrect?",
    ["The jejunum has more densely packed plicae circulares compared to the ileum", "The jejunum is darker than the ileum", "The jejunum has more Peyer's patches compared to the ileum", "The jejunum has a thicker wall than the ileum", "The jejunum has longer vasa recta than the ileum"], 2,
    "Peyer's patches are unique to the ileum, where they are found in the greatest abundance. Whilst they may be found in the jejunum, they are distinguishably less in quantity. The jejunum has densely packed plicae circulares, a thicker wall, longer vasa recta, fewer arcades and is darker (red) in colour."),
  Q("y2t14_a2", "y2t14", "Anatomy",
    "Which of the following structures is NOT part of the foregut?",
    ["Jejunum", "Oesophagus", "Stomach", "Pancreas", "Liver"], 0,
    "The jejunum is considered part of the midgut since it is supplied by the superior mesenteric artery."),
  Q("y2t14_a3", "y2t14", "Anatomy",
    "Name the terminal branch of the inferior mesenteric artery.",
    ["Right colic artery", "Superior rectal artery", "Sigmoid artery", "Left colic artery", "Ileocolic artery"], 1,
    "The superior rectal artery is the terminal branch of the inferior mesenteric artery. This supplies the rectum."),
  Q("y2t14_a5", "y2t14", "Anatomy",
    "From the duodenum descending to the ileum, which of the following is correct?",
    ["Length of villi decreases, goblet cells increase, plicae circularis less prominent", "Length of villi decreases, goblet cells decrease, plicae circularis less prominent", "Length of villi decreases, goblet cells decrease, plicae circularis more prominent", "Length of villi increases, goblet cells increase, plicae circularis more prominent", "Length of villi increases, goblet cells increase, plicae circularis less prominent"], 0,
    "From the duodenum descending to the ileum: length of villi decreases, goblet cells increase (more mucus required due to dryness), and plicae circularis becomes less prominent."),
  Q("y2t14_a7", "y2t14", "Anatomy",
    "Which of the following does not originate from the superior mesenteric artery?",
    ["Right colic artery", "Left colic artery", "Middle colic artery"], 1,
    "The left colic artery originates from the inferior mesenteric artery."),
  Q("y2t14_a8", "y2t14", "Anatomy",
    "Which quadrant is the sigmoid colon located?",
    ["RUQ", "RLQ", "LUQ", "LLQ"], 3,
    "The sigmoid colon extends from the left iliac fossa to the S3 vertebral level, in the left lower quadrant."),
  Q("y2t14_a9", "y2t14", "Anatomy",
    "Which of the following has a thicker wall, increased vasculature and longer vasa recta?",
    ["Jejunum", "Ileum"], 0,
    "The jejunum has a thicker wall, increased vasculature and longer vasa recta. It also has a greater calibre and more densely packed plicae circularis."),
  Q("y2t14_a10", "y2t14", "Anatomy",
    "Where does B12 absorption take place?",
    ["Duodenum", "Jejunum", "Ileum", "Colon"], 2,
    "B12 absorption specifically only occurs in the terminal ileum."),
  Q("y2t14_a11", "y2t14", "Anatomy",
    "Which of the following describes the haustra of the large intestines?",
    ["Sacculations in the wall of the large intestine", "Small fat-filled sacs that project from the outer intestinal wall", "Folds on the internal walls of the large intestine"], 0,
    "Haustra are sacculations in the wall of the large intestine. The other options describe epiploic appendages and semilunar folds respectively."),
  Q("y2t14_a12", "y2t14", "Anatomy",
    "Is the ascending colon intraperitoneal or retroperitoneal?",
    ["Intraperitoneal", "Retroperitoneal"], 1,
    "Both the ascending and descending colons are retroperitoneal."),
  Q("y2t14_p1", "y2t14", "Physiology & Biochem",
    "What is the role of the tumour suppressor gene p53?",
    ["Synthesises the BRCA1 protein which is responsible for DNA repair", "Binds to CDK4 to prevent its binding with cyclin D, hence preventing progression from G1 to S phase", "Stops the progression of the cell cycle and begins to repair the damaged DNA", "Synthesises the BRCA2 protein", "Promotes DNA replication"], 2,
    "The tumour suppressor gene p53 is produced if DNA damage is detected at any checkpoint in the cell cycle. p53 stops the progression of the cell cycle and begins to repair the damaged DNA."),
  Q("y2t14_p2", "y2t14", "Physiology & Biochem",
    "What is the role of the tumour suppressor gene p16?",
    ["Synthesises the BRCA1 protein which is responsible for DNA repair", "Binds to CDK4 to prevent its binding with cyclin D, hence preventing progression from G1 to S phase", "Stops the progression of the cell cycle and begins to repair the damaged DNA", "Synthesises the BRCA2 protein", "Promotes DNA replication"], 1,
    "The tumour suppressor gene p16 binds to CDK4 to prevent its binding with cyclin D, preventing progression from the G1 to S phase. This inhibits phosphorylation of Rb, so E2F is unable to be released as a transcription factor."),
  Q("y2t14_p4", "y2t14", "Physiology & Biochem",
    "Which of the following is NOT a proto-oncogene?",
    ["Rb", "k-Ras", "PRL-3", "ER", "Her2"], 0,
    "Rb is a tumour suppressor gene (antioncogene). k-Ras, PRL-3, ER and Her2 are all examples of proto-oncogenes. Note that for colorectal cancer, k-Ras mutations account for approximately 40% of cases."),
  Q("y2t14_p5", "y2t14", "Clinical & Pharmacology",
    "In carcinoma staging, M1b indicates which of the following?",
    ["No metastasis", "Metastasis to lymph nodes", "Metastasis to multiple distant organs", "Metastasis to one distant site", "Metastasis to adjacent tissues"], 3,
    "M1b in carcinoma staging indicates metastasis to one specific distant site, providing information about the spread of the cancer."),
  Q("y2t14_p6", "y2t14", "Clinical & Pharmacology",
    "Li, a 63 year old female has been diagnosed with bowel cancer. Which of the following features is she least likely to have?",
    ["Vomiting", "Weight loss", "Iron deficiency anaemia", "Rectal bleeding", "Abdominal pain", "Constipation"], 0,
    "Bowel (colorectal) cancer is classically characterised by weight loss, rectal bleeding, change in bowel habit (diarrhoea/constipation), iron deficiency anaemia and abdominal pain. Vomiting is not a common feature, it is more likely associated with inflammatory conditions or oesophageal cancer."),
  Q("y2t14_p7", "y2t14", "Clinical & Pharmacology",
    "Inflammatory bowel disease is a chronic condition characterised by intestinal inflammation. It is classified into ulcerative colitis and Crohn's disease. Which of the following statements is incorrect?",
    ["Crohn's disease can affect the mouth to anus; Ulcerative colitis affects the colon to rectum", "Crohn's disease skips lesions; Ulcerative colitis is characterised by continuous inflammation", "Crohn's disease affects the superficial mucosa; Ulcerative colitis affects the deeper mucosa", "Smoking is a risk factor in Crohn's disease whilst in ulcerative colitis it is protective", "Both conditions may present with diarrhoea", "Both conditions are classified as autoimmune"], 2,
    "Crohn's disease affects the deeper mucosa and is classified as transmural (full thickness inflammation), whilst ulcerative colitis tends to only affect the superficial mucosa."),
  Q("y2t14_p8", "y2t14", "Physiology & Biochem",
    "What is the role of cyclin D/CDK4 in the cell cycle?",
    ["DNA replication during S phase", "Transition from G1 to S phase", "Spindle formation during mitosis", "Transition from G2 to M phase", "Cytokinesis"], 1,
    "Cyclin D/CDK4 activity facilitates the progression of the cell cycle from the G1 phase to the S phase by phosphorylating the Rb protein."),
  Q("y2t14_p9", "y2t14", "Clinical & Pharmacology",
    "Which gene is mutated in 80-90% of sporadic colorectal cancers?",
    ["p53", "KRAS", "APC", "MLH-1", "TGF-β receptor 2"], 2,
    "APC is a tumour suppressor gene central to the Wnt/β-catenin pathway. Loss of APC function leads to β-catenin accumulation and uncontrolled cell proliferation. It is mutated in the majority of sporadic colorectal cancers."),
  Q("y2t14_p10", "y2t14", "Physiology & Biochem",
    "Oncogenic KRAS mutations promote cancer because they:",
    ["Prevent GTP binding", "Increase GTP hydrolysis", "Lock RAS in its active GTP-bound state", "Degrade β-catenin", "Inhibit cyclin D expression"], 2,
    "Mutant KRAS cannot properly hydrolyse GTP to GDP, so it remains constitutively active, continuously driving proliferative signalling even without growth factors."),
  Q("y2t14_p11", "y2t14", "Physiology & Biochem",
    "In the absence of Wnt signalling, β-catenin is normally:",
    ["Transported to the nucleus", "Phosphorylated by GSK-3β and degraded", "Bound to cyclin D", "Converted into a tumour suppressor", "Secreted extracellularly"], 1,
    "Without Wnt binding, β-catenin is phosphorylated by GSK-3β (within a complex including APC), marking it for proteasomal degradation and preventing proliferation signals."),
  Q("y2t14_p12", "y2t14", "Physiology & Biochem",
    "What is the primary function of p53 when activated under cellular stress?",
    ["Stimulate cyclin production", "Promote G1/S transition", "Induce p21 to inhibit CDKs", "Activate RAS signalling", "Degrade APC"], 2,
    "Activated p53 acts as a transcription factor to induce p21. p21 inhibits cyclin-CDK complexes, causing cell cycle arrest to allow DNA repair or trigger apoptosis."),
  Q("y2t14_p13", "y2t14", "Clinical & Pharmacology",
    "The faecal immunochemical test (FIT) used in screening detects:",
    ["DNA mutations", "Haemoglobin", "Alpha-1 antitrypsin antibodies", "Leukocytes", "Intrinsic factor"], 1,
    "FIT detects human haemoglobin in stool, identifying lower GI bleeding and prompting further investigation with colonoscopy."),
  Q("y2t14_p14", "y2t14", "Clinical & Pharmacology",
    "Loperamide reduces diarrhoea primarily by:",
    ["Blocking serotonin receptors", "Inhibiting prostaglandin synthesis", "Acting as a μ-opioid receptor agonist in the gut", "Stimulating acetylcholine release", "Activating VIP receptors"], 2,
    "Loperamide activates peripheral μ-opioid receptors, reducing peristalsis, increasing sphincter tone, and enhancing fluid reabsorption, leading to firmer stools."),
  Q("y2t14_p15", "y2t14", "Clinical & Pharmacology",
    "Which chemotherapy drug is a pyrimidine analogue?",
    ["Fluorouracil", "Methotrexate", "Oxaliplatin", "Folinic acid", "Cisplatin"], 0,
    "Fluorouracil (5-FU) is a pyrimidine analogue that inhibits thymidylate synthase, impairing DNA synthesis in rapidly dividing cancer cells."),
  Q("y2t14_p16", "y2t14", "Clinical & Pharmacology",
    "Which feature best describes familial adenomatous polyposis (FAP)?",
    ["Few polyps with rapid progression", "Hundreds of colonic polyps", "Caused by KRAS mutation", "Caused by mismatch repair defect", "Accounts for the majority of colorectal cancers"], 1,
    "FAP is characterised by hundreds of adenomatous polyps lining the colon due to inherited APC mutation. Without treatment, progression to cancer is almost inevitable."),
  Q("y2t14_p17", "y2t14", "Clinical & Pharmacology",
    "Lynch syndrome (hereditary non-polyposis colorectal cancer) differs from FAP because it is primarily caused by:",
    ["APC", "β-catenin", "Mismatch repair genes", "Cyclin D", "CDK 4"], 2,
    "Lynch syndrome results from mutations in DNA mismatch repair genes (e.g. MSH2, MLH1), leading to microsatellite instability and rapid cancer progression with fewer polyps."),
  Q("y2t14_p18", "y2t14", "Physiology & Biochem",
    "Serotonin increases gut motility by binding to which receptor?",
    ["5-HT1", "5-HT2", "5-HT3", "5-HT4", "5-HT6"], 2,
    "Serotonin released from enterochromaffin cells binds to 5-HT3 receptors on afferent neurons, activating the enteric nervous system and increasing peristalsis."),
);
