// questions/y2t13.jsx, Year 2 Theme 13: Pancreas (legacy bank, ISOCMEDED).
// Diagram/histology-image questions (A&H 1, 2, 7, 8, 9) are omitted.
window.QUESTIONS.push(
  Q("y2t13_a3", "y2t13", "Anatomy",
    "The superior pancreaticoduodenal artery is a branch of which artery?",
    ["Splenic artery", "Gastroduodenal artery", "Gastro-omental artery", "Superior mesenteric artery", "Left gastric artery"], 1,
    "The superior pancreaticoduodenal artery is a branch of the gastroduodenal artery. This artery arises from the hepatic artery, which is a branch of the coeliac trunk."),
  Q("y2t13_a4", "y2t13", "Anatomy",
    "The convergence between which two veins forms the hepatic portal vein?",
    ["Inferior mesenteric vein and left renal vein", "Inferior mesenteric vein and right colic vein", "Superior mesenteric vein and splenic vein", "Superior mesenteric vein and left gastric vein", "Superior rectal vein and left gastro-omental vein"], 2,
    "The superior mesenteric vein and splenic vein join together to form the hepatic portal vein."),
  Q("y2t13_a5", "y2t13", "Anatomy",
    "Which of the following best describes the overall functional role of the pancreas?",
    ["Produces digestive enzymes for the small intestine and secretes hormones that regulate blood glucose.", "It functions solely as an exocrine gland that secretes digestive enzymes into the small intestine.", "It functions solely as an endocrine gland that regulates blood glucose levels.", "It produces bile for fat digestion and hormones for metabolic control.", "It stores digestive enzymes and releases them only during fasting."], 0,
    "The pancreas has both exocrine and endocrine roles. Exocrine: most of the pancreas produces digestive enzymes (amylase, lipase, proteases) released into the small intestine via the ampulla of Vater. Endocrine: islet cells secrete hormones such as insulin and glucagon directly into the bloodstream to regulate blood glucose."),
  Q("y2t13_a6", "y2t13", "Anatomy",
    "Which of the following parts of the pancreas is intraperitoneal and which ligament does it lie within?",
    ["The Uncinate Process which lies within the splenorenal ligament", "The Tail which lies within the splenorenal ligament", "The Head which lies within the gastrosplenic ligament", "The Tail which lies within the gastrosplenic ligament", "The Uncinate Process which lies within the gastrosplenic ligament"], 1,
    "The pancreas spans horizontally across L1-L2 and is primarily retroperitoneal. The tail is the only part that lies intraperitoneally, attached to the splenorenal ligament. The gastrosplenic and splenorenal ligaments are continuous peritoneal folds forming a channel transmitting splenic vessels."),
  Q("y2t13_a10", "y2t13", "Anatomy",
    "During a pancreatic head resection (Whipple procedure), injury to which structure would MOST directly impair parasympathetic stimulation of pancreatic exocrine secretion while sparing sympathetic vasomotor control?",
    ["Greater thoracic splanchnic nerve", "Lesser thoracic splanchnic nerve", "Vagus nerve branches traveling through the celiac plexus", "Celiac ganglia", "Superior mesenteric plexus"], 2,
    "Parasympathetic fibres, derived primarily from the vagus nerve, pass through the celiac and superior mesenteric plexuses without synapsing and stimulate exocrine secretion. Sympathetic fibres travel via the thoracic splanchnic nerves and synapse in the celiac and superior mesenteric ganglia, mainly regulating vasomotor tone."),
  Q("y2t13_p1", "y2t13", "Physiology & Biochem",
    "Cholecystokinin (CCK) is a hormone released in the GI system. Which of the following is NOT a role of this hormone?",
    ["Stimulates gallbladder contraction", "Inhibits gastric acid secretion", "Stimulates gastric emptying", "Suppresses appetite", "Stimulates release of pancreatic enzymes", "Relaxation of sphincter of Oddi"], 2,
    "CCK stimulates gallbladder contraction, relaxes the sphincter of Oddi, stimulates pancreatic enzyme secretion, inhibits gastric acid secretion and suppresses appetite. It INHIBITS (not stimulates) gastric emptying, allowing sufficient time for the small intestine to digest and absorb nutrients."),
  Q("y2t13_p2", "y2t13", "Physiology & Biochem",
    "Cholecystokinin (CCK) is released by which cells?",
    ["G cells in the stomach and duodenum", "I cells in the duodenum and small intestine", "L cells in the small intestine", "D cells in the stomach and duodenum", "K cells in the small intestine"], 1,
    "Cholecystokinin is released by the I cells in the duodenum and small intestine."),
  Q("y2t13_p3", "y2t13", "Physiology & Biochem",
    "Which of the following hormones is responsible for stimulating the release of bicarbonate ions from the pancreas?",
    ["Ghrelin", "CCK", "Secretin", "GLP-1", "Somatostatin"], 2,
    "Secretin is released by the S cells in the small intestine in response to increased acidity. It stimulates the pancreas to release bicarbonate (HCO3-) ions to neutralise the pH as well as inhibiting gastrin."),
  Q("y2t13_p4", "y2t13", "Clinical & Pharmacology",
    "Chung, a 47 year old male, has been diagnosed with pancreatitis. Which of the following is the most common cause of pancreatitis?",
    ["Gallstones", "Alcohol", "Steroids", "Hyperlipidaemia", "Drugs"], 0,
    "Gallstones are the most common cause of pancreatitis, followed by alcohol. The rest of the options are also valid causes but do not come close in significance to the first two."),
  Q("y2t13_p5", "y2t13", "Clinical & Pharmacology",
    "In pancreatitis, which electrolyte is distinguishably low due to saponification?",
    ["Na+", "Ca2+", "K+", "Cl-", "H+", "Mg2+"], 1,
    "Pancreatitis leads to the release of pancreatic enzymes, especially lipase. Lipase breaks down fats into fatty acids, which bind to calcium, decreasing the amount of Ca2+ in the blood. This binding process is known as saponification."),
  Q("y2t13_p6", "y2t13", "Clinical & Pharmacology",
    "Alcohol is one of the most common causes of pancreatitis. According to the NHS, what is the recommended limit of units of alcohol per week?",
    ["14 units", "12 units", "10 units", "16 units", "8 units"], 0,
    "The NHS recommends that people do not drink more than 14 units of alcohol per week."),
  Q("y2t13_p7", "y2t13", "Clinical & Pharmacology",
    "Pancreatic cancer may present with Courvoisier's sign. Which of the following signs characterises this?",
    ["Blood in urine", "Palpable gallbladder", "Tarry stools", "Hesitancy in urination", "Blood in stools"], 1,
    "Courvoisier's sign is the presence of painless jaundice with a palpable, non-tender gallbladder. This suggests pancreatic cancer as opposed to a gallstone pathology, a tumour enables the gallbladder to distend whilst a stone tends to cause the gallbladder to shrink."),
  Q("y2t13_p8", "y2t13", "Clinical & Pharmacology",
    "A 39-year-old man presents with severe epigastric pain radiating to the back after heavy alcohol intake. Serum lipase is markedly elevated. Which cellular event is most directly responsible for pancreatic autodigestion in acute pancreatitis?",
    ["Reduced bicarbonate secretion from ductal cells", "Premature activation of trypsinogen within acinar cells", "Increased insulin secretion from beta cells", "Obstruction of the common hepatic duct", "Increased gastrin secretion"], 1,
    "Acute pancreatitis is triggered by intrapancreatic activation of trypsinogen into trypsin, which then activates other digestive enzymes, leading to autodigestion of the pancreas."),
  Q("y2t13_p9", "y2t13", "Clinical & Pharmacology",
    "A 60-year-old woman presents with acute pancreatitis. You suspect gallstones as the cause. Which investigation is most appropriate as first-line to identify the underlying cause?",
    ["CT abdomen", "Serum amylase", "Abdominal ultrasound", "ERCP", "MRCP"], 2,
    "Ultrasound is first-line to detect gallstones and biliary dilation. CT is used to assess complications (e.g. pseudocysts, necrosis), not the initial cause."),
  Q("y2t13_p10", "y2t13", "Clinical & Pharmacology",
    "A patient presents with weight loss and pale, bulky stools that float. There is no haematemesis or melaena. Which mechanism best explains the stool findings?",
    ["Reduced intrinsic factor production", "Impaired bile storage", "Increased gastric acid secretion", "Reduced pepsin activity", "Reduced pancreatic lipase secretion"], 4,
    "Exocrine pancreatic insufficiency → reduced lipase → fat malabsorption → steatorrhoea. Haematemesis is vomiting fresh blood; melaena is black/tarry stool due to digested blood."),
  Q("y2t13_p11", "y2t13", "Clinical & Pharmacology",
    "A patient with chronic pancreatitis develops protein-energy malnutrition. Which physiological effect is most likely?",
    ["Increased wound healing", "Increased albumin synthesis", "Increased muscle mass", "Reduced immune function", "Hypercalcaemia"], 3,
    "Malnutrition can cause immunosuppression, muscle wasting, poor wound healing, hypoalbuminaemia, increased hospital stay, and increased morbidity and mortality."),
  Q("y2t13_p12", "y2t13", "Clinical & Pharmacology",
    "A patient with chronic pancreatitis is started on pancreatic enzyme replacement therapy (PERT). Which instruction is most appropriate?",
    ["Take on an empty stomach", "Take once daily before breakfast", "Take with meals", "Stop if stools remain pale", "Avoid fatty foods completely"], 2,
    "PERT must be taken with meals to mix with food for digestion."),
  Q("y2t13_p13", "y2t13", "Clinical & Pharmacology",
    "Chronic alcohol use increases risk of pancreatitis by:",
    ["Promoting protein plug formation and ductal obstruction", "Causing autoimmune destruction", "Increasing pancreatic bicarbonate secretion", "Increasing bile flow", "Reducing enzyme synthesis"], 0,
    "Alcohol increases enzyme secretion, promotes the formation of protein plugs, and causes ductal obstruction leading to premature enzyme activation."),
  Q("y2t13_p14", "y2t13", "Physiology & Biochem",
    "During recovery from pancreatitis, a patient begins oral feeding. Glucose absorption across the intestinal epithelium depends on:",
    ["Primary active transport using ATP directly", "Secondary active transport coupled to sodium", "Passive diffusion only", "Chloride channels", "Endocytosis"], 1,
    "The Na+/K+ pump creates a concentration gradient (primary active transport). SGLT1, a Na+-dependent co-transporter, transports 2Na+ and 1 glucose/galactose into the cell against the glucose gradient (secondary active transport). Glucose is then transported into blood by GLUT2 (facilitated diffusion)."),
  Q("y2t13_p15", "y2t13", "Physiology & Biochem",
    "Glucose absorption in the small intestine relies on a sodium gradient maintained by which transporter?",
    ["CFTR", "Na⁺/Ca²⁺ exchanger", "GLUT5", "Na⁺/K⁺ ATPase", "H⁺/K⁺ ATPase"], 3,
    "Na⁺/K⁺ ATPase maintains low intracellular Na⁺, driving SGLT1-mediated glucose uptake (secondary active transport)."),
  Q("y2t13_p16", "y2t13", "Clinical & Pharmacology",
    "A patient with chronic pancreatitis develops prolonged bleeding after minor injury. Which deficiency is most likely responsible?",
    ["Vitamin A", "Vitamin D", "Vitamin E", "Iron", "Vitamin K"], 4,
    "Fat malabsorption → deficiency of fat-soluble vitamins (A, D, E, K). Vitamin K deficiency → impaired clotting → prolonged PT."),
  Q("y2t13_b1", "y2t13", "BSS",
    "A 47-year-old man is admitted with acute pancreatitis. You suspect alcohol misuse. You decide to screen him using the CAGE questionnaire. Which of the following questions forms part of the CAGE tool?",
    ["How many units of alcohol do you drink per week?", "Have you ever felt you should Cut down on your drinking?", "Have you experienced blackouts after drinking?", "Has alcohol affected your employment?", "Do you drink in the morning daily?"], 1,
    "CAGE consists of 4 questions: Cut down (have you ever felt you needed to cut down on your drinking?), Annoyed (have people annoyed you by criticising your drinking?), Guilty (have you ever felt guilty about drinking?), Eye-opener (have you ever felt you needed a drink first thing in the morning?). Two or more positive responses suggest clinically significant alcohol misuse."),
  Q("y2t13_b2", "y2t13", "BSS",
    "A 35-year-old woman with alcohol dependency presents with recurrent abdominal pain. On examination, you've noticed bruising across her body. You are concerned about possible domestic abuse. Which question forms part of the HARK screening tool?",
    ["Have you ever felt guilty about drinking?", "Have you been Humiliated by your partner?", "How many units of alcohol do you drink weekly?", "Do you require an Eye-opener in the morning?", "Has alcohol affected your job?"], 1,
    "HARK screens for domestic abuse: Humiliation, Afraid, Rape, Kick. It is a screening tool used in primary care to identify intimate partner violence."),
);
