// questions/y2t2.jsx, Year 2 Theme 2: Musculoskeletal system (legacy bank, ISOCMEDED).
// Diagram-dependent questions from the PDF (Anatomy 1, 2) are omitted.
window.QUESTIONS.push(
  Q("y2t2_a3", "y2t2", "Anatomy",
    "The atlas (C1) and axis (C2) articulate together to form the atlanto-axial joint. Which type of synovial joint is this?",
    ["Synovial plane", "Synovial pivot", "Synovial hinge", "Synovial condyloid", "Synovial ball-and-socket"], 1,
    "The atlanto-axial joint is restricted to rotation of the head. It is not involved in the various other ranges of movement such as flexion, extension, abduction, circumduction like the majority of synovial joints. This joint which permits only rotation is called the synovial pivot joint. It also features in the forearm to enable rotation of the arm."),
  Q("y2t2_a4", "y2t2", "Anatomy",
    "The intervertebral disc is composed of which of the following structures?",
    ["Hyaline cartilage and articular cartilage", "Annulus fibrosus and nucleus pulposus", "Fibrous capsule and synovial membrane", "Elastic cartilage and ligamentum flavum", "Fibrocartilage and periosteum"], 1,
    "Each intervertebral disc sits between adjacent vertebral bodies and serves as a fibrocartilaginous joint allowing slight movement and shock absorption. The annulus fibrosus is the tough outer ring made of concentric layers of fibrocartilage that attach to the vertebral bodies. The nucleus pulposus is the central, gelatinous core that allows for flexibility and compression resistance."),
  Q("y2t2_a5", "y2t2", "Anatomy",
    "Which of the following features distinguishes thoracic vertebrae from other vertebral regions?",
    ["Transverse foramina for vertebral arteries", "Bifid spinous process", "Costal facets on the body and transverse processes", "Large kidney-shaped vertebral body", "Triangular vertebral foramen"], 2,
    "Cervical vertebrae have transverse foramina (for vertebral arteries) and often bifid spinous processes. Lumbar vertebrae have large kidney-shaped bodies and short, blunt spinous processes."),
  Q("y2t2_a6", "y2t2", "Anatomy",
    "Which of the following correctly describes the course of the sciatic nerve?",
    ["Arises from L1–L3 and passes through the lesser sciatic foramen", "Formed by L4–S3, passes beneath piriformis through the greater sciatic foramen", "Formed by L2–L5, passes superficial to gluteus maximus", "Formed by S1–S4, divides at the knee into femoral and obturator nerves", "Formed by L3–S2, crosses the ischial spine and exits via obturator canal"], 1,
    "The sciatic nerve originates from the lumbosacral plexus (L4–S3). It forms on the anterior surface of the sacrum. It exits the pelvis by passing below the piriformis through the greater sciatic foramen. It then runs deep to gluteus maximus, crossing the ischial tuberosity, and descends posterior to the thigh beneath the hamstrings. It bifurcates into the tibial and common peroneal nerves usually near the popliteal fossa."),
  Q("y2t2_a7", "y2t2", "Anatomy",
    "The anterior spinal artery is primarily formed by branches of which vessel?",
    ["Internal carotid artery", "Vertebral arteries", "Posterior inferior cerebellar arteries only", "Basilar artery", "Radicular arteries"], 1,
    "The anterior spinal artery arises from branches of both vertebral arteries near the medulla and descends in the anterior median fissure of the spinal cord."),
  Q("y2t2_a8", "y2t2", "Anatomy",
    "Which of the following best describes the relationship of the sciatic nerve as it exits the pelvis?",
    ["Passes above the piriformis through the greater sciatic foramen", "Passes below the piriformis through the greater sciatic foramen, deep to gluteus maximus", "Passes below the piriformis through the lesser sciatic foramen, superficial to gluteus maximus", "Passes above the obturator internus through the obturator canal", "Passes between the heads of gluteus medius through the greater sciatic foramen"], 1,
    "Exits the pelvis below the piriformis (through the greater sciatic foramen). Lies deep to the gluteus maximus and superficial to the obturator internus and quadratus femoris. Descends into the posterior thigh where it gives rise to branches to the hamstring muscles and terminates as tibial and common peroneal nerves."),
  Q("y2t2_h1", "y2t2", "Anatomy",
    "Which of the following neuroglial cells are primarily involved in phagocytosis?",
    ["Schwann cells", "Ependymal cells", "Oligodendrocytes", "Astrocytes", "Microglia"], 4,
    "Microglia are part of the neuroglial cell group. These specialised cells perform a similar role to macrophages since they are primarily involved in phagocytosis. Astrocytes form the blood-brain barrier, ependymal cells line the ventricles and choroid plexus, oligodendrocytes produce the myelin sheath in the CNS whilst schwann cells do this in the PNS."),
  Q("y2t2_h2", "y2t2", "Anatomy",
    "Which of the following statements about the microscopic structure of the spinal cord is true?",
    ["White matter is located centrally, surrounded by grey matter", "Grey matter contains myelinated axons only", "The anterior horns contain motor neuron cell bodies", "The posterior horns contain motor neurons for limb control", "The central canal is lined by oligodendrocytes"], 2,
    "The anterior (ventral) horns have a motor function which is required for the innervation of skeletal muscle. The rest of the options are incorrect."),
  Q("y2t2_h3", "y2t2", "Anatomy",
    "Which of the following correctly matches a supporting cell to its function?",
    ["Astrocyte – Produces myelin in the CNS", "Oligodendrocyte – Forms myelin in the CNS", "Schwann cell – Found only in ganglia of the PNS", "Microglia – Produces cerebrospinal fluid", "Satellite cell – Forms myelin in the PNS"], 1,
    "Oligodendrocytes produce the myelin sheath in the CNS where each can myelinate multiple axons. Schwann cells produce the myelin sheath in the PNS. Astrocytes provide structural support, maintain the blood-brain barrier, and remove excess neurotransmitters. Microglia are the immune cells of the CNS. Ependymal cells line the ventricles and central canal, helping produce and circulate cerebrospinal fluid. Satellite cells provide support in ganglia."),
  Q("y2t2_h4", "y2t2", "Anatomy",
    "The dorsal root ganglia contain which of the following types of neurons?",
    ["Bipolar sensory neurons", "Multipolar motor neurons", "Unipolar sensory neurons", "Pseudobipolar interneurons", "Multipolar autonomic neurons"], 2,
    "The DRG are a collection of sensory neuron cell bodies posterior to the spinal cord. They are unipolar with a single process that splits into two (peripheral and central). They are used to transmit pain, touch and temperature."),
  Q("y2t2_p1", "y2t2", "Physiology & Biochem",
    "Which of the following options is correct for Type I skeletal muscle fibres?",
    ["Effective in a 100m sprint", "Energy source is anaerobic glycolysis", "Fast contraction speed", "High fatigue resistance", "High force generated"], 3,
    "Type I skeletal muscle fibres, also known as slow oxidative fibres, are distinguishably characterised by having high fatigue resistance and slow contraction speed. This makes it effective for long-distance and endurance training. Type II fibres on the other hand use anaerobic glycolysis due to the demand for quick energy required especially in a 100m sprint, hence there is a great contraction speed and force generated."),
  Q("y2t2_p2", "y2t2", "Physiology & Biochem",
    "The parasympathetic division of the autonomic nervous system involves a network of nerves which relax your body to conserve energy. Which of the following statements is correct for the contents of the parasympathetic division?",
    ["Short pre-ganglionic neurones (uses ACh neurotransmitter) and long post-ganglionic neurones (uses Noradrenaline neurotransmitter)", "Long pre-ganglionic neurones (uses ACh neurotransmitter) and short post-ganglionic neurones (uses ACh neurotransmitter)", "Short pre-ganglionic neurones (uses ACh neurotransmitter) and long post-ganglionic neurones (uses ACh neurotransmitter)", "Long pre-ganglionic neurones (uses Noradrenaline neurotransmitter) and short post-ganglionic neurones (uses ACh neurotransmitter)", "Short pre-ganglionic neurones (uses Noradrenaline neurotransmitter) and long post-ganglionic neurones (uses Noradrenaline neurotransmitter)"], 1,
    "The parasympathetic nervous system contains long pre-ganglionic neurones (derived from the brainstem far away) and short post-ganglionic neurones (derived from the parasympathetic ganglion closer to the target organs). Both neurones use acetylcholine (ACh) as the neurotransmitter. The sympathetic nervous system, on the other hand, contains short pre-ganglionic neurones (ACh) and long post-ganglionic neurones (Noradrenaline)."),
  Q("y2t2_p3", "y2t2", "Physiology & Biochem",
    "An athlete is due to run in a 100m race at the World Athletics Championship. Which of the following muscle fibres are they most likely to optimise during this race?",
    ["Type I", "Type IIa", "Type IIb", "Type III", "Type IIc"], 2,
    "Type IIb muscle fibres are optimised during maximal intensity exercises when short, sudden bursts of energy is required. This includes 100m sprints since there is insufficient oxygen for aerobic respiration to occur, hence ruling out oxidative fibres such as Type I and Type IIa. Type IIb fibres also are much larger, faster and generate greater force. Type III and Type IIc notation does not exist."),
  Q("y2t2_p4", "y2t2", "Physiology & Biochem",
    "Which of the following is a correct difference between skeletal and cardiac muscle?",
    ["Skeletal muscles involve slow contraction, cardiac muscles involve rapid contraction", "Skeletal muscles are striated, cardiac muscles are unstriated", "Skeletal muscles are uninucleated, cardiac muscles are multinucleated", "Skeletal muscles are involuntary, cardiac muscles are voluntary", "Skeletal muscles are unbranched, cardiac muscles are branched"], 4,
    "Skeletal muscles are unbranched, whilst cardiac muscles are branched. Cardiac muscles are branched via intercalated discs which propagate the action potential (electric impulse) along via rapid conduction."),
  Q("y2t2_p5", "y2t2", "Physiology & Biochem",
    "Which of the following stores Ca2+ ions for muscle contraction?",
    ["Sarcolemma", "Sarcoplasmic reticulum (SR)", "Mitochondria", "T-tubules", "Actin"], 1,
    "The sarcoplasmic reticulum (SR) stores Ca2+ ions for muscle contraction. This structure contains RyR (Ryanodine receptors) which Ca2+ ions (released already from the L-type Ca2+ channels) bind to, activating RyR, which opens to release Ca2+ from the SR."),
  Q("y2t2_p6", "y2t2", "Physiology & Biochem",
    "Which of the following enables muscle contraction to continue longer?",
    ["Phosphorylation of PLB promotes activity of SERCA, Ca2+ ions are reabsorbed into the sarcoplasmic reticulum", "Non-phosphorylated PLB is inactive, inhibits activity of SERCA, Ca2+ ions are prevented from being reabsorbed into the sarcoplasmic reticulum", "Non-phosphorylated PLB is inactive, inhibits activity of SERCA, Ca2+ ions are reabsorbed into the sarcoplasmic reticulum", "Phosphorylation of PLB inhibits the activity of SERCA, Ca2+ ions are reabsorbed into the sarcoplasmic reticulum", "Phosphorylation of NCX promotes the activity of SERCA, Ca2+ ions are reabsorbed into the sarcoplasmic reticulum"], 1,
    "Ca2+ ions are actively reabsorbed into the sarcoplasmic reticulum (SR) via SERCA (sarcoendoplasmic reticulum calcium ATPase). SERCA is regulated by phospholamban (PLB). This inhibits SERCA activity, hence restricts the uptake of Ca2+ ions into the SR. This enables muscle contraction to last longer."),
  Q("y2t2_p7", "y2t2", "Physiology & Biochem",
    "Which of these is not generally an excitatory neurotransmitter?",
    ["Glutamate", "Acetylcholine", "GABA", "Dopamine", "Serotonin"], 2,
    "GABA binds to GABA receptors causing Cl- ion channels to open therefore hyperpolarisation so neurone can't fire. This is for GABA A receptors, GABA B receptors involve K+ efflux."),
  Q("y2t2_p8", "y2t2", "Physiology & Biochem",
    "Which statement is NOT true for the production of Acetylcholine?",
    ["Choline is one of the reactants", "Acetyl Coenzyme A is also a reactant", "Choline acetyl transferase is needed for the reaction", "Coenzyme A is a product", "Acetylcholine is made in the mitochondria"], 4,
    "ACh is made in the cytoplasm. Even if you didn't know this you could work out E is incorrect as Acetyl CoA + Choline → Coenzyme A + Acetylcholine (catalysed by choline acetyl transferase), so the other answers are correct."),
  Q("y2t2_p9", "y2t2", "Physiology & Biochem",
    "Which is the smallest structural unit making up a muscle?",
    ["Fascicle", "Myofibril", "Myocyte", "Muscle Fibre", "Sarcolemma"], 1,
    "Sarcomere → Myofibril → Myocyte (same thing as muscle fibre) → Fascicle. The sarcolemma is the cell membrane of a muscle cell, not a structural unit."),
  Q("y2t2_p10", "y2t2", "Physiology & Biochem",
    "What is the correct order of the 'power stroke'?",
    ["Myosin head binds to actin, ADP detaches, Pi detaches, ATP binds", "ATP binds to myosin, Myosin head binds to actin, Pi detaches, ADP detaches", "Myosin head binds to actin, Pi detaches, ADP detaches, ATP binds", "ATP binds to myosin, myosin head binds to actin, ADP detaches, Pi detaches", "ATP binds to myosin, myosin head binds to actin, Pi detaches, ADP detaches"], 2,
    "Myosin head with ADP + Pi attached binds to actin (cross bridge forms). Pi is released, triggering the power stroke. ADP is released ending the power stroke and myosin remains tightly bound in a rigor state. ATP binds to myosin causing detachment of the head from actin."),
  Q("y2t2_p11", "y2t2", "Physiology & Biochem",
    "Which statement about actin is NOT true?",
    ["Troponin I has a strong affinity for actin", "Tropomyosin is a rope like protein that covers actin binding sites at rest", "Troponin C is what calcium binds to", "Tropomyosin binds to calcium to free actin binding site and initiate contraction", "Troponin T has a strong affinity for tropomyosin"], 3,
    "Troponin C binds to calcium to free the site, not tropomyosin."),
  Q("y2t2_p12", "y2t2", "Physiology & Biochem",
    "Which of these statements is true regarding skeletal muscle fibres?",
    ["There are 2 types of type 1: 1a and 1b", "Type 2b has high mitochondrial density", "Type 1b is fatigue resistant", "Type 2a is a mix of type 1 and type 2b", "Type 2b has an extensive blood supply"], 3,
    "The 3 types are: 1, 2a and 2b. 1 is for aerobic use, 2a for mixed and 2b is purely for anaerobic use eg a powerlifter. Because of this, 2b does not need a rich blood supply or a high mitochondrial density as it doesn't need oxygen for the few seconds it is in use."),
  Q("y2t2_p13", "y2t2", "Physiology & Biochem",
    "Which of these is an example of an isometric contraction?",
    ["A concentric contraction", "A pull up", "A plank", "An eccentric contraction"], 2,
    "Isometric means the muscle is contracting but does not change length (like a plank). Concentric means muscle shortening and eccentric means lengthening, they are both types of isotonic contractions (muscle length changes causing movement)."),
  Q("y2t2_p14", "y2t2", "Physiology & Biochem",
    "Which isn't true about these gaits?",
    ["Hemiplegic gait is caused by a LMN lesion", "Parkinsonian gait is due to basal ganglion dysfunction", "Parkinsonian gait has a small shuffling and reduced arm swing", "Cerebellar ataxia involves swaying side to side", "Hemiplegic gait affects only one leg"], 0,
    "Hemiplegic gait is caused by an upper motor neurone lesion."),
  Q("y2t2_p15", "y2t2", "Physiology & Biochem",
    "Which of the following statements about myasthenia gravis is false?",
    ["Ptosis is a symptom", "It's an autoimmune disorder", "It involves insufficient ACh signalling", "Dysphagia is a symptom", "Rivastigmine is a treatment"], 4,
    "Although rivastigmine is an ACh inhibitor, it acts in the CNS and is used for Alzheimer's. Pyridostigmine acts in the peripheral NMJ and is used for myasthenia gravis."),
);
