// questions/y2t3.jsx, Year 2 Theme 3: Neurodegeneration (legacy bank, ISOCMEDED).
// Diagram-dependent questions from the PDF (Anatomy 1–3) are omitted.
window.QUESTIONS.push(
  Q("y2t3_a4", "y2t3", "Anatomy",
    "Which of the following nerve modalities/fibres of the facial nerve (CN VII) innervate the muscles of facial expression?",
    ["Special Visceral Efferent (SVE)", "General Somatic Afferent (GSA)", "General Somatic Efferent (GSE)", "Special Visceral Afferent (SVA)", "General Visceral Afferent (GVA)"], 0,
    "The facial nerve (CN VII) consists of 4 nerve modalities: GSA, sensory innervation of external acoustic meatus; SVA, taste from anterior 2/3 tongue; GVE, parasympathetic innervation of salivary glands (apart from parotid); SVE, innervation of muscles of facial expression + stapedius + stylohyoid."),
  Q("y2t3_a5", "y2t3", "Anatomy",
    "Which of the following cranial nerves is the only one to exit from the posterior surface of the brainstem?",
    ["Oculomotor nerve", "Trochlear nerve", "Abducens nerve", "Hypoglossal nerve", "Accessory nerve"], 1,
    "The trochlear nerve is the only cranial nerve to exit from the posterior surface of the brainstem."),
  Q("y2t3_a6", "y2t3", "Anatomy",
    "Saddam, an 18 year old male, suffers from a condition called Friedreich's ataxia. A lesion in which of the following tracts is likely to cause this?",
    ["Corticospinal tract", "Spinocerebellar tract", "Dorsal column", "Lateral spinothalamic tract", "Anterior spinothalamic tract"], 1,
    "The spinocerebellar tract is involved in the unconscious proprioception (joint sense). Friedreich's ataxia is an inherited, degenerative disease which characterises damage to the spinocerebellar tract. It leads to intense tremor and a wide-based, reeling gait."),
  Q("y2t3_a7", "y2t3", "Anatomy",
    "Through which foramen does the maxillary branch of the trigeminal nerve pass through to enter/exit the cranial cavity?",
    ["Facial canal", "Foramen rotundum", "Foramen ovale", "Internal acoustic meatus", "Superior orbital fissure"], 1,
    "The maxillary branch (V2) of the trigeminal nerve leaves the cranial cavity by passing through the foramen rotundum. The facial canal is for the facial nerve (CN VII); the foramen ovale carries the mandibular branch (V3); the internal acoustic meatus carries the facial (CN VII) and vestibulocochlear (CN VIII) nerves; the superior orbital fissure carries the ophthalmic branch (V1)."),
  Q("y2t3_a8", "y2t3", "Anatomy",
    "What modality does the optic nerve convey?",
    ["SVE", "SVA", "GSE", "SSA", "GSA"], 3,
    "SSA (Special Somatic Afferent) fibres carry vision and hearing. The optic nerve (CN II) transmits visual sensory input from the retina. SVA is for taste and smell; GSA is general somatic sensation from skin/mucosa; GSE is motor to skeletal muscle; SVE supplies branchial arch motor muscles."),
  Q("y2t3_a9", "y2t3", "Anatomy",
    "Which cranial nerve carries parasympathetic fibers to the parotid gland?",
    ["Facial nerve (CN VII)", "Trigeminal nerve (CN V)", "Glossopharyngeal nerve (CN IX)", "Hypoglossal nerve (CN XII)", "Optic nerve (CN II)"], 2,
    "The glossopharyngeal nerve (CN IX) sends preganglionic parasympathetic fibres via the lesser petrosal nerve to the otic ganglion, which then innervates the parotid gland. The facial nerve (CN VII) supplies other salivary glands: the submandibular and sublingual glands."),
  Q("y2t3_a10", "y2t3", "Anatomy",
    "Where do second-order neurons of the dorsal column pathway decussate?",
    ["At entry level in spinal cord", "In the medulla (nucleus gracilis/cuneatus)", "In the thalamus", "In the pons", "In the primary sensory cortex"], 1,
    "First-order neurons carrying discriminative touch, vibration & proprioception ascend ipsilaterally via the fasciculus gracilis/cuneatus to the nucleus gracilis/cuneatus in the medulla. The second-order neurons then decussate and terminate at the ventral posterior (VP) nucleus of the thalamus. They do not cross in the spinal cord or thalamus."),
  Q("y2t3_a11", "y2t3", "Anatomy",
    "The trochlear nerve (CN IV) primarily innervates which muscle?",
    ["Superior oblique", "Superior rectus", "Lateral rectus", "Medial rectus", "Inferior oblique"], 0,
    "The trochlear nerve innervates only one extraocular muscle: the superior oblique, which depresses and intorts the eyeball. CN VI innervates the lateral rectus, while CN III innervates the medial rectus, superior rectus, inferior rectus, inferior oblique and levator palpebrae."),
  Q("y2t3_a12", "y2t3", "Anatomy",
    "Which cranial nerve contains BOTH general sensory fibres and autonomic parasympathetic afferents?",
    ["Vestibulocochlear nerve (CN VIII)", "Hypoglossal nerve (CN XII)", "Optic nerve (CN II)", "Glossopharyngeal nerve (CN IX)", "Trigeminal nerve (CN V)"], 3,
    "The glossopharyngeal nerve (CN IX) carries general sensory fibres (pharynx, posterior tongue, middle ear), special sensory taste (posterior 1/3 of tongue), parasympathetic efferents to the parotid gland via the otic ganglion, and visceral afferents (carotid body/sinus). The other options either supply only sensory (VIII, II), only motor (XII), or lack parasympathetic components (V)."),
  Q("y2t3_a13", "y2t3", "Anatomy",
    "Which of the following is true about the lateral corticospinal tract?",
    ["It does not cross the midline", "It carries sensory information from the limbs", "It decussates at the level of the medullary pyramids", "It terminates in the thalamus", "It arises in the dorsal horn"], 2,
    "The lateral corticospinal tract carries voluntary motor commands from the cortex to limbs. It decussates at the pyramidal decussation (medulla), descends in the lateral funiculus, and synapses with lower motor neurons in the spinal cord. It's motor not sensory, terminates in the spinal cord not thalamus, and arises from the cortex not the dorsal horn."),
  Q("y2t3_p1", "y2t3", "Clinical & Pharmacology",
    "Chorea is a hyperkinetic movement disorder which involves involuntary movements spontaneously. Which disease is classically associated with chorea?",
    ["Alzheimer's Disease", "Parkinson's Disease", "Progressive muscular atrophy", "Huntington's Disease", "Primary lateral sclerosis"], 3,
    "Huntington's Disease is an autosomal dominant, neurodegenerative disorder classically characterised by progressive chorea. Primary lateral sclerosis and progressive muscular atrophy are both motor neurone diseases which affect the muscles rather than the disorder of movement. AD and PD do not cause chorea; in fact PD does the opposite due to increased rigidity and can be characterised by bradykinesia."),
  Q("y2t3_p2", "y2t3", "Clinical & Pharmacology",
    "Which neurotransmitter is involved in the transmission of the impulse from an upper motor neurone to a lower motor neurone?",
    ["Glutamate", "Acetylcholine", "Noradrenaline", "Serotonin", "Dopamine"], 0,
    "Glutamate is the neurotransmitter involved in the transmission from a UMN to a LMN. LMNs then use acetylcholine to synapse at the muscle fibre, which triggers depolarisation and contraction."),
  Q("y2t3_p3", "y2t3", "Clinical & Pharmacology",
    "A patient is suffering from Alzheimer's Disease and is given treatment by his GP in the form of an acetylcholinesterase inhibitor called donepezil. However, he is unable to tolerate this and so is given an alternative medication. What is the name of this alternative medication?",
    ["Memantine", "Haloperidol", "Aripiprazole", "Fluoxetine", "Carbidopa"], 0,
    "Memantine is the most common alternative after acetylcholinesterase inhibitors (if they cannot be tolerated). Memantine is a NMDA receptor antagonist used for moderate-severe Alzheimer's."),
  Q("y2t3_p4", "y2t3", "Clinical & Pharmacology",
    "Parkinson's Disease (PD) is a neurodegenerative disease characterised by the loss of dopaminergic neurones in the substantia nigra. Which of the following is NOT a likely symptom of Parkinson's Disease?",
    ["Postural instability", "Babinski sign", "Rigidity", "Resting tremor", "Bradykinesia"], 1,
    "Tremor, postural instability, rigidity and bradykinesia are all classic symptoms and signs of PD. Babinski sign, on the other hand, is not one of them. This sign is seen in an upper motor lesion."),
  Q("y2t3_p5", "y2t3", "Clinical & Pharmacology",
    "Leah, a 63 year old, has been diagnosed with Parkinson's Disease (PD). The doctor decides to prescribe her a dopamine receptor agonist along with Levodopa. Which of the following options below is an example of a dopamine agonist?",
    ["Selegiline", "Pramipexole", "Entacapone", "Carbidopa", "Safinamide"], 1,
    "Pramipexole is a dopamine receptor agonist. It mimics dopamine by directly binding and stimulating dopamine receptors. Selegiline is a MAO-B inhibitor which prevents dopamine breakdown to prolong its action. Entacapone is a COMT inhibitor which prolongs L-dopa. Carbidopa is a dopa decarboxylase inhibitor used alongside L-dopa. Safinamide is a MAO-B inhibitor."),
  Q("y2t3_p6", "y2t3", "Clinical & Pharmacology",
    "Hessie, a 39 year old female, has been told by the doctor that she has been found to have had progressive neurodegeneration of the upper motor neurones in her brain, upon investigation. Which condition does she likely have?",
    ["Primary lateral sclerosis", "Progressive muscular atrophy", "Huntington's Disease", "Parkinson's Disease", "Alzheimer's Disease"], 0,
    "Parkinson's Disease is ruled out since that involves dopaminergic neurones; Huntington's involves basal ganglia degeneration. Primary lateral sclerosis involves upper motor neurone (UMN) degeneration, whereas progressive muscular atrophy involves lower motor neurone (LMN) degeneration. Therefore the answer is primary lateral sclerosis."),
  Q("y2t3_p7", "y2t3", "Clinical & Pharmacology",
    "Which basal ganglia structure provides the main inhibitory output to the thalamus?",
    ["Caudate nucleus", "Subthalamic nucleus", "Globus pallidus internus", "Globus pallidus externus", "Putamen"], 2,
    "The GPi, together with the substantia nigra pars reticulata, forms the major inhibitory output of the basal ganglia, projecting to the thalamus."),
  Q("y2t3_p8", "y2t3", "Clinical & Pharmacology",
    "In Parkinson's disease, which change occurs in basal ganglia circuitry?",
    ["Enhanced activity of the direct pathway", "Reduced inhibition of the GPi", "Increased activity of the indirect pathway", "Increased thalamic excitation of motor cortex", "Reduced glutamate release from cortex to striatum"], 2,
    "Loss of dopamine leads to reduced activity in the direct pathway and increased activity in the indirect pathway, resulting in excessive inhibition of the thalamus and impaired movement initiation."),
  Q("y2t3_p9", "y2t3", "Clinical & Pharmacology",
    "Which neurotransmitter is released from medium spiny neurons of the striatum?",
    ["Acetylcholine", "Glutamate", "Dopamine", "GABA", "Serotonin"], 3,
    "Medium spiny neurons of the striatum are GABAergic and form the major inhibitory projections to GPi/GPe."),
  Q("y2t3_p10", "y2t3", "Clinical & Pharmacology",
    "Which cerebellar lesion is most likely to cause intention tremor?",
    ["Vestibulocerebellum", "Spinocerebellum", "Cerebrocerebellum", "Fastigial nucleus", "Flocculonodular lobe"], 2,
    "Damage to the cerebrocerebellum impairs planning and coordination of skilled movements, producing intention tremor."),
  Q("y2t3_p11", "y2t3", "Clinical & Pharmacology",
    "Which spinal tract carries fine touch and proprioception to the brain?",
    ["Spinothalamic tract", "Dorsal column-medial lemniscus", "Corticospinal tract", "Spinocerebellar tract", "Vestibulospinal tract"], 1,
    "The dorsal columns transmit fine touch, vibration, and proprioception, crossing at the medulla before reaching the thalamus."),
  Q("y2t3_p12", "y2t3", "Clinical & Pharmacology",
    "Which pathway is primarily responsible for the non-motor symptoms of apathy and depression in Parkinson's disease?",
    ["Nigrostriatal", "Mesolimbic", "Mesocortical", "Spinocerebellar", "Rubrospinal"], 1,
    "The mesolimbic pathway (VTA → limbic system) regulates reward and motivation. Dopamine imbalance here contributes to apathy and depression in PD."),
  Q("y2t3_p13", "y2t3", "Clinical & Pharmacology",
    "Which pathological hallmark defines Parkinson's disease at the cellular level?",
    ["Beta-amyloid plaques", "Lewy bodies (α-synuclein aggregates)", "TDP-43 inclusions", "Neurofibrillary tangles", "Huntingtin protein aggregates"], 1,
    "Lewy bodies, composed of misfolded α-synuclein, are the key pathological finding in Parkinson's disease."),
  Q("y2t3_p14", "y2t3", "Clinical & Pharmacology",
    "Which mechanism best explains bradykinesia in Parkinson's disease?",
    ["Overexcitation of motor cortex", "Excess dopamine in nigrostriatal pathway", "Increased inhibitory outflow from basal ganglia to thalamus", "Increased GABA release from thalamus to motor cortex", "Lesions of the cerebellar vermis"], 2,
    "Loss of dopamine increases GPi/SNr inhibitory output to the thalamus, reducing thalamic drive to motor cortex and slowing initiation of movement."),
  Q("y2t3_p15", "y2t3", "Clinical & Pharmacology",
    "Levodopa must be combined with a peripheral DOPA decarboxylase inhibitor because:",
    ["It prevents breakdown of dopamine in the CNS", "It enhances dopamine receptor sensitivity", "It prevents peripheral conversion of levodopa to dopamine", "It blocks dopamine reuptake transporters", "It prevents dopamine degradation by COMT"], 2,
    "Peripheral decarboxylase inhibitors (e.g., benserazide, carbidopa) stop conversion of levodopa to dopamine outside the CNS, reducing side effects and ensuring more levodopa crosses the BBB."),
  Q("y2t3_e1", "y2t3", "Ethics & EBM",
    "Which feature makes a QoL scale useful for monitoring treatment response over time?",
    ["Reliability", "Validity", "Sensitivity", "Specificity", "Predictive value"], 2,
    "Sensitivity ensures the scale can detect meaningful changes in QoL over time."),
  Q("y2t3_e2", "y2t3", "Ethics & EBM",
    "When using QoL scores in treatment prioritisation, what is a major limitation?",
    ["Lack of reliability", "Lack of consensus on what defines good QoL", "Excessive sensitivity", "Inability to compare between groups", "Too much patient subjectivity"], 1,
    "There is no universal consensus on what constitutes \"good\" QoL, so scores must always be interpreted in context."),
);
