// questions/y2t4.jsx, Year 2 Theme 4: Neurocognition (legacy bank, ISOCMEDED).
// Diagram-dependent questions from the PDF (Anatomy 1–3, 6) are omitted.
window.QUESTIONS.push(
  Q("y2t4_a4", "y2t4", "Anatomy",
    "Which of the following spinal nerve roots is incorrect?",
    ["Obturator nerve L2-L4", "Femoral nerve L2-L4", "Tibial nerve S2-S4", "Sciatic nerve L4-S3", "Common fibular nerve L4-S2"], 2,
    "The tibial nerve is derived from L4-S3. The rest of the options are correct."),
  Q("y2t4_a5", "y2t4", "Anatomy",
    "Which of the following arteries terminates at the fossa located at the junction between the posterior thigh and leg?",
    ["Femoral artery", "Popliteal artery", "Pudendal artery", "Anterior tibial artery", "Posterior tibial artery"], 1,
    "This fossa is called the popliteal fossa, hence deriving the name for the artery which terminates here. The popliteal artery terminates at the lower border here to bifurcate into anterior and posterior tibial arteries which descend to supply the leg."),
  Q("y2t4_a7", "y2t4", "Anatomy",
    "Jackie, a 34 year old patient, has numbness in the anterior-lateral thigh. Which nerve is most likely to be compressed?",
    ["Sciatic", "Anterior Tibial", "Posterior tibial", "Anterior Femoral cutaneous branch", "Lateral femoral cutaneous branch"], 3,
    "The femoral nerve has cutaneous branches and the anterior branch supplies the anterior-lateral aspect."),
  Q("y2t4_a8", "y2t4", "Anatomy",
    "Which vein does the femoral vein drain into?",
    ["Anterior Tibial", "Posterior Tibial", "Popliteal", "External iliac", "Internal iliac"], 3,
    "Think of it like rivers flowing into one another. Think of the heart as the centre and the more distal veins drain into more proximal ones: popliteal drains into femoral, femoral drains into external iliac, etc."),
  Q("y2t4_h1", "y2t4", "Anatomy",
    "Which of the following correctly describes the difference between osteoblasts and osteoclasts?",
    ["Osteoblasts are derived from mesenchymal stem cells (MSCs); Osteoclasts are derived from haemopoietic stem cells (HSCs). Osteoblasts are smaller cells and uninucleated; Osteoclasts are larger cells and uninucleated.", "Osteoblasts are derived from mesenchymal stem cells (MSCs); Osteoclasts are derived from haemopoietic stem cells (HSCs). Osteoblasts are smaller cells and uninucleated; Osteoclasts are larger cells and multinucleated.", "Osteoblasts are derived from haemopoietic stem cells (HSCs); Osteoclasts are derived from mesenchymal stem cells (MSCs). Osteoblasts are smaller cells and uninucleated; Osteoclasts are larger cells and multinucleated.", "Osteoblasts are derived from haemopoietic stem cells (HSCs); Osteoclasts are derived from mesenchymal stem cells (MSCs). Osteoblasts are larger cells and uninucleated; Osteoclasts are smaller cells and multinucleated.", "Osteoblasts are derived from haemopoietic stem cells (HSCs); Osteoclasts are derived from mesenchymal stem cells (MSCs). Osteoblasts are smaller cells and multinucleated; Osteoclasts are larger cells and multinucleated."], 1,
    "Osteoblasts are derived from mesenchymal stem cells (MSCs); osteoclasts are derived from haemopoietic stem cells (HSCs). Osteoblasts are smaller, uninucleated cells; osteoclasts are larger, multinucleated cells."),
  Q("y2t4_h2", "y2t4", "Anatomy",
    "The matrix of a bone is primarily composed of:",
    ["Calcium phosphate and hydroxyapatite", "Collagen fibres and calcium phosphate", "Osteocytes, collagen and calcium ions", "Type I collagen and calcium carbonate", "Type II collagen and calcium salts"], 1,
    "The bone matrix is the same for compact and spongy bone: 2/3 is calcium phosphate and 1/3 is collagen. Calcium phosphate is hard allowing it to withstand compression whereas collagen is quite flexible and provides a framework for crystals to form."),
  Q("y2t4_h3", "y2t4", "Anatomy",
    "An example of a flat bone is:",
    ["Femur", "Patella", "Pelvis", "Sternum", "Carpal bones"], 3,
    "Flat bones are quite flattened (as the name suggests) and they protect organs such as the heart and brain whilst remaining lightweight. In this example, the sternum protects the heart."),
  Q("y2t4_h4", "y2t4", "Anatomy",
    "What is the name of mature bone cells that maintain the matrix?",
    ["Osteocytes", "Osteoblasts", "Osteoclasts", "Osteogenic stem cells", "Osteon"], 0,
    "Osteoblasts build new bone, osteoclasts break down and reabsorb bone, and osteocytes are mature bone cells that act as sensors and orchestrators for the remodeling process. Osteogenic stem cells can differentiate into osteoblasts and osteons are the basic unit of compact bone."),
  Q("y2t4_h5", "y2t4", "Anatomy",
    "Which part of the body is not made of hyaline cartilage?",
    ["Articulating surfaces", "Respiratory tract", "Epiphyseal plates of developing bones", "Intervertebral discs", "Costal cartilages"], 3,
    "Intervertebral discs need to be stronger and more adapted for support so they are made of fibrocartilage which is resistant to compression and tearing whereas hyaline cartilage needs to be more 'flexible'."),
  Q("y2t4_p1", "y2t4", "BSS",
    "Jamie, a 75 year old male, requires a neuropsychological test to assess his brain's functioning and determine which lobe is affected if so. One of the tests assesses his attention as he is required to read the colour of the ink in which the word is written. What is the name of this test?",
    ["Stroop test", "Wisconsin Card-Sorting test", "Brixton test", "Ishihara colour test", "Boston naming test"], 0,
    "The Stroop test assesses the frontal lobe via tests on executive function and attention, the person reads the colour of the ink in which the word is written and ignores the word itself. The Ishihara colour test assesses colour perception (occipital lobe). The Brixton and Wisconsin Card-Sorting tests assess executive function (frontal lobe). The Boston naming test tests memory and language (temporal lobe)."),
  Q("y2t4_p2", "y2t4", "BSS",
    "Piaget's Cognitive Development describes a series of stages in intellectual development that children evolve through. Egocentrism is a feature at which of the following stages?",
    ["Concrete operational stage", "Sensory-motor stage", "Pre-operational stage", "Formal operational stage"], 2,
    "Egocentrism is where one feels their view and thought process is shared with everyone. This is a feature of the pre-operational stage (2-7 years). The four stages are: sensory-motor (0-2y, object permanence), pre-operational (2-7y, egocentrism, symbolic thinking), concrete operational (7-11y, conservation, ordering and classifying with concrete examples), and formal operational (>11y, abstract thought and logic)."),
  Q("y2t4_p3", "y2t4", "Clinical & Pharmacology",
    "A patient is suffering from Alzheimer's Disease and is given treatment by his GP in the form of an acetylcholinesterase inhibitor called donepezil. However, he is unable to tolerate this and so is given an alternative medication. What is the name of this medication?",
    ["Memantine", "Haloperidol", "Aripiprazole", "Fluoxetine", "Carbidopa"], 0,
    "Memantine is the most common alternative after acetylcholinesterase inhibitors (if they cannot be tolerated). Memantine is a NMDA receptor antagonist used for moderate-severe Alzheimer's."),
  Q("y2t4_p4", "y2t4", "Clinical & Pharmacology",
    "Poreia, a 39 year old female, comes into the clinic with a suspected brain injury. The doctor performs tests to investigate the issue. The patient has impaired proprioception and hemineglect syndrome. Upon investigation, which lobe is most likely to have been affected?",
    ["Frontal lobe", "Parietal lobe", "Occipital lobe", "Temporal lobe"], 1,
    "The parietal lobe, also known as the somatosensory cortex, is affected in this scenario. Lesion to this lobe is characterised by contralateral hemisensory loss, hemineglect syndrome (ignoring one side), impaired proprioception, acalculia, agraphia, alexia and more."),
  Q("y2t4_p5", "y2t4", "Clinical & Pharmacology",
    "The term agnosia best describes which of the following?",
    ["Impaired object recognition", "Impaired ability to read", "Impaired ability to write", "Impaired spatial awareness", "Impaired ability to perform calculations"], 0,
    "Agnosia refers to the inability to recognise objects or people. This may be due to damage of the occipital lobe."),
  Q("y2t4_p6", "y2t4", "Clinical & Pharmacology",
    "Alzheimer's Disease is characterised by a progressive decline in cognitive function. Which of the following protein kinases is upregulated in this pathology?",
    ["CDK4", "CDK2", "CDK5", "CDK3", "CDK6"], 2,
    "CDK5 is upregulated in Alzheimer's Disease (AD). This leads to hyperphosphorylation of tau and the formation of neurofibrillary tangles, thus leading to AD."),
  Q("y2t4_p7", "y2t4", "Clinical & Pharmacology",
    "Which of the following biomarker results would likely confirm the diagnosis of Alzheimer's Disease? (Note that no biomarker can confirm a diagnosis but can aid the investigation itself)",
    ["Increase in amyloid-beta (Aβ) and decrease in phosphorylated tau (p-tau) in CSF", "Decrease in amyloid-beta (Aβ) and decrease in phosphorylated tau (p-tau) in CSF", "Increase in amyloid-beta (Aβ) and increase in phosphorylated tau (p-tau) in CSF", "Decrease in amyloid-beta (Aβ) and increase in phosphorylated tau (p-tau) in CSF"], 3,
    "In AD, we would expect a decrease in Aβ in the CSF since it is getting deposited in the brain, hence less is available to remain in the CSF. There would, however, be an increase in phosphorylated tau since this represents the upregulation of CDK5 which promotes tau hyperphosphorylation and the formation of neurofibrillary tangles."),
  Q("y2t4_p8", "y2t4", "Clinical & Pharmacology",
    "Alzheimer's Disease (AD) can arise due to mutation in certain genes. Which of the following gene mutations does NOT lead to Alzheimer's Disease?",
    ["APP", "PSEN1", "PSEN2", "LRRK2", "APOE-ε4"], 3,
    "Mutation of the LRRK2 gene would lead to Parkinson's Disease, not AD. The rest of the gene mutations would however lead to AD."),
  Q("y2t4_p9", "y2t4", "BSS",
    "Which of the following components of the brain is central for emotional processing?",
    ["Hippocampus", "Amygdala", "Hypothalamus", "Pituitary gland", "Prefrontal cortex"], 1,
    "The amygdala is the primary centre for the emotional processing of the brain. The hippocampus is vital for the consolidation of memory. The prefrontal cortex controls and regulates emotions after the amygdala has processed the information, however is not the primary processing hub."),
  Q("y2t4_p10", "y2t4", "Ethics & EBM",
    "Which of the following is NOT part of the legal test for assessing a person's capacity to make a decision under the Mental Capacity Act (2005)?",
    ["Understanding information relevant to the decision", "Retaining the information long enough to make the decision", "Weighing up the information to reach a choice", "Communicating the decision by any means", "Agreeing with the healthcare professional's opinion"], 4,
    "Capacity is about the process of decision-making, not whether the person's choice aligns with a professional's view. People are legally entitled to make unwise decisions if they have capacity."),
  Q("y2t4_p11", "y2t4", "BSS",
    "An 8-year-old sees two equal glasses of juice. One is poured into a taller, thinner glass. When asked which has more juice, she says, \"They have the same amount.\" Which Piaget's stage of cognitive development is she in?",
    ["Sensorimotor", "Preoperational", "Concrete operational", "Formal operational", "Secondary operational"], 2,
    "When a child is in the concrete operational stage, they are able to understand concepts attached to concrete situations. Time, space, and quantity are understood and can be applied. The age range of the concrete operational stage is 7-11 years old. Secondary operational stage is not a real stage."),
  Q("y2t4_p12", "y2t4", "BSS",
    "What is Broca's area responsible for?",
    ["Vision processing", "Balance and coordination", "Speech production", "Emotional regulation", "Long-term memory storage"], 2,
    "Broca's area is located in the left frontal lobe. It is responsible for speech production and articulation. Damage to the Broca's area will result in ungrammatical speech."),
  Q("y2t4_p13", "y2t4", "BSS",
    "Which part of the brain is primarily responsible for transferring information from short-term memory to long-term memory?",
    ["Cerebellum", "Amygdala", "Hippocampus", "Medulla oblongata", "Wernicke's area"], 2,
    "The hippocampus is essential for forming new memories through consolidation."),
  Q("y2t4_p14", "y2t4", "BSS",
    "Which of the following best explains how normal ageing affects information processing in the brain?",
    ["Increased grey and white matter improves multitasking and memory", "Reduced grey matter affects communication speed, while white matter loss impacts memory formation", "Reduced grey matter slows thinking and memory, while white matter decline reduces processing speed and coordination", "Ageing enhances neuroplasticity, leading to faster learning and decision-making", "Ageing primarily affects emotional processing, leaving memory and attention unchanged"], 2,
    "As part of normal ageing, both grey matter and white matter in the brain gradually decrease in volume and integrity, leading to slower and less efficient information processing."),
  Q("y2t4_p15", "y2t4", "BSS",
    "Which of the following is NOT a way of assessing the frontal lobe?",
    ["Interviewing significant others", "Colour discrimination", "Wisconsin card sorting task", "Brixton test", "Stroop test"], 1,
    "The colour discrimination test is used to assess the occipital lobe."),
  Q("y2t4_p16", "y2t4", "Clinical & Pharmacology",
    "A 75-year-old woman is brought to the GP by her daughter, who reports that her mother has been increasingly forgetful, often repeating herself and misplacing items. She recently got lost walking to the local shop she has visited for years. During the consultation, she struggles to find the right words and becomes irritable. Which of the following best represents the key clinical signs of cognitive decline seen in dementia?",
    ["Visual hallucinations, intention tremor, and resting bradykinesia", "Memory impairment, language difficulties, disorientation, and personality changes", "Hemiparesis, dysphasia, and facial droop", "Euphoria, increased goal-directed behaviour, and pressured speech", "Sudden onset of confusion, fluctuating consciousness, and visual disturbances"], 1,
    "Option B describes classic cognitive symptoms of dementia, particularly Alzheimer's disease. Option A describes features more typical of Parkinson's disease or Lewy body dementia. Option C suggests a stroke. Option D is more characteristic of mania or bipolar disorder. Option E suggests delirium."),
  Q("y2t4_p17", "y2t4", "Clinical & Pharmacology",
    "What is the primary mechanism of action of donepezil?",
    ["Inhibits dopamine reuptake to enhance frontal lobe function", "Blocks NMDA receptors to reduce excitotoxicity", "Inhibits monoamine oxidase to increase serotonin levels", "Inhibits acetylcholinesterase to increase acetylcholine availability", "Stimulates GABA receptors to reduce neuronal hyperactivity"], 3,
    "Donepezil is a reversible acetylcholinesterase inhibitor. It works by preventing the breakdown of acetylcholine in the synaptic cleft, thereby enhancing cholinergic transmission in the brain, especially in areas involved in memory and cognition."),
  Q("y2t4_p18", "y2t4", "Clinical & Pharmacology",
    "Which of the following best describes a key pathological process involved in the development of Alzheimer's disease?",
    ["Loss of dopaminergic neurons in the substantia nigra", "Hyperphosphorylation of tau protein leading to intracellular tangles", "Overactivation of NMDA receptors causing increased GABA release", "Reduced serotonin synthesis in the raphe nuclei", "Demyelination of neurons in the cerebral cortex"], 1,
    "In Alzheimer's Disease, tau proteins become hyperphosphorylated, leading to the formation of neurofibrillary tangles inside neurons. These tangles disrupt normal cellular function and correlate closely with brain atrophy and clinical symptoms, especially in the medial temporal lobe."),
  Q("y2t4_p19", "y2t4", "Ethics & EBM",
    "Which of the following statements regarding advance care planning is correct?",
    ["An Advanced Statement is legally binding and must be followed by healthcare professionals", "An Advanced Decision to Refuse Treatment (ADRT) allows a competent adult to refuse treatment at the time of making the decision only", "A Lasting Power of Attorney for health and welfare can only be used if the person loses capacity", "An ADRT does not need to be in writing, even if it relates to life-sustaining treatment", "A person must be 16 or over to make a Lasting Power of Attorney"], 2,
    "An advanced statement is not legally binding. An ADRT allows refusal of treatment for a future time when capacity may be lost. If the ADRT relates to life-sustaining treatment, it must be in writing, signed, witnessed, and include a statement that it applies even if life is at risk. A person must be 18 or over to make a Lasting Power of Attorney."),
  Q("y2t4_p20", "y2t4", "BSS",
    "What is the phonological loop of the working memory model?",
    ["Performs cognitive tasks", "Links information we see, hear and smell into the memory that we have of these events", "Stores visual information", "Processes emotional responses to stimuli", "Deals with spoken and written information"], 4,
    "The phonological loop deals with spoken and written information. Option A relates to the central executive. Option B relates to the episodic buffer. Option C relates to the visuo-spatial sketchpad."),
);
