// questions/y2t5.jsx, Year 2 Theme 5: Mental disorders (legacy bank, ISOCMEDED).
// Diagram-dependent questions from the PDF (Anatomy 1, 2) are omitted.
window.QUESTIONS.push(
  Q("y2t5_a3", "y2t5", "Anatomy",
    "Which muscle is the main extensor of the hip?",
    ["Sartorius", "Tensor fascia lata", "Gluteus medius", "Gluteus maximus", "Obturator externus"], 3,
    "Gluteus maximus is in the superficial compartment of the gluteal region. It is the main extensor of the hip joint."),
  Q("y2t5_a4", "y2t5", "Anatomy",
    "Which muscle does the sciatic nerve emerge under?",
    ["Superior gemellus", "Gluteus minimus", "Quadratus femoris", "Gluteus maximus", "Piriformis"], 4,
    "The sciatic nerve exits the pelvis below the piriformis muscle through the greater sciatic foramen."),
  Q("y2t5_a5", "y2t5", "Anatomy",
    "The main venous drainage of the hip region ultimately flows into the femoral triangle. Which muscle forms the medial borders of this triangle?",
    ["Sartorius", "Pectineus", "Adductor longus", "Inguinal ligament", "Adductor brevis"], 2,
    "The femoral triangle is bordered by the inguinal ligament (superior), sartorius (lateral) and adductor longus (medial). The contents are summarised by the mnemonic NAVEL (Femoral Nerve, Femoral Artery, Femoral Vein, Empty space, Lymph)."),
  Q("y2t5_a6", "y2t5", "Anatomy",
    "A 35 year old man sustains a deep laceration to his posterior hip region after a motorbike accident. He is unable to extend his hip or flex his knee and walks with his leg hanging limp behind him. Which nerve is most likely injured and through where does it leave the pelvis?",
    ["Superior gluteal nerve - greater sciatic foramen", "Obturator nerve - Obturator foramen", "Inferior gluteal nerve - greater sciatic foramen", "Sciatic nerve - greater sciatic foramen", "Femoral nerve - femoral canal"], 3,
    "The sciatic nerve supplies all muscles in the posterior thigh (hamstrings) so loss of hip extension & knee flexion. It exits the pelvis below the piriformis muscle through the greater sciatic foramen, this makes it vulnerable in posterior hip trauma."),
  Q("y2t5_a7", "y2t5", "Anatomy",
    "The adductor hiatus is an opening in which muscle?",
    ["Adductor Magnus", "Sartorius", "Adductor Longus", "Adductor Brevis", "Biceps femoris"], 0,
    "The adductor hiatus allows the femoral vessels (femoral artery and vein) to pass from the adductor canal into the popliteal fossa where they become popliteal artery and vein respectively."),
  Q("y2t5_a8", "y2t5", "Anatomy",
    "Which muscle of the thigh flexes both the hip and the knee?",
    ["Rectus femoris", "Sartorius", "Gracilis", "Semitendinosus", "Biceps femoris"], 1,
    "Sartorius is a long muscle that crosses the hip and knee joints; the rectus femoris flexes the thigh but extends the knee."),
  Q("y2t5_a9", "y2t5", "Anatomy",
    "Which statement is correct about the long and short heads of the biceps femoris?",
    ["Both originate from the ischial tuberosity", "Long head: ischial tuberosity; Short head: linea aspera", "Both originate from the linea aspera", "Both are innervated by the femoral nerve", "Both are innervated by the tibial division of sciatic nerve"], 1,
    "Long head: origin at ischial tuberosity and crosses hip & knee, innervated by tibial division of sciatic nerve. Short head: origin at linea aspera and only crosses knee, innervated by common fibular division of sciatic nerve. Both insert at the head of the fibula."),
  Q("y2t5_a10", "y2t5", "Anatomy",
    "A 28-year-old man suffers a knife injury to the anterior thigh. He cannot extend his knee, and the patellar reflex is absent. Which nerve is most likely injured?",
    ["Obturator nerve", "Tibial Nerve", "Common fibular", "Femoral nerve", "Superior gluteal"], 3,
    "The femoral nerve innervates the anterior thigh muscles, including the quadriceps femoris, which are responsible for knee extension and the patellar reflex. Injury results in weakness or loss of knee extension and a diminished or absent patellar reflex, while hip adduction and abduction remain intact."),
  Q("y2t5_a11", "y2t5", "Anatomy",
    "Which of the following correctly describes the origin of the pectineus muscle?",
    ["Ischial tuberosity", "Linea aspera", "Pecten of pubis", "Iliac crest", "Pubic symphysis"], 2,
    "The pectineus originates from the pecten of the pubis (pectineal line of the superior pubic ramus) and inserts on the pectineal line of the femur. It is primarily innervated by the femoral nerve, and occasionally receives a small branch from the obturator nerve, allowing it to flex and adduct the hip."),
  Q("y2t5_a12", "y2t5", "Anatomy",
    "Which muscle acts as both an adductor and hamstring?",
    ["Adductor brevis", "Gracilis", "Biceps femoris", "Adductor Longus", "Adductor Magnus"], 4,
    "Adductor magnus has adductor and hamstring parts with different origins and insertions. Clinically, this is important because the hamstring part can be affected in sciatic nerve injuries, while the adductor part is affected by obturator nerve lesions."),
  Q("y2t5_h1", "y2t5", "Anatomy",
    "Which of the following correctly distinguishes slow-twitch (Type-I) from fast-twitch (Type-II) muscle fibres?",
    ["Type I fibres fatigue quickly and rely mainly on anaerobic metabolism", "Type II fibres have high myoglobin content and appear dark red", "Type I fibers generate less ATP and are suited for short bursts of strength", "Type I fibres resist fatigue and are mitochondria rich", "Type II fibers fire slowly and are primarily used for endurance activity"], 3,
    "Slow-twitch (Type I) fibers are adapted for endurance and continuous activity because they generate ATP efficiently through aerobic metabolism and resist fatigue. Fast-twitch (Type II) fibers are designed for short bursts of power or speed, rely more on anaerobic metabolism, and fatigue quickly."),
  Q("y2t5_h2", "y2t5", "Anatomy",
    "Which of the following correctly matches the connective tissue layer with the structure it surrounds in skeletal muscle?",
    ["Epimysium surrounds individual muscle fibers", "Perimysium surrounds a fascicle", "Endomysium surrounds a group of fascicles", "Perimysium surrounds the entire muscle", "Epimysium surrounds a myofibril"], 1,
    "The epimysium surrounds the entire muscle, the perimysium surrounds a fascicle, and the endomysium surrounds individual muscle fibres."),
  Q("y2t5_h3", "y2t5", "Anatomy",
    "Under the microscope, which of the following features is characteristic of skeletal muscle fibers?",
    ["Spindle-shaped cells with a single central nucleus", "Striated fibers with multiple peripheral nuclei", "Non-striated fibers with intercalated discs", "Branching fibers with a single central nucleus", "Cells connected by gap junctions and involuntary contraction"], 1,
    "Skeletal muscle fibers are long, cylindrical, multinucleated, and have nuclei located at the periphery of the fiber. They are striated due to the regular arrangement of actin and myosin in sarcomeres, which distinguishes them from cardiac (branched, central nuclei) and smooth muscle (spindle-shaped, central nuclei)."),
  Q("y2t5_p1", "y2t5", "Clinical & Pharmacology",
    "A 49 year old patient suffers from depression and is given antidepressants for 7 weeks. He comes to see his GP again with further problems. An ECG is performed and upon its analysis it shows a prolonged QT interval. Which medication is most likely to cause this abnormality?",
    ["Venlafaxine", "Mirtazapine", "Sertraline", "Citalopram", "Fluoxetine"], 3,
    "Citalopram is an antidepressant which can prolong the QT interval."),
  Q("y2t5_p2", "y2t5", "Clinical & Pharmacology",
    "Which of the following is NOT true for Generalised Anxiety Disorder (GAD)?",
    ["GAD-7 questionnaire may be used for screening", "Symptoms present for at least 6 months", "GAD is twice as common in men than women", "Symptoms may include restlessness, fatigue and poor concentration", "Treatment involves the use of SSRIs and SNRIs as well as CBT"], 2,
    "GAD is twice as common in women than men, rather than the other way around. The rest of the options hold true."),
  Q("y2t5_p3", "y2t5", "Clinical & Pharmacology",
    "James, a 45 year old patient, has been diagnosed with depression and prescribed antidepressant medications for this. He has been using them for a few days and notices he has been feeling worse. Which of the following is the doctor most likely to do next?",
    ["Continue treatment for at least 2 weeks before switching", "Continue treatment for at least 4 weeks before switching", "Stop medication immediately and switch to alternative", "Continue at same dose for 6 months", "Continue treatment for at least 6 weeks before switching"], 1,
    "Antidepressants typically take 2-4 weeks before their therapeutic effects become apparent. In the first few days the patient may actually feel worse and this is normal, part of the early adjustment period. You would continue treatment with the same medication for at least 4 weeks before considering a change. 2 weeks is too soon whilst 6 weeks may be a stretch."),
  Q("y2t5_p4", "y2t5", "Clinical & Pharmacology",
    "Which of the following medications is not classified as a SSRI?",
    ["Citalopram", "Duloxetine", "Fluoxetine", "Sertraline", "Paroxetine"], 1,
    "Duloxetine is a SNRI, not SSRI. The rest of the options are all SSRIs."),
  Q("y2t5_p5", "y2t5", "Clinical & Pharmacology",
    "Which of the following medications acts to rapidly decrease symptoms of anxiety within 1 hour?",
    ["Sertraline", "Escitalopram", "Diazepam", "Venlafaxine", "Propranolol"], 2,
    "Diazepam is part of the benzodiazepine family, which also includes lorazepam and chlordiazepoxide. It acts rapidly to decrease symptoms of anxiety in <1 hour. However, it is addictive and patients can develop dependence long-term. Only a temporary solution."),
  Q("y2t5_p6", "y2t5", "Clinical & Pharmacology",
    "What is treatment resistant depression defined as?",
    ["Consistent feeling of low mood for a period of 3 months", "Consistent feeling of low mood for 2 months with failure to respond to SSRIs", "Failure to respond to 3 different antidepressant drugs of different classes taken for 3 weeks", "Failure to respond to 2 different antidepressant drugs of different classes, taken for at least 4 weeks", "Failure to respond to 2 different SSRIs for 3 weeks"], 3,
    "Treatment resistant depression is defined as failure to respond to 2 different antidepressant drugs of different classes, each taken for an adequate duration (at least 4 weeks)."),
  Q("y2t5_p7", "y2t5", "Clinical & Pharmacology",
    "Which of these correctly describes the mechanism of action of the GABAa receptor?",
    ["GABA binds between two adjacent a subunits to allow chloride ions to flow in", "GABA binds between a and b subunits allowing chloride ions to flow in", "GABA binds between two adjacent b subunits allowing chloride ions to flow in", "GABA binds between a and b subunits allowing potassium ions to flow in", "GABA binds between b and c subunits allowing chloride ions to flow in"], 1,
    "GABA binds at the interface between the α and β subunits of the GABAA receptor, opening the channel to allow chloride ions to flow in and hyperpolarise the neurone."),
  Q("y2t5_p8", "y2t5", "Clinical & Pharmacology",
    "What is the mechanism of action of benzodiazepines for GAD?",
    ["Bind at separate site of GABAA receptor between a and Y subunits causing influx of chloride ions", "Bind at a separate site of GABAb receptor between a and Y subunits causing influx of chloride ions", "Bind at GABAA receptor between a and b subunits causing influx of K+ ions", "Bind at GABAc receptor between a and Y subunits causing influx of chloride ions", "Bind at separate site of GABAA receptor between a and Y subunits causing influx of ammonium ions"], 0,
    "Benzodiazepines bind at a separate (allosteric) site of the GABAA receptor between the α and γ subunits, enhancing the effect of GABA and increasing chloride ion influx."),
  Q("y2t5_p9", "y2t5", "Clinical & Pharmacology",
    "Which of these is not an SSRI?",
    ["Sertraline", "Fluoxetine", "Paroxetine", "Escitalopram", "Amitriptyline"], 4,
    "Amitriptyline is a TCA not an SSRI."),
  Q("y2t5_p10", "y2t5", "Clinical & Pharmacology",
    "Which SSRI is contraindicated in arrhythmias and why?",
    ["Sertraline", "Fluoxetine", "Paroxetine", "Citalopram", "Amitriptyline"], 3,
    "Citalopram is contraindicated in patients with arrhythmias because it can prolong the QT interval which increases the risk of torsades de pointes."),
  Q("y2t5_p11", "y2t5", "Clinical & Pharmacology",
    "How does cannabis act on neurotransmitters?",
    ["THC acts as an antagonist of the pre-S CB1 receptor", "THC acts as a partial agonist on pre-S CB1 receptor", "THC is a full agonist of the Pre-S CB1 receptor", "THC is a partial agonist of the Post-S CB1 receptor", "THC is a full agonist of the Post-S CB1 receptor"], 1,
    "THC acts as a partial agonist on the pre-synaptic CB1 receptor."),
  Q("y2t5_p12", "y2t5", "Clinical & Pharmacology",
    "Which enzyme is responsible for the first step of serotonin synthesis?",
    ["Tyrosine hydroxylase", "Monoamine oxidase (MAO)", "Tryptophan Hydroxylase", "Tryptophan decarboxylase", "Dopamine β-hydroxylase"], 2,
    "Tryptophan hydroxylase converts tryptophan to 5-hydroxytryptophan, the first step of serotonin synthesis."),
  Q("y2t5_p13", "y2t5", "Clinical & Pharmacology",
    "What is the treatment of choice for those under 18 with major depressive disorder?",
    ["SSRIs", "TCAs + SSRIs for a period of 3 weeks then review", "TCAs only 3 weeks then review", "Psychotherapy (e.g CBT)", "Psychotherapy + two SSRIs of different classes"], 3,
    "Psychotherapy (e.g. CBT) is first-line for under-18s with major depressive disorder, generally speaking, try the talking therapy before medication."),
  Q("y2t5_p14", "y2t5", "Clinical & Pharmacology",
    "Which of these describes the typical sleep disturbance experienced in Major depressive disorder?",
    ["Initial insomnia (difficulty falling asleep)", "Difficulty falling asleep + waking up early", "Waking up early", "Scrolling on reels at night", "2am motivation gym session"], 2,
    "Early morning waking is the classic sleep disturbance in major depressive disorder."),
  Q("y2t5_p15", "y2t5", "Clinical & Pharmacology",
    "What is the mechanism of duloxetine?",
    ["Selectively blocks Serotonin and noradrenaline release", "Selectively blocks Serotonin release", "Selectively blocks Noradrenaline release", "Selectively blocks Norepinephrine release", "Causes gastrin release"], 0,
    "Duloxetine is an SNRI hence blocks both serotonin and noradrenaline reuptake."),
  Q("y2t5_p16", "y2t5", "Clinical & Pharmacology",
    "Which of these foods should be avoided if you're on isocarboxazid?",
    ["Cheese", "Noodles", "Oranges", "Grapefruit", "Bread"], 0,
    "Isocarboxazid is a MAO inhibitor. Tyramine is a monoamine and cheese has high levels of tyramine. If you eat cheese while your monoamine oxidase is being inhibited you won't be able to oxidise the tyramine and levels will rise, causing a potential hypertensive crisis."),
);
