// questions/y2t6.jsx, Year 2 Theme 6: Neurovascular conditions (legacy bank, ISOCMEDED).
// Diagram-dependent questions (Anatomy 1, 2) and the multi-answer knee-flexor question (Anatomy 5) are omitted.
window.QUESTIONS.push(
  Q("y2t6_a3", "y2t6", "Anatomy",
    "Danny, a 25 year old footballer, suffers a lesion to his superficial fibular nerve. Which of the following actions may be impaired?",
    ["Dorsiflexion of foot", "Extension of toes", "Flexion of knee", "Eversion of foot", "Plantarflexion of foot"], 3,
    "The superficial fibular nerve innervates the two fibularis muscles (fibularis brevis and fibularis longus). Both muscles are primarily involved in eversion of the foot, whilst the fibularis longus can additionally plantarflex the foot."),
  Q("y2t6_a4", "y2t6", "Anatomy",
    "James, a 35 year old, sees his GP to show an abnormality with his foot. The GP discovers that James has a condition called 'foot drop'. Which nerve is most likely to be damaged?",
    ["Femoral nerve", "Common peroneal (fibular) nerve", "Tibial nerve", "Obturator nerve", "Superficial peroneal (fibular) nerve"], 1,
    "A foot drop describes a condition where the foot points downwards due to an inability to dorsiflex it. This is often due to weakness or paralysis of the dorsiflexor muscles (tibialis anterior, extensor hallucis longus, extensor hallucis brevis). Since the deep peroneal nerve innervates these muscles, damage to either this nerve or the common peroneal nerve (since it originates from there) will result in a foot drop."),
  Q("y2t6_a6", "y2t6", "Anatomy",
    "Which of the following muscles inserts into the calcaneal tendon?",
    ["Tibialis anterior", "Flexor hallucis longus", "Plantaris", "Popliteus", "Flexor digitorum longus"], 2,
    "The plantaris is part of the trio of muscles in the superficial posterior compartment of the leg. All those muscles, gastrocnemius, soleus and plantaris, insert into the calcaneal tendon."),
  Q("y2t6_a7", "y2t6", "Anatomy",
    "Mr Smith has a fall at home which causes the pressure in the anterior compartment of his leg to increase. How does this affect the action of his leg muscles?",
    ["Loss of plantarflexion", "Loss of dorsiflexion", "Loss of toe flexion", "Loss of inversion", "Loss of eversion"], 1,
    "Trauma or a leg injury can cause swelling and bleeding, which will increase the pressure inside a compartment because the surrounding fascia is non-stretchy. The anterior compartment houses dorsiflexors and the deep fibular nerve, so injury to this compartment causes foot drop."),
  Q("y2t6_a8", "y2t6", "Anatomy",
    "Where is the dorsalis pedis pulse palpated?",
    ["Lateral to extensor hallucis longus tendon", "Posterior to medial malleolus", "Between sesamoids of the great toe", "On plantar surface near calcaneus", "Lateral to extensor hallucis brevis"], 0,
    "The dorsalis pedis artery is a direct continuation of the anterior tibial artery. The anterior tibial artery crosses the ankle and becomes the dorsalis pedis, which is palpated lateral to the extensor hallucis longus tendon. If a patient extends their big toe, the tendon stands out which makes it easier to palpate the pulse lateral to it."),
  Q("y2t6_a9", "y2t6", "Anatomy",
    "If the anterior tibial artery is compromised, which artery could still supply the foot?",
    ["Arcuate artery", "Anterior lateral malleolar artery", "Posterior tibial artery", "Fibular artery", "Lateral plantar artery"], 2,
    "If the anterior tibial artery is blocked, the posterior tibial artery can still supply the foot through collateral circulation. Blood flows from the posterior tibial artery into the plantar arch, then passes up through the deep plantar branch to reach the dorsalis pedis artery on the dorsum of the foot."),
  Q("y2t6_a10", "y2t6", "Anatomy",
    "Which pair correctly matches muscle to action?",
    ["Tibialis posterior - dorsiflexion", "Fibularis longus - inversion", "Tibialis anterior - dorsiflexion + inversion", "Tibialis posterior - dorsiflexion + inversion", "Tibialis anterior - plantarflexion"], 2,
    "The tibialis anterior and tibialis posterior both invert the foot on opposite sides of the ankle joint. Tibialis anterior, located in the anterior compartment and innervated by the deep fibular nerve, is the main dorsiflexor of the ankle and assists in inversion, as it runs medially."),
  Q("y2t6_a11", "y2t6", "Anatomy",
    "A runner presents with a burning pain and tingling on the sole of the foot. Symptoms worsen after long runs and there is weakness of toe flexion. Which structure is most likely compressed?",
    ["Common fibular nerve", "Superficial fibular nerve", "Deep fibular nerve", "Tibial nerve", "Sural nerve"], 3,
    "The tibial nerve passes behind the medial malleolus in the tarsal tunnel and innervates the posterior compartment of the leg and sole of the foot. Compression causes plantar sensory loss and weakness of intrinsic foot muscles."),
  Q("y2t6_a12", "y2t6", "Anatomy",
    "A patient can not stand on their tiptoes but can invert the foot. Which nerve is injured?",
    ["Common fibular nerve", "Superficial fibular nerve", "Deep fibular nerve", "Tibial nerve", "Sural nerve"], 3,
    "The posterior compartment of the leg is responsible for plantarflexion, and is innervated by the tibial nerve. Inversion partly remains due to the tibialis anterior, which is in the anterior compartment, so is supplied by the deep fibular nerve."),
  Q("y2t6_p1", "y2t6", "Clinical & Pharmacology",
    "An aneurysm is defined as the abnormal dilation of a blood vessel. This can lead to a haemorrhage and a potential stroke. Which artery is most likely to give rise to an aneurysm in the brain?",
    ["Basilar artery", "Middle cerebral artery", "Anterior communicating artery", "Internal carotid artery", "Anterior cerebral artery"], 2,
    "The anterior communicating artery is the most frequent location for intracranial aneurysms, accounting for approximately 40% of cases. This aneurysm is known as a berry (saccular) aneurysm. Rupture can lead to a subarachnoid haemorrhage (SAH) which is characterised by a sudden, thunderclap headache."),
  Q("y2t6_p2", "y2t6", "Clinical & Pharmacology",
    "A patient comes into A & E and presents with a sudden, severe headache. Which diagnostic test should be performed as soon as possible?",
    ["Non-contrast CT scan", "X-ray", "MRI scan", "Lumbar puncture", "PET scan"], 0,
    "A non-contrast CT scan is the most suitable and urgent diagnostic test for a patient suffering from a sudden, severe headache. This description most likely resembles a subarachnoid haemorrhage, hence it is pivotal to assess whether there is bleeding in the brain. This test is used first to exclude haemorrhage."),
  Q("y2t6_p3", "y2t6", "Clinical & Pharmacology",
    "Vanessa, a 45 year old, suffers from a subarachnoid haemorrhage. Which of the following medications would be most suitable to give in response?",
    ["Entacapone", "Selegiline", "Donepezil", "Nimodipine", "Amantadine"], 3,
    "Nimodipine is the first-line pharmacological treatment in response to a subarachnoid haemorrhage. It is a calcium channel blocker designed to prevent vasospasm and improve blood flow to the brain. This helps reduce the risk of an ischaemic stroke."),
  Q("y2t6_p4", "y2t6", "Clinical & Pharmacology",
    "Following a suspected subarachnoid haemorrhage, the doctor orders a lumbar puncture after the CT scan returns negative. How many hours minimum after symptom onset should you wait for CSF markers to be detectable?",
    ["3 hours", "6 hours", "9 hours", "12 hours", "15 hours"], 3,
    "In the lumbar puncture, we assess for xanthochromia (yellow discolouration of CSF due to bilirubin). This is due to breakdown of haemoglobin from red blood cells into bilirubin, which takes time. Detectable xanthochromia requires at least 12 hours."),
  Q("y2t6_p5", "y2t6", "Clinical & Pharmacology",
    "Following a TIA, once haemorrhage is excluded, which of the following is given as immediate management?",
    ["Warfarin 5mg/day", "Aspirin 300mg/day", "Apixaban 5mg/day", "Clopidogrel 75mg/day + Aspirin 75 mg/day", "Aspirin 75mg/day + Ticagrelor 75mg/day"], 1,
    "Following a TIA, once haemorrhage is excluded, the patient will be immediately started on aspirin 300mg/day for 2 weeks. This will then be reduced to 75mg/day after 2 weeks, and may be combined with clopidogrel or ticagrelor 75mg/day in dual antiplatelet therapy."),
  Q("y2t6_p6", "y2t6", "Clinical & Pharmacology",
    "A patient is currently on the medications amlodipine, candesartan, allopurinol, levodopa and apixaban. Following an intracerebral haemorrhage, which of the following medications should you immediately discontinue?",
    ["Amlodipine", "Candesartan", "Allopurinol", "Levodopa", "Apixaban"], 4,
    "Following any haemorrhage, it is vital your clotting factors should be activated to clot the blood rather than inhibit the clotting process. Hence we would immediately discontinue our anticoagulant medication here which is apixaban."),
  Q("y2t6_p7", "y2t6", "Clinical & Pharmacology",
    "A patient presents with loss of personality and contralateral leg weakness as well as impaired executive function. The doctor predicts an ischaemic stroke lesion in one of the arteries. Which of the following arteries is most likely to have suffered from ischaemia?",
    ["Middle cerebral artery (MCA)", "Anterior cerebral artery (ACA)", "Posterior cerebral artery (PCA)", "Basilar artery", "Cerebellar artery"], 1,
    "The anterior cerebral artery (ACA) supplies the medial frontal + parietal lobes of the brain which includes the medial prefrontal cortex. This cortex is responsible for executive function and personality. A lesion to this can result in impaired executive function, loss of personality and contralateral leg weakness."),
  Q("y2t6_p8", "y2t6", "Clinical & Pharmacology",
    "Where does the lateral corticospinal tract decussate?",
    ["Ventral tegmental area", "Pons", "Medullary pyramids", "C4", "C5"], 2,
    "The lateral corticospinal tract decussates (crosses over) at the pyramids of the medulla oblongata before descending into the spinal cord."),
  Q("y2t6_p9", "y2t6", "Clinical & Pharmacology",
    "Upper motor neuron fibres that decussate at the medulla form...",
    ["The anterior corticospinal tract", "The posterior corticospinal tract", "The medial corticospinal tract", "The lateral corticospinal tract", "The corticospinal tract"], 3,
    "Fibres that cross at the medullary pyramids continue as the lateral corticospinal tract, controlling voluntary limb movements."),
  Q("y2t6_p10", "y2t6", "Clinical & Pharmacology",
    "Which descending spinal tract is responsible for adjusting posture to maintain balance?",
    ["Corticospinal", "Corticobulbar", "Vestibulospinal", "Rubrospinal", "Colliculospinal"], 2,
    "The vestibulospinal tract originates from the vestibular nuclei and helps maintain posture and balance by influencing extensor muscle tone."),
  Q("y2t6_p11", "y2t6", "Clinical & Pharmacology",
    "Which of the following is a sign of a lower motor neuron lesion?",
    ["Increased muscle tone", "Increased reflexes", "Upward Babinski Sign", "Sustained clonus", "Areflexia"], 4,
    "Lower motor neuron lesions cause loss of reflexes (areflexia), flaccid paralysis, and muscle wasting due to denervation."),
  Q("y2t6_p12", "y2t6", "Clinical & Pharmacology",
    "Broca's area and Wernicke's area are connected by a large bundle of nerve fibres called the...",
    ["Superior colliculus", "Internal capsule", "Arcuate fasciculus", "Lateral sulcus", "Genu"], 2,
    "The arcuate fasciculus connects Broca's (speech production) and Wernicke's (language comprehension) areas, enabling coherent speech."),
  Q("y2t6_p13", "y2t6", "Clinical & Pharmacology",
    "Occlusion of the ACA would cause",
    ["Speech defects", "Death due to respiratory failure", "Contralateral paralysis mostly in the lower face and arm", "Paralysis and sensory loss in the lower face and arm", "Paralysis and sensory loss in contralateral leg and perineum"], 4,
    "The anterior cerebral artery supplies the medial part of the motor and sensory cortices, which control the contralateral leg and perineum."),
  Q("y2t6_p14", "y2t6", "Clinical & Pharmacology",
    "Homonymous hemianopia can present in which stroke",
    ["Total anterior circulation infarct", "Partial anterior circulation infarct", "Posterior circulation infarct", "Haemorrhagic stroke", "All of the above"], 2,
    "The posterior cerebral artery supplies the occipital lobe, and its infarction can cause contralateral homonymous hemianopia."),
  Q("y2t6_p15", "y2t6", "Clinical & Pharmacology",
    "Which neurotransmitter transmits nerve impulses from upper to lower motor neurons?",
    ["GABA", "ACh", "Glutamate", "Serotonin", "Na+"], 2,
    "Glutamate is the excitatory neurotransmitter that transmits signals from upper to lower motor neurons in the corticospinal pathway."),
  Q("y2t6_p16", "y2t6", "Clinical & Pharmacology",
    "Which drug catalyses the conversion of plasminogen to plasmin?",
    ["Sertraline", "Alteplase", "Phenelzine", "Atorvastatin", "Diazepam"], 1,
    "Alteplase is a tissue plasminogen activator (tPA) that converts plasminogen to plasmin, promoting fibrinolysis and clot breakdown."),
  Q("y2t6_e1", "y2t6", "Ethics & EBM",
    "A 68-year-old man suffers an ischaemic stroke affecting his right middle cerebral artery territory. After a short hospital stay, he is discharged home with mild residual left-sided weakness. According to DVLA guidance, what should he be advised to do regarding driving?",
    ["He must inform the DVLA immediately and stop driving for at least 1 month", "He can continue driving if his symptoms are mild", "He only needs to inform the DVLA if his vision is affected", "He must stop driving for 6 months but does not need to notify the DVLA", "He must inform the DVLA and stop driving permanently"], 0,
    "After a stroke or TIA, patients must stop driving for a minimum of one month and notify the DVLA; driving can only resume once medical clearance confirms adequate recovery."),
  Q("y2t6_b1", "y2t6", "BSS",
    "There are 5 primary models of disability which focus on various perspectives on how disability is understood and addressed in society. Sunil, a 35 year old male, suffers from a rare cancer and is often in and out of hospital for his treatment. Which of the following models is the most likely to take a holistic approach in treating him?",
    ["Medical model", "Social model", "Charity model", "Human rights model", "Biopsychosocial model"], 4,
    "The biopsychosocial model takes the most holistic approach since it takes into account all 3 factors: biological, psychological and social factors when treating a patient rather than solely the physical health side, unlike the medical model, which focuses on the individual's condition as something requiring fixing."),
);
