// questions/y2t7.jsx, Year 2 Theme 7: Severe mental disorders (legacy bank, ISOCMEDED).
// Diagram-dependent questions from the PDF (Anatomy 1–3) are omitted.
window.QUESTIONS.push(
  Q("y2t7_a4", "y2t7", "Anatomy",
    "Which of the following glands typically produces both serous and mucous secretions?",
    ["Parotid gland", "Submandibular gland", "Sublingual gland", "Otic ganglion", "Lacrimal gland"], 1,
    "There are 3 salivary glands, producing varying secretions: parotid, serous; submandibular, serous + mucous (remember S + M for submandibular); sublingual, mucous."),
  Q("y2t7_a5", "y2t7", "Anatomy",
    "Which of the following nerve modalities/fibres of the facial nerve (CN VII) innervate the muscles of facial expression?",
    ["Special Visceral Efferent (SVE)", "General Somatic Afferent (GSA)", "General Somatic Efferent (GSE)", "Special Visceral Afferent (SVA)", "General Visceral Afferent (GVA)"], 0,
    "The facial nerve (CN VII) consists of 4 nerve modalities: GSA, sensory innervation of external acoustic meatus; SVA, taste from anterior 2/3 tongue; GVE, parasympathetic innervation of salivary glands (apart from parotid); SVE, innervation of muscles of facial expression + stapedius + stylohyoid."),
  Q("y2t7_a6", "y2t7", "Anatomy",
    "A patient struggles to puff their cheeks in a cranial nerve examination as air escapes through their teeth. Which is the best explanation for this deficit?",
    ["Damage to the trigeminal nerve affecting the masseter muscle", "Paralysis of the buccinator due to an injury to the facial nerve", "Paralysis of the orbicularis oris muscle affecting lip closure", "Paralysis of risorius muscle", "Damage to the trigeminal nerve affecting the lateral pterygoid muscle"], 1,
    "The function of the buccinator muscle is to compress the cheek against the teeth. An injury to the facial nerve resulting in paralysis of the buccinator would impair its function, resulting in the cheek becoming flaccid so air leaks out."),
  Q("y2t7_a7", "y2t7", "Anatomy",
    "During a neurological examination, a patient is asked to protrude their mandible. Their jaw deviates to one side. Which nerve is most likely to be injured?",
    ["Facial nerve", "Maxillary nerve (V2)", "Hypoglossal nerve", "Glossopharyngeal nerve", "Mandibular nerve (V3)"], 4,
    "The mandibular branch of the trigeminal nerve (V3) is responsible for innervating the muscles of mastication. The lateral pterygoid muscle (a muscle of mastication) is responsible for protrusion of the mandible, therefore the most likely suggestion is that there is damage to V3."),
  Q("y2t7_a8", "y2t7", "Anatomy",
    "Examination of a patient's tongue demonstrates weakness in tongue retraction and elevation. Which muscle is most likely impaired?",
    ["Genioglossus", "Palatoglossus", "Hyoglossus", "Styloglossus", "Longitudinal muscle of the tongue"], 3,
    "The styloglossus muscle is responsible for tongue retraction and elevation. Therefore, impairment of this muscle will result in the abnormalities described above."),
  Q("y2t7_a9", "y2t7", "Anatomy",
    "A patient is struggling to close their mouth, leading to drooling from one corner. On examination, there is weakness in the muscle that controls lip sealing. What muscle is likely to be responsible?",
    ["Buccinator", "Lateral pterygoid", "Orbicularis oris", "Orbicularis oculi", "Risorius"], 2,
    "Orbicularis oris has two components, the labial part and the marginal part. Both parts are responsible for compression and protrusion of the lips. Therefore, if this muscle is weakened, a patient may have difficulty closing their lips fully."),
  Q("y2t7_a10", "y2t7", "Anatomy",
    "A patient has difficulty tightly closing their eye on neurological examination. Which muscle is most likely affected?",
    ["Orbicularis oculi", "Levator palpebrae superioris", "Frontalis", "Zygomaticus major", "Orbicularis oris"], 0,
    "Orbicularis oculi has three components, the orbital, palpebral and lacrimal parts. The orbital part specifically is responsible for voluntary tight closure of the eye."),
  Q("y2t7_a11", "y2t7", "Anatomy",
    "During vertical acceleration, what primary vestibular organ activates the hair cells?",
    ["Utricle", "Saccule", "Semicircular canals", "Cochlea", "Vestibular nerve"], 1,
    "The saccule is an otolith organ that detects linear acceleration. Specifically, it detects linear acceleration in the vertical plane, for example: jumping or falling."),
  Q("y2t7_a12", "y2t7", "Anatomy",
    "At what level does the vestibular nerve enter the brainstem?",
    ["Cervical spinal cord", "Medulla", "Lower pons/medullary junction", "Midbrain", "Upper pons"], 2,
    "The vestibular nerve is a branch of the vestibulocochlear nerve, CN VIII. Use the rule of 4s: the first 4 cranial nerves lie above the pons, the next 4 lie in the pons, and the final four lie in the medulla. CN VIII lies in the pons, right toward the bottom, at the junction of the pons and medulla."),
  Q("y2t7_p1", "y2t7", "Clinical & Pharmacology",
    "Dopamine antagonism at which of the following dopaminergic pathways will result in worsening and exacerbation of negative symptoms?",
    ["Nigrostriatal pathway", "Mesolimbic pathway", "Mesocortical pathway", "Tuberoinfundibular pathway"], 2,
    "The mesocortical pathway is involved in emotions and cognition. Dopamine antagonism leads to reduced dopamine levels, thus worsening negative symptoms such as anhedonia. This pathway is already underactive in schizophrenia. Nigrostriatal D2 antagonism causes extrapyramidal symptoms; mesolimbic antagonism reduces positive symptoms; tuberoinfundibular antagonism causes excess prolactin release (galactorrhoea, gynaecomastia)."),
  Q("y2t7_p2", "y2t7", "Clinical & Pharmacology",
    "Which of the following second-generation antipsychotics (SGA) requires regular blood monitoring?",
    ["Risperidone", "Aripiprazole", "Clozapine", "Quetiapine", "Olanzapine"], 2,
    "Clozapine requires regular blood monitoring due to its risk of agranulocytosis (drop in WBCs)."),
  Q("y2t7_p3", "y2t7", "Clinical & Pharmacology",
    "A 49 year old patient suffers from depression and is given antidepressants for 7 weeks. He comes to see his GP again with further problems. An ECG is performed and upon its analysis it shows a prolonged QT interval. Which medication is most likely to cause this abnormality?",
    ["Venlafaxine", "Mirtazapine", "Sertraline", "Citalopram", "Fluoxetine"], 3,
    "Citalopram is an antidepressant which can prolong the QT interval."),
  Q("y2t7_p4", "y2t7", "Clinical & Pharmacology",
    "Kess, a 27 year old female, has been diagnosed with Bipolar Disorder. The GP is considering suitable treatment for her. The GP considers giving lithium, however this is contraindicated by an electrolyte abnormality that Kess has. Which electrolyte abnormality is contraindicated by lithium?",
    ["Hyperkalaemia", "Hyponatremia", "Hypokalaemia", "Hypernatremia", "Hypocalcaemia"], 1,
    "Hyponatremia is described as low sodium (Na+) levels in the blood. Lithium is contraindicated in hyponatremia since low sodium levels lead to kidneys retaining greater lithium to compensate. This leads to the risk of lithium toxicity."),
  Q("y2t7_p5", "y2t7", "Clinical & Pharmacology",
    "Which of the following medications is NOT characterised as a 'mood stabiliser'?",
    ["Carbamazepine", "Lithium", "Quetiapine", "Valproate", "Lamotrigine"], 2,
    "Quetiapine, although commonly used in Bipolar Disorder, is not classified as a mood stabiliser. Instead it is a second generation antipsychotic (SGA) with some properties for stabilising mood, however not to the extent of the classic mood stabilisers which include lithium, valproate, carbamazepine and lamotrigine."),
  Q("y2t7_p6", "y2t7", "Clinical & Pharmacology",
    "Which of the following descriptions correctly describes Bipolar II Disorder?",
    ["More than one episode of severe depression, and one episode of hypomania", "Mixture of manic episodes with depression, at least one manic episode >1 week", "At least 4 mood episodes in a 12 month period", "More than one episode of severe mania, and one episode of depression", "Mixture of manic episodes with depression, at least one depression episode >1 week"], 0,
    "Bipolar II Disorder is characterised by predominantly depression, more than one episode of severe depression should be present, plus one episode of hypomania (mild). Bipolar I Disorder, on the other hand, is a mixture of both with at least one manic episode lasting longer than a week."),
  Q("y2t7_p7", "y2t7", "Clinical & Pharmacology",
    "Which of the following is a positive symptom of schizophrenia?",
    ["Avolition", "Blunted affect", "Delusions", "Alogia", "Asociality"], 2,
    "Positive symptoms are excesses or distortions of normal function: delusions, hallucinations, disorganised speech, thought disorder. Negative symptoms are reductions in normal emotional/motivational function: avolition, alogia, blunted affect, asociality."),
  Q("y2t7_p8", "y2t7", "Clinical & Pharmacology",
    "According to DSM-5, diagnosing schizophrenia requires at least:",
    ["1 symptom for 1 month", "2 symptoms for 1 month, including 1 of delusions/hallucinations/disorganised speech", "3 symptoms for 2 weeks", "1 first-rank symptom", "4 symptoms for 6 months"], 1,
    "DSM-5 requires 2 of the 5 core symptoms (delusions, hallucinations, disorganised speech, disorganised or catatonic behaviour, negative symptoms), including at least 1 of the first 3, most of the time for at least 1 month within an episode of illness lasting at least 6 months. This prevents misdiagnosis of brief psychotic episodes or schizophreniform disorder (<6 months)."),
  Q("y2t7_p9", "y2t7", "Clinical & Pharmacology",
    "Which dopamine pathway is primarily associated with extrapyramidal side effects when blocked?",
    ["Mesolimbic", "Mesocortical", "Nigrostriatal", "Tuberoinfundibular", "Nigrolimbic"], 2,
    "The nigrostriatal pathway (substantia nigra → dorsal striatum) controls involuntary movement. Blocking dopamine D2 receptors here (via antipsychotics) can cause parkinsonism, dystonia, akathisia and tardive dyskinesia. This is why antipsychotic dose must balance psychosis improvement with risk of EPSE."),
  Q("y2t7_p10", "y2t7", "Clinical & Pharmacology",
    "Which serious adverse effect is uniquely associated with clozapine?",
    ["Agranulocytosis", "Anhedonia", "Hypercalcemia", "Hyperprolactinemia", "Thrombocytopenia"], 0,
    "Clozapine is uniquely effective for treatment-resistant schizophrenia, but it carries a rare, life-threatening risk of agranulocytosis: dangerously low neutrophils leading to severe infection. Because of this risk, clozapine requires regular blood counts and strict national monitoring systems."),
  Q("y2t7_p11", "y2t7", "Clinical & Pharmacology",
    "Which drug is teratogenic and associated with neural tube defects?",
    ["Lithium", "Lamotrigine", "Valproate", "Clozapine", "Quetiapine"], 2,
    "Valproate is a powerful GABAergic antiepileptic used in acute mania and bipolar prophylaxis, but it is highly teratogenic, causes neural tube defects (e.g. spina bifida), and causes major congenital malformations and long-term neurodevelopmental deficits. Therefore, it is contraindicated in pregnancy and avoided in females of childbearing age."),
  Q("y2t7_p12", "y2t7", "Clinical & Pharmacology",
    "Schizoaffective disorder requires features of schizophrenia plus:",
    ["PTSD", "Anxiety Disorder", "Mood Disorder", "Autism", "Personality Disorder"], 2,
    "Schizoaffective disorder sits between schizophrenia and mood disorders. Diagnosis requires a full episode of schizophrenia symptoms AND a major mood episode (depressive or manic) during the same period. Crucially, psychotic symptoms must also occur in the absence of mood symptoms at times, otherwise it is a mood disorder with psychosis."),
  Q("y2t7_p13", "y2t7", "Clinical & Pharmacology",
    "Bipolar I disorder typically presents at what age?",
    ["3", "18", "25", "30", "42"], 1,
    "Bipolar I mean onset is ~18 years; Bipolar II ~mid-20s. Early onset reflects the neurodevelopmental basis of bipolar disorder and explains why many patients first present during late adolescence/early adulthood, often after a first manic episode."),
  Q("y2t7_p14", "y2t7", "Clinical & Pharmacology",
    "Dopamine antagonists begin to work as soon as:",
    [">60-70% of the striatal D2 receptors are blocked", ">60-70% of the tuberoinfundibular D5 receptors are blocked", ">20-30% of the striatal D2 receptors are destroyed", ">70-80% of the limbic 5HT2 receptors are blocked", "20% of the dopamine in the brain is metabolised"], 0,
    "Antipsychotics work by blocking D2 receptors in the striatum. Therapeutic threshold: ~60–70% D2 occupancy. Side-effects threshold: >75–80% → motor EPSE. Too low: no improvement; too high: EPSE, hyperprolactinaemia, worsening negative symptoms."),
  Q("y2t7_p15", "y2t7", "Clinical & Pharmacology",
    "VMAT is responsible for:",
    ["Breaking down dopamine", "Transporting dopamine into synaptic vesicles", "Reuptake of dopamine from the synapse", "Blocking sodium channels", "Stimulating serotonin synthesis"], 1,
    "VMAT loads synthesised dopamine into presynaptic vesicles for safe storage. Drugs like reserpine block VMAT, leading to dopamine depletion and depression-like symptoms. Psychostimulants like amphetamine reverse VMAT → increased release."),
  Q("y2t7_e1", "y2t7", "Ethics & EBM",
    "As per the Mental Health Act 1983, which section enables a consultant psychiatrist to detain an inpatient for up to 72 hours?",
    ["Section 2", "Section 5(2)", "Section 5(4)", "Section 4", "Section 3"], 1,
    "Section 5(2) enables a consultant to detain an inpatient for up to 72 hours. Section 5(4) enables a nurse to do this for up to 6 hours. Section 2 allows detention for up to 28 days for assessment; Section 3 for up to 6 months for treatment; Section 4 enables emergency detention up to 72 hours."),
  Q("y2t7_e2", "y2t7", "Ethics & EBM",
    "Section 2 of the Mental Health Act allows detention for:",
    ["Emergency 72h assessment", "Assessment up to 28 days", "Treatment for 6 months", "Police holding powers", "Nurse holding powers"], 1,
    "Section 2 (MHA 1983) is used for assessment, not long-term treatment; lasts up to 28 days; requires 2 doctors + an AMHP; used when diagnosis is unclear but detention is required for safety. Section 3: treatment, up to 6 months; Section 4: emergency, 72 hours; Section 136: police holding power."),
  Q("y2t7_b1", "y2t7", "BSS",
    "Early Intervention Services (EIS) typically support a patient for how long?",
    ["1 month", "6 months", "1 year", "3 years", "Lifetime duration"], 3,
    "EIS covers the first 3 years following first-episode psychosis, typically for people aged 14–65. This is considered the critical period for improving prognosis via rapid treatment, vocational support, psychological therapies and family interventions."),
  Q("y2t7_b2", "y2t7", "BSS",
    "The Recovery Model focuses on:",
    ["Cure of mental illness", "The clinician's goals for the patient", "Minimising symptoms only", "Enabling meaningful life even with ongoing symptoms", "Removing all treatment responsibilities from the patient"], 3,
    "The Recovery Model emphasises hope, empowerment, personal responsibility, meaning and purpose, and living well despite symptoms. It is not about curing mental illness but about helping people live fulfilling lives with or without ongoing symptoms."),
);
