// questions/y2t8.jsx, Year 2 Theme 8: Vision & hearing (legacy bank, ISOCMEDED).
// Diagram-dependent questions from the PDF (Anatomy 1–3) are omitted.
window.QUESTIONS.push(
  Q("y2t8_a4", "y2t8", "Anatomy",
    "A patient suffers damage to their Meyer's Loop. Which of the following lesions would they suffer?",
    ["Monocular loss", "Contralateral superior quadrantanopia", "Contralateral inferior quadrantanopia", "Bitemporal hemianopia", "Contralateral homonymous hemianopia", "Homonymous hemianopia with macular sparing"], 1,
    "Damage to the Meyer's Loop (temporal lobe) would cause contralateral superior quadrantanopia since the loop carries inferior retinal fibres which represent the superior visual field. On the other hand, damage to the parietal radiations would cause contralateral inferior quadrantanopia."),
  Q("y2t8_a5", "y2t8", "Anatomy",
    "Damage to the occipital cortex would cause which of the following lesions?",
    ["Monocular loss", "Contralateral superior quadrantanopia", "Contralateral inferior quadrantanopia", "Bitemporal hemianopia", "Contralateral homonymous hemianopia", "Homonymous hemianopia with macular sparing"], 5,
    "Damage to the occipital cortex would cause homonymous hemianopia with macular sparing. The macula is spared due to having dual blood supply since both the PCA and MCA supply it."),
  Q("y2t8_a6", "y2t8", "Anatomy",
    "Which cranial nerve innervates the lateral rectus muscle?",
    ["Trochlear", "Abducens", "Optic", "Oculomotor", "Trigeminal"], 1,
    "The abducens nerve innervates the lateral rectus muscle."),
  Q("y2t8_a7", "y2t8", "Anatomy",
    "Which of the following extra ocular muscles does not adduct the eye at all?",
    ["Inferior rectus", "Inferior oblique", "Medial rectus", "Superior rectus", "Superior oblique"], 1,
    "The inferior oblique muscle is involved in abduction and elevation."),
  Q("y2t8_a8", "y2t8", "Anatomy",
    "Which of the following extra ocular muscles attaches to the sphenoid bone?",
    ["Medial rectus", "Inferior oblique", "Superior rectus", "Superior oblique", "Inferior rectus"], 3,
    "The superior oblique muscle originates from the sphenoid bone."),
  Q("y2t8_a9", "y2t8", "Anatomy",
    "How many semicircular canals are there within the inner ear?",
    ["2", "3", "4", "5", "6"], 1,
    "Each inner ear has 3 canals (anterior, posterior, lateral)."),
  Q("y2t8_a10", "y2t8", "Anatomy",
    "Which layer of the eye contains the choroid?",
    ["Fibrous", "Vascular", "Outer retina", "Inner retina", "Cornea"], 1,
    "The vascular layer consists of the choroid, ciliary body and iris."),
  Q("y2t8_p1", "y2t8", "Clinical & Pharmacology",
    "Urvase, a 45 year old female, suffers from a condition called ptosis. Which of the following below describes ptosis?",
    ["Eye deviates down and outwards", "Eye deviates up and outwards", "Loss of accommodation reflex", "Pupil dilates and is unresponsive to light", "Drooping of the upper eyelid"], 4,
    "Ptosis describes the drooping of the upper eyelid due to a lesion of the oculomotor nerve (CN III). A lesion to this nerve results in denervation of the levator palpebrae superioris which is normally involved in elevating the upper eyelid. A CN III lesion can also cause the eye to deviate down and out, however this condition is not specifically called ptosis."),
  Q("y2t8_p2", "y2t8", "Clinical & Pharmacology",
    "Jane, an 80 year old female, has a pituitary adenoma which compresses the optic chiasm. Which of the following visual field defects is she most likely to suffer from?",
    ["Monocular blindness", "Bitemporal hemianopia", "Homonymous hemianopia", "Homonymous hemianopia with macular sparing", "Retinitis pigmentosa"], 1,
    "Compression of the optic chiasm leads to bitemporal hemianopia (loss of temporal fields)."),
  Q("y2t8_p3", "y2t8", "Clinical & Pharmacology",
    "Which of the following pathologies is most likely to be found in multiple sclerosis?",
    ["Glaucoma", "Optic neuritis", "Cataract", "Conjunctivitis", "Diabetic retinopathy"], 1,
    "Optic neuritis is a classic presentation of multiple sclerosis (MS). It is characterised by the inflammation of the optic nerve. This leads to pain and blurred vision."),
  Q("y2t8_p4", "y2t8", "Clinical & Pharmacology",
    "A patient with an isolated right oculomotor (CN III) palsy attempts to focus on a near object. Which component of the near reflex will be impaired?",
    ["Pupillary constriction bilaterally", "Lens accommodation in the right eye", "Convergence of the right eye", "Retinal phototransduction", "Signal transmission in the LGN"], 2,
    "Convergence requires bilateral contraction of the medial rectus muscles, which are innervated by the oculomotor nerve (CN III). A right CN III palsy prevents adduction of the right eye, impairing convergence on that side."),
  Q("y2t8_p5", "y2t8", "Clinical & Pharmacology",
    "Which of the following correctly describes the immediate cellular response to light hitting a rod photoreceptor?",
    ["Increased intracellular cGMP → Na influx → depolarisation", "Decreased PDE activity → hyperpolarisation", "Closure of Na channels → hyperpolarisation", "Increased glutamate release → bipolar cell activation", "Opening of Ca² channels → depolarisation"], 2,
    "Light activates rhodopsin, which activates G-protein and phosphodiesterase, reducing cGMP. This causes closure of Na channels, leading to hyperpolarisation and reduced glutamate release."),
  Q("y2t8_p6", "y2t8", "Clinical & Pharmacology",
    "A 52-year-old patient complains of gradually worsening difficulty reading small print. Distance vision remains good. What is the underlying physiological change?",
    ["Increased corneal thickness", "Reduced aqueous humour production", "Loss of lens elasticity", "Weakening of medial rectus muscles", "Increased vitreous viscosity"], 2,
    "Presbyopia occurs due to age-related stiffening of the lens, reducing its ability to become more convex during accommodation for near vision."),
  Q("y2t8_p7", "y2t8", "Clinical & Pharmacology",
    "A 58-year-old man presents with sudden, painless loss of vision in his right eye. There is an absent direct and consensual light reflex when light is shone in the right eye, but both reflexes are present when light is shone in the left eye. Where is the lesion most likely located?",
    ["Right optic nerve", "Left optic nerve", "Optic chiasm", "Right optic tract", "Right oculomotor nerve"], 0,
    "Absent direct and consensual responses when the right eye is stimulated indicates failure of the afferent pathway (CN II) on the right. Normal responses when the left eye is stimulated confirm intact efferent pathways."),
  Q("y2t8_p8", "y2t8", "Clinical & Pharmacology",
    "A woman with normal colour vision has a son with red–green colour blindness. Which of the following is most likely true?",
    ["The father is also colour blind", "The mother is a carrier", "The mutation is autosomal recessive", "The mutation is on chromosome 7", "The mutation affects rods"], 1,
    "Red–green colour blindness is X-linked recessive. Affected males inherit the defective X chromosome from their mother, who is typically an asymptomatic carrier."),
  Q("y2t8_p9", "y2t8", "Clinical & Pharmacology",
    "A 26-year-old woman presents with painful visual loss in one eye that worsens with eye movement. Visual acuity is reduced and a relative afferent pupillary defect is present. What is the most likely underlying pathology?",
    ["Retinal detachment", "Demyelination of the optic nerve", "Compression of the optic chiasm", "Occlusion of the central retinal artery", "Ciliary body dysfunction"], 1,
    "This presentation is classic for optic neuritis, which typically affects young adults and is strongly associated with multiple sclerosis. Key features include pain on eye movement, reduced visual acuity, and a relative afferent pupillary defect (RAPD). The underlying pathology is inflammatory demyelination of the optic nerve."),
  Q("y2t8_p10", "y2t8", "Clinical & Pharmacology",
    "A 55 year old patient presents with difficulty hearing. On Weber's, the sound lateralises to the left ear. He is Rinne's positive in the right ear. What is the most likely diagnosis?",
    ["Left conductive hearing loss", "Right conductive hearing loss", "Left sensorineural hearing loss", "Right sensorineural hearing loss", "Mixed hearing loss"], 0,
    "In conductive hearing loss, Weber's lateralises to the affected ear. Rinne's positive (air > bone conduction) in the right ear is normal, so the left ear with lateralisation indicates left conductive hearing loss."),
  Q("y2t8_p11", "y2t8", "Clinical & Pharmacology",
    "Which of the following is the most appropriate treatment for persistent otitis media with effusion?",
    ["Acetic acid", "Oral antibiotics", "Watchful waiting", "Myringotomy", "Surgical intervention with grommets"], 4,
    "OME is considered persistent when after 3 months of watchful waiting it has not spontaneously resolved (which it does in most cases). After 3 months, surgical intervention with tympanostomy tubes (grommets) is considered."),
  Q("y2t8_p12", "y2t8", "Clinical & Pharmacology",
    "A 32 year old pregnant woman is having seizures and requires anti-epileptic medication. Which of the following is the most appropriate?",
    ["Valproate", "Lamotrigine", "Phenytoin", "Carbamazepine", "Phenobarbital"], 1,
    "Valproate is contraindicated in pregnant women as it carries a very high risk of neural tube defects, craniofacial anomalies and neurodevelopmental delays. Phenytoin, carbamazepine and phenobarbital are also contraindicated in pregnancy. Lamotrigine and levetiracetam are first-line anti-epileptics in pregnant women."),
  Q("y2t8_p13", "y2t8", "Clinical & Pharmacology",
    "What type of seizure involves rhythmic, jerking movements of the body, and typically involves the arms, legs, or both?",
    ["Tonic-clonic", "Tonic", "Clonic", "Atonic", "Myoclonic"], 0,
    "Tonic-clonic seizures involve 2 phases: the tonic phase, where muscles stiffen and air is expelled from the lungs, and the clonic phase, which is rapid rhythmic jerking of the limbs. Atonic seizures involve a loss of muscle tone; myoclonic seizures involve sudden, brief jerking movements lasting a fraction of a second to a few seconds."),
  Q("y2t8_p14", "y2t8", "Clinical & Pharmacology",
    "A 50 year old male presents with brief episodes of vertigo that are triggered when he moves his head or lies down. He does not have hearing loss or tinnitus, and is diagnosed with BPPV. What is the most appropriate treatment?",
    ["Dix-Hallpike manoeuvre", "Meclizine", "Epley manoeuvre", "Watchful waiting", "Vestibular rehabilitation exercises"], 2,
    "The first-line treatment for BPPV is the Epley manoeuvre which acts to dislodge the crystals from the semicircular canals. Not to be confused with the Dix-Hallpike manoeuvre, which is used to diagnose BPPV."),
);
