// questions/y2t9.jsx, Year 2 Theme 9: Pain & arthritis (legacy bank, ISOCMEDED).
// Diagram-dependent questions from the PDF (Anatomy 1, 2) are omitted.
window.QUESTIONS.push(
  Q("y2t9_a3", "y2t9", "Anatomy",
    "The adduction of the vocal cords is pivotal for producing sound and protecting the airway during swallowing. Which of the following muscles contribute to adduction of the vocal cords?",
    ["Lateral cricoarytenoid, transverse arytenoid and oblique arytenoid", "Thyrohyoid muscle", "Lateral cricoarytenoid and posterior cricoarytenoid", "Posterior cricoarytenoid", "Cricothyroid muscle"], 0,
    "Adduction of the vocal cords is performed by 3 muscles: the lateral cricoarytenoid, transverse and oblique arytenoid muscles. However, abduction of the vocal cords is solely done by the posterior cricoarytenoid muscle."),
  Q("y2t9_a4", "y2t9", "Anatomy",
    "The anterior triangle of the neck is split up into different divisions. One of these divisions is the carotid triangle. Which of the following contents does NOT feature in the carotid triangle?",
    ["Facial artery", "Vagus nerve", "Internal jugular vein", "Common carotid artery", "Hypoglossal nerve"], 0,
    "The carotid triangle contains the vagus nerve, internal jugular vein, common carotid and external + internal carotid arteries as well as the hypoglossal nerve. However, it does not contain the facial artery since this is found in the submandibular triangle."),
  Q("y2t9_a5", "y2t9", "Anatomy",
    "Specifically which muscle separates the Occipital and Supraclavicular triangles of the Posterior triangle of the neck?",
    ["Geniohyoid", "Trapezius", "Superior Belly of Digastric", "Inferior Belly of Omohyoid", "Sternocleidomastoid"], 3,
    "The inferior belly of the omohyoid muscle passes into the Posterior Triangle of the neck, and separates the Posterior Triangle into the Occipital Triangle and the Supraclavicular Triangle."),
  Q("y2t9_a6", "y2t9", "Anatomy",
    "A patient has difficulty turning their head from side to side and shrugging their shoulders after injury to the neck. Which triangle of the neck has most likely been damaged?",
    ["Supraclavicular", "Muscular", "Submandibular", "Submental", "Occipital"], 4,
    "Difficulty in turning the head side to side as well as shrugging the shoulders indicates damage to CN XI (Accessory Nerve). CN XI passes into the Posterior Triangle of the neck, more specifically into the Occipital Triangle."),
  Q("y2t9_a7", "y2t9", "Anatomy",
    "The Median Nerve can be found in a specific nerve plexus, what is the name of this nerve plexus AND which triangle of the neck is it found in?",
    ["Brachial Plexus; Occipital Triangle", "Brachial Plexus; Supraclavicular Triangle", "Cervical Plexus; Occipital Triangle", "Cervical Plexus; Submental Triangle", "Coeliac Plexus; Supraclavicular Triangle"], 1,
    "The Median Nerve is found within the Brachial Plexus, and the Brachial Plexus is found near the shoulder, thus it is contained within the Supraclavicular Triangle of the neck (part of the Posterior Triangle)."),
  Q("y2t9_a8", "y2t9", "Anatomy",
    "Which muscle separates the Anterior and Posterior Triangles of the neck?",
    ["Omohyoid", "Trapezius", "Digastric", "Sternocleidomastoid", "Mylohyoid"], 3,
    "The sternocleidomastoid separates the Anterior and Posterior Triangles of the neck."),
  Q("y2t9_a9", "y2t9", "Anatomy",
    "An artery that branches from the Brachiocephalic Trunk can be palpated in the neck, name the artery and identify which triangle it can be found in:",
    ["External Carotid Artery; Carotid Triangle", "Subclavian Artery; Muscular Triangle", "Common Carotid Artery; Carotid Triangle", "Axillary Artery; Submandibular Triangle", "Facial Artery; Submandibular Triangle"], 2,
    "The Brachiocephalic Trunk branches to give off the Common Carotid Artery, which is easily palpable within the neck. As the name suggests, it is found in the Carotid Triangle of the neck."),
  Q("y2t9_a10", "y2t9", "Anatomy",
    "A patient has started to notice their voice changing and becoming more hoarse after an injury to the neck, which triangle of the neck has most likely been damaged?",
    ["Submental", "Submandibular", "Occipital", "Carotid", "Muscular"], 4,
    "Changes to the voice can occur due to damage to the Recurrent Laryngeal Nerve (a branch of the Vagus Nerve), which is found within the Muscular Triangle of the neck."),
  Q("y2t9_a11", "y2t9", "Anatomy",
    "Name and locate the salivary gland which can be found within one of the triangles of the neck:",
    ["Submental", "Submandibular", "Supraclavicular", "Muscular", "Carotid"], 1,
    "As the name suggests, the submandibular gland is located within the Submandibular Triangle, and the submandibular gland is one of the major salivary glands for the mouth."),
  Q("y2t9_p1", "y2t9", "Clinical & Pharmacology",
    "Rheumatoid arthritis is an inflammatory autoimmune condition. Which of the following is NOT a common feature of rheumatoid arthritis?",
    ["Systemic inflammation", "Associated with HLA-DR4 and HLA-DR1 genes", "Inflammation of synovial capsule", "Bone spur formation", "Affects female gender predominantly"], 3,
    "Rheumatoid arthritis is characterised by systemic inflammation, female predominance (3:1), morning stiffness >1hr, association with HLA-DR4 and HLA-DR1 genes, and inflammation of the synovial capsule. Bone spur (osteophyte) formation occurs in osteoarthritis where there is bony overgrowth."),
  Q("y2t9_p2", "y2t9", "Clinical & Pharmacology",
    "Patients with rheumatoid arthritis are typically given conventional disease-modifying anti-rheumatic (DMARD) drugs as a first-line treatment. Which of the following options is NOT part of this group?",
    ["Hydroxychloroquine", "Sulfasalazine", "Infliximab", "Methotrexate", "Leflunomide"], 2,
    "Infliximab is part of the biologic group of DMARDs as a 2nd line treatment, rather than the conventional group. The conventional DMARDs are 1st line and include methotrexate (gold standard), leflunomide, hydroxychloroquine and sulfasalazine."),
  Q("y2t9_p3", "y2t9", "Clinical & Pharmacology",
    "Polly, a 65 year old female, has been diagnosed with gout and is given the medication allopurinol. What is the mechanism of action of allopurinol?",
    ["NSAID- relieves pain", "Xanthine oxidase inhibitor- reduces uric acid production", "Uricosuric agent- increases excretion of uric acid", "Acetylcholinesterase inhibitor", "Dopamine agonist"], 1,
    "Allopurinol is a xanthine oxidase inhibitor, reducing uric acid production. Patients with gout are characterised by hyperuricemia (excess uric acid levels) due to overproduction of uric acid and decreased excretion."),
  Q("y2t9_p4", "y2t9", "Clinical & Pharmacology",
    "Which of the following is a common side-effect of NSAIDs?",
    ["Glucose intolerance", "Gastrointestinal irritation", "Weight gain", "Weight loss", "Postural hypotension"], 1,
    "GI system irritation is a common side-effect of NSAIDs. Inhibition of protective prostaglandins leads to gastric irritation, destruction of the mucosal lining, peptic ulcers and bleeding."),
  Q("y2t9_p5", "y2t9", "Clinical & Pharmacology",
    "Which of the following arthritis conditions is distinguishably characterised by the inflammation of the sacroiliac joints and spine?",
    ["Viral arthritis", "Septic arthritis", "Reactive arthritis", "Ankylosing spondyloarthritis", "Psoriatic arthritis", "Gout"], 3,
    "Ankylosing spondyloarthritis is characterised by the inflammation of the sacroiliac joints and spine. 90% of patients are HLA-B27 positive, emphasising it as a genetically inherited condition. It presents as lower back pain and reduced spinal mobility."),
  Q("y2t9_p6", "y2t9", "Clinical & Pharmacology",
    "Jane, a 54 year old female, attends a GP appointment regarding stiffness in her joints. She complains specifically of pain and swelling at the base of her big toe. Which of the following arthritis conditions is most likely to fit based on her history?",
    ["Viral arthritis", "Septic arthritis", "Reactive arthritis", "Ankylosing spondyloarthritis", "Psoriatic arthritis", "Gout"], 5,
    "Gout is clinically distinguished by the onset of pain and swelling at the base of the big toe, the metatarsophalangeal (MTP) joint; the presentation is known as podagra. The pathology involves deposition of monosodium urate (MSU) crystals in joints and tissues, hence gout is known as crystal arthritis."),
  Q("y2t9_p7", "y2t9", "Clinical & Pharmacology",
    "A 52 year old patient has been suffering from a moderate pain in his teeth. Which of the following opioid medications would be most suitable to give to them?",
    ["Methadone", "Oxycodone", "Codeine", "Morphine", "Fentanyl"], 2,
    "Codeine is a weak opioid which should be given during moderate pain only. Methadone, morphine, fentanyl and oxycodone are strong opioids and so should be given during extreme pain only. Weak opioids include codeine and tramadol."),
  Q("y2t9_p8", "y2t9", "Clinical & Pharmacology",
    "Which of the following is an exogenous opioid?",
    ["Enkephalin", "Oxycodone", "Dynorphin", "β-endorphin", "Endomorphin-1"], 1,
    "Oxycodone is an exogenous opioid, pain-relieving substances developed externally. Endogenous opioids (produced naturally by the body) include endorphins, enkephalins, dynorphins and endomorphins. Exogenous examples: morphine, codeine, oxycodone, heroin, fentanyl, tramadol."),
  Q("y2t9_p9", "y2t9", "Clinical & Pharmacology",
    "Shahid, a 35 year old male, has been taking opioids to manage his pain following a surgery. He has recently noticed some side effects since starting the medication. Which of the following side-effects is he most likely to be referring to?",
    ["Diarrhoea", "Dry cough", "Constipation", "Weight gain", "Tachycardia"], 2,
    "Constipation is often the most characteristic side-effect of opioids, they increase fluid absorption and decrease GI motility. ACE inhibitors cause a dry cough due to inhibiting the breakdown of bradykinin. Opioids more often cause bradycardia rather than tachycardia, since they stimulate the vagus nerve."),
  Q("y2t9_p10", "y2t9", "Clinical & Pharmacology",
    "Seronegative spondyloarthropathies share which common immunogenetic association?",
    ["HLA-B27", "HLA-DR4", "HLA-DR1", "HLA-A1", "No HLA associations"], 0,
    "Many seronegative arthropathies (ankylosing spondylitis, reactive, enteropathic, psoriatic arthritis) are associated with HLA-B27. Rheumatoid arthritis, on the other hand, is associated with HLA-DR4 and HLA-DR1."),
  Q("y2t9_p11", "y2t9", "Clinical & Pharmacology",
    "A patient has chronic neuropathic pain after nerve injury, with allodynia and hyperalgesia. Which spinal change best explains allodynia?",
    ["Loss of C-fibres only", "Sprouting of Aβ fibres to pain lamina (II/III) so non-noxious input activates nociceptive circuits", "Downregulation of NMDA receptors", "Only peripheral inflammation with no central changes", "Increased perineural blood flow"], 1,
    "After nerve injury, Aβ fibres may sprout into superficial dorsal horn laminae or synaptic changes lead to non-noxious inputs activating pain pathways → allodynia."),
  Q("y2t9_p12", "y2t9", "Clinical & Pharmacology",
    "Neostigmine aids recovery at the neuromuscular junction by:",
    ["Blocking ACh receptors", "Inhibiting AChE", "Increasing breakdown of ACh", "Blocking sodium channels", "Blocking potassium channels"], 1,
    "Neostigmine inhibits acetylcholinesterase (AChE), the enzyme that breaks down ACh → ACh concentration increases at the NMJ → stronger depolarisation → restored neuromuscular transmission."),
  Q("y2t9_p13", "y2t9", "Clinical & Pharmacology",
    "Which of the following is a partial agonist used in medium-term opioid substitution therapy?",
    ["Methadone", "Buprenorphine", "Naltrexone", "Naloxone", "Heroin"], 1,
    "Buprenorphine is a partial μ-opioid receptor agonist used in medium-term opioid substitution therapy. Its partial agonism gives it sufficient activity to prevent withdrawal and it tends to be combined with naloxone to reduce misuse."),
  Q("y2t9_p14", "y2t9", "Clinical & Pharmacology",
    "Which drug acts as a competitive antagonist at the mu-opioid receptor and is used to prevent relapse by blocking opioid effects?",
    ["Methadone", "Buprenorphine", "Naltrexone", "Naloxone", "Codeine"], 2,
    "Naltrexone is an oral competitive antagonist at mu receptors used to block opioid effects and reduce relapse risk. Naloxone works by the same mechanism but is short-acting, used for emergency reversal of life-threatening opioid overdose. Naltrexone = long-acting, oral, relapse prevention; Naloxone = short-acting, IV or intranasal, emergency overdose reversal."),
  Q("y2t9_p15", "y2t9", "Clinical & Pharmacology",
    "Which analgesic reduces central sensitization by antagonizing NMDA receptors?",
    ["Morphine", "Ketamine", "Ibuprofen", "Lidocaine (topical)", "Paracetamol"], 1,
    "Ketamine is an NMDA receptor antagonist that can reduce central sensitization and opioid tolerance mechanisms."),
  Q("y2t9_p16", "y2t9", "Clinical & Pharmacology",
    "A 54-year-old man on long-term high-dose opioids for chronic back pain undergoes major abdominal surgery. Postoperatively, he reports severe pain despite escalating doses of IV morphine. The acute pain team suspects opioid-induced hyperalgesia and central sensitization. Which medication would most effectively improve his analgesia by reducing NMDA-mediated spinal sensitization and helping overcome opioid tolerance?",
    ["Hydromorphone infusion", "Ketamine infusion (sub-anaesthetic dose)", "Clonidine (α2-agonist)", "Intravenous lidocaine infusion", "Duloxetine"], 1,
    "Ketamine infusion would be the most effective option since it is an NMDA receptor antagonist, blocking receptors and in turn reducing central sensitisation."),
);
